### ISSUE TITLE
feature request: add one grpc config

### ISSUE THREAD

**Issue by m0x61h0x64i** [bia-pain-bache/BPB-Worker-Panel#101]
Hi, thanks for your job.
If it is possible please add one grpc tls config to subscription it works great on tci & samantel.

**Comment by silent1360** [comment]
اگه ممکنه GRPC رو اضافه کنید دربیشتر مواقع Bpb با همراه اول وصل نمیشه

**Comment by bia-pain-bache** [comment]
Hi,
workers don't support grpc unfortunately.
For MCI please use normal configs or fragment with rethink app.

**Comment by silent1360** [comment]
من از کانفیگ فرگمنت هم استفاده کردم هر چی عددها رو بالا پایین کردم بازم نتونستم با همراه اول وصل بشم. از ip تمیز مخصوص mci هم اسنفاده کردم بازم فایده نداشت.  کانفیگها با نت مبین نت عالین ولی روی همراه اول بگیر نگیر داره
