### ISSUE TITLE
bug: environment variables seems do not work

### ISSUE THREAD

**Issue by m0x61h0x64i** [bia-pain-bache/BPB-Worker-Panel#102]
Hi, I have set PROXYIP & UUID like this:

![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/109550653/52c56da8-35ad-4ee8-a156-821c3a35181c)
after that when I retry deploy of the last deployment my subscription configs which are in v2rayng still works!
and when im using the configs my IP is not the IP in PROXYIP variable!
so it seems that environment variables do not work, any ideas ?
`BPB Panel 2.3.5`

**Comment by bia-pain-bache** [comment]
Hi,
Maybe you are using a wrong build for retrying deployment. From production page go to view details and choose retry deployment there. 
Also please consider that cloudflare KV has a cache which makes troubles sometimes.

**Comment by m0x61h0x64i** [comment]
Im using right build for retrying deployment. I did what u said but that didn't work.

![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/109550653/79e92c26-ac7b-44e3-a1df-4d3480a85374)
This is my proxy settings in kv namespace and I only have 3 keys:

![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/109550653/83f5d193-e63f-48f3-b6c2-febf0c42875f)
Is this correct?

@bia-pain-bache

**Comment by bia-pain-bache** [comment]
Yes that's correct. Environment vars are different from KV. If Env is not working, you can either try to deploy another project or set proxy IP from panel. please remember to update sub after applying from panel.
