### ISSUE TITLE
رمز پنل

### ISSUE THREAD

**Issue by CyrusTheV** [bia-pain-bache/BPB-Worker-Panel#103]
سلام
رمز پنل روقبول نمیکنه آیا راهی برای ریست کردنش هست؟ مثلا توی کد تغییرش داد

**Comment by 3reilii** [comment]
سلام از توی پنل cloudflare 
KV
که ساختی رو باز کن view  بزن نوشته PWD همون پسوردت هست

**Comment by CyrusTheV** [comment]
متاسفانه قبول نمیکنه....پسورد درسته اما میگه wrong passwordT 
این مشکلی نیست دوباره دپلوی میکنم ولی این باگ رو قبلا هم یکی گفته بود .

> سلام از توی پنل cloudflare KV که ساختی رو باز کن view بزن نوشته PWD همون پسوردت هست



> سلام از توی پنل cloudflare KV که ساختی رو باز کن view بزن نوشته PWD همون پسوردت هست

**Comment by 3reilii** [comment]
اگر اینطوریه باید KV را پاک کنی دوباره از اول بسازی و معرفی کنی توی پیجزت درست میشه

**Comment by 3reilii** [comment]
عین آموزش
دوباره بسازش

**Comment by NiREvil** [comment]
> متاسفانه قبول نمیکنه....پسورد درسته اما میگه wrong passwordT این مشکلی نیست دوباره دپلوی میکنم ولی این باگ رو قبلا هم یکی گفته بود .
> 
> > سلام از توی پنل cloudflare KV که ساختی رو باز کن view بزن نوشته PWD همون پسوردت هست
> 
> > سلام از توی پنل cloudflare KV که ساختی رو باز کن view بزن نوشته PWD همون پسوردت هست



> سلام رمز پنل روقبول نمیکنه آیا راهی برای ریست کردنش هست؟ مثلا توی کد تغییرش داد

سلام ببین راه درستش همونه که بچه‌ها گفتن، از اکانت کلادفلر خودت وارد **KV** که ساختی بشی و پسوورد رو ادیت کنی و تغییر بدی و بعد **retry deployment** بزنی درست بشه، ولی میگی نمیشه اوکی طبق این شات ک میذارم برو گیت‌هاب خودت و فایل **worker.js** رو ادیت بزن و لاین **122** که نوشته 'admin' رو تغییر بده به پسوورد دلخواهت، و ذخیره کن (commit changes) سی ثانیه صبر کن خودش deploy بشه و بعد برو باز کن پنل رو ببین چطور شد . 
```js
120-      let secretKey = await env.bpb.get('secretKey');
121-      const pwd = await env.bpb.get('pwd');
122-      if (!pwd) await env.bpb.put('pwd', 'admin');
```
![Screenshot_20240605-231250_cropped](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/126243832/c83e22ec-5510-4fe1-a93c-7a3215148038)

**Comment by bia-pain-bache** [comment]
سلام،
میتونی کوکی‌های پنل رو پاک کنی یا کش مرورگر رو، اگر که مطمئنی پسورد درسته. ممکنه اینجوری مشکلت حل بشه.

**Comment by CyrusTheV** [comment]
> سلام، میتونی کوکی‌های پنل رو پاک کنی یا کش مرورگر رو، اگر که مطمئنی پسورد درسته. ممکنه اینجوری مشکلت حل بشه.

ممنون.این نشد
