### ISSUE TITLE
Ability to add custom ip list via url

### ISSUE THREAD

**Issue by Graveyard9988** [bia-pain-bache/BPB-Worker-Panel#104]
Please provide a feature to import ip list via URL, like this:
https://raw.githubusercontent.com/yebekhe/cf-clean-ip-resolver/main/list.json

**Comment by NiREvil** [comment]
> Please provide a feature to import ip list via URL, like this: https://raw.githubusercontent.com/yebekhe/cf-clean-ip-resolver/main/list.json



> Please provide a feature to import ip list via URL, like this: https://raw.githubusercontent.com/yebekhe/cf-clean-ip-resolver/main/list.json

We perform this task with the assistance of a third-party worker such as [Harmony.js](https://github.com/NiREvil/Harmony) or we create a worker called [Trauma](https://github.com/NiREvil/Trauma) and assign our ADDAPI variable to our own Clean IP  link.

**Comment by bia-pain-bache** [comment]
the link provided shows ircf clean IPs which is not gonna maintained anymore regarding their notice. Also this is not a general format list.

**Comment by bia-pain-bache** [comment]
you can insert your IPs behind a dns record and set that subdomain in clean IP field. for more personalised format please modify code for your own deployment.

**Comment by bia-pain-bache** [comment]
Unfortunately not...
