### ISSUE TITLE
عدم اتصال به تلگرام

### ISSUE THREAD

**Issue by Behnamjef** [bia-pain-bache/BPB-Worker-Panel#105]
سلام. خیلی ممنون بابت زحماتی که میکشین.
از دیروز متاسفانه تلگرام لود نمیشه. ممنون میشم اگه راهکاری هست راهنمایی کنین.

**Comment by bia-pain-bache** [comment]
سلام، خواهش میکنم.
فقط تلگرام؟! با کدوم کانفیگ، فرگمنت یا معمولی؟ تلگرام رو force stop کنید و بعد کش رو پاک کنید اگر فقط تلگرامه.

**Comment by 3reilii** [comment]
حتی منم همین مشکل رو دارم در سوال قبلیم اعلام کردم برای تلگرام و سایتهای http  ایراد میگیره اما پیجزی که قبل 30 - 5 ساختم بدون مشکل کار میکنه 3 تا دیگه ساختم هیچکدوم کار نمیکنه برای دو موردی که گفتم

**Comment by Behnamjef** [comment]
> سلام، خواهش میکنم. فقط تلگرام؟! با کدوم کانفیگ، فرگمنت یا معمولی؟ تلگرام رو force stop کنید و بعد کش رو پاک کنید اگر فقط تلگرامه.

سایتای معمولی مثل یوتیوب و اینستا خیلی سرعت خوبی دارن. اما تلگرام و سایتای کلودفلری باز نمیشن. حتی whatismyipaddress هم باز نمیشه.
اینو روی همه‌ی دیوایس‌ها، اندروید، آی‌اواس،مک و ویندوز تست کردم ولی نتیجه یکسانه. مطمئن شدم مشکل از نرم‌افزار نیست.
هم روی ورکر و هم پیجز این موضوع وجود داره.
خیلی برام عجیبه!

**Comment by bia-pain-bache** [comment]
خب این مشکل proxy ip هست. طبق آموزش‌ها برید و تست کنید تا یه سالم پیدا کنید.

**Comment by Behnamjef** [comment]
اینکارو کرده بودم و به جواب نرسیدم، اما بیشتر تست میکنم با ای‌پی‌های جدید. نتیجه رو اعلام میکنم.
ممنون بابت همراهیتون.

**Comment by bia-pain-bache** [comment]
remote dns 
رو خم به https://8.8.8.8/dns-query  تغییر بدید داخل برنامه

**Comment by Behnamjef** [comment]
> remote dns رو هم به https://8.8.8.8/dns-query .تغییر بدید داخل برنامه

اینکارم کرده بودم. طبق [این آموزش](https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/worker_installation_fa.md#%D8%AA%D9%86%D8%B8%DB%8C%D9%85%D8%A7%D8%AA-%D9%BE%DB%8C%D8%B4%D8%B1%D9%81%D8%AA%D9%87-%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%DB%8C) پروکسی آی‌پی‌های مختلفو تست کردم ولی الان اصلا یه مشکل دیگه هم پیش میاد. اینکه آی‌پی هایی که ست میکنمو اصلا در نظر نمیگیره و رندم آی‌پی میذاره! ولی تا پریروز درست داشت کار میکرد!
لاگ هم گذاشتم توی try catch که ببینم آی‌پی چی انتخاب میشه. اونجا آی‌پی که من دادم ست میشه ولی وقتی کانکت میشی با اون آی‌پی نیست!
جایی میتونم لاگی بذارم که بتونیم مشکلشو پیدا کنیم؟

**Comment by bia-pain-bache** [comment]
لطفا IP مورد نظرو بذارید تا تست کنیم

**Comment by amebrahimi** [comment]
@bia-pain-bache 
سلام,
به نظرم نسخه جدید یک اشکالی داره,
چون من هم این مشکل را با پنلی که جدیدا نصب کردم دارم
در نسخه قدیمی که هنوز proxyip به پنل پیچز اضافه نشده بود یکی در حال حاضر دارم که با این آی پی به راحتی کار میکند 8.219.111.175
اما یک پنل نسخه جدید گذاشتم با همین آی پی کار نمیکند.
هنوز دیباگ نکردم ولی حدس میزنم که آی پی ای که در انوایرمنت وریبلز قرار میدهیم اعمال نمیشود.

**Comment by Behnamjef** [comment]
> لطفا IP مورد نظرو بذارید تا تست کنیم

این سه تا برای آلمان هستن:
'141.144.232.81', '152.70.173.38', '193.122.61.167'

**Comment by bia-pain-bache** [comment]
هیچکدوم از ۳ ip کار نمیکنن. از کجا گرفتید اینها رو؟ بخاطر همین تو آموزش تاکید کردم از اون لینک‌ها IP بردارید، اونجا مرتب بروزرسانی میشه.

`سلام,
به نظرم نسخه جدید یک اشکالی داره`

سلام، نسخه‌ی جدید مشکلی نداره، تست شده و همه دارن استفاده میکنن. باید ببینید چی از قلم افتاده موقع دپلوی. طبق آموزشای خود گیتهاب بسازید مشکلتون برطرف میشه به احتمال زیاد.

**Comment by amebrahimi** [comment]
شما چطور آی پی را تست میکنید؟ الان این آی پی کار میکند روی یکی از پنل های من ولی روی پنل جدیدم کار نمیکند 
8.219.111.175

**Comment by Behnamjef** [comment]
> هیچکدوم از ۳ ip کار نمیکنن. از کجا گرفتید اینها رو؟ بخاطر همین تو آموزش تاکید کردم از اون لینک‌ها IP بردارید، اونجا مرتب بروزرسانی میشه.
> 
> `سلام, به نظرم نسخه جدید یک اشکالی داره`
> 
> سلام، نسخه‌ی جدید مشکلی نداره، تست شده و همه دارن استفاده میکنن. باید ببینید چی از قلم افتاده موقع دپلوی. طبق آموزشای خود گیتهاب بسازید مشکلتون برطرف میشه به احتمال زیاد.

ممنونم که تست کردی. بهت قول میدم که طبق آموزش پیش رفتم. از اینجا برداشتم که لینکشو گذاشته بودی:
https://www.nslookup.io/domains/cdn-all.xn--b6gac.eu.org/dns-records/
این سه تا نمونه‌ست حدود ۲۰تا تست کردم.
میپذیرم که شاید آی‌پی‌ها بسته شده باشن ولی با همین تنظیمات باقی سایتا مثل یوتیوب باز میشن، ولی آی‌پیم رندم میشه اصلا اینا ست نمیشن. طبق آموزش پیش رفتم و لیست آی‌پی‌ها رو توی کد تغییر دادم، بار اولی که ست کردم درست بود ولی یهو دیگه ستشون نکرد.
اینم بگم که با مقادیری که خودت گذاشتی از nslookup بگیره هم درست بود و تلگرام باز میشد اما الان باز نمیشه.
به یکی از دوستان هم گفتم، مثل اینکه ستاپ قبلیش درسته و کار میکنه، الان که یه ورکر جدید تست میکنه دقیقا به همین مشکل میخوره.
اگه زحمتت نیست خودت رو یه ورکر جدید تست میکنی؟

**Comment by bia-pain-bache** [comment]
بهنام جان proxy ip فقط واسه سایتای پشت کلادفلر هست، تلگرام پشت کلادفلر نیست، یوتیوبم نیست‌. شما نمیتونی ۳ تا ip رو همزمان برای proxy ip ست کنی، فقط یه دونه!
شما یه زحمتی بکش یه جدید بساز به هیچی هم دست نزن اصلا، با پیشفرض پنل کانفیگ بگیر وصل شو، اگه بازم مشکل داشت بگو من حتما برات تست میکنم.

**Comment by Behnamjef** [comment]
> بهنام جان proxy ip فقط واسه سایتای پشت کلادفلر هست، تلگرام پشت کلادفلر نیست، یوتیوبم نیست‌. شما نمیتونی ۳ تا ip رو همزمان برای proxy ip ست کنی، فقط یه دونه! شما یه زحمتی بکش یه جدید بساز به هیچی هم دست نزن اصلا، با پیشفرض پنل کانفیگ بگیر وصل شو، اگه بازم مشکل داشت بگو من حتما برات تست میکنم. خواستی جدید بسازی یه kv جدید هم براش بساز

متوجهم. این ۳تا ای‌پی رو تو لیست گذاشتم بالای خطی که رندم انتخاب میکنی تا از بینشون یکی رو انتخاب کنه.
از اول چندین بار تست کردم هم با اسکریپت شما، هم اقا فرید، هم یه اسکریپت چینی هست، حتی با تنظیمات پیشفرض هم همین مشکل بین همشون وجود داشت.
حرف شما سنده، احتمالا یه dnsای چیزی یه جا کش شده که اینجوری میشه.
من به یکی دیگه از دوستانم گفتم همینو تست کنه ببینیم چی میشه. اگه نشد زحمتشو به شما میدم.
خیلی خیلی ممنونم که کمک میکنی.🙏

**Comment by bia-pain-bache** [comment]
توی ورکر میشه چنتا IP گذاشت ولی pages فقط یکی. اصلا میخوای مطمئن بشی بحث کش kv نیست توی پنل IP رو بذار ساب رو آپدیت کن، واسه اطمینان ۳ بار ساب رو آپدیت کن بعد وصل شو. 
ورکر بعد از آخرین اتفاقات و تغییراتش مشکلاتی داره، روش پیشنهادی من فقط Pages هست.

**Comment by hadikanan37qom** [comment]
مشکل وصل نشدن تلگرام با فرگمنت درست شد
