### ISSUE TITLE
مشکل در کلودفلر برای پروکسی آی پی و مشکل تلگرام

### ISSUE THREAD

**Issue by 3lei** [bia-pain-bache/BPB-Worker-Panel#106]
سلام چند روزه دارم تست میکنم برای تمام مواردی که راهنمایی کردی. ( 100 تا پروکسی آی پی و انواع ساخت ها)
پروکسی آی پی و بیلد مجدد و ...
اما اکانت هایی که در ماه جون ساختم تلگرام را باز نمیکنن و مشکل در تست سرعت دارن
اول فکر کردم شاید اشکال از ورکر باشد اما بعد از چندین تست و ساخت ورکر و پیجز در 4 اکانت ساخته شدم ( یکی شون که کار میکنه قبل از جون ساختم) فکر کردم شاید از کلود فلر باشد مشکل تمام منو ها رو در تمام اکانت ها چک کردم اکانت اولی که در می ساخته شده ریجن اکتیو سشنش مال آلمانه اما 3 تای دیگه مال آمریکا هست. و منوی جدید های یه تب جدید به نام هوم دارد.
آیا میتونه ربطی به این موضوع داشته باشد؟
آیا راهی برای عوض کردن ریجن اکانت کلودفلر وجود داره؟
اگر میدونی چطور میتونم این موضوع رو حل کنم ممنون میشم راهنمایی کنی

**Comment by bia-pain-bache** [comment]
سلام،
واقعا نمیدونم مشکل از چیه، یادمه تو یه ایشو دیگه هم صحبت کردیم. هر چیزی که ممکن بود مشکلتو برطرف کنه تا الان گفتم. پنل رو بالا بیاری اصلا با تنظیمات پیشفرض خودش بدون هیچ کار اضافه‌ای کانفیگاش باید کار کنه بدون مشکل.

**Comment by claxpoint** [comment]
سلام عزیز. من در حال تقویت سازی هستم و احتمال میدم این مشکل حل بشه داخل صفحه گیت هابم میزارم نسخه پراکسی سیستم در درون کد رو.

**Comment by claxpoint** [comment]
> سلام، واقعا نمیدونم مشکل از چیه، یادمه تو یه ایشو دیگه هم صحبت کردیم. هر چیزی که ممکن بود مشکلتو برطرف کنه تا الان گفتم. پنل رو بالا بیاری اصلا با تنظیمات پیشفرض خودش بدون هیچ کار اضافه‌ای کانفیگاش باید کار کنه بدون مشکل.

مشکل کلا از سیستمش نیست از مرکز پردازش ورکر هست

**Comment by bia-pain-bache** [comment]
الان هزاران نفر دارن از این ورکر استفاده میکنن، طبیعتا از خود ورکر باشه صدای بقیه هم در میومد، ولی جدیدا فقط دو مورد گزارش دادن که یه مورد هم مشکلش حل شده. عجیبه و نیاز داره دیباگ بشه درست، با این اطلاعات و دسترسی تقریبا غیر ممکنه.
منظور شما از تقویت‌سازی رو هم متوجه نشدم.

**Comment by 3reilii** [comment]
> الان هزاران نفر دارن از این ورکر استفاده میکنن، طبیعتا از خود ورکر باشه صدای بقیه هم در میومد، ولی جدیدا فقط دو مورد گزارش دادن که یه مورد هم مشکلش حل شده. عجیبه و نیاز داره دیباگ بشه درست، با این اطلاعات و دسترسی تقریبا غیر ممکنه. منظور شما از تقویت‌سازی رو هم متوجه نشدم.

تمام کد ها رو با ورژن چینی و اونی که دفعه اول فورک کردم مقایسه کردم اگر مشکلی در کد ورکر بود اولی هم باید از کار میفتاد اما فقط اکانت هایی در ماه می ساختم این مشکل رو دارن.

**Comment by claxpoint** [comment]
عزیز حرفت درست ولی من از خیلیا پرسیدم گفتن تلگرام وصل نمیشه

**Comment by bia-pain-bache** [comment]
@3reilii 
یه دوره‌ای خیلی از اکانت‌های کلادفلر بخاطر ترافیک نامحدود و بالا فلگ شد و اصلا وقتی دپلوی میکردی ارور میداد. مطمئن نیستم موردت این باشه ولی محض احتیاط با یه ایمیل رسمی مثل جیمیل یه اکانت کلادفلر جدید بساز و روی اون دپلوی کن ببین چی میشه. حتی برای خود من پیش اومده که اکانت گیتهابم بخاطر این فورک فلگ شده بود و نمیذاشت پیجز بسازم. در هر صورت اگه امتحان نکردی این کارو بکن.

**Comment by 3reilii** [comment]
تمام میل هایی استفاده کردم رسمی بوده gmail yahoo و سالهاست دارم استفاده میکنم ازشون.
جایی هم ریپرت نشدم تا جایی میدونم اما باشه یه میل جدید میسازم ببینم چی میشه دوباره باهات مشورت میکنم

**Comment by claxpoint** [comment]
> @3reilii یه دوره‌ای خیلی از اکانت‌های کلادفلر بخاطر ترافیک نامحدود و بالا فلگ شد و اصلا وقتی دپلوی میکردی ارور میداد. مطمئن نیستم موردت این باشه ولی محض احتیاط با یه ایمیل رسمی مثل جیمیل یه اکانت کلادفلر جدید بساز و روی اون دپلوی کن ببین چی میشه. حتی برای خود من پیش اومده که اکانت گیتهابم بخاطر این فورک فلگ شده بود و نمیذاشت پیجز بسازم. در هر صورت اگه امتحان نکردی این کارو بکن.

تا جایی که میدونم کلودفلر روی UDP که نداره حساسه

**Comment by bia-pain-bache** [comment]
@sahar-km 
سلام ممنون،
راستش من اصلا منظور اون جمله رو نمیفهمم! تو گیتهاب خودشم چک کردم هیچ ایشویی برای تلگرام نیست...کلا مورد عجیبیه.

**Comment by roozbehaa** [comment]
سلام این مشکل فقط برای تلگرام با شماره های ایران هستش و اگر شماره خارج داشته باشید همین وصل میشه بدون مشکل

**Comment by 3lei** [comment]
@bia-pain-bache
سلام همونطور که گفتی مشکل از ورکر نبود و با ساخت اکانت جدید با آی پی جای دیگه تونستم وصل بشم خیلی ممنون از وقتی گذاشتی

**Comment by ehsanna11111** [comment]
سلام و ممنون بابت کد ورکر که تهیه کردی
متاسفانه حدود 2 هفته هست که کد ورکری که با پیج گیتهاب ساختم دیگه وصل نمیشه و توی کلاینت هیدیفای ارور تایم اوت میده جه با فرگمنت چه بدون فرگمنت. اینترنت دی اس ال مخابرات هست . راهی هست که بتونم این مشکل رو حل کنم
ممنون
![SharedScreenshot](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/134102795/b070e280-8b77-4c5a-81b6-036eb25397fc)

**Comment by bia-pain-bache** [comment]
سلام،
اول اینکه لطف میکنید اگر هر موضوعی رو یه ایشو جداگونه باز کنید.
ظاهرا شما ساب singbox رو با هیدیفای ایمپورت کردید، چون ارور geo asset میده. ساب مخصوص خودش رو بردارید.

**Comment by ehsanna11111** [comment]
> سلام، اول اینکه لطف میکنید اگر هر موضوعی رو یه ایشو جداگونه باز کنید. ظاهرا شما ساب singbox رو با هیدیفای ایمپورت کردید، چون ارور geo asset میده. ساب مخصوص خودش رو بردارید.

شرمنده من فکر کردم مربوط به همین موضوع میشه و نباید ایشو جدید ایجاد کنم
کد هم من مثل قبل از پنل و قسمت مربوط هیدیفای کپی کردم و تا دو هفته قبل عالی کار میکرد که ناگهانی قطع شد و مشکل پیش اومد

**Comment by bia-pain-bache** [comment]
دشمنتون شرمنده. احتمالا هیدیفای رو آپدیت نکردید؟ قوانین مسیریابی دستی ست نکردید؟ اون geosite که تو ارورا میبینید مال مسیریابیه. از قسمت تنظیمات برید به routing assets و هر دو گزینه رو آپدیت کنید.

**Comment by Behnamjef** [comment]
سلام. من یه issue باز کرده بودم راجع‌به این مشکل و کلی با bpb صحبت کردیم، بذارید یه توضیج بدم.
من رو ورکر بالا آوردم و همه چیز به خوبی کار میکرد تا اینکه به محدودیت ۱۰۰هزارتا رسید. از فرداش به همین مشکلی که تلگرامو باز نمیکرد برخوردم.
هم رو ورکر، هم پیجز، هم با کد آقای vfarid، هم با کد چینی EDTunnel همین مشکل وجود داشت.
تا اینکه بعد از کلی ور رفتن دیدم حل نمیشه و ورکرمو باز گذاشتم و ولش کردم.
بعد از ۳ روز، امروز دیدم که همون ورکری که کار نمیکرد و ولش کرده بودم داره کار میکنه! انگار خود کلودفلر از یه جایی یه سری دسترسی رو محدود کرده بود و امروز بازشون کرد!
الان درسته و اگه بازم چیز جدیدی پیدا کردم حتما اطلاع میدم.
پیشنهاد میکنم با یه اکانت جدید روی یک سیستم جدید تست کنین بیبینین درست میشه؟ من اون موقع با اکانت جدید هم تست کرده بودم همین مشکل وجود داشت انگار خود سیستم رو هم در نظر میگیره.

**Comment by ehsanna11111** [comment]
ممنون بابت راهنمایی
هیدیفای اخرین ورژن رسمی بروز کردم و قسمت geosite رو هم آپدیت کردم ولی بازهم تایم اوت میده... برای حدود 2 ثانیه موقع کانکت شدن ای پی مقصد رو میگیره ولی بعد بدون پینگ میشه
![SharedScreenshot](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/134102795/21b9b5b2-5f99-4ed4-bc72-1a2b37f0ded3)

**Comment by ehsanna11111** [comment]
> سلام. من یه issue باز کرده بودم راجع‌به این مشکل و کلی با bpb صحبت کردیم، بذارید یه توضیح بدم. من رو ورکر بالا آوردم و همه چیز به خوبی کار میکرد تا اینکه به محدودیت ۱۰۰هزارتا رسید. از فرداش به همین مشکلی که تلگرامو باز نمیکرد برخوردم. هم رو ورکر، هم پیجز، هم با کد آقای vfarid، هم با کد چینی EDTunnel همین مشکل وجود داشت. تا اینکه بعد از کلی ور رفتن دیدم حل نمیشه و ورکرمو باز گذاشتم و ولش کردم. بعد از ۳ روز، امروز دیدم که همون ورکری که کار نمیکرد و ولش کرده بودم داره کار میکنه! انگار خود کلودفلر از یه جایی یه سری دسترسی رو محدود کرده بود و امروز بازشون کرد! الان درسته و اگه بازم چیز جدیدی پیدا کردم حتما اطلاع میدم. پیشنهاد میکنم با یه اکانت جدید روی یک سیستم جدید تست کنین بیبینین درست میشه؟ من اون موقع با اکانت جدید هم تست کرده بودم همین مشکل وجود داشت انگار خود سیستم رو هم در نظر میگیره.

سلام 
من کلودفلر رو چک کردم و اصلا کدم به محدودیت 100 هزار نرسیده بود و کد رو روی دوتا دیوایس مختلف دیگه هم تست کردم ولی جواب نگرفتم... مشکل من از زمانی بوجود اومد که چند هفته پیش اپراتورها شروع کردن محدودیت های شدید اعمال کنن روی نت ایران

**Comment by ehsanna11111** [comment]
سلام مجدد
اینبار ریموت dns داخل پنل رو عوض کردم و دوباره کانفیگ جدید رو داخل هیدیفا کپی کردم و چندتا از کانفیگ ها پینگ داد و وصل شد البته سرعتش یکمقدار پایینه ولی دیگه قطع نشد
