### ISSUE TITLE
مشکل در سینک کردن پنل۲.۳.۹#

### ISSUE THREAD

**Issue by emisemok** [bia-pain-bache/BPB-Worker-Panel#108]
bpb سلام و خسته نباشی خدمتت
عزیز من نتونستم این ورژنو سینکش کنم
غیر آموزشای قبلی چیزی تغییر کرده؟
ممنونت میشم راهنماییم کنی🙏🙏

**Comment by bia-pain-bache** [comment]
سلام، سلامت باشید. الان نمیتونید، نسخه پایدار بدم میتونید. میتونید با ورکر دپلوی کنید این نسخه رو
