### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by EhsanGhaf** [bia-pain-bache/BPB-Worker-Panel#112]
![test](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/38631760/69adc48e-f0e4-4e28-b1f1-39ecfbbee252)
after updating this error has occured

**Comment by ali32b** [comment]
داخل پنل clean ip رو یه تغییر بدید و اپلای کنید درست میشه

**Comment by bia-pain-bache** [comment]
با راهنمایی دوستمون اوکی شد؟

**Comment by EhsanGhaf** [comment]
بله مرسی
