### ISSUE TITLE
مشکل ورود به پنل

### ISSUE THREAD

**Issue by mohammad35322** [bia-pain-bache/BPB-Worker-Panel#113]
من یک پنل جدید پیجز ساختم و تمام مراحل ساخت رو درست رفتم و بعد از باز شدن پنل توی قسمت پسورد هرچی admin میزنم وارد نمیشه و wron password میده
چیکار کنم؟

**Comment by mohammad35322** [comment]
یه kv جدید ساختم جایگزین kv قبلی کردم و bindش کردم مشکل حل شد ولی قبلا اینجوری نبود که!

**Comment by drzadhmstfy690** [comment]
Gxc

**Comment by bia-pain-bache** [comment]
شما ظاهرا پنل جدید ساختید و وصل کردید به یه KV که از قبل بوده، طبیعتا باید با پسورد اون KV قدیمی وارد میشدید.
