### ISSUE TITLE
warp configs

### ISSUE THREAD

**Issue by hosseinfarnia** [bia-pain-bache/BPB-Worker-Panel#114]
درود و خسته نباشید

پیشنهاد میکنم برای هر کدوم از اپراتورها یک کانفیگ وارپ به نام خودشون تو پنل اضافه کنید که بشه اندپوینت مناسب برای هر کدوم رو جداگانه اضافه کرد تا وقتی کسی میخواد مثلا به ایرانسل وصل بشه به وارپی که اندپوینت ایرانسل اختصاص میدیم وصل بشه
فکر کنم بشه مثلا اپراتورهای معروف رو به این شکل اضافه کنید با اسم خودشون
warp hamrah
warp irancell
warp rightel
warp shatel
warp mokhaberat
warp (main)
آخری میتونیم همون آدرسس اصلی بذاریم
یدونه هم
warp other ISPs
باشه برای افرادی که از بقیه سرویس دهنده‌های اینترنت استفاده میکنن که اندپوینت اختصاصی خودشونو بذارن

بقیه رو خودمون اندپوینت مناسب هر اپراتور رو در میاریم که کاربر راحت باشه
فقط تو کلاینت اسم هر اپراتور جلوی وارپ بیاد که کاربر متوجه بشه
این شکلی حداقل خوبیش اینه چندتا اندپوینت هم هست، کاربر به یکیش وصل نشه به احتمال زیاد به یکی دیگه وصل میشه

یه پیشنهاد دیگه اگه این قابلیتو اضافه کردید تو کلاینت به جای warp on warp عبارت wow بذارید به اضافه اسم اپراتور که کوتاه بشه، مثلا
WoW Hamrah

برای هیدیفای هم میشه همشون رو تو یه لینک ساب اضافه کرد

من امتحان هم کردم با اندپوینت اختصاصی تو
v2rayng
و هیدیفای به راحتی وارپ وصل میشه

یه سوالی هم داشتم کاری که rethink میکنه، نمیشه از سمت پنل پیاده کنید؟

سپاس

**Comment by mahdi-salimi05** [comment]
اگه اندرویدتون بالای 9 هست؛ میتونید از تنظیمات خود سیستم DNS over TLS ست کنید.
![Screenshot_20240624-213650_Settings](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/119876901/a6011847-b127-4569-8ddb-c90fb1d58a49)

**Comment by bia-pain-bache** [comment]
سلام، در آپدیت جدید قابلیت اضافه کردن چند Endpoint ایجاد شده ولی remark نداره، خودتون باید ویرایش کنید.

**Comment by hosseinfarnia** [comment]
سلام
تو آپدیت جدید ساب وارپ فچ نمیشه
با اینها تست کردم:
v2rayng
hiddify
mahsang
یکی تو توییتر گفته بود پورت رو بذارید غیر ۴۴۳ درست میشه، اینکار رو کردم، فچ شد.

**Comment by bia-pain-bache** [comment]
ممنون که اطلاع دادید، ببینم مشکل چیه شاید بتونم رفعش کنم.

**Comment by Hamedespo** [comment]
سلام
ساب warp اصلا روی Streisand کار نمیده.

**Comment by bia-pain-bache** [comment]
سلام، کار کردنش منوط به خیلی فاکتورهاست مثل اپراتور یا endpoint، در حال حاضر روی تک‌و‌توک اپراتور مثل ایرانسل با endpoint تمیز وصل میشه.

**Comment by amzaf** [comment]
> سلام، کار کردنش منوط به خیلی فاکتورهاست مثل اپراتور یا endpoint، در حال حاضر روی تک‌و‌توک اپراتور مثل ایرانسل با endpoint تمیز وصل میشه.

من اسکریپتی که تو پنل گذاشتید را ران کردم هیچ آیپی بر نمیگردونه چه ورژن ۴ چه ورژن ۶. هیچ جوری نتونستم وارپ پنل را راه بندازم. درصورتی که الان دارم از امکان وارپ نرم افزار هیدیفای استفاده می‌کنم و روی ایرانسل و همراه اول جواب میده.
