### ISSUE TITLE
بالا بودن پینگ در لینک ساب فرگمنت

### ISSUE THREAD

**Issue by DarkKingTNi** [bia-pain-bache/BPB-Worker-Panel#13]
سلام و عرض خسته نباشید ممنون بابت کار خوبتون،، من از وژن آخر استفاده کردم ولی مشکلی که توی کانفیگ های فرگمنت وجود داره پینگ بسیار بالای اوناست و از طرفی در پنل 2.2.9 بخوام فرگمنت رو به تنهایی تغییر بدم نمیشه و ارور میده ممنون میشم راهنمایی کنید سپاس فراوان

**Comment by bia-pain-bache** [comment]
لطفا برای راه‌اندازی صحیح آموزش رو مطالعه کنید، در صورت حل نشدن مشکل قسمت سوالات متداول رو هم ببینید.
