### ISSUE TITLE
Karing Format

### ISSUE THREAD

**Issue by alireza-rasouli** [bia-pain-bache/BPB-Worker-Panel#132]
WARP subscription formatting for singbox doesn't work in karing app iOS/Macos in it's current format.
How ever by changing the format to one of the following will make the app both recognize the subs and connect to them successfully:

current sub formatting: 

> 
         {
            "local_address": [
                "XXXXX",
                "XXXXX.XXXXX"
            ],
            "mtu": 1280,
            "peer_public_key": "XXXXXXXXX",
            "pre_shared_key": "",
            "private_key": "XXXXX",
            "reserved": "CZ4h",
            "server": "engage.cloudflareclient.com",
            "server_port": 2408,
            "type": "wireguard",
            "domain_strategy": "prefer_ipv6",
            "tag": "💦 Warp-ir"
        },
>
Sing-box working and tested formatting for karing:

<
        {"type": "wireguard",
        "tag": "💦 Warp-ir",
        "server": "188.XXX.XX.XXX",
        "server_port": 4500,

        "local_address": [
        "XXXXXXX",
        "XXXXXXXXX.XXXXX"
        ],
        "private_key": "XXXXXX",
        "peer_public_key": "XXXXXXXX",
        "reserved": "iGZe",
  
        "mtu": 1280,
        "fake_packets": "5-10"
        },

>
Clash.Meta working and tested format for karing:

<
   proxies:
     - name: "💦 Warp-ir"
     type: wireguard
     private-key: XXXXXXXX
     server: engage.cloudflareclient.com
     port: 2408
     ip: XXXX/32
     ipv6: XXXXXX/128
     public-key: XXXXXXXXXX
     allowed-ips: ['0.0.0.0/0']
     reserved: "UC8D"
     udp: true
     mtu: 1280
     remote-dns-resolve: true
     dns: [ https://94.140.14.14/dns-query , 8.8.8.8 ]
>

1. By just changing the formatting or adding one for "outbound" of current sing-box format, karing warp sub will be active
2. Clash meta format could be added as an alternative sub button for karing and/or other apps supporting the format

Thanks for you hard work as always.

**Comment by bia-pain-bache** [comment]
I don't see any differences except `fake_packets`. Also the BPB Panel is not going to support none open source apps.
