### ISSUE TITLE
希望能在面板添加关闭ipv6开关，使订阅能干净

### ISSUE THREAD

**Issue by MINGERTAI** [bia-pain-bache/BPB-Worker-Panel#145]
希望能在面板添加关闭ipv6开关，使订阅能干净

          因为有很多网络供应商不支持ipv6
                                                                            谢谢

**Comment by angus5788** [comment]
我把它  删除了  https://github.com/angus5788/BPB-Worker-Panel

**Comment by bia-pain-bache** [comment]
So do not use it.

**Comment by Starry-Sky-World** [comment]
中文翻译：所以不要用这个
