### ISSUE TITLE
add proxy

### ISSUE THREAD

**Issue by hamidrabedi** [bia-pain-bache/BPB-Worker-Panel#147]
add socks and http proxies using cloudflare deployments. (mainly for servers that are hard or can't install v2ray)

**Comment by ennm666** [comment]
good idea

**Comment by bia-pain-bache** [comment]
What's the point when it doesn't work in Iran or get blocked very soon? do you know any good implementation?

**Comment by ennm666** [comment]
I believe that as long as Cloudflare is not blocked, adding a Sock proxy function can achieve the same effect as ProxyIP, such as accessing the website speedtest.net or using chained proxies to access streaming services like Netflix, even if the Sock proxy server is blocked.
Just like that
1.Normally(No ProxyIP)
User--->GFW--->The BPB on Cloudflare CDN Network--->General Website (Such as Google)
User--->GFW--->The BPB on Cloudflare CDN Network--->Close the connection that IP is Cloudflare CDN network -X->Websites using Cloudflare(Such as Speedtest by Ookla)
2.Configured ProxyIP or Socks
User--->GFW--->The BPB on Cloudflare CDN Network--->ProxyIP/Socks--->Websites using Cloudflare(Such as Speedtest by Ookla)
User--->GFW--->The BPB on Cloudflare CDN Network--->ProxyIP/Socks--->Streaming websites(Such as Netflix)

**Comment by hamidrabedi** [comment]
> What's the point when it doesn't work in Iran or get blocked very soon? do you know any good implementation?

I'm not an expert, but servers in iran usually have less restrictions than home networks. but I believe it is possible to use cloud flare APIs to recreate the pages with new name and new domain name in case of getting blocked.
DNS server would be a good idea for this problem as well.
and you can have a feature that admin put domains that they need to use this dns or proxy on like docker, linux package managers, pip, npm etc.

**Comment by ennm666** [comment]
I agree that in China, many servers can bypass DNS pollution and obtain correct DNS resolution results. This approach is targeted at gray area applications without ICP licenses (such as Steam). Just a short while ago, all Docker images in China were required to be taken down, causing a lot of trouble.

**Comment by bia-pain-bache** [comment]
I've got confused and canot understand the main issue. If you have a server, even a blocked one, why don't you just setup VLESS WS TLS to use?! setting socks and assigning to worker not only limits worker speed but also limits server performance.

**Comment by hamidrabedi** [comment]
> I've got confused and canot understand the main issue. If you have a server, even a blocked one, why don't you just setup VLESS WS TLS to use?! setting socks and assigning to worker not only limits worker speed but also limits server performance.

now I'm confused, wdym server performance?
the proxies and v2ray are on cloudflare pages or workers.

now sometimes for docker images or just some updates you need a proxy or DNS and you don't want to install a v2ray client on the server. there might be a lot of servers working together and installing a v2ray client on every one of them can be a headache. 
or some times there are some rules forced from the owner of server to not to install any 3rd party libraries on it
and many other reasons.

**Comment by bia-pain-bache** [comment]
Got it, in fact this case is an exception which I'm not gonna develop. there are thousands of features which could be implemented, however the panel supposed to be minimal for noob people. anyway I consider it as last priority in order not to get it more complicated.
