### ISSUE TITLE
ECH to prevent SNI leaks

### ISSUE THREAD

**Issue by mahdi-salimi05** [bia-pain-bache/BPB-Worker-Panel#157]
### Feature description | توضیحات ویژگی

This makes SNI disappear from the network firewall; Because the normal ``hello'' message that contains SNI is not encrypted. With this technology, it encrypts the message containing SNI. Fortunately, Cloudflare supports this.

**Comment by mahdi-salimi05** [comment]
I will check this encryption with TCP dump. This has nothing to do with the bpb panel and must be from the CDN and the client side.

**Comment by mahdi-salimi05** [comment]
> ### Feature description | توضیحات ویژگی
> 
> This makes SNI disappear from the network firewall; Because the normal ``hello'' message that contains SNI is not encrypted. With this technology, it encrypts the message containing SNI. Fortunately, Cloudflare supports this.

I will check this encryption with TCP dump. This has nothing to do with the bpb panel and must be from the CDN and the client side.

**Comment by mahdi-salimi05** [comment]
All browsers (like Firefox) seem to support it. I tested this with wireshark

**Comment by bia-pain-bache** [comment]
ECH on cloudflare CDN is disabled temporarily, and workers and pages use cloudflare CDN.
