### ISSUE TITLE
روی پلتفرم PHP

### ISSUE THREAD

**Issue by liMilCo** [bia-pain-bache/BPB-Worker-Panel#158]
با سلام
بسیار هوشمندانه بود که این پلتفرم با جاوا نوشته شده و روی سیستم هی کلود فلر کار میکنه ...
ایا میتوان این پلتفرم را با زبان PHP نوشت تا روی سرور های وب سایت (حتی روی wordpress) اجرا کرد ؟
آیا نمونه ای وجود دارد ؟

**Comment by bia-pain-bache** [comment]
سلام، مساله فقط زبان نیست، این پنل بدون سرور هست و از زیرساخت خود کلادفلر برای برقراری پروکسی استفاده میکنه.

**Comment by liMilCo** [comment]
خوب با php هم میتوان از زیرساخت خود سرور هاست استفاده کرد ...
