### ISSUE TITLE
BPB Panel 2.4.4 💦 Something went wrong! ⚠️ Cannot read properties of null (reading 'panelVersion')

### ISSUE THREAD

**Issue by heven18** [bia-pain-bache/BPB-Worker-Panel#159]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

BPB Panel 2.4.4 💦
Something went wrong!
⚠️ Cannot read properties of null (reading 'panelVersion')

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

BPB Panel 2.4.4 💦
Something went wrong!
⚠️ Cannot read properties of null (reading 'panelVersion')

### Relevant log output | لاگ برنامه یا پنل

```shell
BPB Panel 2.4.4 💦
Something went wrong!
⚠️ Cannot read properties of null (reading 'panelVersion')
```

**Comment by Abbas121133** [comment]
Something went wrong!

⚠️ Cannot read properties of null (reading 'panelVersion')

**Comment by bia-pain-bache** [comment]
Please try again, a bug fixed right now...

**Comment by heven18** [comment]
> Please try again, a bug fixed right now...

still not work

**Comment by bia-pain-bache** [comment]
I mean deploy another one please, the bug has beed fixed.
