### ISSUE TITLE
Environment variables (advanced)

### ISSUE THREAD

**Issue by mostafacpr** [bia-pain-bache/BPB-Worker-Panel#16]
سلام ارادت
ضمن خسته نباشین و تشکر از زحماتتون
من برای تغییر آی پی و uuid این مسیر رو تو تضیحاتتون پیدا نمیکنم یا توکلود فلر تغییر کرده یا من پیدا نکردم اگه میشه دقیق تر بگین

**Comment by Kazama988** [comment]
سلام دوست عزیز دیگه نیازی به تغییر UUID در نسخه های جدید نیست چون پنل کاربری قابلیت رمز نگاری داره و رمزش به صورت پیشفرض admin هست که بعد که وارد شدین تغییرش بدین و اما ورود به پنل بعد از آدرس سایت /panel رو اضافه کنین تا وارد صفحه ورکر بشه

**Comment by mostafacpr** [comment]
من میخاستم آی پیم ثابت باشه آیا تو این ورژن آخر این قابلیت وجود داره ؟

**Comment by bia-pain-bache** [comment]
بله وجود داره از دو روش. لطفا آموزش رو مطالعه کنید.

**Comment by mostafacpr** [comment]
تشکر
