### ISSUE TITLE
خطای invalid domain or ip

### ISSUE THREAD

**Issue by vahidghadim** [bia-pain-bache/BPB-Worker-Panel#160]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام، این مشکل توی این ورژن به وجود اومده و توی ورژن‌های قبلی این مشکل را اصلاً نداشتم. 
وقتی می‌خوام Chain Proxy یا proxy ip رو فعال بکنم حتی با اینکه از کانفیگ و آی پی مطمئن هستم خطای invalid domain or ip دریافت می‌کنم. 
حتی مجدد با اکانت جدید هم صفحه جدید که ساختم باز هم همین مشکل برقرار بود. 
من پنل رو از طریق پیج دیپلوی کردم، به نظرت می‌تونه این علت باشه؟
برای پروکسی آی پی از همون دو لینکی که معرفی کردی استفاده می‌کردم و برای اتصال Chain Proxy از سایتی که معرفی کرده بودی استفاده می‌شد.

### Relevant log output | لاگ برنامه یا پنل

```shell
*invalid ips or domains
```

**Comment by bia-pain-bache** [comment]
سلام، هربار که جدید میسازید براش KV جدید هم بسازید.

**Comment by vahidghadim** [comment]
بله همین کار رو انجام میدم، میتونه علت این باشه که توی این ورژن چون میخوام از خود پنل ای پی رو بدم، قبول نکنه؟
چون ورژن های قبلی با پنل انجام میدادم، مشکلی نبودش.

**Comment by bia-pain-bache** [comment]
یه باگ جدید پیدا کردم که ممکنه مربوط به اون باشه، احتمالا این هفته یه آپدیت جدید میدم. گرچه همین الان هن من تست میکنم مشکلی نداره...
