### ISSUE TITLE
update panel

### ISSUE THREAD

**Issue by lord-wolf7** [bia-pain-bache/BPB-Worker-Panel#161]
### Feature description | توضیحات ویژگی

من وقتی میزنم آپدیت تو قسمت ریپازیتوری پروفایلم وقتی صفحه پنلم رفرش میکنم اتفاقی نمیوفته باید کار دیگه ای هم انجام بدم؟
چرا کانفیگ ها داخل پی سی هم پینگ میده هم کار میکنه ولی داخل گوشی پینگ پایین میده و وصل نمیشه یا قطع وصل میشه باید تنظیمات خاصی داخل گوشی انجام بدیم؟

**Comment by bia-pain-bache** [comment]
قسمت سوالات متداول رو بخونید، راهنمایی کردم. برای تنظیمات گوشی هم میتونید قسمت تنظیمات و استفاده رو مطالعه کنید‌.

**Comment by lord-wolf7** [comment]
> قسمت سوالات متداول رو بخونید، راهنمایی کردم. برای تنظیمات گوشی هم میتونید قسمت تنظیمات و استفاده رو مطالعه کنید‌.

خوندم داداش من remote dns 
https://8.8.8.8/dns-query
اینو زدم 
و قسمت vpn dns 
1.1.1.1
بصورت پیش فرض
Enable local dns >>>off
Mux >>>off
الان پینگ میگیرم ولی تلگرام کانکت نمیشه

**Comment by lord-wolf7** [comment]
> قسمت سوالات متداول رو بخونید، راهنمایی کردم. برای تنظیمات گوشی هم میتونید قسمت تنظیمات و استفاده رو مطالعه کنید‌.

داداش آیدی تلگرام یا کانال تلگرام داری ؟؟میخام دوتا اسکرین شات بدم 
t.me/Lord_wolf

**Comment by bia-pain-bache** [comment]
اگر قبلا روی همون اکانت کلادفلر ورکر داشتی احتمالا اکانتت Flag شده. با یه ایمیل جدید یه اکانت جدید بساز و استفاده کن. قبلا همین مورد رو یک نفر گزارش کرده بود و از این طریق برطرف شد.

**Comment by lord-wolf7** [comment]
> اگر قبلا روی همون اکانت کلادفلر ورکر داشتی احتمالا اکانتت Flag شده. با یه ایمیل جدید یه اکانت جدید بساز و استفاده کن. قبلا همین مورد رو یک نفر گزارش کرده بود و از این طریق برطرف شد.

داداش دمت گرم دس مریزاد مشکلم حل شد فقط دوتا سوال 
این bypass lan v bypas iran چیه باید فعال باشه یا نه؟
این دوتا سایتی که گفتی برا گرفتن آیپی هر دوتاسایت فیلتره دسترسی ندارم میتونم ازآیپی هایی که توسط اسکنر داخل پنل استفاده کنم قسمت PROXYIP CLOUDFLARE؟
چطور میشه اون اکانت از FLAG درش بیارم ؟

**Comment by bia-pain-bache** [comment]
توی آموزش‌ها همه اینها رو توضیح دادم، سایت nslookup.io در ایران فیلتر نیست، با یه نت دیگه امتحان کن. اون اسکنر مال Ip تمیز هست نه Proxy IP. اون اکانت دیگه در نمیاد.

**Comment by lord-wolf7** [comment]
> توی آموزش‌ها همه اینها رو توضیح دادم، سایت nslookup.io در ایران فیلتر نیست، با یه نت دیگه امتحان کن. اون اسکنر مال Ip تمیز هست نه Proxy IP. اون اکانت دیگه در نمیاد.

ممنون از اینکه وقت گذاشتی دمت گرم من توضیحاتت کامل خوندم ولی کاربرد bypass lanو bypass iran متوجه نشدم اون سایت با نت دیگه تست کردم اوکی بود با مخابرات فیلتره و دسترسی ندارم بهش 😘😘

**Comment by bia-pain-bache** [comment]
https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/configuration_fa.md
