### ISSUE TITLE
请问怎么同时设置ipv4的proxyIp和ipv6的proxyIp?

### ISSUE THREAD

**Issue by lyd123qw2008** [bia-pain-bache/BPB-Worker-Panel#163]
### Feature description | توضیحات ویژگی

我在proxy ip设置了一个ipv4的ip，它是一个韩国的ip，但是谷歌搜索引擎有时会把它判定为英国的ip，我看了一下节点的ipv6的ip是英国的，这与我所期望的韩国ip不一致，请问有什么解决办法吗？谢谢
![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/28444822/c581e745-32d9-4984-aeec-b6042336687d)

**Comment by bia-pain-bache** [comment]
Some ISPs have this issue, in different ip location databases they show different behaviour, you can use another one.
Also you can deploy via workers and edit proxy IPs in code. In panel you can only set one IP or you can set many IPs for a dns record and insert domain in panel.

**Comment by lyd123qw2008** [comment]
好的，我试试

**Comment by lyd123qw2008** [comment]
> Some ISPs have this issue, in different ip location databases they show different behaviour, you can use another one. Also you can deploy via workers and edit proxy IPs in code. In panel you can only set one IP or you can set many IPs for a dns record and insert domain in panel.

我是用了这个网址 [https://ipcheck.ing/?hl=en#/](https://ipcheck.ing/?hl=en#/) 对我的 ip 进行了检测，发现有些地方和我期望的不太一致，不知道作者未来是否会改善这些方面：
我用的 proxy ip 是 146.56.132.247。
1. 检测出来的 ipv4 与 ipv6 的归属地不一致。
![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/28444822/ab7dd3b9-e968-4827-85d1-af906fd3c8d7)
2. webrtc 测试返回了我的真实 ip。
![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/28444822/fc4aea70-e69e-4e79-8875-cdc5528063aa)
3. dns 检测的出口地区，不是我的 proxy ip 所在地区。
![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/28444822/bbfb2948-62dc-4194-a681-6a1e19e38348)

**Comment by lyd123qw2008** [comment]
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
As I told, it's a known inconsistency related to some providers. the proxy IP you used is from an provider which has this issue. There's nothing I can do about it, you have to choose a proxy IP from a known solid provider like Hetzner or Oracle...

**Comment by lyd123qw2008** [comment]
好的，我试试别的
