### ISSUE TITLE
 Something went wrong! 

### ISSUE THREAD

**Issue by aespa6177** [bia-pain-bache/BPB-Worker-Panel#164]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

BPB Panel 2.4.4 💦
Something went wrong!
⚠️ Cannot read properties of undefined (reading 'vnext')

### Relevant log output | لاگ برنامه یا پنل

```shell
BPB Panel 2.4.4 💦
Something went wrong!
⚠️ Cannot read properties of undefined (reading 'vnext')
```

**Comment by MorfiWifi** [comment]
تمام پورت های ssl رو بردارید و فقط پورت 80 رو باز بگذارید. تا این خطا رخ بدهد.
