### ISSUE TITLE
File worker.js does not exist

### ISSUE THREAD

**Issue by Airuop** [bia-pain-bache/BPB-Worker-Panel#167]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

2.4.5 File worker.js does not exist

### Relevant log output | لاگ برنامه یا پنل

```shell
_
```

**Comment by bia-pain-bache** [comment]
It's there now. please wait for release.
