### ISSUE TITLE
مشکل در Chain Proxy

### ISSUE THREAD

**Issue by DaashIman** [bia-pain-bache/BPB-Worker-Panel#168]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود
بنده طبق آموزش و برای ثابت موندن IP از طریق Chain Proxy یک کانفیگ از پنل شخصیم وارد کردم.
حالا میخوام حذفش کنم و مثل سابق قسمت Chain Proxy رو خالی بگذارم اما هر چی حذفش میکنم و Apply Settings رو میزنم، مجددا اون کانفیگ توی قسمت Chain Proxy بازنویسی میشه!

چظور میتونم پنل رو ریست کنم به تنظیمات خام خودش؟

در واقع قبل از آپدیت و قبل از وارد کردن کانفیگ در Chain Proxy کانفیگ ها عالی و پرسرعت بودن. الان همه جز Workerless از کار افتادن.
کانفیگ شخصیم از یه پنل فیلتر شده در ایران اما ساالم بوده.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

آپدیت پنل در گیتهاب به آخرین نسخه ی فعلی 2.4.4

### Relevant log output | لاگ برنامه یا پنل

```shell
Not Exist
```

**Comment by DaashIman** [comment]
در واقع قبل از آپدیت و قبل از وارد کردن کانفیگ در Chain Proxy کانفیگ ها عالی و پرسرعت بودن. الان همه جز Workerless از کار افتادن.
کانفیگ شخصیم از یه پنل فیلتر شده در ایران اما ساالم بوده.

**Comment by bia-pain-bache** [comment]
سلام،
باگ بود، در نسخه جدید برطرف شده. احتمالا امروز منتشر میشه.
