### ISSUE TITLE
سوال در مورد پروتکل sing box

### ISSUE THREAD

**Issue by hameed-maleki** [bia-pain-bache/BPB-Worker-Panel#169]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

چرا در پروتکل سینگ باکس در صورتی که ما دمین و حتی خود ورکر رو از کلادفلر  به طور کامل حذف کنیم داخل سینگ باکس هنوز اتصال برقرار هست و همه چی کار میکنه  و فقط اپدیت نمیشه؟
خیلی برام عجیب بود 

### Relevant log output | لاگ برنامه یا پنل

```shell
بدون لاگ
```

**Comment by bia-pain-bache** [comment]
بخاطر کش‌های کلادفلر هست. حتی بعضی وقتی KV رو پاک کنید تا چندوقت پنل بالا میاد.
