### ISSUE TITLE
2.4.5 -  New Version Configurations Do Not Work in Streisand Application

### ISSUE THREAD

**Issue by Airuop** [bia-pain-bache/BPB-Worker-Panel#170]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

2.4.5 Latest version of Config does not work in Streisand application 

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1 - import config
2 - select config and connect (warp and fragment config)
3 - show VPN icon, but reset connection after a second 

### Relevant log output | لاگ برنامه یا پنل

```shell
Not logged
```

**Comment by bia-pain-bache** [comment]
ظاهرا مشکل اپلیکیشن هست، هیچ موردی نداشتیم تا الان. متاسفانه اینجور مشکل‌ها که لاگ نداریم از دست من کاری برنمیاد.
