### ISSUE TITLE
Cannot be opened after deployment using uploaded zip archive

### ISSUE THREAD

**Issue by DbuyCN** [bia-pain-bache/BPB-Worker-Panel#171]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Cannot be opened after deployment using uploaded zip archive

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Cannot be opened after deployment using uploaded zip archive

### Relevant log output | لاگ برنامه یا پنل

```shell
Cannot be opened after deployment using uploaded zip archive
```

**Comment by DbuyCN** [comment]
Page display
HTTP ERROR 404

**Comment by DbuyCN** [comment]
2.4.3 is OK. 
2.4.4 and 2.4.5 display 404 error.

**Comment by bia-pain-bache** [comment]
This is due to cloudflare pages DNS and happens time to time. after deployment refresh many times or wait for some minutes, it wil be fixed.
