### ISSUE TITLE
ایجاد واپ در وارپ

### ISSUE THREAD

**Issue by esa-esa** [bia-pain-bache/BPB-Worker-Panel#172]
### Feature description | توضیحات ویژگی

متاسفانه وارپ با ip4 بسته شده و در سیستم wifi آی پی 6 فعال نیست با تشکر در صورت امکان وارپ در وارپ را فعال کنید

**Comment by bia-pain-bache** [comment]
تغییرات اپراتور به پنل مربوط نیست، وارپ در وارپ به اسم WoW هست توی کانفیگا.
