### ISSUE TITLE
پلی نشدن ویديوهای twitch

### ISSUE THREAD

**Issue by arminmacx** [bia-pain-bache/BPB-Worker-Panel#175]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با سلام تشکر از برنامه خوبتون

من بعد از نصب نمیتونم ویديوهای twitch رو ببینم. سایت twitch باز میشه ولی زمان پلی خطای مشکل در network میده.
با IP ثابت برای proxyip هم رفتم باز همین مشکل هست.
سایت های دیگه مثل youtube رو باز میکنه و ویديوهای پلی میشن ولی twitch نه.
اگه امکانش باشه کمک یا راهنمایی کنید ممنون میشم.
من از کانفیگهای نرمال استفاده میکنم

### Relevant log output | لاگ برنامه یا پنل

```shell
--
```

**Comment by bia-pain-bache** [comment]
متاسفانه بدون لاگ نمیتونم کمک خاصی بکنم. remote dns رو تغییر بدید به
https://8.8.8.8/dns-query 
و دوباره تست کنید.

**Comment by arminmacx** [comment]
> متاسفانه بدون لاگ نمیتونم کمک خاصی بکنم. remote dns رو تغییر بدید به https://8.8.8.8/dns-query و دوباره تست کنید.

لاگ روی cloudflare رو منظورتون هست یا لاگ نرم افزاری که دارم وصل میشم؟.
اگه لاگ پیج رو میگین چون نمیدونم چجوری باید دانلود کنم راهنمایی بفرمایید براتون ارسال کنم اگر هم لاگ برنامه می خواین که اون رو براتون بفرستم

**Comment by bia-pain-bache** [comment]
نه لاگ برنامه، از لحظه‌ای که ویدئو رو پخش میکنید، احتمالا داخل لاگ بتونید نام دامنه‌های twitch رو ببینید.

**Comment by arminmacx** [comment]
![Screenshot 2024-07-18 162016](https://github.com/user-attachments/assets/96c57649-0c7e-481a-9afb-fede67fa5f36)
این چیزیه که زمان لود ویدئو نشون میده. اگر جای دیگه ای رو باید ببینم بهم بگید

**Comment by bia-pain-bache** [comment]
این لاگ مرورگره، منظورم لاگ اپلیکیشن بود، ولی حدس میزنم به بلاک شدن تبلیغات حساسه. از routing بلاک تبلیغات رو غیرفعال کنید، با v2rayng ساب رو آپدیت کنید و  تست کنید ببینید مشکل برطرف میشه یا نه.

**Comment by arminmacx** [comment]
> این لاگ مرورگره، منظورم لاگ اپلیکیشن بود، ولی حدس میزنم به بلاک شدن تبلیغات حساسه. از routing بلاک تبلیغات رو غیرفعال کنید، با v2rayng ساب رو آپدیت کنید و تست کنید ببینید مشکل برطرف میشه یا نه.

اتفاقا منم اول گفتم شاید بخاطره adblocker روی کروم بوده باشه که adblocker رو disable کردم بازم نشد.
من اصلا بلاک تبلیغات رو تو پنل فعال نکردم

**Comment by bia-pain-bache** [comment]
خود remote DNS توی پنل پیشفرض Adguard هست. تغییرش بده به https://8.8.8.8/dns-query ببین فرقی میکنه؟

**Comment by arminmacx** [comment]
> خود remote DNS توی پنل پیشفرض Adguard هست. تغییرش بده به https://8.8.8.8/dns-query ببین فرقی میکنه؟

این کار رو همون اول انجام دادم بازم فرقی نمیکنه. حتی با dns های متفاوت هم تست کردم بازم نشد

**Comment by bia-pain-bache** [comment]
حق با شماست، حواسم نبود. آخرین چیزی که به ذهنم میرسه Proxy IP هست، سعی کنید یه دونه اروپایی پیدا کنید و ست کنید و امتحان کنید، راه دیگه‌ای به ذهنم نمیرسه متاسفانه.

**Comment by arminmacx** [comment]
> حق با شماست، حواسم نبود. آخرین چیزی که به ذهنم میرسه Proxy IP هست، سعی کنید یه دونه اروپایی پیدا کنید و ست کنید و امتحان کنید، راه دیگه‌ای به ذهنم نمیرسه متاسفانه.

خوب گویا تغییر proxyIP مشکل رو فعلا حل کرد و ویدئوها پلی میشن فعلا تست میکنم چند روز بعد دوباره گزارش میدم که ایا مشکل پیش میاد یا نه.
فعلا اینجا رو نمیبندم تا پند روز اینده که نتیجه رو اعلام کنم

**Comment by arminmacx** [comment]
خوب بازم مشکل حتی با عوض کردن proxyip ادامه داره و فقط برای چند دقیقه کار کرد. حالا بازم سعی میکنم ببینم میشه ip دیگه ای پیدا کرد یا نه

**Comment by bia-pain-bache** [comment]
حدس میزدم مشکل همونه، پیدا کردن Proxy ip که قبلا ازش سواستفاده نشده باشه یه کم سخته، اون لینکایی که من گذاشتم چون IP هاش عمومی هستن احتمالش کمه سالم پیدا کنی. از روش chain proxy شاید سریعتر کارت راه بیافته.

**Comment by lmahdiyar85l** [comment]
![0000](https://github.com/user-attachments/assets/6aedcf24-e277-452e-9ea7-ec450e905672)
سلام برای تویچ روی کیفیت source مشکل داره دقت کن روی این کیفیت نباشه ،تویچ پشت کلادفلر نیست ربطی به Proxy ip  نداره

**Comment by arminmacx** [comment]
> حدس میزدم مشکل همونه، پیدا کردن Proxy ip که قبلا ازش سواستفاده نشده باشه یه کم سخته، اون لینکایی که من گذاشتم چون IP هاش عمومی هستن احتمالش کمه سالم پیدا کنی. از روش chain proxy شاید سریعتر کارت راه بیافته.

من ip  سرور خودمم که تمی هست و جز خودم هیچکس دیگه وصل نمیشه بهش رو هم گذاشتم فرقی نکرد.



> ![0000](https://private-user-images.githubusercontent.com/128718326/350970462-6aedcf24-e277-452e-9ea7-ec450e905672.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTg4NjgsIm5iZiI6MTcyMTY1ODU2OCwicGF0aCI6Ii8xMjg3MTgzMjYvMzUwOTcwNDYyLTZhZWRjZjI0LWUyNzctNDUyZS05ZWE3LWVjNDUwZTkwNTY3Mi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNDI5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjE1YzA4YjA1ZDBkNWViYjFlM2IxZThmNzVkYjI5Y2MxMDY3NmU2YzFlMmQ3NTE2YjIyNDUyNDNkMDEzOTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1J_Ur1jzcgGIbt6Tc92jBKJb9_Iuw6VFb3mDDPlKss) سلام برای تویچ روی کیفیت source مشکل داره دقت کن روی این کیفیت نباشه ،تویچ پشت کلادفلر نیست ربطی به Proxy ip نداره

کلا نباید این مشکل باشه چون یک موقع روی یک سری ip برای چند دقیقه اوکی هست بد دوباره خراب میشه.

**Comment by bia-pain-bache** [comment]
هر IP که نمیتونه Proxy IP باشه! تو آموزش دو تا لینک گذاشتم، باز کنید یکیشو انتخاب کنید.

**Comment by arminmacx** [comment]
> هر IP که نمیتونه Proxy IP باشه! تو آموزش دو تا لینک گذاشتم، باز کنید یکیشو انتخاب کنید.

میشه گفت 90% ip چک کردم همین مشکل هست

**Comment by bia-pain-bache** [comment]
خب من بالاخره خودم رفتم تست کردم، دوستمون درست میگفت، روی 1080p60 network error میده.

**Comment by arminmacx** [comment]
> خب من بالاخره خودم رفتم تست کردم، دوستمون درست میگفت، روی 1080p60 network error میده.

بله منم تست کردم روی اون کیفیت ارور میده ولی چراش هنوز نتونستم پیدا کنم چون یه موقع هایی کار میکنه برای چند دقیقه ولی 99% مواقع نه

**Comment by bia-pain-bache** [comment]
چون اینترنت شما نمیتونه برای اون کیفیت به اندازه کافی بافر کنه.

**Comment by lmahdiyar85l** [comment]
نمیدونم تفاوت کیفیتی که جلوش نوشته source با حالتی که ننوشته چیه ولی هر چیزی هست ورکر(خود کلادفلر) نمیتونه این موضوع رو هندل کنه مثل udp رو نمیتونه هندل کنه (شایدم خود تویچ روی شبکه کلادفلر(ip) کیفیت source محدودیت گذاشته)،البته شاید یه کاری کرد برای تویچ از proxy ip استفاده کنه مشکل حل بشه ، ولی در کل اینترنتمون نه حجمی نه سرعتی زیاد مناسب 1080 نیست 😄 همون 720 کفایت میکنه .

**Comment by bia-pain-bache** [comment]
مساله اینه اون ۱۰۸۰ نیست! 1080p60 هست، ینی 60fps هست بخاطر همین هم به پینگ پایین نیاز داره هم پهنای باند خوب. با کانفیگ workerless تحت وب امتحان کنید با اینترنتی که مثلا تا ۲۰ میگ دانلود میده، پینگش هم توی اپ نهایتا ۴۵۰ باشه. احتمالا پخش کنه.

**Comment by arminmacx** [comment]
> چون اینترنت شما نمیتونه برای اون کیفیت به اندازه کافی بافر کنه.

والا من تا امروز از سرور خودم که استفاده میکنم همش روی همون 1080 source نگاه میکنم اینترنتم هم زیتل هست. ولی باید دید که چرا تویچ وقتی روی او کیفیت میزاریم وقتی از cloudflare استفاده میکنیم گیر میده

**Comment by arminmacx** [comment]
> من همه جوره تست کردم نهایت بیتریت مورد نیاز برای همون 60 فریم 1080 طبق مستندات خود تویچ 6000kbps هستش https://help.twitch.tv/s/article/broadcasting-guidelines?language=en_US ![bitrate](https://private-user-images.githubusercontent.com/128718326/351317662-a3c967f5-a7fd-46a1-a0c3-ff8bfdb4fa81.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzgyOTEsIm5iZiI6MTcyMTczNzk5MSwicGF0aCI6Ii8xMjg3MTgzMjYvMzUxMzE3NjYyLWEzYzk2N2Y1LWE3ZmQtNDZhMS1hMGMzLWZmOGJmZGI0ZmE4MS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMjMzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTBlZDhkOWQzNWY5ZDNmODE5MGU2ZDUxMjRlN2IwYzljYTNhNmNhNDkyNjQ3NDk1ZmI1OTFhMWM2OGI1YzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-TvukNt4URYOWI5e7Xp6bK3iHXjnNczVEzLvDDAnm0o) اینم نمونه 720 source : که با ورکر -دقت کن source نباشه پلی میشه ولی بره source پلی نمیشه ![720 source](https://private-user-images.githubusercontent.com/128718326/351318946-7241e3d0-492c-4fb5-9a9e-0aa636a8772c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzgyOTEsIm5iZiI6MTcyMTczNzk5MSwicGF0aCI6Ii8xMjg3MTgzMjYvMzUxMzE4OTQ2LTcyNDFlM2QwLTQ5MmMtNGZiNS05YTllLTBhYTYzNmE4NzcyYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMjMzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjVmN2RkNmVlOWNiZWQwNjc0M2JkMzM3YTM0NDZiZjY5YWIyN2NkMDc5NjBhNDE4ODg0Yjc0YjdhMzA5ZGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u6XwpifMYfITe1drs2wGjBKV4MNJ8oadGq-21qw3ys4) حدس من اینه که کدک هاشون متفاوته که نمیدونم میتونه ربطی به ورکر داشته باشه که اینو نمیتونه مثلا بخونه codec source : avc1.64002A,mp4a.40.2 Codec not source : avc1.4D401F,mp4a.40.2 پس یه جمع بندی کنم حرفامو با کانفیگ ورکر نمیشه کیفت هایی که source هست رو پلی کرد ولی میشه 1080p60 که source نباشه پلی کرد یه نکته هم که هست اینه که سرور های پخش تویچ مثل اینکه فیلتر نیست شما vpn رو خاموش کنی پلی کنی پخش میشه ولی چت نمیتونی بکنی اون قطع میشه ولی در کل به نظرم این از دست منو شما خارجه بر میگرده به خود کلادفلر ببخشید یکم نامرتب گفتم خواستم اگه شد بشه کمکی کرد

اره فکر میکنم ورکر یا پیچ نمیتونه یا یه مشکلی ایجاد میکنن سر همین قضیه. فعلا با همون کیفیت 720 زمانی که سرور خودم قطع کنن نگاه میکنم زمانی که قطع نکنن 1080 🤣
