### ISSUE TITLE
可以支持 clash 订阅吗？

### ISSUE THREAD

**Issue by kingkongdog** [bia-pain-bache/BPB-Worker-Panel#178]
### Feature description | توضیحات ویژگی

可以支持 clash 订阅吗？

**Comment by wwt519** [comment]
可以的，正常用

**Comment by baidu169msn** [comment]
> 可以的，正常用

q请问如何使用?

**Comment by bia-pain-bache** [comment]
I wasn't planning to implement it right now, due to minority of it's community. However maybe in long-term...

**Comment by kingkongdog** [comment]
> I wasn't planning to implement it right now, due to minority of it's community. However maybe in long-term...

OK. Thanks！
