### ISSUE TITLE
Disable IPV6

### ISSUE THREAD

**Issue by presolve0** [bia-pain-bache/BPB-Worker-Panel#179]
### Feature description | توضیحات ویژگی

گزینه ای برای غیرفعال کردن کانفیگ های IPV6 یا نشون ندادن اونها در subscription

**Comment by bia-pain-bache** [comment]
دلیل درخواستتون چیه؟

**Comment by bia-pain-bache** [comment]
بله فقط روی ایرانسل و آسیاتک کار میکنه.

**Comment by bia-pain-bache** [comment]
من توجیه منطقی‌ای براش پیدا نمیکنم که چرا باید چنین چیزی به پنل اضافه بشه. هر کس دوست نداره میتونه اون دو تا کانفیگ رو استفاده نکنه. هدف اولیه این پنل سادگی و مینیمال بودن بوده که کاربرای مبتدی گیج نشن، همین الان هم بخاطر وارپ که جدیدا اضافه شده پنل شلوغتر از چیزی شده که مدنظرم بوده، نمیتونم برای چنین مواردی فیچر اضافه کنم.
