### ISSUE TITLE
用cloudflare搭建的BPB面板节点导入shadowrocket后没有显示国家旗帜

### ISSUE THREAD

**Issue by liangfengquhe** [bia-pain-bache/BPB-Worker-Panel#181]
### Feature description | توضیحات ویژگی

用cloudflare搭建的BPB面板节点导入shadowrocket后没有显示国家旗帜，这是特点吗

**Comment by bia-pain-bache** [comment]
it doesnt have flags basically because nodes from default panel setup return many IPs from many locations. Even if you use proxy ip you will have two ips, one for domains which are not using cloudflare and one for domains using it. So somehow it is not rational.

**Comment by liangfengquhe** [comment]
多谢您的解惑，十分感谢发自我的 iPhone在 2024年7月19日，16:56，bia-pain-bache ***@***.***> 写道：﻿
it doesnt have flags basically because nodes from default panel setup return many IPs from many locations. Even if you use proxy ip you will have two ips, one for domains which are not using cloudflare and one for domains using it. So somehow it is not rational.

**Comment by liangfengquhe** [comment]
﻿
发自我的 iPhone

发自我的 iPhone
