### ISSUE TITLE
ارور Service Failure در سرور WorkerLess

### ISSUE THREAD

**Issue by nissanskyliner34g** [bia-pain-bache/BPB-Worker-Panel#182]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وصل نشدن ورکر لس

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

ارور Service Failure در هنگام اجرای سرور Workerless که با Start Service و بعد ارور Service Start Failure میاد ولی بقیه سرور ها بدون هیچ مشکلی اجرا میشن

### Relevant log output | لاگ برنامه یا پنل

```shell
--------- beginning of main
07-19 16:08:34.720 I/GoLog   ( 6121): loading core config
07-19 16:08:34.721 I/GoLog   ( 6121): Preparing Domain: google.com:443
07-19 16:08:34.748 I/GoLog   ( 6121): Prepare Result:
07-19 16:08:34.748 I/GoLog   ( 6121):  Domain: google.com
07-19 16:08:34.748 I/GoLog   ( 6121):  Port: 443
07-19 16:08:34.748 I/GoLog   ( 6121):  IPs: [2a00:1450:4019:80b::200e]
07-19 16:08:35.162 I/GoLog   ( 6121): new core
07-19 16:08:35.408 I/GoLog   ( 6121): app/router: this rule has no effective fields
07-19 16:08:35.409 D/com.v2ray.ang( 6121): go.Universe$proxyerror: app/router: this rule has no effective fields
```

**Comment by bia-pain-bache** [comment]
لطفا prefer ipv6 رو غیرفعال کنید، اگر باز هم نشد enable local dns رو فعال کنید.

**Comment by nissanskyliner34g** [comment]
--------- beginning of main
07-19 17:03:53.772 I/GoLog   (10212): loading core config
07-19 17:03:53.773 I/GoLog   (10212): Preparing Domain: google.com:443
07-19 17:03:53.778 I/GoLog   (10212): PrepareDomain err: lookup google.com: no such host
07-19 17:03:54.123 I/GoLog   (10212): new core
07-19 17:03:54.281 I/GoLog   (10212): app/router: this rule has no effective fields
07-19 17:03:54.282 D/com.v2ray.ang(10212): go.Universe$proxyerror: app/router: this rule has no effective fields
07-19 17:03:55.782 I/GoLog   (10212): PrepareDomain err: lookup google.com: no such host
07-19 17:03:57.787 I/GoLog   (10212): PrepareDomain err: lookup google.com: no such host
07-19 17:03:59.792 I/GoLog   (10212): PrepareDomain err: lookup google.com: no such host
07-19 17:04:01.796 I/GoLog   (10212): PrepareDomain err: lookup google.com: no such host



ipv6 هم غیرفعال بوده
LocalDns هم خاموش بوده روشن کردم و این لوگ سرور و Local DNS port : 10853

**Comment by nissanskyliner34g** [comment]
(این لوگ با اینترنت فیبرنوری مخابرات و روشن بودن Local DNS و خاموش بودن Ipv6)

--------- beginning of main
07-19 17:36:11.482 I/GoLog   (27014): loading core config
07-19 17:36:11.482 I/GoLog   (27014): Preparing Domain: google.com:443
07-19 17:36:11.485 I/GoLog   (27014): Prepare Result:
07-19 17:36:11.485 I/GoLog   (27014):  Domain: google.com
07-19 17:36:11.485 I/GoLog   (27014):  Port: 443
07-19 17:36:11.485 I/GoLog   (27014):  IPs: [2001:4860:4802:32::78]
07-19 17:36:11.657 I/GoLog   (27014): new core
07-19 17:36:11.809 I/GoLog   (27014): app/router: this rule has no effective fields
07-19 17:36:11.809 D/com.v2ray.ang(27014): go.Universe$proxyerror: app/router: this rule has no effective fields




(این لوگ هم با اینترنت همراه اول با روشن بودن Local DNS و خاموش بودن Ipv6 )

--------- beginning of main
07-19 17:37:08.956 I/GoLog   (27810): loading core config
07-19 17:37:08.956 I/GoLog   (27810): Preparing Domain: google.com:443
07-19 17:37:09.009 I/GoLog   (27810): Prepare Result:
07-19 17:37:09.009 I/GoLog   (27810):  Domain: google.com
07-19 17:37:09.009 I/GoLog   (27810):  Port: 443
07-19 17:37:09.009 I/GoLog   (27810):  IPs: [216.239.38.120 2001:4860:4802:32::78]
07-19 17:37:09.145 I/GoLog   (27810): new core
07-19 17:37:09.317 I/GoLog   (27810): app/router: this rule has no effective fields
07-19 17:37:09.317 D/com.v2ray.ang(27810): go.Universe$proxyerror: app/router: this rule has no effective fields

**Comment by bia-pain-bache** [comment]
نکته‌ی عجیب اینه که فقط داره ipv6 گوگل رو پیدا میکنه! شما apn سیمکارت رو گذاشتی روی ipv6؟ 
داخل پنل local dns رو بذارید localhost و ساب رو آپدیت کنید ببینید بازم همینه وضعیت؟
پیشنهاد میکنم برنامه حتما آخرین ورژن باشه و کش رو یه بار پاک کنید.

**Comment by nissanskyliner34g** [comment]
تنظیمات apn سیم‌کارت روی ipv4/ipv6 هست من قبل اینکه بیام issue بزارم تو گیتهاب یدفعه ساب رو پاک کردم و دوباره ساب گذاشتم تو v2ray و بازهم نشد در ادامه و قبلا هم در آپدیت bpb panel که آموزشش رو تو ایکس منتشر کردید هم عمل کردم و همون اول هم نسبت به تغییر local DNS به localhost هم انجام داده ام

**Comment by bia-pain-bache** [comment]
این چیزی که من میبینم DNS cache میتونه باشه. احتمالا با clear cache، clear data، پاک کردن و نصب دوباره‌ی v2ray درست بشه، ولی قطعی نمیتونم بگم. ورژن پنل هم حتما آخری ۲.۴.۵
