### ISSUE TITLE
ارور ورکرلس

### ISSUE THREAD

**Issue by nissanskyliner34g** [bia-pain-bache/BPB-Worker-Panel#183]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وصل نشدن ورکر لس

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

ارور Service Failure در هنگام اجرای سرور Workerless که با Start Service و بعد ارور Service Start Failure میاد ولی بقیه سرور ها بدون هیچ مشکلی اجرا میشن

### Relevant log output | لاگ برنامه یا پنل

```shell
--------- beginning of main
07-19 16:14:38.284 I/GoLog   (19778): loading core config
07-19 16:14:38.285 I/GoLog   (19778): Preparing Domain: google.com:443
07-19 16:14:38.287 I/GoLog   (19778): PrepareDomain err: lookup google.com: no such host
07-19 16:14:38.537 I/GoLog   (19778): new core
07-19 16:14:38.705 I/GoLog   (19778): app/router: this rule has no effective fields
07-19 16:14:38.705 D/com.v2ray.ang(19778): go.Universe$proxyerror: app/router: this rule has no effective fields
07-19 16:14:40.292 I/GoLog   (19778): PrepareDomain err: lookup google.com: no such host
07-19 16:14:42.301 I/GoLog   (19778): PrepareDomain err: lookup google.com: no such host
07-19 16:14:44.311 I/GoLog   (19778): PrepareDomain err: lookup google.com: no such host
```

**Comment by bia-pain-bache** [comment]
لطفا از تنظیمات enable local dns رو فعال کنید و نتیجه رو بگید.

**Comment by h-a-m-i-d** [comment]
enable local dns توی کدوم قسمت از تنظیماته؟

**Comment by h-a-m-i-d** [comment]
> لطفا از تنظیمات enable local dns رو فعال کنید و نتیجه رو بگید.


enable local dns توی کدوم قسمت از تنظیماته؟
