### ISSUE TITLE
BPB-Worker-Panel 面板 严重信息泄露漏洞曝光

### ISSUE THREAD

**Issue by ddan889** [bia-pain-bache/BPB-Worker-Panel#187]
### Feature description | توضیحات ویژگی

泄露问题整理
默认反代www.speedtest.net（泄露项目地址，使其该项目网站便于采集，且有封号危险）
默认面板弱口令admin（未强制修改面板密码，且该密码无法修改实际负责订阅的UUID，导致无密码也可以绕过并成功获取订阅）
默认UUID89b3cbba-e6ac-485a-9481-976a0415eab9（无法通过管理面板修改UUID，导致修改面板密码也无法阻止获取默认订阅）油管频道：https://youtu.be/uYFqLASLfbI?si=yBTYpz3J7sJlRT_2

**Comment by bia-pain-bache** [comment]
there is a documentation with explains all of mentioned concerns. you can change uuid and password. Also there is no limitations on pages deployments regarding traffic or resources and besides there is no personal info which could be obtained even if subscription is compromised. So please translate docs and setup it regarding your concerns.
