### ISSUE TITLE
v2.3.2 problem

### ISSUE THREAD

**Issue by badmast** [bia-pain-bache/BPB-Worker-Panel#19]
![image](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/45063563/29a02aee-c10a-4a79-b760-529a8bbe54aa)

**Comment by bia-pain-bache** [comment]
Someone else told me this before, although it's not a comprehensive problem. I don't even know what's the reason! have you ever tried downloading another js files from git?

**Comment by ParhamzXc** [comment]
doesn't matter. even tagged as severe, non happens unless you run it on your device localhost, you need Visual studio and json plugin debugger to run it. Next time just simply copy the code mb??? Copy then paste into cloudflare worker playground.

**Comment by ParhamzXc** [comment]
rename it to _worker.js it can't be detect even if you write malware or bad script in it

**Comment by bia-pain-bache** [comment]
Unfortunately windows security is sensitive to it, also changing the filename would make it hard to mobile deployment. So for now please deactivate Windows security temporarily.
