### ISSUE TITLE
استفاده از آی پی مستقیم به جای دامنه

### ISSUE THREAD

**Issue by AlirezaMoseni** [bia-pain-bache/BPB-Worker-Panel#20]
سلام. اولا ممنون بابت زحماتت. یه سوال/پیشنهاد داشتم. تو توییتر میدیدم به خیلی از کسایی که مشکل اتصال داشتن، میگفتی که مشکل dns شونه. خواستم ببینم دلیل خاصی داره که مستقیما از آی پی های کلادفلر استفاده نمیکنی؟ (مثلا به خاطر proxyIP؟)
من از پارسال تا حالا یه سرور پشت کلادفلر دارم و تو سابسکریپشن تعداد زیادی کانفیگ با آی پی کلادفلر برمیگردوندم. تحت کلاینت تست میگرفتم و به بهترینش وصل میشدم و تا حالا مشکلی نداشتم. الانم که دیگه با observer/balancer ترکیبش کردم و همونم اتوماتیک شده.
خواستم پیشنهاد کنم شما هم همینکار رو انجام بدی outboundهای زیادی با آی پی های مختلف تولید کنی و بسپری به observer که clean Ip رو پیدا کنه. مشکلی هم برای dns وجود نداره دیگه. proxyIP هم که با chain کردن حل میشه
من یه نمونه اش رو هم برات اینجا آماده کردم خواستی تست بگیری.
https://ctxt.io/2/AADImv4tFg

**Comment by bia-pain-bache** [comment]
سلام ممنونم از پیشنهادت، کانفیگ Best Ping دقیقا همین کارو میکنه و چند ماه پیش به پنل اضافه شده.
در مورد DNS مساله‌ای که هست بخاطر ورکره، DNS خود کلادفلر روی اپ‌های با هسته Xray پینگ هندشیک رو با ورکر میبرن بالا. اپ‌های با هسته Sing-box هم با ورکر با این DNS به مشکل میخورن و مثلا وبگردی مختل میشه.
