### ISSUE TITLE
نرمال کانفیگ کار نمی کنه

### ISSUE THREAD

**Issue by HASHHman** [bia-pain-bache/BPB-Worker-Panel#208]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام خدا قوت
چند روزیه نرمال کانفیگ ها کار نمی کنه. 
از nekoray استفاده می کنم. لاگ های کور سینگ باکس (با کانفیگ سینگ باکس نکوری) و کور اکس ری (با کانفیگ اکس ری) رو فرستادم. 
با یه اکانت کلود فلر دیگه هم تست کردم همین مشکلو داره.
![FireShot Capture 001 - BPB Panel 2 4 5 - bpb-test pages dev](https://github.com/user-attachments/assets/46067f03-91d5-4870-84d9-c62a6f12e986)

### Relevant log output | لاگ برنامه یا پنل

```shell
xray core:
2024/07/21 04:14:46 [Error] app/dns: failed to retrieve response for www.youtube.com. > Post "https://8.8.8.8/dns-query": context deadline exceeded
sing-box core:
ERROR[0011] [392602728 10.0s] dns: lookup failed for www.youtube.com: exchange6: Post "https://8.8.8.8/dns-query": context canceled | exchange4: context canceled | upstream: context deadline exceeded
```

**Comment by HASHHman** [comment]
@bia-pain-bache هیچ نظری دارید چرا این ارور رو می ده؟
کانفیگ های [VLESS barry-far](https://github.com/barry-far/V2ray-Configs) کار می کنه برام

**Comment by bia-pain-bache** [comment]
سلام ممنون،
نکوری خیلی مشکل DNS داره، تنظیمات زیر رو تست کنید:
local dns: 8.8.8.8 
یا روی هسته xray بذارید localhost و هسته singbox بذارید local.
میتونید از فورک مهدی زارعی هم استفاده کنید ولی هسته xray نداره.

**Comment by HASHHman** [comment]
تشکر برای جواب
الان با هسته xray و نکوری این ارور رو میده:
```
2024/07/22 09:57:52 [Warning] [3075851350] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://bpb-test.pages.dev/2S8f9TePYExLX9sy):  > read tcp 192.168.1.100:58146->172.66.46.208:443: i/o timeout
2024/07/22 09:57:52 [Warning] [2325511301] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://bpb-test.pages.dev/2S8f9TePYExLX9sy):  > read tcp 192.168.1.100:58130->172.66.46.208:443: i/o timeout
2024/07/22 09:57:52 tcp:127.0.0.1:46506 accepted tcp:10.202.8.220:443 [socks-in -> proxy]
2024/07/22 09:57:55 [Warning] [3749981460] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://bpb-test.pages.dev/2S8f9TePYExLX9sy):  > read tcp 192.168.1.100:47290->172.66.45.48:443: i/o timeout
2024/07/22 09:58:17 [Error] transport/internet/websocket: failed to dial to bpb-test.pages.dev:443 > read tcp 192.168.1.100:47286->172.66.45.48:443: read: connection reset by peer
```
چک کردم، UUID کانفیگ ها با UUID داخل کلودفلر یکی بود.

**Comment by bia-pain-bache** [comment]
من خودمم خیلی وقتا با نکوری به مشکل میخوردم، با آزمون و خطا برطرف میشد. تو آپدیت جدیدشم اومده کلا هسته xrayرو حذف کرده. متاسفانه برای مشکلتون چیز دیگه‌ای به ذهنم نمیرسه.

**Comment by HASHHman** [comment]
> من خودمم خیلی وقتا با نکوری به مشکل میخوردم، با آزمون و خطا برطرف میشد. تو آپدیت جدیدشم اومده کلا هسته xrayرو حذف کرده. متاسفانه برای مشکلتون چیز دیگه‌ای به ذهنم نمیرسه.

مشکل از نکوری نیست، من با اینترنت پیشگامان روی hiddify v2ran هم تست کردم همین مشکل رو داشت ولی با نت همراه اول رو نکوری مشکلی نداشتم.
با نت پیشگامان
 *.pages.dev/panel
رو برام باز می کنه. با https://check-host.net هم که تست کردم پیجم پینگ می داد.
حتی با ورکر و یا کلا با یه اکانت کلودفلر جدید هم تست کردم همین ارور رو می داد.
فک کنم پیشگان یه طرفند جدیدی زده. شما نظرت چیه؟

**Comment by bia-pain-bache** [comment]
چرا خود نکوری هم خیلی مشکل داره، ولی اگر با نت همراه مشکل نداشتید صد درصد بخاطر اپراتوره. کانفیگای فرگمنت رو هم تست کنید.
