### ISSUE TITLE
Error in nekoray with workerless config

### ISSUE THREAD

**Issue by h-a-m-i-d** [bia-pain-bache/BPB-Worker-Panel#209]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

app/router: this rule has no effective fields
این ارور برای کانفیگ ورکرلس میاد

### Relevant log output | لاگ برنامه یا پنل

```shell
>>>>>>>> Starting profile [Xray config] workerless
<<<<<<<< Failed to start profile [Xray config] workerless
```

**Comment by bia-pain-bache** [comment]
دوتا کار میشه کرد:
۱- از routing میتونید bypass iran رو غیرفعال کنید.
۲- میتونید geo asset برای Nekoray رو آپدیت کنید با اون دو تا فایل که تو آموزشها گذاشتم.
