### ISSUE TITLE
Hope to add this feature

### ISSUE THREAD

**Issue by bike3097a** [bia-pain-bache/BPB-Worker-Panel#216]
### Feature description | توضیحات ویژگی

https://github.com/XTLS/Xray-core/releases/tag/v1.8.21

At present, xray core updates are frequent, and we hope to synchronize updates. Thank you

**Comment by bia-pain-bache** [comment]
Xray core updates will be implemented on client applications, besides I will reflect any changes related to protocol on worker. Right now there's not any.
