### ISSUE TITLE
اجبار به تغییر رمز

### ISSUE THREAD

**Issue by ShadowOwlCode** [bia-pain-bache/BPB-Worker-Panel#220]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام وقت بخیر.
بسیار پنل خوبی دارید و ممنون از زحمتی که میکشید
یک مورد امنیتی هست در پنل و اونم اجبار به تغییر رمز هست.
در صورتی که کاربر رمز اولیه تغییر نده بسیار راحت میشه از بخش فورک های ریپازتوی شما وارد پنل هایی که با روش Pages ساخته شدن شد.
 بهترین حالت فقط 40 درصد کاربران تغییر رمز admin رو انجام میدن.
 
 ممنون از پنل خوبتون

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Go to fork
2. find new fork update
3. check details of last run
4. find cloudflare pages(image)
5. add /panel
6. use default password "admin"

![image](https://github.com/user-attachments/assets/12c1e101-8fe1-42b7-a3a0-1035e8a888dc)

### Relevant log output | لاگ برنامه یا پنل

```shell
NO LOG
```

**Comment by bia-pain-bache** [comment]
سلام،
خواهش میکنم. اتفاقا پیشنهاد خوبیه، آپدیتای بعدی لحاظ میکنم، ممنون از وقتی که گذاشتید.
