### ISSUE TITLE
کار نکردن حالت های دیگه به جز system proxy هیدیفای

### ISSUE THREAD

**Issue by kingparsa1010** [bia-pain-bache/BPB-Worker-Panel#221]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در هیدیفای به جز حالت سیستم پروکسی حالت دیگه مثل vpn mode کار نمیکند و این در حالی است که وارپ و سایر کانفیگ ها در همه حالات سالم هستند!

### Relevant log output | لاگ برنامه یا پنل

```shell
-
```

**Comment by bia-pain-bache** [comment]
باید این رو با خود تیم هیدیفای مطرح کنید، تستای من روی هیدیفای مشکلی نداشت، remote DNS رو بذارید:
https://8.8.8.8/dns-query 
و تست کنید، اگر فایده نداشت برای خودشون issue بزنید.
