### ISSUE TITLE
const proxyIPs= ['cdn.xn--b6gac.eu.org', 'cdn-all.xn--b6gac.eu.org', 'edgetunnel.anycast.eu.org'];

### ISSUE THREAD

**Issue by SorenMika** [bia-pain-bache/BPB-Worker-Panel#223]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود و وقت بخیر
ای پی های پشت این دامنه ها 
const proxyIPs= ['cdn.xn--b6gac.eu.org', 'cdn-all.xn--b6gac.eu.org', 'edgetunnel.anycast.eu.org'];
از کار افتادن 

لطفا میتونید بگید چطوری میتونیم از ای پی یا سرورهای شخصی استفاده کنیم 
ممنون میشم راهنمایی کنید

### Relevant log output | لاگ برنامه یا پنل

```shell
0
```

**Comment by bia-pain-bache** [comment]
سلام، چند روز پیش توییت زدم در موردش. از این دامین بعنوان Proxy IP استفاده کن:
bpb.yousef.isegaro.com

**Comment by liMilCo** [comment]
میشه از ای پی تمیز های کلود فلر استفاده کرد ؟
 یا حتمی باید از اون لیست باشه !

**Comment by moldavimod** [comment]
یه مشکل دیگه ای که هست اینه
توی بعضی از سایت های نمایش ای پی بهمون ای پی کلودفلر رو میده و بعضی جاها هم ای پی پروکسی رو نمایش میده

برای اینکه همه جا ای پی اصلی پروکسی رو بهمون بده و ای پی کلودفلر نده، ایا میشه مارک کنیم که تمام ترافیک از پروکسی رد بشه؟
یا روش دیگه ای داره

**Comment by Mikael1993** [comment]
سلام
وقتی توی سایت واتس مای ای پی ادرس میزنیم تا ای پی رو نمایش بده ای پی پروکسی رو نمایش میده
ولی وقتی توی گوکل سرچ میکنیم my ip  یه ای پی کلود فلر از نوع ورژن ۶ نمایش میده
۲ تا تصویر ضمیمه کردم لطفا ببینید
چیکار کنیم تا همه جا ای پی همون پروکسی رو نمایش بده، لطفا راهنمایی کنید خیلی مهم هست 
@bia-pain-bache 

![Screenshot_20240801_192904_Chrome](https://github.com/user-attachments/assets/641c28a3-efe0-49d6-b2cb-38477622f093)
![Screenshot_20240801_192911_Chrome](https://github.com/user-attachments/assets/e841da53-2246-42ed-89b5-66fc7099e12f)

**Comment by bia-pain-bache** [comment]
۱- در ورژن جدید ۲.۴.۷ کلا Proxy IP ها تغییر کردن، حتما آپدیت کنید.
۲- پروکسی IP با IP تمیز کلادفلر متفاوته.
۳- بزودی آموزش مینویسم برای اینکه خودتون بتونید اسکن.
۴- در آموزش‌ها توضیح دادم که Proxy IP فیط برای سایتای پشت کلادفلر هست. بنابراین اگر سایتی که چک میکنید پشت کلادفلر باشه این IP رو نشون در غیر اینصورت IP ورکر شما رو نشون میده که یه IP متعلق به کلادفلر هست.

**Comment by Maleka1399** [comment]
سلام @bia-pain-bache 
ایا راهی داره به سایت هایی که پشت کلادفلر نیستن هم ای پی پروکسی رو نمایش بدیم؟

**Comment by M-Sadegh-M** [comment]
> سلام @bia-pain-bache ایا راهی داره به سایت هایی که پشت کلادفلر نیستن هم ای پی پروکسی رو نمایش بدیم؟

امکانش نیست اگه میخواهید ایپی ثابت باشه، از chain proxy استفاده کنید.
یک کانفیگ رایگان که فیلتر هم باشه مبتونید وارد کنید

**Comment by moldavimod** [comment]
> > سلام @bia-pain-bache ایا راهی داره به سایت هایی که پشت کلادفلر نیستن هم ای پی پروکسی رو نمایش بدیم؟
> 
> امکانش نیست اگه میخواهید ایپی ثابت باشه، از chain proxy استفاده کنید. یک کانفیگ رایگان که فیلتر هم باشه مبتونید وارد کنید


من فکر میکنم بشه با تغییر دادن قوانین خروجی این کارو کرد
شما تست کردید این مورد رو؟

**Comment by M-Sadegh-M** [comment]
> من فکر میکنم بشه با تغییر دادن قوانین خروجی این کارو کرد شما تست کردید این مورد رو؟
خیر، بر اساس document پروژه میگم

**Comment by Redruby110** [comment]
> ۱- در ورژن جدید ۲.۴.۷ کلا Proxy IP ها تغییر کردن، حتما آپدیت کنید. ۲- پروکسی IP با IP تمیز کلادفلر متفاوته. ۳- بزودی آموزش مینویسم برای اینکه خودتون بتونید اسکن. ۴- در آموزش‌ها توضیح دادم که Proxy IP فیط برای سایتای پشت کلادفلر هست. بنابراین اگر سایتی که چک میکنید پشت کلادفلر باشه این IP رو نشون در غیر اینصورت IP ورکر شما رو نشون میده که یه IP متعلق به کلادفلر هست.

لطفا آموزش بدید برای اسکن .من ip  های دیتا سنتر کلودفلر برای ایران و اوکراین قرار میدم اما سایت هایی که HSTS دارند اجازه انتقال نمیدند
