### ISSUE TITLE
Update warp conf & proxy ip

### ISSUE THREAD

**Issue by Airuop** [bia-pain-bache/BPB-Worker-Panel#226]
### Feature description | توضیحات ویژگی

Hi there. 
Please update warp configs (adapted for new hidify 2.0.5 support) and fix default proxy IP.

**Comment by bia-pain-bache** [comment]
Hi,
Do you mean noise parameters for warp?
I'm waiting for MahsaNG to release new version which implements the same approach and then develop Panel to support both.
Default Proxy IPs are changed in 2.4.7

**Comment by Airuop** [comment]
> Hi,
> 
> Do you mean noise parameters for warp?
> 
> I'm waiting for MahsaNG to release new version which implements the same approach and then develop Panel to support both.
> 
> Default Proxy IPs are changed in 2.4.7

6 new modes have been added to Warp, ranging from m1 to m6.

**Comment by bia-pain-bache** [comment]
It's gonna be added for both Hiddify and NikaNG soon.
