### ISSUE TITLE
مشکل عدم اتصال کانفیگ در برنامه V2RAYNG

### ISSUE THREAD

**Issue by Nimamohammadi** [bia-pain-bache/BPB-Worker-Panel#228]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با سلام
وقتی از پنل کپی ساب انجام میدم، کانفیگها در برنامه هیدفای ویندوز به درستی کار میکنه ولی در برنامه هیدفای موبایل برخی از برنامه ها مثه توییتر و گوگل پلی رو باز نمیکنه. 
مشکل بعدی اینکه همین کانفیگ کپی شده اصلا وارد برنامه v2rayng نمیشه و وقتی از منو + گزینه import config from clipboard رو میزنم بعد چند ثانیه Failure میزنه.  اینم بگم هم با NORMAL CONFIGS امتحان کردم هم با FRAGMENT SUB که در هر دو حالت Failure میشه. برنامه v2rayng هم آخرین نسخه نصب روی گوشی.

### Relevant log output | لاگ برنامه یا پنل

```shell
failure in add config to v2rayng.
```

**Comment by bia-pain-bache** [comment]
سلام، در سوالات متداول توضیح داده بودم برای هیدیفای remote dns رو عوص کنید به:
https://8.8.8.8/dns-query 

با اون یه خط نمیتونم بفهمم مشکل چیه، اتصال به هر کانفیگی رو قطع کنید، لاگ برنامه رو کامل پاک کنید بعد ساب رو ایمپورت کنید هرچی توی لاگ اومد بفرستید لطفا.

**Comment by Nimamohammadi** [comment]
سلام، تشکر از شما بابت پاسخگویی.
عرض کردم خدمت شما اصلا ساب وارد برنامه v2rayng و v2rayn نمیشه که من بتونم
از لاگی که ایجاد میشه واستون چیزی بفرستم. همون اول وفتی میخام ساب رو
ایمپورت کنم ارور میده مینویسه failure.
برای هیدیفای بدون تغییر remote dns توی لپ تاپ مشکلی ندارم ولی توی گوشی فقط
تلگرام و اینستاگرام باز میشن، توییتر و فیسبوک باز نمیشه.
بازم تشکر بابت وقت و حوصله ای که بخرج میدین.


–—–—–—–—–—

*Nima Mohammadi.*

**Comment by bia-pain-bache** [comment]
خواهش میکنم، اگر ایمپورت کردن لاگ نمیندازه متاسفانه نمیتونم کمکی بکنم، میتونید ساب رو توی مرورگر باز کنید کحتویاتش رو کپی کنید تو برنامه ایمپورت کنید. مورد عجیبیه و حدس میزنم با Clear Cache و Clear Data ممکنه درست بشه.

**Comment by yamorgonesh** [comment]
سلام با وای فای کار میکنم . هر کانفینگ که اجرا میکنم اپلودش مثلا تا 200میره اما دانلود صفحه پنکه هم 1 میده ایراد کجاست چند روز پیش خوب بود یکمرتبه اینگونه شد

**Comment by yamorgonesh** [comment]
> سلام با وای فای کار میکنم . هر کانفینگ که اجرا میکنم اپلودش مثلا تا 200میره اما دانلود صفحه پنکه هم 1 میده ایراد کجاست چند روز پیش خوب بود یکمرتبه اینگونه شد

**Comment by yamorgonesh** [comment]
سلام دلیل کپی نشدن در سابقه گوشی ،،،فکر کنم و البته مطمئنم که برای حجم زیاده و هنگ میکنه من هم این مشکل رو داشتم و اون فایل ساب شما احتمالا تعداد زیادی کانفیگ داره و واسه گوشی سنگینه و کپی نمیشه پیشنهاد میدم ساب رو با مقدار کانفینگ کمتر کپی کنید حتما جواب میگیرید

**Comment by ninamoradi** [comment]
چطوری حلش کنیم😭😭😭

**Comment by m43126053-cmd** [comment]
وای کانفیگ من قطع وصلی داره قطع شده دیگه پینگ ۱ میده چیکار کنم حجم هم داره
