### ISSUE TITLE
درخواست اضافه کردن دکمه برگشت به تنظیمات پیشفرض

### ISSUE THREAD

**Issue by DarkKingTNi** [bia-pain-bache/BPB-Worker-Panel#232]
### Feature description | توضیحات ویژگی

سلام و وقت بخیر ، تشکر بابت زحماتتون
ممنون میشم یه دکمه به پنل اضافه کنید که تنظیمات اشتباهی انجام دادیم یا اینکه تغییرات غیر قابل برگشت باشن
بشه با زدن دکمه برگشت به تنظیمات پیشفرض موارد ریست بشن
با تشکر فراوان

**Comment by bia-pain-bache** [comment]
سلام ممنون، هیچکدوم گزینه‌ها غیر قابل بازگشت نیست ولی بهش فکر میکنم.
