### ISSUE TITLE
 (WorkerLess ⭐️) امکان غیرفعال کردن کانفیگ هایی مثل 

### ISSUE THREAD

**Issue by coolnum1** [bia-pain-bache/BPB-Worker-Panel#233]
### Feature description | توضیحات ویژگی

درود. من روی v2ray اندروید نصب کردم. با هر بار به روز رسانی اشتراک به صورت پیش فرض روی workerless* میره و برای افرادی که نا بلد هستن خیلی سخته (به فرض بالای نوتیفیکیشن بار براشون ویجت v2ray گذاشتم که راحت وصل بشن.ولی بعد به روز رسانی اشتراک هی میاد روی workerless) و باید از اول وارد برنامه بشن و کانفیگ دیگه ای انتخاب کنن.
لطفا این امکان  رو قرار بدین که بشه غیر فعال کرد کانفیگ هایی مثل WorkerLess ⭐️

**Comment by bia-pain-bache** [comment]
سلام، متاسفانه من نمیتونم برای کاربردهای خاص یا استثناها پنل رو تغییر بدم وگرنه الان پنل بسیار شلوغ میشد و برای افراد مبتدی گیج‌کننده.

**Comment by planetkeeper1** [comment]
سپاس از شما

**Comment by coolnum1** [comment]
سپاس از شما
