### ISSUE TITLE
درخواست اضافه کردن اضافه کردن راهنما

### ISSUE THREAD

**Issue by Glimpser-zz** [bia-pain-bache/BPB-Worker-Panel#234]
### Feature description | توضیحات ویژگی

اگر امکانش باشد که روی خود پنل برای هر آیتم توضیحات و راهنمای تنظیم آن اضافه شود خیلی برای یوزرهای عادی مفید و کمک خواهد بود.
الان مثلا آیتم 
Chain proxy 
را من چه میدانم که اصلا چی هست . چه برسد به اینکه چه مقادیری  و از کجا باید برایش پیدا کنم . 
از دید یک یوزر صفر کیلومتر توضیحات بگذارید حرفه‌ایها خودشان بلد هستند

**Comment by bia-pain-bache** [comment]
آموزش بسیار مفصل برای نحوه استفاده و تنظیمات نوشتم، همون صفحه‌ی اول پروژه فقط نیازه بخونیدش. حرفه‌ای‌ها هم بلد نبودن.

**Comment by Glimpser-zz** [comment]
چرا نباید توی خود پنل و کنار هر آیتم راهنما تنظیم آن نوشته شده باشد ؟

**Comment by bia-pain-bache** [comment]
سعی میکنم اگر فرصتی پیدا کنم این کارو انجام بدم.
