### ISSUE TITLE
چطور میتونم از نسخه ۲٫۴٫۵ که قبلا نصب کردم به نسخه جدید آپدیت کنم؟

### ISSUE THREAD

**Issue by persian85** [bia-pain-bache/BPB-Worker-Panel#237]
### Feature description | توضیحات ویژگی

چطور میتونم از نسخه ۲٫۴٫۵ که قبلا نصب کردم به نسخه جدید آپدیت کنم؟

**Comment by SoheilFM** [comment]
سلام و درود
شما میتوانید طبق مراحل زیر پیش برید و آپدیت کنید

1. اولین مرحله شما باید به گیت هاب خود مراجعه کنید و در ریپازیتوری که کلون گرفتید وارد شوید .
2. در مرحله بعد طبق تصویر گزینه sync fork اضافه شده است که باید بر روی آن کلیک کنید
![image](https://github.com/user-attachments/assets/4e59ee7b-9a6c-44b8-a5e0-188022d86a96)

3. حال ریپوزیتوری شما آپدیت شده است و باید با پیام  This branch is up to date with bia-pain-bache/BPB-Worker-Panel:main. روبرو شوید 
![image](https://github.com/user-attachments/assets/51447a2b-cd1e-409e-8a20-39cc973a75bd)

4. در مرحله بعد وارد پنل کلودفلر خود شوید و از قسمت سمت چپ پنل بر روی گزینه Workers and pages  و بعد از آن بر روی Overview کلیک کنید 
![image](https://github.com/user-attachments/assets/63d134d8-5412-42d3-a6ff-8de025ef6a3b)
5- و در آخر نگاه کنید اگر در قسمت پروداکشن پنل آپدیت شده بود که هیچ اگر نه میتوانید با زدن بر روی گزینه retry دوباره دیپلوی کنید
![image](https://github.com/user-attachments/assets/0e67bda2-af88-499e-8e57-62cca1e8d193)
6- تمام .  
پنل به صورت کامل آپدیت شده است حتما یکبار وارد پنل شوید که کانفیگ های وارپ نیز آپدیت شوند
امیدوارم که توضیحات بنده مفید واقع شود.

**Comment by bia-pain-bache** [comment]
@SoheilFM 

ممنون از کمکت، عالی بود.

**Comment by persian85** [comment]
ممنونم بابت راهنمایی. منتها تا مرحله ۴ پیش رفتم ولی مرحله پنجم چنین گزینه ای رو پیدا نکردم! به همین خاطر رفتم کد رو کپی کردم و با جایگذاری یوزر آیدی save & deploy کردم و ظاهرا موقع ورود به پنل نوشته ورژن ۲٫۴٫۷ ولی نمیدونم آیا این روشی که انجام دادم بدرستی و کامل آپدیتش میکنه یا نه!
