### ISSUE TITLE
مشکل در اپ سینگ باکس 

### ISSUE THREAD

**Issue by emad1381** [bia-pain-bache/BPB-Worker-Panel#24]
تو اپ سینگ باکس به این ارور میخورم 
![Screenshot_2024-04-17-16-51-17-904_io nekohasekai sfa](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/80378806/712d6740-37c6-42e0-be64-c1539cf076f4)

**Comment by emad1381** [comment]
و اینکه من نسخه آخر پنل و سینگ باکس رو دارم از این جهت مشکل نداره مشکل چیز دیگست

**Comment by bia-pain-bache** [comment]
1- گیتهاب رو سینک کردی ولی کلادفلر نشده، باید بری دستی Retry deployment رو بزنی و ورژن پنلت بشه 2.3.3
2- موقعی که میخوای وصل بشی هیچ VPN دیگه وصل نباشه. این فایل‌ها باید از اینترنت مستقیم دانلود بشن.
3- چندبار بزن
