### ISSUE TITLE
pages.dev域名后面有一个这样的小点>  .

### ISSUE THREAD

**Issue by tyy840913** [bia-pain-bache/BPB-Worker-Panel#241]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

自定义域名  dynv6二级域名
添加CNAME记录时要求地址后面带个小点
获取订阅链接，然后有一条pages.dev的地址后面同样有一个小点......
导致这条订阅链接无法启动，删除小点后正常。
重新更新订阅又出现小点

### Relevant log output | لاگ برنامه یا پنل

```shell
没有输出日志
```

**Comment by bia-pain-bache** [comment]
Can you fill `Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟
No response` section carefully? I need to know what happend from beginning to end please.

**Comment by tyy840913** [comment]
cf创建pages页面,添加自定义域，使用的是dynv6.net二级域名,添加域名记录CNAME，需要在xxx.pages.dev地址后面添加一个点>>.   如"xxx.pages.dev."   如果不添加这个点，会添加失败,在bpb面板页面获取连链接,在代理软件里添加这个链接，更新订阅，其中有一条节点的地址是CF部署后自动分配的地址 xxx.pages.dev  这条地址的后面同样带有一个小点>>.  
![IMG_20240814_144238](https://github.com/user-attachments/assets/26ac1670-e7e8-4a59-9a7f-d83ff2aa27c8)

**Comment by bia-pain-bache** [comment]
Understood, when you add a custom domain, you have to open panel using that CNAME not the original pages.dev domain.
