### ISSUE TITLE
نمایش آیپی ایران در https://whatismyipaddress.com/

### ISSUE THREAD

**Issue by coolnum1** [bia-pain-bache/BPB-Worker-Panel#242]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود بعد از این سیستم پیدا کردن آیپی جدید این سایت لوکیشن رو ایران نشون میده https://whatismyipaddress.com/
به نظرتون چی کار کنم ؟
هم در هیدیفای و هم در نیکا ان جی

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

**Comment by bia-pain-bache** [comment]
سلام، لطفا اون IP رو برام بذارید.

**Comment by coolnum1** [comment]
من هر آیپی از اسکنر گذاشتم آیپی کلادفلر  ایران رو نشون داد بعد از 2 یا 3 بار قطع و وصل کانفیگ میره رو کشور انتخابی 
باشه
باشه پایین قرار میدم

**Comment by coolnum1** [comment]
129.146.46.164
بفرمایید 
من در این سایت متوجه شدم که آی پی ها در ایرانه 
https://whatismyipaddress.com/
در اپ نیکا و در اپ هیدیفای شاید ۹۹ درصد آیپی های پیدا شده با روش جدید به این صورت هست چه از سایت بردارم و یا اینکه اسکن کنم هر دو همینه

**Comment by coolnum1** [comment]
![IMG_20240814_104403](https://github.com/user-attachments/assets/03256ed9-9f20-4bec-a2cf-b67f123e8945)

**Comment by coolnum1** [comment]
![IMG_20240814_104319](https://github.com/user-attachments/assets/0cb43e00-9213-4e33-9b34-18167cbbd5b6)

**Comment by planetkeeper1** [comment]
این ایشو رو ببندم ؟ کمکی کرد ؟

**Comment by coolnum1** [comment]
این ایشو رو ببندم ؟ کمکی کرد ؟

**Comment by bia-pain-bache** [comment]
بخاطر تفاوت در Database های مختلف IP location هست. من با whatismyipaddress نتیجه مشابه شما رو میگیرم ولی یه اسکرین‌شات از افزونه مرورگرم میذارم:


![Screenshot 2024-08-23 223517](https://github.com/user-attachments/assets/e96c82f8-1a52-475c-b413-55d1d1c689d4)
