### ISSUE TITLE
Vmess & Warp+

### ISSUE THREAD

**Issue by MmadWolf** [bia-pain-bache/BPB-Worker-Panel#245]
### Feature description | توضیحات ویژگی

سلام بر دوست عزیز ، یه چند تا خواهش و پیشنهاد دارم که خوشحال میشم اگه اضافه شه1:اگه میشه کانفینگ از نوع vmess اضافه شه چون جدیدا vless اختلال داره و پینگ کمتر ۴۰۰ نمیده در همراه بقیه اپراتور ها رو نمیدونم  عجیبه برام همه کار هم کردم اصلا به دیسکورد وصل نمیشه اما با vmess هم پینگ کم دانلود و اپلود خوبی دارم برای گیم هم عالیه، اگه میشه گزینه به صورت تیک باشه و از اون لینک ساب vless جدا باشه ، دومی مشکل وارپ روی همراه هست به هیچ وجه وصل نمیشه با ipv6 میزارم باگ هنوز پابرجاست ،  3:گزینه دیگه گذاشتن لاینسس برای وارپ پنله اگه بشه که عالی میشه ،ممنون ❤️

**Comment by bia-pain-bache** [comment]
سلام،

روی ورکر VMESS پیاده‌سازی نشده اصلا. VLESS رو با فرگمنت و اپ‌های MahsaNG و NikaNG و v2rayN-PRO استفاده کن.
آپدیت جدید مشکل وارپ برطرف شده.
