### ISSUE TITLE
forget password

### ISSUE THREAD

**Issue by H033ein1766** [bia-pain-bache/BPB-Worker-Panel#246]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام متاسفانه توی ساخت اکانت های کلاودفلر و گیت هاب و kv از پسورد های مختلفی استفده شد و بعد از تغییر پسورد پنل از admin به چیز دیگه فراموش شده
راهی رو برای فراموشی پسورد و forgetpassword قرار ندادید 
همه چی عالیه ممنون از زحماتتون
ایمیل 
hosseingholamiad@gmail.com

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

open worker panel than forget my password

### Relevant log output | لاگ برنامه یا پنل

```shell
there is no information for loging
```

**Comment by tyy840913** [comment]
删除绑定的kv空间，重新创建连接部署

**Comment by MmadWolf** [comment]
دوست من یه kv دیگه بساز دولوپ کن مشکل حل میسه
