### ISSUE TITLE
اتصال به چت جی پی تی و اوپن ای آی

### ISSUE THREAD

**Issue by Ehsan7681** [bia-pain-bache/BPB-Worker-Panel#248]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟
سلام و درود 
چرا با کانفیگ های پنل برنامه و سایت ChatGPT مشکل داره و باز نمیکنه 
یا اگه روش خاصی داره یا تنظیمات برنامه ها رو باید دستکاری کرد لطفا راهنمایی کنید که چیکار باید انجام بشه که بدون مشکل باز کنه برنامه ChatGPT رو 

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

.

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

**Comment by Saeed9899** [comment]
سلام مشکل از PROXY IP هست باید از IP ثابت استفاده کنی روشش رو آموزش داده توو سوالات و گزارش ها هم هست انجام بدی حل میشه

**Comment by bia-pain-bache** [comment]
دقیقا مشکل Proxy IP هست چون چیزی که پیشفرض پنل هست عمومیه و خیلی IP های تمیزی نیستن، به لوکیشن IP هم مربوطه.
