### ISSUE TITLE
مشکل استفاده از chain proxy

### ISSUE THREAD

**Issue by hadifarnoud** [bia-pain-bache/BPB-Worker-Panel#252]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

تا جایی که فهمیدم من باید از chain proxy استفاده کنم برای اینکه آی پی نهایی من کلودفلر نباشه. درسته؟ برای من کار نمیکنه و همچنان آی پی کلودفلر نشون میده که لوکیشن ایران نشون میده توی ipinfo

من یک کانفیگ vless گذاشتم توی chain proxy

در مورد Proxy IP هم نفهمیدم میتونم آدرس آی پی سرور خودم بدم یا نه و فرق این دوتا چیه. داکیومنت ها خیلی گیج کننده هست توی این دو بخش

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

نسخه آخر استفاده میکنم.

### Relevant log output | لاگ برنامه یا پنل

```shell
لاگ خاصی ندارم
```

**Comment by bia-pain-bache** [comment]
کدوم قسمتش گیج‌کننده هست؟ بگو اصلاحش کنم.
اون proxy chain فقط روی ساب فرگمنت اعمال میشه نه همه‌ی کانفیگا.
نه proxy ip رو نمیشه هر ip استفاده کرد، از اسکنر استفاده کنید که آموزششو نوشتم یا از همون ip های پشت دامنه که معرفی کردم.

**Comment by hadifarnoud** [comment]
آها پس کلا اشتباه متوجه شدم. فکر کرم proxy chain یا proxy ip میتونه IP نهایی من از CF عوض کنه به سرور خودم.

**Comment by bia-pain-bache** [comment]
آموزش رو درست بخون لطفا، proxy chain کلا ip رو عوض میکنه.

**Comment by hadifarnoud** [comment]
چون من از قابلیت fragment نمیتونم روی Clash Meta استفاده کنم پس آی پی عوض نمیکنه برام. درست متوجه شدم؟

**Comment by bia-pain-bache** [comment]
دقیقا، فقط میتونی از Proxy IP استفاده کنی.
