### ISSUE TITLE
PROXY IP کار نمی کنه

### ISSUE THREAD

**Issue by Noseme** [bia-pain-bache/BPB-Worker-Panel#253]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

من داخل پنل توی قسمت پراکسی آی پی این آی پی رو قرار دادم
141.147.163.68
ولی بعد از آپلای کردن و آپدیت ساب ها آی پی هنوز هم برای  cloudflare germany هست.
از ساب های fragment sub  استفاده می کنم.
من حتا داخل cloudflare با variable  هم  اضافه کردم ولی آی پی تغییر نمیکنه.
آیا مشکل از آی پی هست؟

### Relevant log output | لاگ برنامه یا پنل

```shell
نمی دونم لاگ  رو از کجا پیدا کنم
```

**Comment by bia-pain-bache** [comment]
باید از سایتی IP رو چک کنید که خودش پشت کلادفلر باشه. از این استفاده کنید:

https://whatismyipaddress.com/

**Comment by Noseme** [comment]
ممنون یه سوال دیگه هم داشتم
الان هم از توی پنل proxy ip  تنظیم کردم هم از  cloudflare
می تونم برم توی CF و  variable  رو تغییر بدم, بدونه این که کانفیگ های اهدایی قت بشن؟
یا اول باید قسمت proxy IP  توی پنل رو خالی کنم؟

**Comment by bia-pain-bache** [comment]
اگر قبل از اهدا proxy ip پنل گذاشته باشی دیگه فایده نداره، چون خالیش کنی باید ساب آپدیت بشه، یوزراتم ساب ندارن.
