### ISSUE TITLE
سوال ؟

### ISSUE THREAD

**Issue by planetkeeper1** [bia-pain-bache/BPB-Worker-Panel#254]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

شما گفتین گزینه‌ی fragment packets اضافه شده، فقط در نظر داشته باشید ۱-۱ فقط روی MahsaNG و NikaNG و v2rayN-PRO کار میکنه.

پس بقیه گزینه ها رو کدوم برنامه ها کار میکنه ؟

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

**Comment by bia-pain-bache** [comment]
بقیه گزینه‌ها روی بقیه اپ‌ها کار میکنه. v2rayNG و v2rayN و...
