### ISSUE TITLE
An option to show only clean IP configs

### ISSUE THREAD

**Issue by Noseme** [bia-pain-bache/BPB-Worker-Panel#255]
### Feature description | توضیحات ویژگی

Hi, can we have a checkbox to enable only clean ip configurations? After enabling it, when subs are updated, only clean ip configuration would be shown.
This would be helpful for elderly users who might accidentally touch one of the other, non functioning configurations in the  list.
-
سلام
میشه یه آپشن اضافه کنید که ساب فقط کانفیگ های clean ip  رو  اضافه کنه؟
برای افراد سالمند بهتر میشه چون بعضی موقع ها دستشون می خوره به یکی از کانفیگ هایی مثل  best fragment یا ipv6 و از کار می افته اینترنت براشون.
ممنون

**Comment by bia-pain-bache** [comment]
والا اگر بخوام این چیزا رو در نظر بگیرم باید ۵ صفحه اسکرول کنید فقط تنظیمات انجام بدید که اینم برای افراد سالمند بده.

**Comment by Noseme** [comment]
نمیدونم متوجه شدین منظورم رو یا نه,
ب نظر شخصی من مشکلی نیست اگه پنل یکم سخت تر بشه کار باهاش, چون مثلا پدر و مادر 70 سال من قرار نیست که پنل رو  راه اندازی کنن
ولی وقتی ساب آپدیت میشه الان  چندتا آیتم هست که کار نمیکنن بستگی به شبکه ای که توش هستی و  کاربر هایی که از نظر تکنلوژی ضعییف هستن به مشکل می خورن

**Comment by bia-pain-bache** [comment]
من کاملا متوجه منظورت هستم، منتها اگر بخوام چیزی به پنل اضافه کنم باید موردی باشه که واقعا نیاز همه باشه، نمیتونم بخاطر استثناها پنل رو توسعه بدم. اتفاقا خیلی از کسایی که اصلا آشنایی با هیچگونه پروکسی نداشتن دارن از پنل استفاده میکنن.
