### ISSUE TITLE
مشکل کانفیگ best ping ساب فرگمنت در برنامه v2rayn pro

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#257]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

در برنامه v2rayn pro و برنامه های دیگر دارای هسته xray mahsa کانفیگ best ping ساب فرگمنت کار نمیکند 
طبق تغییراتی که انجام دادم با تغییر تنظیمات fragment packets از tls hello به 1-1 کانفیگ درست میشود
البته در اپ nikang تست نکردم هنوز

### Relevant log output | لاگ برنامه یا پنل

```shell
doesn't have log
```

**Comment by bia-pain-bache** [comment]
تست‌ها اوکی هستن، بدون لاگ و اطلاعات کافی هم کاری از دستم بر نمیاد.

**Comment by developer861** [comment]
https://github.com/GFW-knocker/Xray-core/issues/8

الان رفتم نگاه کردم به نظر میرسه مود tls hello فرگمنت روی کلاینت هایی که هسته مهسارو دارن درست کار میکنه ولی کلاینت هایی که هسته اصلی xray رو دارن برای اینکه کانفیگ best ping فعال بشه باید مود فرگمنتو بذارید رو ۱-۱ تا کار کنه
کسایی که آیفون دارن و مجبورن ار هسته اصلی xray استفاده کنن باید تو تنظیمات مود فرگمنتو عوض کنن
پیشنهاد میکنم در تنظیمات دیفالت پنل هم مود دیفالو به ۱-۱ تغییر بدین

**Comment by developer861** [comment]
توضیحات در لینک بالاش نوشته ولی خودم حقیقتش اطلاعات فنی ای درباره کارکردش ندارم

**Comment by bia-pain-bache** [comment]
مود ۱-۱ هم مخصوص هسته‌ی Knocker هست. اگه قراره این هسته استفاده بشه که همون tlshello هم جواب میده. هسته روی کلاینتای آیفون پیاده‌سازی نشده.

**Comment by developer861** [comment]
خب من از کلاینت Streisand استفاده میکنم وقتی کانفیگارو از مود tls hello به ۱-۱ تغییر میدم کار میکنه علتشو نمیدونم

**Comment by bia-pain-bache** [comment]
بخاطر اینکه ساپورت نمیکنه ینی در عمل بدون فرگمنت وصل میشه. مثل اینه که کانفیگای نرمال وصل بشی.

**Comment by developer861** [comment]
آها گرفتم پس دمت گرم

**Comment by bia-pain-bache** [comment]
توی توییتی که ورژن اعلام کردم گفتم چجوری کار میکنه!

**Comment by developer861** [comment]
اوکیه پس به نظرم بهتره به داکیومنتم اضافه ش کنید بازم دمتون گرم❤️

**Comment by bia-pain-bache** [comment]
تو آموزش و release بهش اشاره کردم.
