### ISSUE TITLE
ipv4/ipv6 checkboxes in the panel

### ISSUE THREAD

**Issue by facereviewer** [bia-pain-bache/BPB-Worker-Panel#260]
### Feature description | توضیحات ویژگی

چک‌باکس هایی برای انتخاب ورژن ایپی کانفیگ هایی که از ساب دریافت میشن.

**Comment by bia-pain-bache** [comment]
مواردی که سلیقه‌ای هستن و در کیفیت اتصال کاربردی ندارن اعمال نمیشن.
