### ISSUE TITLE
IPv6 Address

### ISSUE THREAD

**Issue by kut2tjjj** [bia-pain-bache/BPB-Worker-Panel#262]
### Feature description | توضیحات ویژگی

"Requesting support for IPv6 addresses, including 'Local DNS' and 'CLEAN IP.' The latest version of v2rayN for PC now supports WARP/WARP+. Please request BPB to support importing WARP into v2rayN."

**Comment by bia-pain-bache** [comment]
Clean IP already supports IPv6.
Also warp/warp+ has been implemented in previous versions. I guess u missed announcements.
What's the advantage of IPv6 local DNS?

**Comment by kut2tjjj** [comment]
IPv6 local DNS offers enhanced scalability, efficiency, security, and future-proofing, making it an essential component for modern networks, especially as the world continues to shift towards IPv6.

**Comment by bia-pain-bache** [comment]
Not in Iran, IPv6 infrastructure is not stable and useful at all specially for DNS! To be mentioned, the usage of local DNS is only for routing like bypassing iranian hosts....
