### ISSUE TITLE
اضافه کردن rule های بیشتر به  کانفیگ ها

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#264]
### Feature description | توضیحات ویژگی

geoip:malware,
geoip:phishing,
geosite:category-ads-all, 
geosite:malware,
geosite:phishing, 
geosite:cryptominers
اگه میشه این rule هارو به بخش بلاک اضافه کنید
domain:ir,
geosite:category-ir,
geosite:private,
geoip:ir,
geoip:private
و این rule هارو به بخش direct

**Comment by bia-pain-bache** [comment]
کانفیگ Singbox همه رو داره چون geo asset متفاوتی لود کردم ولی کانفیگای فرگمنت و وارپ xray بخشای phishing و malware رو نداره چون geo asset پیشفرض کلاینت‌ها اینا رو ندارن.
