### ISSUE TITLE
Firefox: Potential Security Issue

### ISSUE THREAD

**Issue by fromseer** [bia-pain-bache/BPB-Worker-Panel#269]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

به هر سایتی میخوام وصل شم فایرفاکس گیر میده:

![image](https://github.com/user-attachments/assets/7a1725f7-25c9-44b3-b6a6-4b6cae6029e2)

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Normal Sub

💦 BPB - Domain_1 : 443

### Relevant log output | لاگ برنامه یا پنل

```shell
nemidunam koja bud
```

**Comment by bia-pain-bache** [comment]
بخاطر proxy ip هست. چون پیشفرض پنل رو عموم دارن استفاده میکنن و بعضیاش کثیف شده. خودت اسکن کن و یه IP بدون مشکل بذار.
