### ISSUE TITLE
Vless chain proxy not working

### ISSUE THREAD

**Issue by mrmoein** [bia-pain-bache/BPB-Worker-Panel#27]
Chain Proxy from site [https://www.racevpn.com](https://www.racevpn.com) not working, i select netherlands server and get a vless websocket config
I redeploy page too.
My ip changes with every request. 

![Screenshot 2024-04-21 003409](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/48438999/91768e51-e818-4f4a-8886-2e3c809e3c09)

**Comment by bia-pain-bache** [comment]
This feature only applies on Fragment configs, Also you have to update your sub to take effect.

**Comment by mrmoein** [comment]
Worked, but it too slow!

**Comment by m0x61h0x64i** [comment]
سلام مهندس جان،
یه سوال در مورد chain proxy داشتم. اونم اینکه اگر chain proxy تنظیم نکنیم وقتی سایت هایی که پشت کلودفلیر نیستن رو باز کنیم ایپیمون همیشه المان هست؟ میشه به عنوان یک ایپی ثابت المان بهش نگاه کرد؟
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
سلام،
ثابت آلمان هست و معمولا یک منطقه هم هست ولی همیشه IP ثابت نیست.

**Comment by m0x61h0x64i** [comment]
ممنون مهندس جان،
بعد یه سوال دیگه. اگر proxy chain غیرفعال باشه و proxy ip فعال باشه از اونجایی که v2rayng تست پینگی که میگیره چون dns گوگل هست نمیشه فهمید پینگ واقعی کانفیگ با proxy ip تنظیم شده چقدر هست. ادرس تست دیفالت v2rayng پشت کلود نیست. اینو چطوری میشه فهمید؟ اگر ادرس تست رو cp.cloudflare بزاریم میشه فهمید؟ (تست کردم پینگ میده ولی خیلی فرق نداشت نمیدونم داره با proxy ip پینگ میگیره یا نه ولی dns هاش برای کلودفلیره حالا نمیدونم میشه بهش به عنوان نتیجه تست پینگ proxy ip بهش اعتماد کرد یا خیر)
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
خواهش میکنم، هیچ فرقی نداره، Proxy IP فقط برای گول زدن کلادفلر هست، ترافیک شما از پروکسی جداگونه رد نمیشه که سرعت تغییر کنه.dns هم ارتباطی به این قضیه نداره اصلا.

**Comment by m0x61h0x64i** [comment]
خیلی ممنون،
حالا با توجه به اینکه ترافیک از proxy ip رد نمیشه و proxy chain فعال نیست، ایپی ای که وب سایت های پشت کلودفلیر از کانفیگ دریافت میکنن همیشه ایپی proxy ip هست؟ یعنی اون سایت باید dns کلودفلیر داشته باشه تا proxy ip رو ببینن درسته؟
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
بله هر سایتی که اصطلاحا پشت کلادفلره ینی دامنه روی کلادفلر ثبت شده باشه Proxy IP رو میبینه.

**Comment by m0x61h0x64i** [comment]
سلام مجدد مهندس جان، ممنون بابت پاسخگویی به سوالات بنده حقیر
ببخشید یه سوالی برام پیش اومد. اونم اینکه اگر proxy cahin غیرفعال باشه و یه proxy ip فعال باشه ایا اون proxy ip برای همیشه فعال هست یا ممکن هست از دست بره؟ سه تا ساب برای proxy ip هست میخاستم بدونم ایپیاشون عوض نخواهند شد؟ حذف بشن یا اضافه بشن یا ایپیا از کار بیافتن
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
سلام،
این چه حرفیه خواهش میکنم.
تک IP مثل هندونه دربسته هست، ممکنه بعد از یه مدت از کار بیافته که البته شما متوجهش میشید. اون ۳ تا ساب هم IP هاشون آپدیت میشه، حذف و اضافه میشن و تک IP هم نیستن. میتونید خودتون طبق آموزش یکیشو انتخاب کنید و ست کنید.
