### ISSUE TITLE
تعداد بسیار درخواست در مدت زمان کم

### ISSUE THREAD

**Issue by fromseer** [bia-pain-bache/BPB-Worker-Panel#270]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام حدود 2-3 ساعت دارم استفاده میکنم، رفتم اکانت کلودفلر دیدم 17 هزار درخواست رد وبدل شده! به جایی هم به اشتراک نذاشتمش اخه چرا؟ نکوری هستش

![image](https://github.com/user-attachments/assets/0416905d-7a2f-4bf2-aa50-7d8f6d662f5b)

### Relevant log output | لاگ برنامه یا پنل

```shell
soal
```

**Comment by bia-pain-bache** [comment]
هر نفر متوسط روزی ۳۰-۵۰ هزار تا مصرف میکنه، ۱۷ تا چیز عجیبی نیست.

**Comment by fromseer** [comment]
مرسی برای پاسخگویی

میتونی بگی چرا انقدر تعداد درخواست های xray انقدر بالاست ؟ اخه اونقدر سایت باز نکردم 😅
