### ISSUE TITLE
WARP and WOW endpoint updating! (Warp section updating))

### ISSUE THREAD

**Issue by ahmadpromax** [bia-pain-bache/BPB-Worker-Panel#271]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

After the initial setup for warp and wow endpoints,
For updating ( adding or removing endpoints) 
It keeps showing the error that :
**An error occurred , please try again 
Too many connected devices!**

While there is none connected to the warp sub!

Please fix this bug , so that the editing of warp section, would be smoother!

### Relevant log output | لاگ برنامه یا پنل

```shell
Not submitted!
```

**Comment by bia-pain-bache** [comment]
You can update warp twice using each licence,  after that you get that error. So please remove it or replace with new one.

**Comment by ahmadpromax** [comment]
I've tried to only remove the license, but even so ,  the error 
**....Too many connected devices!**
Still shows on!

**Comment by bia-pain-bache** [comment]
Either after adding or after removing license you have to apply first and then update.

**Comment by ahmadpromax** [comment]
Thanks, problem solved!❤️
