### ISSUE TITLE
NekoBox is not available

### ISSUE THREAD

**Issue by gittyspirit** [bia-pain-bache/BPB-Worker-Panel#273]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

When I add a group for bpb and update the subscription. It works. But when you try to use connect to specific config. It shows 1005 error.

### Relevant log output | لاگ برنامه یا پنل

```shell
No
```

**Comment by bia-pain-bache** [comment]
Please read FAQ. it's a common issue.
