### ISSUE TITLE
سوال در مورد نحوه عملکرد این برنامه

### ISSUE THREAD

**Issue by fromseer** [bia-pain-bache/BPB-Worker-Panel#277]
اول میخوام تشکر کنم برای این برنامه عالی

من یه سوال برام به وجود اومده، ما که xray نصب نداریم تو سرورهای کلودفلر، پس این برنامه چطوری کار میکنه؟ الان درخواست ها به کجا هدایت داده میشه ؟ ممنون

**Comment by bia-pain-bache** [comment]
خواهش میکنم،
خود xray رو هم با یه زبانی نوشتن، با زیرساخت کلادفلر هم میشه تعدادی از پروتکل‌ها رو برنامه‌نویسی کرد. درخواست‌ها به زیرساخت کلادفلر میرسه.
