### ISSUE TITLE
 نحوه اضافه کردن ای پی

### ISSUE THREAD

**Issue by hameed-maleki** [bia-pain-bache/BPB-Worker-Panel#278]
### Feature description | توضیحات ویژگی

سلام لطفا نحوه اضافه کردن ای پی ها رو راحت تر کنید که جوری باشه که مثل اسکنر های رایج  باشه اکثر اسکنر ها ای پی ها زیر هم قرار میگیره لطفا به این صورت کنیدش تا نیاز ب ویرایش اضافی و اضافه کردن ویرگول بین هر ای پی نباشه
با تشکر

**Comment by arshiacomplus** [comment]
```sh
   bash <(curl -fsSL https://raw.githubusercontent.com/arshiacomplus/WarpScanner/main/install.sh)
```
این رو بزن تو ترماکس نسخه گیت هاب 
بعد  اول فیلتر روشن کن پیش نیاز ها نصب بشند بعد 
منو اومد بالا خاموش کن 
گزینه ۱ بعد 
بعد دسترسی بده به ترماکس بعد گزینه ۱ برای bpb 

بعد ازت میخواد یا پورت یا بدون پورت ذخیره کنه 
بعد 
رنج پینگ از صفر تا چند رو ذخیره کنه بعد 
 ورژن آیپی رو انتخاب کن 

سوال داشتی تلگرام بپرس :
@arshiacomplus

**Comment by kazii130** [comment]
@arshiacomplus
عالی دست مریزاد 
با تشکر از شما و bpb عزیز 👏👏

**Comment by emisemok** [comment]
> @arshiacomplus عالی دست مریزاد با تشکر از شما و bpb عزیز 👏👏

@bia-pain-bache

**Comment by bia-pain-bache** [comment]
من اون اسکنرو ندیده بودم تا حالا، ممنون بابت معرفی.
