### ISSUE TITLE
مشکل باز نشدن وویس چت تلگرام با کانفیگ های وورکر

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#280]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

کانفیگ های وورکر اصلا وویس چت تلگرامو باز نمیکنن ولی کانفیگ های warp pro باز میکنن مشکلش چیه؟

### Relevant log output | لاگ برنامه یا پنل

```shell
doesn't have log
```

**Comment by bia-pain-bache** [comment]
کانفیگای VLESS و Trojan روی ورکر و پیجز مشکل UDP دارن. برطرف نمیشه.
