### ISSUE TITLE
عدم امکان آپدیت فورک

### ISSUE THREAD

**Issue by Mahantor** [bia-pain-bache/BPB-Worker-Panel#282]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام
چرا تو این چندتا آپدیت آخری که دادید امکان آپدیت فورک وجود نداره؟؟؟
Sync fork > This branch is not behind the upstream bia-pain-bache/BPB-Worker-Panel:main.

No new commits to fetch. Enjoy your day! 

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

My repositories
Sync fork

### Relevant log output | لاگ برنامه یا پنل

```shell
>>>>>>>>>
```

**Comment by emisemok** [comment]
فقط پنل های ریلیز شده امکان آپدیت رو دارن و برای نسخه های پیش انتشار باید ی فورک جدید دیپلوی کنید
