### ISSUE TITLE
new panel ui bug

### ISSUE THREAD

**Issue by Airuop** [bia-pain-bache/BPB-Worker-Panel#283]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

⚠️ Cannot read properties of undefined (reading 'domains')

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

update to 2.5.4 from 2.5.3
show error in panel ui :
⚠️ Cannot read properties of undefined (reading 'domains')

### Relevant log output | لاگ برنامه یا پنل

```shell
⚠️ Cannot read properties of undefined (reading 'domains')
```

**Comment by xpeagle** [comment]
一样的问题，出现“域”出错，无法读取未定义的属性（读取‘域’），用workers部署的时候，用pages好像没有，另外环境变量中设置TROJAN_PASS和HASH_PASS，前面TROJAN_PASS这个是不是随便几个英文字母或者数字结合的就行，后面的HASH_PASS也是随便的数字+字母的组合或者都是字母就行，然后将这些字符转换成hash字符再复制填入即可。

**Comment by bia-pain-bache** [comment]
That was not a UI bug, however i fixed it, thanks for reporting.
