### ISSUE TITLE
سوال ؟

### ISSUE THREAD

**Issue by coolnum1** [bia-pain-bache/BPB-Worker-Panel#286]
### Feature description | توضیحات ویژگی

چن تا آیپی تمیز میشه قرار داد در قسمت clean ip چون بعضی اوقات ارور 1102 میده پنل
![Screenshot 2024-09-14 110813](https://github.com/user-attachments/assets/86d923d7-25f9-46d3-9363-56940c573675)

**Comment by bia-pain-bache** [comment]
هر وقت اون ارور رو داد لطفا اسکرین‌شات بذارید، بعیده بخاطر تعداد باشه، محدودیتی نداره.

**Comment by coolnum1** [comment]
باشه حتما
پس این 1102 برای چی بود به نظرتون

**Comment by coolnum1** [comment]
البته من لیست آیپی  تمیز داشتم نزدیک 900 تا آی پی داشت رو ورژن 2.5 اوکی بود ولی روی 2.5.5 وقتی تروجان رو در کنار  ویلس  زدم پنل ارور داد(اگه ویلس خاموش کنم فقط تروجان باشه اوکیه یا برعکس) تعداد آیپی ها رو نصف کردم اوکی شد
الان دارم دوباره آیپی اسکن میکنم

**Comment by coolnum1** [comment]
![Screenshot 2024-09-15 132119](https://github.com/user-attachments/assets/8d6ab534-f24a-4066-9cd5-49dea063b8fa)
الان نزدیک 700 تا آیپی دادم این پیام رو میده ولی وقتی بر میگردونم پنل رو به ورژن قبل اوکی میشه

**Comment by coolnum1** [comment]
رو ورژن 2.5.5 با آیپی تعداد بالا اگر فقط روی ویلس یا تروجان باشه اوکیه ولی هر دو همزمان ارور میده

**Comment by coolnum1** [comment]
1102
![Uploading Screenshot 2024-09-15 132806.png…]()

**Comment by coolnum1** [comment]
![Screenshot 2024-09-15 132806](https://github.com/user-attachments/assets/018aa067-2443-478d-b665-04a1a2ec63f0)
این صفحه میاد این سری 700 تا آیپی دادم. ولی اگه تنها تروجان یا ویلس روشن باشه اوکی هست

**Comment by bia-pain-bache** [comment]
۹۰۰ تا IP حجم وحشتناکی از کانفیگ میشه، احتمالا نمیتونه render کنه صفحه رو، ممکنه موقع آپدیت ساب هم به مشکل بخوره. ولی از سمت من محدودیتی اعمال نشده.

**Comment by coolnum1** [comment]
نه تنها به مشکلی بر نمیخوره بسیار عالی کار میکنه و به راحتی با 900 تا آیپی ساب آپدیت میشه (تنها روی اپ هیدیفای و اف ال کلش  "دسکتاپ" ) چون رو اپ موبایل اپ کرش میکنه با اون همه حجم از آیپی. ولی الان تو ورژن 2.5.5 فقط باید یک آپشن رو انتخاب کنم (تروجان یا وی لس) البته چون من هر دو رو میخواستم آی پی های تمیز رو حدود 400 تا کردم که عالی کار میکنه همچنان رو دسکتاپ.
امیدوارم هر چه که دوست داری با افتخار بهش برسی(هم شما و هم بچه هایی که در این مسیر آزادی اینترنت ایران قدم بر می دارند).-پنل شما عالیه
