### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by Lord-wolf70** [bia-pain-bache/BPB-Worker-Panel#287]
### Feature description | توضیحات ویژگی

درود بر شما
داداش میشه یه آموزش ویدئویی صفر تا صد تو یوتیوب قرار بدی کانال های دیگه خیلی کلی توضیح دادن من میخام وارپ و وارپ پلاس هم فعال کنم ولی خیلی مبتدی هستم اگر کانال تلگرامی هم داری قرار بده

**Comment by bia-pain-bache** [comment]
سلامت باشید. آموزش صفر تا صد نوشتم براتون با تصویر، مراجعه کنید صفحه اول گیتهاب میبینید.

**Comment by Lord-wolf70** [comment]
> سلامت باشید. آموزش صفر تا صد نوشتم براتون با تصویر، مراجعه کنید صفحه اول گیتهاب میبینید.

خوندم  تمومش خیلی قشنگ هم توضیح دادی ولی تو قسمت وارپ و اندپوینت منونمیدونم چطوری تنظیم کنم مشکل از منه چون من خیلی مبتدی هستم

**Comment by bia-pain-bache** [comment]
https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/configuration_fa.md#4-4-1-%D8%AA%D9%86%D8%B8%DB%8C%D9%85%D8%A7%D8%AA-warp-settings

**Comment by Lord-wolf70** [comment]
> https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/configuration_fa.md#4-4-1-%D8%AA%D9%86%D8%B8%DB%8C%D9%85%D8%A7%D8%AA-warp-settings

داداش من برای همراه اول فرگمنت استفاده میکنم ولی با خود برنامه پینگ میده ولی تلگرام وصل نمیشه مشکل از چی میتونه باشه؟

**Comment by bia-pain-bache** [comment]
تنظیمات پنل رو برگردون به پیشفرض، اگر کار خاصی روی پنل یا برنامه نکردی و بازم اینجوریه یه اکانت گیتهاب و کلادفلر جدید بساز. کلادفلر بعضی وقتا فلگ میکنه.

**Comment by Lord-wolf70** [comment]
> تنظیمات پنل رو برگردون به پیشفرض، اگر کار خاصی روی پنل یا برنامه نکردی و بازم اینجوریه یه اکانت گیتهاب و کلادفلر جدید بساز. کلادفلر بعضی وقتا فلگ میکنه.

پیش فرضه همش

**Comment by Lord-wolf70** [comment]
> تنظیمات پنل رو برگردون به پیشفرض، اگر کار خاصی روی پنل یا برنامه نکردی و بازم اینجوریه یه اکانت گیتهاب و کلادفلر جدید بساز. کلادفلر بعضی وقتا فلگ میکنه.

من قسمت wow اینو قرار دادم از سایت  آی آر سی اف 162.159.192.88:1018
توقسمت warp endpoing هم دوباره اینو قرار دادم ولی ارور too many conectied  میده
از طریق بات تلگرام میخام کد وارپ بگیرم میگه موجود نیس از اون کانال تلگرامی برداشتم ولی هرکاری میکنم این ارور همش میده کجای کارم اشتباهه؟؟؟

**Comment by mrmm158** [comment]
Create your first project
Ready to start building? Create a repository for a new idea or bring over an existing repository to keep contributing to it.

**Comment by mrmm158** [comment]
برای من اول صفحه این میاد نه اسم پروژه و ...

**Comment by bia-pain-bache** [comment]
از آموزش ساخت با pages خود گیتهاب پروژه برید. کلیک به کلیک آموزش دادم.
