### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'address')

### ISSUE THREAD

**Issue by miladrasooli** [bia-pain-bache/BPB-Worker-Panel#3]
I tried to deploy and receive this error after navigating to address/uuid

TypeError: Cannot read properties of undefined (reading 'address')

**Comment by civilhps** [comment]
I tried to deploy and receive this error after navigating to address/uuid

TypeError: Cannot read properties of undefined (reading 'get')

**Comment by bia-pain-bache** [comment]
Please deply worker according to its instructions. it needs KV to be set.

**Comment by civilhps** [comment]
thanks for following up the issue
as this instruction : https://telegra.ph/%D9%86%D8%AD%D9%88%D9%87%E2%80%8C%DB%8C-%D8%B1%D8%A7%D9%87%E2%80%8C%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-BPB-Worker-Panel-%D8%A8%D9%87%E2%80%8C%D9%87%D9%85%D8%B1%D8%A7%D9%87-Fragment-01-19
nothing told aboub how to set KV?
do you mind providing any further info to set KV ?

**Comment by bia-pain-bache** [comment]
Oh, you are using previous version, you have to download the worker.js from the same instruction you mentioned, not the latest release.
hope this works.

**Comment by bia-pain-bache** [comment]
Oh, you are using previous version, you have to download the worker.js from the same instruction you mentioned, not the latest release.
hope this works.

**Comment by bia-pain-bache** [comment]
Every single release is accompanied by its own instruction. please follow my twitter in order to be aware of any further changes. From version 2.1 you need to set KV Datasets to save panel settings.

**Comment by asna220** [comment]
> I tried to deploy and receive this error after navigating to address/uuid
> 
> TypeError: Cannot read properties of undefined (reading 'get')

https://telegra.ph/%D9%86%D8%AD%D9%88%D9%87%E2%80%8C%DB%8C-%D8%B1%D8%A7%D9%87%E2%80%8C%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-BPB-Worker-Panel-%D8%A8%D9%87%E2%80%8C%D9%87%D9%85%D8%B1%D8%A7%D9%87-Fragment-01-28

**Comment by TheEmperoor** [comment]
> Every single release is accompanied by its own instruction. please follow my twitter in order to be aware of any further changes. From version 2.1 you need to set KV Datasets to save panel settings.

What should be the name of the variable? Is the name KV important?
