### ISSUE TITLE
no TLS config

### ISSUE THREAD

**Issue by EhsanGhaf** [bia-pain-bache/BPB-Worker-Panel#30]
Hi there, I need vless+ws without TLS,
i there any way?! may you please add it?! 
thanks in advance for the help

**Comment by dev-ehsan-babaei** [comment]
Hi, it doesn't work with custom domains so people would face issues. It's not scalable and secure so I removed it and its not planned to be added. You can make it manually though.

**Comment by EhsanGhaf** [comment]
thanks for the response, there is a trick to use vless+ws without tls even if the domain is filted without using fragment and even using a dirty cloudflare ip address. contact me on telegram to share the trick and talk if you would like: @vip4vpn
    On Sunday, April 21, 2024 at 02:54:55 PM GMT+3:30, dev-ehsan-babaei ***@***.***> wrote:  
 
 


Hi, it doesn't work with custom domains so people would face issues. It's not scalable and secure so I removed it and its not planned to be added. You can make it manually though.

**Comment by bia-pain-bache** [comment]
You can turn TLS off and connect using http ports, right?

**Comment by EhsanGhaf** [comment]
yes, use port 80, use put a dot after the subdomain, use xn-- in the subdomain, use a subdomain that has at least 5 layers, done, you get connected even if subdomain in filtered and cloudflare ip is dirty. 
for example: zula.ir.www.time.ir.xn--mgbug7c2am63g.domain.com.
    On Monday, April 22, 2024 at 02:18:02 AM GMT+3:30, bia-pain-bache ***@***.***> wrote:  
 
 


You can turn TLS off and connect using http ports, right?

**Comment by bia-pain-bache** [comment]
That's true about workers.dev, also regarding my tests it works with any addresses not only your template for filtered sni. However I couldn't get it working with Pages.dev and no TLS at all...

**Comment by EhsanGhaf** [comment]
there is a trick, just run a BPB panel that supports vless+ws without tls, then buy a domain and use CNANE record.the main use of BPB is free server, not necessarily free subdomain.
    On Monday, April 22, 2024 at 10:14:15 PM GMT+3:30, bia-pain-bache ***@***.***> wrote:  
 
 


That's true about workers.dev, also regarding my tests it works with any addresses not only your template for filtered sni. However I couldn't get it working with Pages.dev and no TLS at all...

**Comment by bia-pain-bache** [comment]
But i tested worker with custom domain and didn't work on port 80. I will test pages with custom domain to check.

**Comment by EhsanGhaf** [comment]
thanks very much. 
    On Wednesday, April 24, 2024 at 04:02:03 PM GMT+3:30, bia-pain-bache ***@***.***> wrote:  
 
 


But i tested worker with custom domain and didn't work on port 80. I will test pages with custom domain to check.

**Comment by bia-pain-bache** [comment]
Hi,
I'm gonna release new version which adds http ports, however i couldn't make pages with custom domain to work with http ports! do you have any recommendations on this?

**Comment by EhsanGhaf** [comment]
sorry to disappoint you, but currently no. I will look into in further after your update.
