### ISSUE TITLE
Wrong Password! admin version 2.5.5

### ISSUE THREAD

**Issue by zero-typora** [bia-pain-bache/BPB-Worker-Panel#302]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Wrong Password! admin version 2.5.5

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Wrong Password! admin version 2.5.5

### Relevant log output | لاگ برنامه یا پنل

```shell
Wrong Password! admin version 2.5.5
```

**Comment by isaac56899** [comment]
😑

**Comment by zero-typora** [comment]
Hello! May I ask what is the default password for the 2.5.5 version control panel? I used "admin" but it prompted that the password is incorrect. Please help me. Thank you.
