### ISSUE TITLE
مشکل با اسپید تست

### ISSUE THREAD

**Issue by 3reilii** [bia-pain-bache/BPB-Worker-Panel#306]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام. الان 2 3 روزه هر چی آیپی پروکسی رو عوض میکنم. نمیتونم تست سرعت speedtest.net  را باز کنم و لوکیشن نمیده.
در واقع نمیتونم به سایت های زی کلود فلر دسترسی پیدا کنم.
راه حلی براش دارین؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

could not open speedtest.net
could not open any webpage under cloudflare

### Relevant log output | لاگ برنامه یا پنل

```shell
15:29:05.907	Cloning repository...
15:29:07.563	From https://github.com/3reilii/BPB-Worker-Panel
15:29:07.564	 * branch            a8e9819940d9fa6dde4d6d4fb012d84fc84425f4 -> FETCH_HEAD
15:29:07.564	
15:29:07.633	HEAD is now at a8e9819 Added Warp Pro, Warp Plus, fragment packets.
15:29:07.634	
15:29:07.721	
15:29:07.721	Using v2 root directory strategy
15:29:07.746	Success: Finished cloning repository files
15:29:09.337	Checking for configuration in a wrangler.toml configuration file (BETA)
15:29:09.337	
15:29:09.444	No wrangler.toml file found. Continuing.
15:29:09.526	No build command specified. Skipping build step.
15:29:09.527	Found _worker.js in output directory. Uploading.
15:29:09.533	 ⛅️ wrangler 3.76.0
15:29:09.533	-------------------
15:29:10.430	✨ Compiled Worker successfully
15:29:10.502	Validating asset output directory
15:29:17.510	Success: Assets published!
15:29:19.544	Success: Your site was deployed!
```

**Comment by bia-pain-bache** [comment]
سلام، باید انقدر تست کنید تا سالم پیدا بشه. پیشفرض پنل الان وضعیت خوبی داره و تقریبا همه IP هاش سالمن. اگه نیازی به IP ثابت ندارید بذارید پیشفرض خودش باشه.

**Comment by 3reilii** [comment]
خیلی ممنون از راهنمایی سریعت
