### ISSUE TITLE
club house

### ISSUE THREAD

**Issue by m1745801** [bia-pain-bache/BPB-Worker-Panel#308]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود وقت بخیر و خدا قوت
من هر کاری میکنم تو برنامه کلاب هاوس اصلا صدا رو نمیتونم وصل کنم بدون فیلترشکن همه چی اوکی هست ، ولی وقتی فیلتر وصل باشه وارد گروه ها میشه ، اما صدا ها قطع هست ، ip ثابت گذاشتم نشد ، فرگمنت زدم نشد ، تغییر ip دادم نشد ، لطفا یه راه حل بهم بدید
و اینکه فرگمنت رو همراه اول که تست کردم بانک ها رو باز نمیکنه تیک برنامه های ایرانی رو از پنل فعال کردما ، وصلم میشم با فرگمنت اما بانک ها رو با فیلتر باز نمیکنه

### Relevant log output | لاگ برنامه یا پنل

```shell
فکر کنم اژ پنل باشه
```

**Comment by bia-pain-bache** [comment]
ظاهرا clubhouse از UDP استفاده میکنه که ورکر ساپورت نمیکنه.
