### ISSUE TITLE
Google services fail on Android when Fragment custom configs are used

### ISSUE THREAD

**Issue by amzaf** [bia-pain-bache/BPB-Worker-Panel#31]
سلام
کانفیگهایی که در برنامه v2rayng از طریق لینک سابسکریپشن فرگمنت دریافت می‌کنم خیلی خوب و عالیه تلگرام و اینستاگرام کار میکنه بجز سرویسهای گوگل مثل کروم و پلی استور که از کار میوفتن. به نظر میاد مشکل dns داره. من سرور dns پنل را تغییر دادم به https://8.8.8.8/dns-query تو برنامه v2rayng هرچی تنظیم سرور dns داره گذاشتم رو گوگل هیچ فرقی نمیکنه. routing rules را در پنل غیر فعال کردم بازم هیچی. 
حالا اگه لینک ساب نرمال را استفاده بکنم و خودم تو v2rayng تنظیم فرگمنت را فعال بکنم همه چی درست میشه

**Comment by dev-ehsan-babaei** [comment]
سلام،
مربوط به هیچکدوم نیست، احتمالا Proxy IP ست کردی که کار نمیکنه، تعویضش کن درست میشه.

**Comment by amzaf** [comment]
> سلام، مربوط به هیچکدوم نیست، احتمالا Proxy IP ست کردی که کار نمیکنه، تعویضش کن درست میشه.

پروکسی آی پی نمیدونم چیه. اگه منظورتون Chain Proxy داخل پنل هست خیر هیچ چی ست نکردم.

**Comment by bia-pain-bache** [comment]
این مشکل معمولا مربوط به proxy ip هست. در صورتی که ازش استفاده نکردی لطفا یه بار دیگه دپلوی کن.

**Comment by amzaf** [comment]
> این مشکل معمولا مربوط به proxy ip هست. در صورتی که ازش استفاده نکردی لطفا یه بار دیگه دپلوی کن.

چی رو دیپلوی کنم؟ من از ورکر ورژن ۲.۳.۳ دارم استفاده می‌کنم. شما فکرکنم ذهنیتت روی پیجز هستش. ورکر را فقط با ویرایش uuid همونطوری که تو راهنما گفتید نصب کردم.

**Comment by bia-pain-bache** [comment]
فرقی نداره از چه روشی استفاده میکنید، جفتشون بهش میگن دپلوی. مشکل سایتها فقط به DNS و Proxy IP مربوط میشد که ظاهرا شامل حال شما نمیشه. متاسفانه خودم یا دیگران با کانفیگ فرگمنت به چنین مشکلی نخوردیم و با این اطلاعات کمک دیگه‌ای از من بر نمیاد.

**Comment by amzaf** [comment]
> فرقی نداره از چه روشی استفاده میکنید، جفتشون بهش میگن دپلوی. مشکل سایتها فقط به DNS و Proxy IP مربوط میشد که ظاهرا شامل حال شما نمیشه. متاسفانه خودم یا دیگران با کانفیگ فرگمنت به چنین مشکلی نخوردیم و با این اطلاعات کمک دیگه‌ای از من بر نمیاد.

مشکل را پیدا کردم. v2rayng را حذف کردم و دوباره نصب کردم دیدم ساب فرگمنت راه افتاد. رفتم تو قسمت تنظیمات دیدم در حالت خام  enable local dns غیر فعاله. همین که این local dns را فعال بکنی کروم از کار میوفته ولی اینستاگرام کار می‌کنه.
من از این تنظیم استفاده می‌کنم بخاطر اینکه کاستوم رول تعریف کرده بودم تا آی پی ایران و آی پی لن را پروکسی نکنه. امیدوارم کمکی کرده باشه برای دیگران و برای شما که کانفیگی تهیه بکنید تا با local dns سازگار باشه.

**Comment by bia-pain-bache** [comment]
ممنونم، با همون local dns های معمولی هم روتینگ به خوبی انجام میشه، خیلی ضرورتی نداره بذارید رو local. آپدیت قبلی هم این امکان رو اضافه کردم که تو پنل بتونید local dns رو بذارید localhost.
