### ISSUE TITLE
How change to dev branch

### ISSUE THREAD

**Issue by misagh72** [bia-pain-bache/BPB-Worker-Panel#312]
### Feature description | توضیحات ویژگی

سلام میخواستم بدونم من الان main رو فورک کردم و توی کلودفلر قرار دادم چطوری میتونم به dev تغییرش بدم

**Comment by bia-pain-bache** [comment]
سلام، این کارو نکنید توصیه نمیکنم، اگر میخواید dev تست کنید فایل _worker.js رو بگیرید و با ورکر دپلوی کنید.
