### ISSUE TITLE
انتخاب کانفیگ های مورد نظر برای هر لینک ساب

### ISSUE THREAD

**Issue by rasa68** [bia-pain-bache/BPB-Worker-Panel#317]
### Feature description | توضیحات ویژگی

سلام و خسته نباشید. 
ممنون از تلاش هایی که برای این پنل انجام دادید.
اگر امکانش باشه که خودمون به صورت دستی انتخاب کنیم در هر ساب کدوم کانفیگ ها فعال باشه خیلی عالی میشه و کاربردی هست.

**Comment by bia-pain-bache** [comment]
سلام، سلامت باشید.
متاسفانه موارد سلیقه‌ای یا ظاهری رو معمولا به پنل اضافه نمیکنم، صرفا مواردی که به عملکرد پروکسی مربوطه.
