### ISSUE TITLE
karing sing-box

### ISSUE THREAD

**Issue by bbylw** [bia-pain-bache/BPB-Worker-Panel#320]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Many tools in BPB Panel version 2.5.9 are not working properly, such as karing sing-box. Although it can be pinged, it is not usable. Please fix this issue.

### Relevant log output | لاگ برنامه یا پنل

```shell
no
```

**Comment by bia-pain-bache** [comment]
I just mentioned Karing name in one subscription. Karing claims that supports Clash, SIng-box and Xray but it supports none of them properly, none of standard Clash, Sing-box configs (which perfectly work on main apps) work on Karing!
