### ISSUE TITLE
اشتباه تایبی در فایل congratulations-fa.md 4-1-5

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#322]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

4-1-5- زمان ]ک کردن Best Ping 

اینجا یه اشتباه تایپی کوچیک بود گفتم اطلاع بدم

### Relevant log output | لاگ برنامه یا پنل

```shell
nothing
```

**Comment by bia-pain-bache** [comment]
ممنونم اطلاع دادید.
