### ISSUE TITLE
مشکل در اتصال

### ISSUE THREAD

**Issue by comdoost** [bia-pain-bache/BPB-Worker-Panel#323]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سپاس از زحمات شما
متاسفانه بعد از آپدیت پنل و کانفیگ‌ها، دیگه کار نمی‌کنه و فقط تلگرام باز می‌شه!

### Relevant log output | لاگ برنامه یا پنل

```shell
بدون لاگ
```

**Comment by bia-pain-bache** [comment]
سلام، ممنونم.
بعد از آپدیت 2.6 متوجه یه مشکلی شدم که 2-3 ساعت بعد فیکسش کردم. لطفا آپدیت کنید.

**Comment by comdoost** [comment]
درود بر شما
و سپاس از زحمات

**Comment by comdoost** [comment]
آپدیت کردم ولی هنوز مشکل پابرجاست
با ورژن ۲.۵.۵ مشکلی نیست ولی ۲.۵.۹ و ۲.۶ مشکل داره

**Comment by bia-pain-bache** [comment]
باید اطلاعات دقیق بدید کدوم کانفیگ‌ها کدوم کلاینت. ساب‌ها رو آپدیت کردید بعدش؟

**Comment by comdoost** [comment]
کلیه کانفیگها را پاک می‌کنم و بعد آپدیت می‌کنم و کار نمی‌کنه(کلیه کانفیگ‌های فرگمنت و وارپ پرو)
فقط تلگرام باز می‌شه،‌ یوتیوب و تیک‌تاک و اینستاگرام باز نمی‌شه!
تو کلادفلر deployment را به ورژن ۲.۵.۵ rollback می‌کنم درست می‌شه!

**Comment by bia-pain-bache** [comment]
توی تنظیمات v2ray یا nika گزینه enable local dns رو فعال کن و ببین مشکل برطرف میشه یا نه، اینجا آپدیت کن لطفا.

**Comment by comdoost** [comment]
متاسفانه فایده نداشت

**Comment by bia-pain-bache** [comment]
لطفا کانفیگ شماره ۱ دامنه‌هاشو پاک کن و اینجا بذار

**Comment by comdoost** [comment]
{
  "remarks": "💦 1 - VLESS F - Domain : 443",
  "log": {
    "loglevel": "warning"
  },
  "dns": {
    "hosts": {
      "domain:googleapis.cn": [
        "googleapis.com"
      ],
      "dns.google": [
        "8.8.8.8",
        "8.8.4.4",
        "2001:4860:4860::8844",
        "2001:4860:4860::8888"
      ],
      "geosite:category-ads-all": [
        "127.0.0.1"
      ],
      "geosite:category-ads-ir": [
        "127.0.0.1"
      ]
    },
    "servers": [
      "https://dns.google/dns-query",
      {
        "address": "8.8.8.8",
        "domains": [
          "geosite:private",
          "geosite:category-ir"
        ],
        "expectIPs": [
          "geoip:private",
          "geoip:ir"
        ]
      }
    ],
    "tag": "dns"
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true,
        "routeOnly": true
      },
      "tag": "socks-in"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true,
        "routeOnly": true
      },
      "tag": "http-in"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "******.pages.dev",
            "port": 443,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "86d3-a7cb-b828",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "sockopt": {
          "dialerProxy": "fragment",
          "tcpNoDelay": true
        },
        "tlsSettings": {
          "allowInsecure": false,
          "fingerprint": "randomized",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "serverName": "*****.paGeS.DEV"
        },
        "wsSettings": {
          "headers": {
            "Host": "*****.pages.dev",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
          },
          "path": "/Qn67rZyJ/MTLjETU=?ed=260"
        }
      },
      "tag": "proxy"
    },
    {
      "tag": "fragment",
      "protocol": "freedom",
      "settings": {
        "fragment": {
          "packets": "tlshello",
          "length": "100-200",
          "interval": "1-1"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpKeepAliveIdle": 100,
          "tcpNoDelay": true
        }
      }
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "inboundTag": [
          "socks-in",
          "http-in"
        ],
        "port": "53",
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "network": "udp",
        "port": "53",
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:private",
          "geosite:category-ir"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:category-ads-all",
          "geosite:category-ads-ir"
        ],
        "outboundTag": "block",
        "type": "field"
      },
      {
        "network": "tcp",
        "outboundTag": "proxy",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by bia-pain-bache** [comment]
این از کجا اومده؟
?ed=260
خودت تغییر دادی؟

**Comment by comdoost** [comment]
{
  "remarks": "💦 1 - VLESS F - Domain : 443",
  "log": {
    "loglevel": "warning"
  },
  "dns": {
    "hosts": {
      "domain:googleapis.cn": [
        "googleapis.com"
      ],
      "dns.google": [
        "8.8.4.4",
        "8.8.8.8",
        "2001:4860:4860::8888",
        "2001:4860:4860::8844"
      ],
      "geosite:category-ads-all": [
        "127.0.0.1"
      ],
      "geosite:category-ads-ir": [
        "127.0.0.1"
      ]
    },
    "servers": [
      "https://dns.google/dns-query",
      {
        "address": "8.8.8.8",
        "domains": [
          "geosite:private",
          "geosite:category-ir"
        ],
        "expectIPs": [
          "geoip:private",
          "geoip:ir"
        ]
      }
    ],
    "tag": "dns"
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true,
        "routeOnly": true
      },
      "tag": "socks-in"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true,
        "routeOnly": true
      },
      "tag": "http-in"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "aaaaaa.pages.dev",
            "port": 443,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "c63bbc0a-86d3-483c-a7cb-b828aede59d1",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "sockopt": {
          "dialerProxy": "fragment",
          "tcpNoDelay": true
        },
        "tlsSettings": {
          "allowInsecure": false,
          "fingerprint": "randomized",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "serverName": "aaaaaa.pAGES.dEv"
        },
        "wsSettings": {
          "headers": {
            "Host": "aaaaaa.pages.dev",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
          },
          "path": "/sRimXuPUlnXsw6YD/MTQxLjE0OC4yNDYuMTU=?ed=2560"
        }
      },
      "tag": "proxy"
    },
    {
      "tag": "fragment",
      "protocol": "freedom",
      "settings": {
        "fragment": {
          "packets": "tlshello",
          "length": "100-200",
          "interval": "1-1"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpKeepAliveIdle": 100,
          "tcpNoDelay": true
        }
      }
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "inboundTag": [
          "socks-in",
          "http-in"
        ],
        "port": "53",
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "network": "udp",
        "port": "53",
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:private",
          "geosite:category-ir"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:category-ads-all",
          "geosite:category-ads-ir"
        ],
        "outboundTag": "block",
        "type": "field"
      },
      {
        "network": "tcp",
        "outboundTag": "proxy",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by comdoost** [comment]
مجدد ارسال کردم

**Comment by comddoost** [comment]
کانکشن‌‌های وارپ مشکل دارن

**Comment by bia-pain-bache** [comment]
الان pre-release 2.6.2 رو منتشر کردم. میتونید با ورکر تست کنید.

**Comment by comddoost** [comment]
درود بر شما و سپاس از زحمات
امیدوارم همیشه همینطور پرتوان باشید

**Comment by bia-pain-bache** [comment]
ممنونم سلامت باشید.
