### ISSUE TITLE
warp config problem

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#326]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

بعد از آپدیت به آخرین نسخه پنل کانفیگای وارپ دچار مشکل میشن و فکر میکنم مشکل از dns کانفیگ ها باشه چون موقع باز کردن سایت ها در مرورگر certificate error میده

### Relevant log output | لاگ برنامه یا پنل

```shell
2024/09/27 23:15:09 [Warning] core: Xray 1.8.23 started
2024/09/27 23:15:09 from 127.0.0.1:6082 accepted //www.google.com:443 [http-in -> warp]
2024/09/27 23:15:10 from DNS accepted udp:1.1.1.1:53 [dns -> direct]
2024/09/27 23:15:10 [Error] app/dns: UDP:1.1.1.1:53 cannot find the pending request
2024/09/27 23:15:10 The ping of current service: 141 ms
2024/09/27 23:15:10 System proxy setting is changed - ForcedChange
```

**Comment by bia-pain-bache** [comment]
بعد از آپدیت 2.6 متوجه یه مشکلی شدم که 2-3 ساعت بعد فیکسش کردم. لطفا آپدیت کنید و ساب رو هم آپدیت کتید.

**Comment by developer861** [comment]
آپدیت کردم. ساب هم آپدیت کردم ولی هنوزم  مشکل داره :(
یه نکته ای که متوجه شدم وقتی با گوگل سرچ میکنم نتیجه رو میاره ولی برای بقیه سایتا ارور دی ان اس میده
فکر کنم به خاطر اینه که واسه گوگل مرورگر نیاز به درخواست dns نداره و سایتو بدون مشکل بالا میاره 

2024/09/29 01:49:48 [Warning] core: Xray 1.8.23 started
2024/09/29 01:49:49 from 127.0.0.1:2830 accepted //www.google.com:443 [http-in -> warp-out_1]
2024/09/29 01:49:49 from DNS accepted udp:1.1.1.1:53 [dns -> direct]
2024/09/29 01:49:49 [Error] app/dns: UDP:1.1.1.1:53 cannot find the pending request
2024/09/29 01:49:50 The ping of current service: 163 ms

هنوز هم همون ارور تو بخش لاگ هست (خط چهارم)

**Comment by bia-pain-bache** [comment]
از لاگ متوجه شدم ساب هنوز آپدیت نشده، بعضی وقتا کلادفلر کش میکنه، ۲-۳ بار ساب رو آپدیت کنید احتمالا اوکی بشه.

**Comment by bia-pain-bache** [comment]
من همین الان متوجه مشکل شدم، به زودی فیکسش میکنم.

**Comment by developer861** [comment]
فکر کنم منم متوجه مشکل شدم 
تو rule ها ترافیک پورت 53 رو direct بود که dns هم از همین پورت استفاده میکرد

**Comment by developer861** [comment]
یه سوال دیگه هم داشتم چرا به جای 1.1.1.1 از 8.8.8.8 استفاده نمیکنید برای dns؟
مال گوگل بهتر نیست؟

**Comment by bia-pain-bache** [comment]
برای وارپ dns پیشنهادی همون ۱.۱.۱.۱ هست، سازگارتره، تو تستام عملکردش بهتره وگرنه میشه هرچی گذاشت.

**Comment by bia-pain-bache** [comment]
یه pre-release ورژن 2.6.1 گذاشتم، میتونید با ورکر دپلوی کنید و ببینید مشکل برطرف شده یا نه.

**Comment by developer861** [comment]
تست کردم اوکی شد دمتون گرم

**Comment by developer861** [comment]
آقا الان به یه مشکل عجیب تر برخورد کردم کانفیگای wow آیپی ایران میدن :0

**Comment by developer861** [comment]
به نظر میرسه مشکل از سمت کلادفلر باشه :(
https://github.com/bepass-org/warp-plus/issues/214#issuecomment-2371999407

**Comment by bia-pain-bache** [comment]
ظاهرا مسیریابی‌های کلادفلر عوض شدن.

**Comment by developer861** [comment]
{
  "remarks": "Tel= arshiacomplus - WoW",
  "log": {
    "loglevel": "warning"
  },
  "dns": {
    "hosts": {
      "geosite:category-ads-all": "127.0.0.1",
      "geosite:category-ads-ir": "127.0.0.1"
    },
    "servers": [
      "https://94.140.14.14/dns-query",
      {
        "address": "8.8.8.8",
        "domains": [
          "geosite:category-ir",
          "domain:.ir"
        ],
        "expectIPs": [
          "geoip:ir"
        ],
        "port": 53
      }
    ],
    "tag": "dns"
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true,
        "routeOnly": true
      },
      "tag": "socks-in"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true,
        "routeOnly": true
      },
      "tag": "http-in"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "outbounds": [
    {
      "protocol": "wireguard",
      "settings": {
        "address": [
          "172.16.0.2/32",
          "2606:4700:110:846c:e510:bfa1:ea9f:5247/128"
        ],
        "mtu": 1300,
        "peers": [
          {
            "endpoint": "188.114.97.123:4198",
            "publicKey": "bmXOC\u002BF1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
          }
        ],
        "reserved": [
          155,
          195,
          125
        ],
        "secretKey": "IDX/j5flUxAayL63wK5bVohiiro\u002BA0mueQ0n5Y7JPlo=",
        "keepAlive": 10,
        "wnoise": "quic",
        "wnoisecount": "10-15",
        "wpayloadsize": "1-8",
        "wnoisedelay": "1-3"
      },
      "streamSettings": {
        "sockopt": {
          "dialerProxy": "warp-ir"
        }
      },
      "tag": "warp-out"
    },
    {
      "protocol": "wireguard",
      "settings": {
        "address": [
          "172.16.0.2/32",
          "2606:4700:110:846c:e510:bfa1:ea9f:5247/128"
        ],
        "mtu": 1300,
        "peers": [
          {
            "endpoint": "188.114.97.219:1002",
            "publicKey": "bmXOC\u002BF1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
          }
        ],
        "reserved": [
          215,
          1,
          250
        ],
        "secretKey": "aKaHdPZUaky1ULLG7yPHm9\u002Bxzr66aejMr1/bVGcrJ3o=",
        "keepAlive": 10,
        "wnoise": "quic",
        "wnoisecount": "10-15",
        "wpayloadsize": "1-8",
        "wnoisedelay": "1-3"
      },
      "tag": "warp-ir"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "geosite:category-ir",
          "domain:.ir"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:ir",
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:category-ads-all",
          "geosite:category-ads-ir"
        ],
        "outboundTag": "block",
        "type": "field"
      },
      {
        "outboundTag": "warp-out",
        "type": "field",
        "network": "tcp,udp"
      }
    ]
  },
  "stats": {}
}

**Comment by developer861** [comment]
عجیبه این کانفیگ WOW آیپی هلند میده
https://github.com/arshiacomplus/WoW-fix
تو این ریپوزیتوری بود

**Comment by developer861** [comment]
دلیل خاصی داره؟

**Comment by bia-pain-bache** [comment]
نمیدونم.

**Comment by developer861** [comment]
احتمالا به خاطر تغییرات کلادفلر باشه
