### ISSUE TITLE
مشکل SNI در [💀 Custom SNI ]

### ISSUE THREAD

**Issue by liMilCo** [bia-pain-bache/BPB-Worker-Panel#328]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با سلام
سیستم موقع ساخت کانفیگ ها دامنه SNI رو با حروف کوچک و بزرگ مینویسد وقتی میخواهیم از دامنه فیک جی-کور در (💀 Custom SNI) استفاده کنیم باید SNI رو یک دامنه پشت جیکور باشد، که اگر این دامنه تماما با حروف کوچک نباشد جی-کور قبول نمیکند 
مثلا cDn..GCOre.cOm را قبول نمیکند و حتی باید cdn.gcore.com باشد ...

### Relevant log output | لاگ برنامه یا پنل

```shell
2024/09/28 21:12:49 [Error] [3544618208] transport/internet/websocket: failed to dial to cdn.gcore.com:443 > remote error: tls: internal error

Error: (503) service Unavailable
```

**Comment by bia-pain-bache** [comment]
سلام، مطمئنی بخاطر اونه؟ یعنی با حروف کوچیک وصل میشه با بزرگ وصل نمیشه؟! چون من دامنه‌های gcore رو با حروف بزرگم چک کردم هم ریزالو میشن هم پینگ دارن، مطمئن نیستم بخاطر این باشه.

**Comment by liMilCo** [comment]
> سلام، مطمئنی بخاطر اونه؟ یعنی با حروف کوچیک وصل میشه با بزرگ وصل نمیشه؟! چون من دامنه‌های gcore رو با حروف بزرگم چک کردم هم ریزالو میشن هم پینگ دارن، مطمئن نیستم بخاطر این باشه.

کاملا مطمعن هستم، تمام حالات رو چک کردم، خیلی ساده اگر اس-ان-ای رو Gcore.com بزاری کار  نمیکنه اما اگر gcore.com بزاری کار میکنه، اگر لازم هست یه نمونه کانکشن بفرستم براتون ....

**Comment by liMilCo** [comment]
خیلی بهتر میشد اگ این امکان که سیستم آدرس دامنه رو درهم میکنه (با حروف بزرگ و کوچک رندم تولید میکنه) بشود خاموش کرد
حداقل در بخش [💀 Custom SNI ] دقیقا همونی که در پنل نوشتیم بدون تغییر وارد کنه که اگر کسی خواست خودش حروف دامنه رو بزرگ-کوچک یا تماما با حروف کوچک بنویسه ...

**Comment by bia-pain-bache** [comment]
ورژن 2.6.2 برای کانفیگ‌های Custom غیرفعال کردم، ضرورتی هم نداشت.
