### ISSUE TITLE
هیچ کدام از تنظمات ارایه شده در openwrt passwall1 , 2  کار نمیکند؟

### ISSUE THREAD

**Issue by amirmhs58** [bia-pain-bache/BPB-Worker-Panel#329]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام

من آخرین ورژن که 2.6 است را دارم و روی موبایل و کامپیوتر اوکی است و تمام تنظمات کار میکند ولی همان تنظیمات در openwrt و روی passwall1 , passwall2 ست کردم کار نمیکند !؟ در صورتی که تنظماتی که از سرور شخصی خودم با Hiddify manager  دارم کار میکند!

لطفا راهنمای بفرمایید
سپاس فراوان

### Relevant log output | لاگ برنامه یا پنل

```shell
bpb panel ver 2.6
openwrt ver 23.05.3
passwall   ver 4.78-2
passwall 2 ver 1.31-1
```

**Comment by bia-pain-bache** [comment]
سلام، متاسفانه تجربه‌ی کار باهاش رو ندارم، نمیتونم راهنمایی خاصی بکنم.
