### ISSUE TITLE
اعداد منفی در پارامترها

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#330]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

مشکل خاصی نیست ولی گفتم اطلاع بدم شاید خواستید فییکس کنید وقتی تو تنظیمات پارامترارو تنظیم میکنید اعداد منفی هم میاره

### Relevant log output | لاگ برنامه یا پنل

```shell
nothing
```

**Comment by bia-pain-bache** [comment]
ممنون اطلاع دادید.
