### ISSUE TITLE
کرش کردن Hiddify و Sing Box در حالت auto

### ISSUE THREAD

**Issue by Siavash1291** [bia-pain-bache/BPB-Worker-Panel#334]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

تمام اپلیکیشن هایی که قابلیت سوئیچ اتوماتیک روی کانفیگ با پینگ بهتر رو دارن، بعد از چند دقیقه کرش میکنن و باید دوباره اپلیکیشن رو باز کنید و دوباره کانکت بشین. ولی زمانیکه مثلا در Hiddify گزینه ی memory limit رو روشن میکنی کمی اوضاع بهتر میشه ولی همچنان آزار دهنده هست. خواستم ببینیم آیا امکانش هست که این وظیفه ی سوئیچ کردن رو انداخت به گردن خود Cloudflare یا  هر کار دیگه ای که این بار پردازش و حافظه رو از دوش دیوایس کاربر برداره؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. run the application
2. connect to the service
3. select 'Auto' mode in 'Proxies' section
4. minimize the application

### Relevant log output | لاگ برنامه یا پنل

```shell
####
```

**Comment by bia-pain-bache** [comment]
نه متاسفانه، مشکل اپلیکیشنه، البته من همیشه آپدیت میکنم و مشکل خاصی تجریه نکردم. هر چی هست سخت‌افزاری/نرم‌افزاریه.

**Comment by Siavash1291** [comment]
تعداد آی پی تمیز رو کم کردم مشکل حل شد
