### ISSUE TITLE
تروجان 

### ISSUE THREAD

**Issue by lord-wolf7** [bia-pain-bache/BPB-Worker-Panel#336]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

این تروجان کار نمیکنه این پسورد که گفتتی تو پنل اختصاص بدیم کجا کاربرد داره؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

این تروجان کار نمیکنه این پسورد که گفتتی تو پنل اختصاص بدیم کجا کاربرد داره؟

### Relevant log output | لاگ برنامه یا پنل

```shell
این تروجان کار نمیکنه این پسورد که گفتتی تو پنل اختصاص بدیم کجا کاربرد داره؟
```

**Comment by misagh72** [comment]
تروجان کار میکنه شما یک جایی رو اشتباه رفتین

**Comment by lord-wolf7** [comment]
> تروجان کار میکنه شما یک جایی رو اشتباه رفتین

آخه کاری نکردم تنظیمات پیش فرض پنل  فقط تو کلود فلر هش پسورد و تروجان پس اضافه کردم با وی تو رای ساپورت میکنه ؟؟

**Comment by lord-wolf7** [comment]
میشه به این تلگرام پیام بدی من لینکش بفرستم یه تست بزنی 
https://t.me/Lord_wolf
