### ISSUE TITLE
عدم آپدیت به نسخه 2.6 

### ISSUE THREAD

**Issue by neonramzy** [bia-pain-bache/BPB-Worker-Panel#339]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود. با اینکه مخزن گیت هاب با نسخه اصلی همگام سازی شده ولی پنل به نسخه 2.6 بروزرسانی نشده و روی 2.5.5 باقی مونده.

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

**Comment by bia-pain-bache** [comment]
سلام، جوابش قسمت سوالات متداول هست.
