### ISSUE TITLE
ترجان 

### ISSUE THREAD

**Issue by lord-wolf7** [bia-pain-bache/BPB-Worker-Panel#347]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

من وقتی تروجان تو وی تو ری میزنم این ارور میده بنظرت مشکل از چیه؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1403/07/10 22:22:08 تنظیمات پراکسی سیستم تغییر کرده است - ForcedClear
+0330 2024-10-01 22:22:10 ERROR [2735145407 1.2s] outbound/urltest[proxy-auto]: EOF
1403/07/10 22:22:10 پینگ سرویس فعلی: -1 ms
پیکربندی با موفقیت انجام شد
[Trojan] 💦 10 - Trojan - Domain : 443(www***net:443)
Microsoft Windows NT 10.0.22631.0 - 64
Start service (1403/07/10 22:22:15)...
Xray 1.8.16 (Xray, Penetrates Everything.) 9432a60 (go1.22.4 windows/amd64)
2024/10/01 22:22:15 Using default config:  E:\v2rayN-With-Core\guiConfigs\config.json
A unified platform for anti-censorship.
2024/10/01 22:22:15 [Info] infra/conf/serial: Reading config: E:\v2rayN-With-Core\guiConfigs\config.json
2024/10/01 22:22:15 [Warning] core: Xray 1.8.16 started
1403/07/10 22:22:16 تنظیمات پراکسی سیستم تغییر کرده است - ForcedClear
2024/10/01 22:22:16 127.0.0.1:11857 accepted //www.google.com:443 [http -> proxy]
1403/07/10 22:22:18 تنظیمات پراکسی سیستم تغییر کرده است - ForcedChange
1403/07/10 22:22:20 پینگ سرویس فعلی: -1 ms
2024/10/01 22:22:22 127.0.0.1:11874 accepted //91.108.56.121:443 [http -> proxy]
2024/10/01 22:22:22 127.0.0.1:11875 accepted http://91.108.56.121:80/api [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11881 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11883 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11880 accepted //149.154.167.151:443 [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11886 accepted http://149.154.167.151:80/api [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11889 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11879 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11882 accepted //149.154.175.54:443 [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11892 accepted http://149.154.175.54:80/api [http -> proxy]
2024/10/01 22:22:23 [Warning] [3926630743] proxy/http: failed to read response from 91.108.56.121:80 > io: read/write on closed pipe
2024/10/01 22:22:23 [Warning] [3926630743] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:11875: wsasend: An established connection was aborted by the software in your host machine.
2024/10/01 22:22:23 127.0.0.1:11895 accepted //149.154.167.92:443 [http -> proxy]
2024/10/01 22:22:23 127.0.0.1:11896 accepted http://149.154.167.92:80/api [http -> proxy]
2024/10/01 22:22:24 [Warning] [1529299299] proxy/http: failed to read response from 149.154.175.54:80 > io: read/write on closed pipe
2024/10/01 22:22:24 [Error] transport/internet/websocket: failed to dial to www.speedtest.net:443 > context canceled
2024/10/01 22:22:24 127.0.0.1:11901 accepted http://149.154.175.54:80/api [http -> proxy]
2024/10/01 22:22:24 127.0.0.1:11900 accepted //149.154.175.54:443 [http -> proxy]
2024/10/01 22:22:25 [Warning] [4102773526] proxy/http: failed to read response from 149.154.167.43:80 > io: read/write on closed pipe
2024/10/01 22:22:25 127.0.0.1:11904 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:25 127.0.0.1:11905 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:25 [Warning] [644846275] proxy/http: failed to read response from 149.154.167.151:80 > io: read/write on closed pipe
2024/10/01 22:22:25 127.0.0.1:11909 accepted //149.154.167.151:443 [http -> proxy]
2024/10/01 22:22:25 127.0.0.1:11910 accepted http://149.154.167.151:80/api [http -> proxy]
2024/10/01 22:22:25 [Warning] [3548337063] proxy/http: failed to read response from 149.154.167.92:80 > io: read/write on closed pipe
2024/10/01 22:22:26 [Warning] [4140823530] proxy/http: failed to read response from 149.154.167.43:80 > io: read/write on closed pipe
2024/10/01 22:22:26 [Warning] [2561425012] proxy/http: failed to read response from 149.154.175.54:80 > io: read/write on closed pipe
2024/10/01 22:22:26 127.0.0.1:11915 accepted //149.154.175.54:443 [http -> proxy]
2024/10/01 22:22:26 127.0.0.1:11916 accepted http://149.154.175.54:80/api [http -> proxy]
2024/10/01 22:22:28 127.0.0.1:11924 accepted //149.154.175.54:443 [http -> proxy]
2024/10/01 22:22:28 127.0.0.1:11925 accepted http://149.154.175.54:80/api [http -> proxy]
2024/10/01 22:22:28 127.0.0.1:11928 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:28 127.0.0.1:11929 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:28 127.0.0.1:11932 accepted //149.154.167.92:443 [http -> proxy]
2024/10/01 22:22:28 127.0.0.1:11933 accepted http://149.154.167.92:80/api [http -> proxy]
2024/10/01 22:22:29 [Warning] [189750562] proxy/http: failed to read response from 149.154.175.54:80 > io: read/write on closed pipe
پیکربندی اولیه
Start service (1403/07/10 22:22:29)...
E:\v2rayN-With-Core\guiConfigs\configSpeedtest.json
Xray 1.8.16 (Xray, Penetrates Everything.) 9432a60 (go1.22.4 windows/amd64)
A unified platform for anti-censorship.
2024/10/01 22:22:29 [Info] infra/conf/serial: Reading config: configSpeedtest.json
2024/10/01 22:22:29 [Warning] core: Xray 1.8.16 started
2024/10/01 22:22:29 [Warning] [3780563882] proxy/http: failed to read response from 149.154.167.92:80 > io: read/write on closed pipe
2024/10/01 22:22:30 127.0.0.1:11939 accepted //www.google.com:443 [http10829 -> proxy10829]
2024/10/01 22:22:31 [Warning] [259836613] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > proxy/trojan: failed to flush payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://www.speedtest.net/trMhXr7PMauXnpH6aJ):  > websocket: protocol "h2" was given but is not supported;sharing tls.Config with net/http Transport can cause this error: read tcp 192.168.1.100:11884->104.17.148.22:443: i/o timeout
2024/10/01 22:22:31 [Warning] [259836613] proxy/http: failed to read response from 149.154.167.43:80 > io: read/write on closed pipe
2024/10/01 22:22:31 [Warning] [259836613] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:11883: wsasend: An established connection was aborted by the software in your host machine.
2024/10/01 22:22:31 127.0.0.1:11943 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:31 127.0.0.1:11945 accepted http://149.154.167.51:80/api [http -> proxy]
2024/10/01 22:22:31 127.0.0.1:11946 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:31 127.0.0.1:11949 accepted http://149.154.167.41:80/api [http -> proxy]
2024/10/01 22:22:31 127.0.0.1:11942 accepted //149.154.167.51:443 [http -> proxy]
2024/10/01 22:22:31 127.0.0.1:11944 accepted //149.154.167.41:443 [http -> proxy]
2024/10/01 22:22:32 127.0.0.1:11957 accepted http://149.154.167.51:80/api [http -> proxy]
2024/10/01 22:22:32 127.0.0.1:11958 accepted http://149.154.167.41:80/api [http -> proxy]
2024/10/01 22:22:32 127.0.0.1:11955 accepted //149.154.167.51:443 [http -> proxy]
2024/10/01 22:22:32 127.0.0.1:11956 accepted //149.154.167.41:443 [http -> proxy]
2024/10/01 22:22:33 127.0.0.1:11964 accepted //149.154.167.151:443 [http -> proxy]
2024/10/01 22:22:33 127.0.0.1:11965 accepted http://149.154.167.151:80/api [http -> proxy]
2024/10/01 22:22:34 [Warning] [66047395] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > proxy/trojan: failed to flush payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://www.speedtest.net/trMhXr7PMauXnpH6aJ):  > websocket: protocol "h2" was given but is not supported;sharing tls.Config with net/http Transport can cause this error: read tcp 192.168.1.100:11918->104.17.148.22:443: i/o timeout
2024/10/01 22:22:34 [Warning] [66047395] proxy/http: failed to read response from 149.154.175.54:80 > io: read/write on closed pipe
2024/10/01 22:22:34 [Warning] [66047395] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:11916: wsasend: An established connection was aborted by the software in your host machine.
2024/10/01 22:22:34 127.0.0.1:11971 accepted http://149.154.167.51:80/api [http -> proxy]
2024/10/01 22:22:34 127.0.0.1:11970 accepted //149.154.167.41:443 [http -> proxy]
2024/10/01 22:22:34 127.0.0.1:11969 accepted //149.154.167.51:443 [http -> proxy]
2024/10/01 22:22:34 127.0.0.1:11972 accepted http://149.154.167.41:80/api [http -> proxy]
2024/10/01 22:22:34 [Warning] [2787224421] proxy/http: failed to read response from 149.154.167.43:80 > io: read/write on closed pipe
2024/10/01 22:22:34 127.0.0.1:11978 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:34 127.0.0.1:11979 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:35 [Error] transport/internet/websocket: failed to dial to www.speedtest.net:443 > context canceled
2024/10/01 22:22:35 [Error] transport/internet/websocket: failed to dial to www.speedtest.net:443 > context canceled
2024/10/01 22:22:36 [Warning] [2175285187] proxy/http: failed to read response from 149.154.167.151:80 > io: read/write on closed pipe
2024/10/01 22:22:36 127.0.0.1:11985 accepted //www.google.com:443 [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11988 accepted //149.154.167.43:443 [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11989 accepted http://149.154.167.43:80/api [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11992 accepted //www.google.com:443 [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11994 accepted //www.google.com:443 [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11997 accepted //www.google.com:443 [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11996 accepted //149.154.167.92:443 [http -> proxy]
2024/10/01 22:22:36 127.0.0.1:11999 accepted http://149.154.167.92:80/api [http -> proxy]
2024/10/01 22:22:37 [Warning] [882709930] proxy/http: failed to read response from 149.154.167.51:80 > io: read/write on closed pipe
2024/10/01 22:22:37 [Warning] [882709930] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:11957: wsasend: An established connection was 

### Relevant log output | لاگ برنامه یا پنل

```shell
من وقتی تروجان تو وی تو ری میزنم این ارور میده بنظرت مشکل از چیه؟
```

**Comment by bia-pain-bache** [comment]
لطفا به آموزش‌ها یا سوالات متداول رجوع کن و تنظیمات رو انجام بده،
