### ISSUE TITLE
About the IPv6 issue

### ISSUE THREAD

**Issue by GuoBing1989100** [bia-pain-bache/BPB-Worker-Panel#349]
### Feature description | توضیحات ویژگی

Hi, can you tell me why my login IP always shows up as Cloudflare's US or Hong Kong IP? Is there any way to change or delete the IP? Also, my proxy IP only shows up as IPv4, but logging in switches to IPv6. Can you help me figure out how to solve this problem? Thanks!

**Comment by bia-pain-bache** [comment]
Hi, 
I don't get it actually! What do you mean by login?
