### ISSUE TITLE
افزایش سرعت

### ISSUE THREAD

**Issue by ghajar77** [bia-pain-bache/BPB-Worker-Panel#35]
برای افزایش سرعت آیا اضافه کردن آی پی تمیز موثره ؟
کدام تنظیم باعث پایین آمدن پینگ میشود ؟

**Comment by bia-pain-bache** [comment]
در صورتی که از فرگمنت استفاده نمیکنید میتونه موثر باشه، کانفیگ‌های پیشفرض حاوی IP های تمیز هم هستن. در صورت استفاده از فرگمنت دیگه خیلی اهمیتی نداره.
