### ISSUE TITLE
About proyx Udp traffic

### ISSUE THREAD

**Issue by Akimio521** [bia-pain-bache/BPB-Worker-Panel#351]
### Feature description | توضیحات ویژگی

Hi:

I found there is some codes about Udp just like `throw new Error("UDP proxy only enable for DNS which is port 53");` which in the in the `woker.js`
I have some question: Cloudflare Workers just like cope the Udp correctly.Why ditch UDP traffic except DNS traffic?Is there are some policy of Cloudflare or some other reason?

Thanks for answering me

**Comment by bia-pain-bache** [comment]
Hi,

Handling (Proxying) UDP in worker runtime is not possible right now. It's about ws stream, udp and runtime characteristics.

**Comment by Akimio521** [comment]
I am dispointed to hear that.I wanted it enable udp originally in order to use http3 which base on quic

**Comment by bia-pain-bache** [comment]
better not to enable quic, it's not that much stable...
