### ISSUE TITLE
cannot login to panel after updating to version 2.6.3

### ISSUE THREAD

**Issue by mmrabbani** [bia-pain-bache/BPB-Worker-Panel#352]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

After I enter the right password, I get the error below

BPB Panel 2.6.3 💦
Something went wrong!

⚠️ TypeError: Cannot read properties of undefined (reading 'replaceAll') at renderHomePage (functionsWorker-0.6869594178415888.js:1448:110) at async Object.fetch (functionsWorker-0.6869594178415888.js:159:30)

proxies are working and I only cannot login to panel.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

syncing fork, logging in
![Screenshot 2024-10-03 at 17-50-29 Error Page](https://github.com/user-attachments/assets/7442a767-fa3b-451f-98b2-9e9ebcc70dac)

### Relevant log output | لاگ برنامه یا پنل

```shell
I cannot access to control panel
```

**Comment by Turbine8845** [comment]
> Which version are you updating from?

I have the exact same problem, and I don't remember which version I updated from to 2.6.3. I believe the last version I used was something like 2.5.x. I haven't updated in a while and missed several releases, which I think is responsible for my problem.

**Comment by kingparsa1010** [comment]
i have an error like this too
![image](https://github.com/user-attachments/assets/2a16aac6-7d61-4dc9-8f3f-d532196a1a54)

**Comment by kingparsa1010** [comment]
i found a soulotion but its not quiet good!
clear kv data or use a new KV

**Comment by alishk7395** [comment]
Having same problem, updating from 2.5 to 2.6.3
BPB Panel 2.6.3 💦
Something went wrong!
⚠️ TypeError: Cannot read properties of undefined (reading 'replaceAll') at renderHomePage (functionsWorker-0.03187786957384575.js:1448:110) at async Object.fetch (functionsWorker-0.03187786957384575.js:159:30)

**Comment by parsaaghayi** [comment]
I have the same eproblem! I updated from 2.5.5

**Comment by hux555** [comment]
v2.6.3 prompts an error when entering the default password admin after deployment ！！

**Comment by bia-pain-bache** [comment]
I had to refactor some codes which made this incompatibility with older versions,  please make a new KV and assign it to project, for pages deployments you have to redeploy after binding.

**Comment by mmrabbani** [comment]
Thank you for help. It is fixed completely.

**Comment by kingparsa1010** [comment]
> Bug fixed in 2.6.4 release, you can update now.

did my reply help?

**Comment by AJFARZIN** [comment]
BPB Panel 3.1.1 💦
❌ Something went wrong!
⚠️ Please set UUID and Trojan password first. Please visit [here](https://bpb-panel-new-48n.pages.dev/secrets) to generate them.

**Comment by AJFARZIN** [comment]
BPB Panel 3.1.1 💦
❌ Something went wrong!
⚠️ Please set UUID and Trojan password first. Please visit [here](https://bpb-panel-new-48n.pages.dev/secrets) to generate them.

**Comment by AJFARZIN** [comment]
BPB Panel 3.1.1 💦
❌ Something went wrong!
⚠️ Please set UUID and Trojan password first. Please visit [here] to generate them.
