### ISSUE TITLE
اضافه کردن کانفیگ warp pro برای نسخه اصلی xray

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#353]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

به نظر میرسه قابلیت udp noise به آخرین نسخه هسته xray اضافه شده به نظرم میتونید کانفیگای warp pro رو برای هسته اصلی xray هم اضافه کنید

https://github.com/XTLS/Xray-core/pull/3711

https://xtls-github-io.translate.goog/config/outbounds/freedom.html/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

these are the documents 

### Relevant log output | لاگ برنامه یا پنل

```shell
nothing
```

**Comment by bia-pain-bache** [comment]
من تست کردم نشد، برای مثال اگر تنظیماتی پیدا کردید که وارپ روی همراه اول وصل بشه اعلام کنید.

**Comment by developer861** [comment]
با آخرین نسخه تست کردین؟
اندپونتی که استفاده کردین سالم بود؟
کانفیگی که ساختین فرمتش درست بود؟

**Comment by developer861** [comment]
https://xtls.github.io/config/outbounds/freedom.html#outboundconfigurationobject

این داکیومنتش بود لینک دوم کار نمیکرد(فقط به زبان چینی نوشته)

**Comment by bia-pain-bache** [comment]
بله درست بود.

**Comment by developer861** [comment]
:( خب پس ایده ای ندارم مشکل از چی میتونه باشه البته نوشته بودن نسخه preview هست شاید تو نسخه های بعدی درست بشه
