### ISSUE TITLE
Error for entering panel

### ISSUE THREAD

**Issue by Verystrangeone** [bia-pain-bache/BPB-Worker-Panel#357]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام من بعد از اینکه پسورد رو میزنم و لاگین میکنم یه صفحه میاد که نمیتونم برم داخل پنل

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

تو پنل لاگین کنید

### Relevant log output | لاگ برنامه یا پنل

```shell
BPB Panel 2.6.3 💦
Something went wrong!
⚠️ TypeError: Cannot read properties of undefined (reading 'replaceAll') at renderHomePage (functionsWorker-0.481523484723547.js:1448:110) at async Object.fetch (functionsWorker-0.481523484723547.js:159:30)
```

**Comment by bia-pain-bache** [comment]
Bug fixed in 2.6.4 release, you can update now.
