### ISSUE TITLE
عدم وجود پروتوکل ترجان در پنل

### ISSUE THREAD

**Issue by shahdad1998** [bia-pain-bache/BPB-Worker-Panel#358]
### Feature description | توضیحات ویژگی

سلام وقت بخیر 
آقا من وقتی میخوام مشخص کنم چه کانفیگ هایی برام بسازه، ترجان رو نداره و فقط وبسوکت ویلس میسازه خودش
دیدم که میشه ساخت و بقیه هم ساختن و خوبیش اینه که حتی بدونه خاموش کردن ماکس هم کار می‌کنه این مدل
باید چجوری بسازمش؟! 
![IMG_20241004_155852](https://github.com/user-attachments/assets/db358216-8749-4782-8210-b46276ca3ed4)

**Comment by misagh72** [comment]
پنلتون رو اپدیت کنید

**Comment by shahdad1998** [comment]
> پنلتون رو اپدیت کنید

سلام
میشه بگی چطوری؟ الان نسخه 2.6.4 هست
فورک رو هم سینک کردم مجدد ولی نسخه تغییری نکرد

**Comment by shahdad1998** [comment]
> پنلتون رو اپدیت کنید

سلام
مرسی آپدیت کرده بودم ولی پنل قبلی میومد بازم . امروز تست کردم اوکی شده بود!!
ولی مشکل دیگه اینکه کانفیگ های ترجااان هیچکدوم پینگ نمیدن بهم!!! نمیدونم ایراد از کجاست
با پروژه epeius که ساختم پینگ میده. ولی میخوام رو همین پنل bpb‌ باشم و ویلس با این نزنم تروجان با اون یکی
نظری داری که مشکل از کجا میتونه باشه؟!

**Comment by bia-pain-bache** [comment]
سلام،
سوالات متداول رو بخونید نوشتم برای تروجان چیکار کنید.
