### ISSUE TITLE
عدم اتصال کافینگ های best ping در برنامه sing box

### ISSUE THREAD

**Issue by Saeed9899** [bia-pain-bache/BPB-Worker-Panel#360]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام مرسی بابت پنل خوبی که ساختین و زحماتتون، من آخرین نسخه  پنل رو آپدیت کردم پس از اون لینک best ping گرفتم برای برنامه sing_box که آخرین نسخه 1.9.6 هست اونم، پینگ نمیده و وصل هم نمیشه لینک های قدیمی best ping رو دارم برای آپدیت قبلی وصل میشن اما لینک های جدید نه پینگ میدن نه وصل میشن.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

۱_ آپدیت پنل به آخرین نسخه انتشار داده شده ۲_ دریافت لینک کانفیگ best ping برای برنامه sing box  و ۳_ وارد کردن لینک در برنامه ۴_ تست پینگ و عدم اتصال
![Screenshot_20241005-004214_sing-box](https://github.com/user-attachments/assets/8a394bb0-c7e8-4b8c-bd50-508055503cd9)
![Screenshot_20241005-004218_sing-box](https://github.com/user-attachments/assets/7ffeb2a1-d5bf-4888-b691-7b8f44406f11)

### Relevant log output | لاگ برنامه یا پنل

```shell
لاگ برنامه رو نشد کپی کنم عکسشو بالا گذاشتم
```

**Comment by Siavash1291** [comment]
منم از ۲.۶ این مشکل رو دارم

**Comment by bia-pain-bache** [comment]
سلام، خواهش میکنم.

در پنل remote DNS و local DNS رو چی گذاشتید؟ آیا chain Proxy هم دارید؟

**Comment by Saeed9899** [comment]
> سلام، خواهش میکنم.
> 
> در پنل remote DNS و local DNS رو چی گذاشتید؟ آیا chain Proxy هم دارید؟

درود مجدد، برای دی ان اس گوگل گذاشتم 8.8.8.8 جفتش اولی ریموت دی ان اس هم 8.8.8.8/dns query، برای chain proxy طبق آموزش های قبلی یدونه vless گذاشتم که گفته بودید کار هم نکنه مهم نیست اما طبق آموزش های جدید از ساکس استفاده نکردم هنوز، البته با همین تنضیمات قبلا کار می‌کرد بعد آپدیت پنل اینجوری هست اگر تغییرات جدید chain proxy بخواد تغییر ندارم هنوز و تست نگرفتم؟!

**Comment by bia-pain-bache** [comment]
تو آموزش نوشته بودم روی sing-box کانفیگ vless tls ws برای chain proxy باگ داره استفاده نکنید. میتونید vless tcp یا reality استفاده کنید.

**Comment by Saeed9899** [comment]
> تو آموزش نوشته بودم روی sing-box کانفیگ vless tls ws برای chain proxy باگ داره استفاده نکنید. میتونید vless tcp یا reality استفاده کنید.

بله کاملا درسته چون قبلا متصل شده بود توجه نکرده بودم به این موضوع، بعد کلی گشتن تونستم یک socks پیدا کنم پینگ بگیرم ولی پینگ خیلی بالاست، به جز منابعی که برای chain proxy توو آموزش گذاشتین منبع دیگه ایی پیشنهاد میدید بهتر باشه و راحت کانفینگ برداشت؟ از تلگرام گشتم اکثرا tls ws بودن و اصلا پینگ نمیدن.

**Comment by Saeed9899** [comment]
> تو آموزش نوشته بودم روی sing-box کانفیگ vless tls ws برای chain proxy باگ داره استفاده نکنید. میتونید vless tcp یا reality استفاده کنید.

بسیار عالی متصل شدم عذرمیخوام issue باز کردم چون قبلا وصل میشد تصور کردم از پنل هست بی نهایت سپاس از زحماتتون.

**Comment by bia-pain-bache** [comment]
خواهش میکنم، قبلا chain proxy فقط روی ساب فرگمنت اعمال میشد، بخاطر همین sing-box بدون chain وصل میشده.
