### ISSUE TITLE
The build-in IP scanner website work worngly in PC, but in Android brower funtional well

### ISSUE THREAD

**Issue by Holocure** [bia-pain-bache/BPB-Worker-Panel#364]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

The "IP scanner"website is useless when I open it in PC. It always show some 1ms IPs, but acturally it can be more than 800ms.
My Android device turn out to be OK. May be my Chrome on PC should be update. My Chrome is 118.0.0
![image](https://github.com/user-attachments/assets/2a200707-a39b-4f6e-9a75-73d35fbfc113)
If the bug is turly the result of my outdated brower, please tell me. Thanks so much!

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Open panel
2. click "Scan now"
3. then the wobsite will scan very quickly and show one 1ms IP(useless)

### Relevant log output | لاگ برنامه یا پنل

```shell
No, sorry
```

**Comment by Holocure** [comment]
I am sure I turn off my proxy, and try many times.

**Comment by bia-pain-bache** [comment]
Please submit issue on related repository:
https://github.com/ircfspace/scanner
