### ISSUE TITLE
مشکل با ADSL مخابرات

### ISSUE THREAD

**Issue by REZAFatf** [bia-pain-bache/BPB-Worker-Panel#366]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام
من پنل رو با pages راه انداختم و با همراه اول و بقیه اپراتورها با سرعت کار میکنه ولی با adsl مخابرات یا کار نمیکنه اصلا یا بسیار کنده. چه تنظیماتی بزنم برای مخابرات؟

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

باب

### Relevant log output | لاگ برنامه یا پنل

```shell
مخابرات
```

**Comment by bia-pain-bache** [comment]
سلام،
من ندارم که تست کنم، باید از بچه‌هایی بپرسید که مخابرات دارن. بدون فرگمنت و یا کانفیگ best fragment هم امتحان کنید.

**Comment by malmal73** [comment]
اومدم تکمیلش کنم امروز با v2rayn تست کردم و دیدم درسته کار نمیکنه.تنها کانفیگای non-tls کار میکنه که باید با ورکر ساخته باشید نه pages .اگر شما هم با نت مخابرات مشکل دارید هیدیفای و سینگ باکس اوکی عمل میکنن.
