### ISSUE TITLE
مشکل chainproxy

### ISSUE THREAD

**Issue by REZAFatf** [bia-pain-bache/BPB-Worker-Panel#368]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام من از سایت racevpn vless grpc گرفتم و وقتی وارد قسمت chainproxy میکنمش میگه: ⛔ VLESS TLS port can be only 443 to be used as a proxy chain! 🫤 .   پورت 443 هم انتخاب هست.

### Relevant log output | لاگ برنامه یا پنل

```shell
ی
```

**Comment by bia-pain-bache** [comment]
سلام، منظورش اینه که Chain Proxy باید پورتش 443 باشه.

**Comment by REZAFatf** [comment]
من این کانفیگ رو میزنم ولی خطا میده:

vless://d8a889c2-53b4-4140-ae0f-183b56b867ca@sg342-full.privateip.net:2003?type=grpc&encryption=none&security=tls&path=%2f&serviceName=GRPC&mode=gun#vless-gRPC

**Comment by bia-pain-bache** [comment]
پورت این کانفیگ ۲۰۰۳ هست، پورت ۴۴۳ نمیده اون سایت؟

**Comment by REZAFatf** [comment]
از سایت racevpn قسمت vless Grpc گرفتم

**Comment by bia-pain-bache** [comment]
از همون سایت کانفیگ VLESS WS بگیر که پورتش 443 باشه.

**Comment by REZAFatf** [comment]
من چطوری میتونم برای وارپ پلاس، endpoint پیدا کنم؟

**Comment by bia-pain-bache** [comment]
فرقی نداره پلاس یا غیر پلاس، endpoint مثل همه.
