### ISSUE TITLE
readme中是支持sing-box还是不支持？

### ISSUE THREAD

**Issue by zwl1619** [bia-pain-bache/BPB-Worker-Panel#37]
readme中是支持sing-box还是不支持？

![Snipaste_2024-04-26_18-44-44](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/13177997/f3af8859-c60c-4cfd-92b6-bac4687a1c72)
不支持还写个版本，我感觉有点奇怪。

**Comment by bia-pain-bache** [comment]
It doese support sing-box subscription but without fragmentation.
