### ISSUE TITLE
Error with the normal subscrition for release 2.6.5 from 2.6.1

### ISSUE THREAD

**Issue by EzSync** [bia-pain-bache/BPB-Worker-Panel#376]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

I can not get results with updated version 2.6.5. When I open the normal subscription for nekobox/nekoray/karing, error is reported:

Something went wrong!
⚠️ Error: An error occurred while resolving DNS - SyntaxError: Unexpected token 'e', "error code: 1003" is not valid JSON at resolveDNS (functionsWorker-0.3004900807391182.js:989:11) at async getConfigAddresses (functionsWorker-0.3004900807391182.js:993:20) at async getNormalConfigs (functionsWorker-0.3004900807391182.js:4285:21) at async Object.fetch (functionsWorker-0.3004900807391182.js:88:35)

When return to 2.6.1, everything is ok. 

### Relevant log output | لاگ برنامه یا پنل

```shell
Something went wrong!
⚠️ Error: An error occurred while resolving DNS - SyntaxError: Unexpected token 'e', "error code: 1003" is not valid JSON at resolveDNS (functionsWorker-0.3004900807391182.js:989:11) at async getConfigAddresses (functionsWorker-0.3004900807391182.js:993:20) at async getNormalConfigs (functionsWorker-0.3004900807391182.js:4285:21) at async Object.fetch (functionsWorker-0.3004900807391182.js:88:35)
```

**Comment by bia-pain-bache** [comment]
2.6.5 has some bugs, it will be fixed for 2.6.6 or higher, please don't deploy it.
