### ISSUE TITLE
تغییر uuid از داخل پنل

### ISSUE THREAD

**Issue by hameed-maleki** [bia-pain-bache/BPB-Worker-Panel#379]
### Feature description | توضیحات ویژگی

سلام ممکنه تو اپدیت بعدی این قابلیت رو اضافه کنید که از داخل پنل بشه uuid رو تغییر داد؟

**Comment by bia-pain-bache** [comment]
سلام، اگر شدنی بود حتما تا الان کرده بودم.

**Comment by hameed-maleki** [comment]
> سلام، اگر شدنی بود حتما تا الان کرده بودم.

ایا نمیشه uuid رو در kv ذخیره کرد ؟ و با دستوری اون رو از داخل پنل ویرایشش کرد مثل پسورد؟

**Comment by mohammadsamimi4** [comment]
سلام توی نسخه جدید ورکر چطوری uuid رو تغییر بدم

**Comment by bia-pain-bache** [comment]
مثل pages باید از settings برید variable اضافه کنید.

**Comment by bia-pain-bache** [comment]
`ایا نمیشه uuid رو در kv ذخیره کرد ؟ و با دستوری اون رو از داخل پنل ویرایشش کرد مثل پسورد؟`

نمیشه، kv محدودیت درخواست روزانه داره.
