### ISSUE TITLE
تیک تاک و ویس چت تلگرام وصل نمیشه

### ISSUE THREAD

**Issue by mortezaafshar92** [bia-pain-bache/BPB-Worker-Panel#38]
مشکل اصلی این پنل اینه که تیک تاک و ویس چت تلگرام وصل نمیشه

**Comment by bia-pain-bache** [comment]
در مورد TikTok مشکلی گزارش نشده ولی تماس صوتی تلگرام بخاطر UDP هست که ورکر هندل نمیکنه فعلا.

**Comment by Aliamiryazdani** [comment]
تماس تلگرام هنوز اوکی نیست درسته؟
