### ISSUE TITLE
clean ip

### ISSUE THREAD

**Issue by malmal73** [bia-pain-bache/BPB-Worker-Panel#382]
### Feature description | توضیحات ویژگی

سلام اول خواستم ازتون تشکر کنم بابت این پنل خوب و کاربردی.دستت درد نکنه.راستش من توی قسمت clean ip نزدیک ۳۰ تا  ip اضافکردم و خب وقتی یکی یا دوتاش از کار میوفته پیدا کردنشون و پاک کردنشون سخته.خواستم پیشنهاد بدم ک اگر میتونید براش یه طراحی ساده و روان تر بذارید.مثلا میتونید دوتا گزینه ی اضاف و لیست بذارید جاش ک با اضاف کردن بشه بهش آی پی داد و وقتی لیستو میزنیم لیست آی پی ها ظاهر بشه ک جلوی هر آی پی قابلیت حذف کردنم هست.بازم بابت این پنل کاربردی و خوبتون ازتون تشکر میکنم.

**Comment by bia-pain-bache** [comment]
سلام،
خواهش میکنم، من روی کانفیگا بخاطر همین شماره گذاشتم که مشخص بشه کدوم IP.
