### ISSUE TITLE
How about cut  HASH_PASS  TROJAN_PASS UUID into PASS & CF_TOKEN ?

### ISSUE THREAD

**Issue by Pigeonszz** [bia-pain-bache/BPB-Worker-Panel#383]
### Feature description | توضیحات ویژگی

Use PASS to generate UUID and TROJAN_PASS based on a specific algorithm, 
and with CF_TOKEN permission, 
for example: editing permissions for Cloudflare Pages and Workers scripts. 
Modify environment variables through the Fetch API at api.cloudflare.com and redeploy. (maybe delete the old deploy?)
Subscriptions use the unique key generated by PASS according to a specific algorithm.

here are the api doc
https://developers.cloudflare.com/api/operations/worker-deployments-create-deployment
https://developers.cloudflare.com/api/operations/worker-script-patch-settings
https://developers.cloudflare.com/api/operations/pages-deployment-create-deployment
https://developers.cloudflare.com/api/operations/pages-project-update-project

Just some ideas

**Comment by bia-pain-bache** [comment]
Many thanks for your recommendation, already working on this, the problem is we can update Pages evn vars via API but not Workers.

**Comment by bia-pain-bache** [comment]
Also hash is cut already in incomming release. The worker generates it itself.

**Comment by Pigeonszz** [comment]
Maybe we can just upload a new Workers by self copy ?

**Comment by bia-pain-bache** [comment]
Yes we can but it's a weired way to update just a UUID or IP... I will work on possible solutions.
