### ISSUE TITLE
Concurrent use: BPB Panel <--> TCP || Cloudflare WARP <--> UDP

### ISSUE THREAD

**Issue by X-49** [bia-pain-bache/BPB-Worker-Panel#384]
### Feature description | توضیحات ویژگی

Hello again, BPB Panel is very pleasant to use, thank you very much for that, but as I understand, the Cloudflare Workers platform does not fully support UDP connection and the VLESS protocol itself, too, including?

Yesterday in Russia began to block the resource discord.com, which uses UDP-connection for voice chat and when using BPB Panel resource does not work, and the site discord.com itself in principle does not load, although vanilla script “yonggekkkk/Cloudflare_vless_trojan” could load it.

In general, I came to such a decision that now, in addition to BPB Panel, I started using Cloudflare WARP client via **MASQUE protocol**. The problem is that they conflict with each other. I expected that BPB Panel will simply intercept all TCP to itself, and Cloudflare WARP in turn all UDP to itself, respectively, I could continue to use discord.com voice chat and use BPB Panel as a more complete VPN solution.

Is there any way to make them work together? Any solution for Windows, macOS, or Linux will do.

P.S. If anything, I made a direct connection to discord.com in BPB Panel script using `'DOMAIN-KEYWORD,discord,DIRECT'` in `function buildClashRoutingRules`. It works as it should, tested in FlClash client on Windows and Android.

**Comment by bia-pain-bache** [comment]
Hi,
It's so easy to direct UDP traffic, but it exposes real IP and leads to DNS, WebRTC leaks and compromises users safety. The solution is using panel Warp and WoW configs.
maybe `yonggekkkk/Cloudflare_vless_trojan` can partly establish UDP connections, but I decided to block it at all due to its malfunctioning.

**Comment by bia-pain-bache** [comment]
Also you can use Workerless config if you do not have security concerns, it almost opens all blockes websites and UDP is working but exposes your local IP.

**Comment by developer861** [comment]
> Hi, It's so easy to direct UDP traffic, but it exposes real IP and leads to DNS, WebRTC leaks and compromises users safety. The solution is using panel Warp and WoW configs. maybe `yonggekkkk/Cloudflare_vless_trojan` can partly establish UDP connections, but I decided to block it at all due to its malfunctioning.

یعنی وورکر میتونه udp رو ساپورت کنه ولی مشکل سرعت داره؟
بهتر نیست که یه گزینه بذارید برای انتخاب بلاک کردن یا نکردن udp؟ (اگه وورکر میتونه با مشکل هندل کنه)

**Comment by developer861** [comment]
> Also you can use Workerless config if you do not have security concerns, it almost opens all blocked websites and some apps and UDP is working but exposes your local IP.

چه مشکل امنیتی ای دارن؟

**Comment by developer861** [comment]
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
`یعنی وورکر میتونه udp رو ساپورت کنه ولی مشکل سرعت داره؟
بهتر نیست که یه گزینه بذارید برای انتخاب بلاک کردن یا نکردن udp؟ (اگه وورکر میتونه با مشکل هندل کنه)`

نه نمیتونه. فقط درخواست میره سمت ورکر و fail میشه.

`چه مشکل امنیتی ای دارن؟`

نوشتم دیگه! IP خودتو نشون میده.

**Comment by developer861** [comment]
> نه نمیتونه. فقط درخواست میره سمت ورکر و fail میشه.

خب پس چطوری با وورکر yonggekkkk/Cloudflare_vless_trojan دیسکوردو باز کرده؟ 

> نوشتم دیگه! IP خودتو نشون میده.

آها اون که اوکیه

**Comment by bia-pain-bache** [comment]
با کانفیگ نرمال تست کن، کد یکیه با yonggekkkk. روی فرگمنت کلا UDP رو بستم.

**Comment by developer861** [comment]
> با کانفیگ نرمال تست کن، کد یکیه با yonggekkkk. روی فرگمنت کلا UDP رو بستم.

عجیبه با v2rayn تست کردم و و ساب فرگمنت دیسکوردو باز کرد ولی ساب نرمال اصلا کار نکرد
کلا ساب نرمال با v2rayn کار نمیکنه ولی پینگ میده :/
 
 ولی با nikang کار میکنه :|

**Comment by bia-pain-bache** [comment]
I enabled UDP on 2.6.9 again, be aware that maybe sometimes it works for some connections, but not always.
