### ISSUE TITLE
trojan configs

### ISSUE THREAD

**Issue by nickjp44** [bia-pain-bache/BPB-Worker-Panel#385]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

in this version (2.6.7) Trojan configs does not work and give -1 when testing :
i update the worker to this current version and create the TROJAN_PASS var in the setting , it working when i check the password in the Trojan config , so the var sett is correctly , i just checked that the trojan configs only works with this special password :bpb-trojan,
please take a  look

### Relevant log output | لاگ برنامه یا پنل

```shell
The ping of current service: -1 ms
```

**Comment by bia-pain-bache** [comment]
You are totally right, that's a bug. Thanks for reporting.
