### ISSUE TITLE
مشکل کانفیگ wow pro best ping در v2rayn pro 

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#386]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

همه کانفیگای وارپ درست و بدون مشکل کار میکنن بجز کانفیگ wow pro best ping

### Relevant log output | لاگ برنامه یا پنل

```shell
A unified platform for anti-censorship.
2024/10/11 02:25:51 Using default config:  C:\Users\userx\Downloads\v2rayN\v2rayN\guiConfigs\config.json
2024/10/11 02:25:51 [Info] infra/conf/serial: Reading config: &{Name:C:\Users\userx\Downloads\v2rayN\v2rayN\guiConfigs\config.json Format:json}
2024/10/11 02:25:51 [Warning] core: Xray 1.8.23 started
2024/10/11 02:25:51 from DNS accepted udp:1.1.1.1:53 [dns >> chain-1]
2024/10/11 02:25:51 from 127.0.0.1:10860 accepted //alive.github.com:443 [http-in >> chain-1]
2024/10/11 02:25:52 from 127.0.0.1:10865 accepted //www.google.com:443 [http-in >> chain-1]
2024/10/11 02:25:55 from DNS accepted udp:94.140.14.14:53 [dns -> direct]
2024/10/11 02:26:00 The ping of current service: -1 ms
2024/10/11 02:26:00 System proxy setting is changed - ForcedChange
```

**Comment by developer861** [comment]
2024/10/11 02:28:51 from 127.0.0.1:9705 accepted //music.youtube.com:443 [http-in -> chain-51]
2024/10/11 02:28:52 [Error] app/dns: UDP:94.140.14.14:53 cannot find the pending request
2024/10/11 02:28:52 [Error] app/dns: UDP:94.140.14.14:53 cannot find the pending request
2024/10/11 02:28:52 [Error] app/dns: UDP:94.140.14.14:53 cannot find the pending request
2024/10/11 02:28:52 [Error] app/dns: UDP:94.140.14.14:53 cannot find the pending request
2024/10/11 02:28:55 [Error] app/dns: UDP:94.140.14.14:53 cannot find the pending request

این هم بخشی از لاگ بود به نظر میرسه مشکل دی ان اس داره

**Comment by bia-pain-bache** [comment]
ورژن پنل چیه؟ و اینکه چرا از ادگارد برای local dns استفاده کردید؟

**Comment by developer861** [comment]
2.6.4


>و اینکه چرا از ادگارد برای local dns استفاده کردید؟

صرفا برای اینکه شبیه هم باشن remote و local ولی فکر نکنم مشکل از اون باشه چون بقیه کانفیگا مشکلی ندارن

**Comment by developer861** [comment]
2024/10/11 08:30:59 [Info] infra/conf/serial: Reading config: &{Name:C:\Users\userx\Downloads\v2rayN\v2rayN\guiConfigs\config.json Format:json}
2024/10/11 08:30:59 [Warning] core: Xray 1.8.23 started
2024/10/11 08:30:59 from DNS accepted udp:1.1.1.1:53 [dns >> chain-1]
2024/10/11 08:31:00 from 127.0.0.1:12459 accepted //www.google.com:443 [http-in >> chain-1]
2024/10/11 08:31:04 from 127.0.0.1:12460 accepted //x.com:443 [http-in -> chain-29]
2024/10/11 08:31:07 from 127.0.0.1:12462 accepted //x.com:443 [http-in -> chain-29]
2024/10/11 08:31:08 from DNS accepted udp:8.8.8.8:53 [dns -> direct]
2024/10/11 08:31:08 [Error] app/dns: UDP:8.8.8.8:53 cannot find the pending request
2024/10/11 08:31:10 The ping of current service: -1 ms
2024/10/11 08:31:10 System proxy setting is changed - ForcedChange

**Comment by developer861** [comment]
به 8.8.8.8 تغییرش دادم ولی بازم تغییری نکرد
عجیب اینه که فقط همون wow pro best ping این مشکلو داره

**Comment by developer861** [comment]
لوکال رو روی همون 8.8.8.8 بذارم؟
تفاوت خاصی داره؟

**Comment by bia-pain-bache** [comment]
لوکال میتونی چیز دیگه هم بذاری، ولی باید عمومی باشه، مثلا تبلیغات و...رو بلاک نکنه مثل ادگارد.
توی پنل count رو افزایش بده به ۳۰-۴۰ مثلا، بعضی وقتا wow طول میکشه تا وصل بشه.

**Comment by developer861** [comment]
> توی پنل count رو افزایش بده به ۳۰-۴۰ مثلا، بعضی وقتا wow طول میکشه تا وصل بشه.
 خب مشکل اینه که من 20 تا اندئوینت گذاشتم هر 20 تاش کانفیگ wow مربوط به اون اندپوینت کار میکنه ولی وقتی میذازم رو wow best ping 
 دیگه کار نمیکنه (warp best ping هم کار میکنه فقط همون wow مشکل داره)

**Comment by bia-pain-bache** [comment]
هرجور صلاح میدونید.

**Comment by developer861** [comment]
گذاشتم رو 30-40 ولی هنوزم همون مشکلو داشت :(

**Comment by bia-pain-bache** [comment]
روی nikang کار میکنه؟

**Comment by developer861** [comment]
نه دقیقا همین مشکلو بازم داره(فقط wow best مشکل داره)
:(

**Comment by developer861** [comment]
جایی هست بتونم سابمو براتون بفرستم؟

**Comment by developer861** [comment]
آقا مشکل با کم کردن تعداد اندپوینت ها حل شد(خیلی زیاد بودن) دمتون گرم
