### ISSUE TITLE
fragment routing?

### ISSUE THREAD

**Issue by HASHHman** [bia-pain-bache/BPB-Worker-Panel#39]
does v2rayn routing rule not work while using fragment? or am I setting rules incorrectly?

**Comment by bia-pain-bache** [comment]
As explained in docs, if routing is enabled you have to update Geo assets.

**Comment by HASHHman** [comment]
the routing settings in panel works fine. but when I add routing rules in v2rayn's routing setting they don't work.
for example I have discord.com in my direct rules but discord still goes through proxy(in browser).
my question is if v2rayn routing rules don't work with fragment configs or I'm setting the rules incorrectly.

sorry for not being clear

**Comment by bia-pain-bache** [comment]
No problem, Custom configs force their own routing and ignore app settings, you have to use normal configs and enable fragment manually for that purpose.

**Comment by HASHHman** [comment]
thanks
is there a way for me to change routing to some sites using your pages config?
