### ISSUE TITLE
FR

### ISSUE THREAD

**Issue by mohammad35322** [bia-pain-bache/BPB-Worker-Panel#390]
### Feature description | توضیحات ویژگی

سلام و عرض ادب خدمت دولوپر عزیز پنل کاربردی BPB
درخواست اضافه شدن قابلیتی داشتم برای اون هایی که میخوان روی یک پنل از چند لوکیشن مختلف استفاده بکنن
برای همین منظور اضافه شدن قابلیت ست کردن چندین proxy ip روی یک پنل رو دارم
و برای هر proxy ip روی لینک های اشتراک کانفیگ های جداگونه تولید بشه
مثلا proxy ip 1 کانفیگ های مخصوص خودش و proxy ip 2 و کانفیگ های خودش به صورت جداگونه متمایز بشن روی لینک اشتراک با نام گذاری های جداگونه.(اگر بشه برای هرکدوم از proxy ip ها نام شخصی سازی شده ای هم اضافه بشه و از همون نام توی کانفیگ ها استفاده بشه هم عالی میشه) 
من که لوکیشن امریکا و المان نیاز دارم مجبور شدم روی یک اکانت کلودفلیر دوتا پنل جداگونه بسازم و هرکدوم رو جدا تنظیم کنم و استفاده کنم
اگر میشد روی یک پنل و روی یک لینک اشتراک این امکان فراهم بشه بنظرم خیلی بهتره
و اگر دوستان راهکار بهتری سراغ دارن خوشحال میشم ارئه بدن
متشکرم

**Comment by bia-pain-bache** [comment]
سلام، زنده باشید.
اضافه نمیکنم چون کاربرهای عادی گیج میشن، همین الان هم پنل زیادی شلوغ شده.
ارادت
