### ISSUE TITLE
تماس صوتی

### ISSUE THREAD

**Issue by hameed-maleki** [bia-pain-bache/BPB-Worker-Panel#393]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام روی پلتفرم ایفون و ویندوز با استفاده از کانفیگ های vless تماس صوتی تلگرام روی یه سری از اپراتور ها (همراه اول-adslمخابرات) به خوبی برقرار میشه
ولی روی اندروید با استفاده از همون کانفیگ ها  و همون اینترنت تماس برقرار نمیشه دلیلش چیه؟
برنامه های استفاده شده
ایفون sing box
اندروید sing box
ویندوز nekoray

### Relevant log output | لاگ برنامه یا پنل

```shell
no log
```

**Comment by bia-pain-bache** [comment]
دلیلشو نمیدونم متاسفانه، ولی حدس میزنی تلگرام دسکتاپ از طریق UDP اتصالو برقرار نمیکنه.
