### ISSUE TITLE
BPB Panel 2.6.8 Something went wrong!

### ISSUE THREAD

**Issue by theufohost** [bia-pain-bache/BPB-Worker-Panel#395]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

bug

### Relevant log output | لاگ برنامه یا پنل

```shell
BPB Panel 2.6.8
Something went wrong!
Error: Invalid UUID: f2e6f0c3-973d-9a0b-d71e-72e36c27219e at Object.fetch (functionsWorker-0.8512394616062289.js:4047:15)
```

**Comment by bia-pain-bache** [comment]
لطفا از این سایت uuid بگیرید:
https://www.uuidgenerator.net/

**Comment by liMilCo** [comment]
نمیدونم این UUID رو از کجا گرفتی اما یه قانون ساده داره:
00000000-0000-X000-Y000-000000000000
بجای X حتمی باید 4 باشه
بجای Y فقط میتونه 4 یا 8 یا a یا b باشه ...
الان تو ای-دی تو خانه سوم با 9 شروع شده ...
مثلا یه کد ساده:
00000000-0000-4000-a000-000000000000
