### ISSUE TITLE
ad block

### ISSUE THREAD

**Issue by salehiparviz** [bia-pain-bache/BPB-Worker-Panel#397]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام
AD block کار نمیکنه مخصوصا یوتیوب

### Relevant log output | لاگ برنامه یا پنل

```shell
AD block کار نمیکنه مخصوصا یوتیوب
```

**Comment by developer861** [comment]
اد بلاکرش اینطوریه که دامنه های تبلیغاتیو مسدود میکنه و برای بعضی از سابتا مثل یوتیوب و توییتر جواب نمیده 
برای اونا میتونین از افزونه ادبلاکر مرورگر استفاده کنید
برای مرورگر از افزونه ublock origin و برای یوتیوب موبایل از revanced
مرورگر موبایل هم میتونید brave نصب کنید خود ad blocker داره
https://ublockorigin.com/
https://revanced.app/
