### ISSUE TITLE
کار نکردن نورمال ساب در برنامه هیدیفای

### ISSUE THREAD

**Issue by benirashed** [bia-pain-bache/BPB-Worker-Panel#40]
سلام.

وقتی sub normal رو از پنل bpb   میبرم تو برنامه hiddify next در موبایل ، وصل میشه ظاهرا  اما هیچ سایتی رو باز نمیکنه .    انگار تو hiddify مشکل داره.

**Comment by bia-pain-bache** [comment]
در تنظیمات remote DNS رو به این شکل بذار:
https://8.8.8.8/dns-query
