### ISSUE TITLE
اضافه کردن lan به قوانین routing

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#403]
### Feature description | توضیحات ویژگی

میتونید به قوانین روتینگ بخش allow connections from lan رو هم اضافه کنید که به جای 127.0.0.1 
0.0.0.0 رو listen کنه

**Comment by bia-pain-bache** [comment]
اصلا معنی نداره، که چی بشه؟

**Comment by developer861** [comment]
در کلاینت هایی مثل v2rayn و v2rayng یه گزینه هست به اسم allow connection from lan که به جای اینکه فقط 127.0.0.1 رو listen کنه از کل local network میتونیم بهش پروکسی بزنیم و وصل شیم
 حالا کانفیگای فرگمنت چون فرمتشون custom هست باید تو خود کانفیگا این گزینه رو فعال کنید تا کار کنه(از دستگاهای دیگه روی لوکال نتورک هم بهش وصل بشیم) 

https://xtls.github.io/en/config/inbound.html#inboundobject

اینجا تو داکیومنت xray نوشته بود برای این کار باید آیپی listen 0.0.0.0 باشه 

قابلیت خوبیه گفتم میتونید اضافه کنید 
(تغییر listen ip از 127.0.0.1 به 0.0.0.0)

**Comment by developer861** [comment]
شایدم اشتباه گفتم مطمين نیستم‌:(

**Comment by bia-pain-bache** [comment]
اون یه چیز دیگه‌ست. شما همین الان بدون مشکل میتونید از این قابلیت استفاده کنید.

**Comment by developer861** [comment]
متوجه شدم. دمتون گرم
