### ISSUE TITLE
نبود ساب های فرگمنت در پنل ورکر برای نکوری

### ISSUE THREAD

**Issue by fromseer** [bia-pain-bache/BPB-Worker-Panel#404]
سلام، ببخشید در پنل Worker قسمت مربوط به ساب های فرگمنت برای nekoray همانند پنل پیجز وجود نداره، چکار میشه کرد ؟

**Comment by bia-pain-bache** [comment]
سلام، فرگمنت برای هیدیفای رو اضافه کردم و نکوری رو حذف کردم چون هسته Xray رو در ورژن‌های جدید حذف کرده و درست آپدیت هم نمیداد (تقریبا منسوخ شده).

**Comment by fromseer** [comment]
من nekoray رو بخاطر این استفاده میکنم که چون قابلیت تونل همه اپ رو داره (TUN) ایا هیدیفای همچین چیزی داره ؟

**Comment by bia-pain-bache** [comment]
بله داره.

**Comment by b8y2045man** [comment]
اگر ممکنه nekoray رو اضافه کن به پنل ، نسخه های قبلی nekoray خیلی بهتر از همه برنامه هاست
hiddify یک خط در میون اپشن ها رو اضافه میکنه و حذف میکنه ، بعد از این همه مدت هنوز راجع به حذف یا اضافه کردن mux به اپ ویندزشون تصمیم نگرفتن، یه بار حذفش میکنن یه بار اضافه 
برنامه هایی مثل spotplayer که خیلی ها ازش استفاده میکنن با برنامه v2rayN مشکل داره ولی با nekoray جواب میده
