### ISSUE TITLE
عدم دسترسی به پنل

### ISSUE THREAD

**Issue by webandappgroup** [bia-pain-bache/BPB-Worker-Panel#405]
### Feature description | توضیحات ویژگی

دوستان ظاهرا pages.dv فیلتر شده و متاسفانه دیگه به هیچ عنوان نمیشه از BPB در ایران استفاده کرد. متخصصین به فکر راه چاره باشند!!!
کمک!!!!!!!!

**Comment by misagh72** [comment]
با فرگمنت میتونی استفاده کنی کانفیگ ها رو

**Comment by shidepayande** [comment]
ورکر هنوز کار میده

**Comment by liMilCo** [comment]
یک راه  برای رد کردن فیلتر اتصال ساب دامنه رایگان به page هست، بسیار عالی داره کار میکنه و هیچ محدودیتی (بجز خود کلودفلر) نداره ..
همچنین
هنوز میشه از دامنه (💀 Custom CDN) در جی-کور استفاده کرد
البته فشار ها رو زیاد کردن دیگه کلا نمیشه رو جی-کور دامنه ir ثبت کرد (چه واقعی چه فیک) اما میشه از دامنه های فیک دیگه استفاده کرد مثلا fak.com ...
خوبیش هم به اینه که همزمان میتونید از tls با پرت 443 و غیر سکیور با پرت 80 که سرعت بهتری هم داره استفاده کنید
مثال:
vless://[xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx@gcore.com](mailto:xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx@gcore.com):80?type=ws&host=f.com#C
با سرعت خوب روی ایرانسل، مبین، مخابرات، همراه اول و ...
