### ISSUE TITLE
حل مشکل فیلترینگ page

### ISSUE THREAD

**Issue by liMilCo** [bia-pain-bache/BPB-Worker-Panel#406]
### Feature description | توضیحات ویژگی

# مدیر محترم لطفا آموزش استفاده از این ها را هم بزار تا مشکل همه حل بشه ...
----
یک راه برای رد کردن فیلتر اتصال ساب دامنه رایگان به page هست، بسیار عالی داره کار میکنه و هیچ محدودیتی (بجز خود کلودفلر) نداره ...
***(باید یه ساب دامنه رایگان ثبت کنید و دی-ان-اس رو با CNAME بندازین روی همون XXXX.pages.dev ، بعد در کلودفلر > افزودن دامنه به صفحه pageای که ساختین)
---
همچنین
هنوز میشه از دامنه (💀 Custom CDN) در جی-کور استفاده کرد
البته فشار ها رو زیاد کردن دیگه کلا نمیشه رو جی-کور دامنه ir ثبت کرد (چه واقعی چه فیک) اما میشه از دامنه های فیک دیگه استفاده کرد مثلا fak.com ...
خوبیش هم به اینه که همزمان میتونید از tls با پرت 443 و غیر سکیور با پرت 80 که سرعت بهتری هم داره استفاده کنید
بدیش هم به اینه که برای هر اکانتی که میسازید یه محدودیت استفاده رایگان داره البته برای استفاده شخصی زیاده، تموم شد باید یه اکانت دیگه ثبت کنید ...
مثال:
vless://xxxxxxxx-xxxx-4xxx-axxx-xxxxxxxxxxxx@gcore.com:80?type=ws&host=f.com#C
با سرعت خوب روی ایرانسل، مبین، مخابرات، همراه اول و ...
---
***(تو جی کور یه دامنه فیک بسازید، 
گزینه Origin pull protocol رو به HTTPS تغییر بدین
روی Edit this group کلیک کنید و در Origin source بجای ای-پی همون XXXX.pages.dev رو بزارید، ذخیره کنید.
 بخش Host header باید فعال کنید و باز  XXXX.pages.dev رو قرار بدین ، هیچ کاری هم در کلودفلر قرار نیست بکنید) ****
 توجه کنید که با این دامنه فیک پنل یا لینک سابسکرایب رو نمیتونید بالا بیارید فقط در کانفیگ vless استفاده میشه ...
---
 برای کانفیگ هم:
 آدرس رو cdn.gcore.com یا هر ای-پی تمیزی روی جیکور بزارید
دامنه (Comouflage domain یا host) رو همون دامنه فیکی که در جیکور ساختین
بخش SNI هم cdn.gcore.com یا یه دامنه پشت کلود فلر (مثل: api.gcore.com ، gns2.gcdn.co ، speedtest.gcore.com)
----
اگر نمیخواهید از tls استفاده کنید ؛ tls را خاموش کنید (SNI هم نمیخواد) و پرت رو 80 بزارید

**Comment by bia-pain-bache** [comment]
آموزش ساخت gcore و fastly به عهده‌ی من نیست، نحوه‌ی استفاده ازشون رو تو آموزش‌ها نوشتم. ممنون از راهنماییت.

**Comment by alirezamoti** [comment]
نمیدونم دامنه های رایگان که می سازم داخل کلودفلر تایید نمی شن.روش ساخت دامنه رایگان و فیک بهم میدی؟
و اینک چجور داخل جیکور تایید هویت کنم؟
