### ISSUE TITLE
مشکل سایت‌های پشت کلاد فلر

### ISSUE THREAD

**Issue by argsun** [bia-pain-bache/BPB-Worker-Panel#41]
واقعا کارت عالیه فقط اینکه این ورژن 2.3.3  که توسط پیجز در کلاود فلر ساخته میشه سایت‌های پشت کلاودفلر رو باز نمی‌کنه ولی ورژن 2.1.1 که توسط وکر ساخته شد این مشکل رو رو نداشت. لطفاً این مشکل رو هم حل کن

**Comment by bia-pain-bache** [comment]
سلام ممنون. در تنظیمات remote DNS رو به این شکل بذار:
https://8.8.8.8/dns-query
