### ISSUE TITLE
Pages را خدا آزاد کرد

### ISSUE THREAD

**Issue by mamali112233** [bia-pain-bache/BPB-Worker-Panel#410]
### Feature description | توضیحات ویژگی

سلام pages داره کار میکنه با نت ایرانسل و آسیاتک تا اینجا ک من امتحان کردم درست شده بود چک کنید بگید ک با نت های دیگه هم درست شده یا نه.

**Comment by misagh72** [comment]
داداش برا این چیزا Issues باز نمیکنن

**Comment by mamali112233** [comment]
من صمیمانه از شما عذرخواهی میکنم.دفعه بعدی حتما از شما اجازه میگیرم.
