### ISSUE TITLE
KV Dataset is not properly set!

### ISSUE THREAD

**Issue by ahmadamahmad** [bia-pain-bache/BPB-Worker-Panel#413]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

https://github.com/ahmadamahmad/BPB-Worker-Panel/blob/main/docs/pages_installation_fa.md
از این روش رفتم، دقیق، اما چنین نتیجه ای نصیب من شد
پنل باز نمیشه و میگه دیتاست ایراد داره

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1- https://github.com/ahmadamahmad/BPB-Worker-Panel/blob/main/docs/pages_installation_fa.md.

### Relevant log output | لاگ برنامه یا پنل

```shell
BPB Panel 2.6.8 💦
KV Dataset is not properly set! Please try again or refer to documents
```

**Comment by bia-pain-bache** [comment]
اگر دقیقا طبق آموزش برید امکان نداره، به چیزی رو جا انداختید.
