### ISSUE TITLE
اضافه کردن آپدیت اتوماتیک کانفیگ ها

### ISSUE THREAD

**Issue by Sinaksh0** [bia-pain-bache/BPB-Worker-Panel#415]
### Feature description | توضیحات ویژگی

سلام و عرض ادب.
ممنون میشم قابلیت اتوماتیک آپدیت رو به کانفیگ ها اضافه کنید تا وقتی تغییراتی در پنل ایجاد میشه خودش کانفیگ رو آپدیت کنه مخصوصا در کلاینت هیدیفای.

**Comment by bia-pain-bache** [comment]
سلام،
آپدیت اتوماتیک باید دستی فعال بشه، با ساب نمیشه.

**Comment by Sinaksh0** [comment]
نمیشه به پنل اضافه بشه؟
