### ISSUE TITLE
مشکل اتصال وارپ در ورژن 2.6.9

### ISSUE THREAD

**Issue by emisemok** [bia-pain-bache/BPB-Worker-Panel#416]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

وارپ توی پنل های ورژن پایینتر بدون مشکل کار میکنه 
ولی تو آپدیت ۲.۶.۹ خیر متاسفانه

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

![Screenshot_۲۰۲۴۱۰۱۸-۰۱۱۰۲۰_MahsaNG](https://github.com/user-attachments/assets/e61a1a55-e1ad-4485-be44-a3e409bc34b2)

### Relevant log output | لاگ برنامه یا پنل

```shell
--------- beginning of main
10-18 01:05:42.237 I/GoLog   ( 9647): loading core config
10-18 01:05:42.237 I/GoLog   ( 9647): Preparing Domain: engage.cloudflareclient.com:2408
10-18 01:05:42.333 I/GoLog   ( 9647): Prepare Result:
10-18 01:05:42.333 I/GoLog   ( 9647):  Domain: 
10-18 01:05:42.333 I/GoLog   ( 9647):  Port: 2408
10-18 01:05:42.333 I/GoLog   ( 9647):  IPs: [162.159.192.1]
10-18 01:05:43.924 I/GoLog   ( 9647): new core
10-18 01:05:46.476 I/GoLog   ( 9647): start core
10-18 01:05:46.491 I/GoLog   ( 9647): [Warning] core: Xray 1.8.23 started
10-18 01:05:46.582 D/com.MahsaNet.MahsaNG( 9647): [/data/app/com.MahsaNet.MahsaNG-49DZcsM4fkGENP7_gY_vRg==/lib/arm/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
10-18 01:05:46.595 D/com.MahsaNet.MahsaNG( 9647): libtun2socks.so check
10-18 01:05:46.600 D/com.MahsaNet.MahsaNG( 9647): Process[pid=9687, hasExited=false]
10-18 01:05:46.600 D/com.MahsaNet.MahsaNG( 9647): /data/user/0/com.MahsaNet.MahsaNG/files/sock_path
10-18 01:05:46.608 I/tun2socks( 9687): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-18 01:05:46.669 D/com.MahsaNet.MahsaNG( 9647): sendFd tries: 0
10-18 01:05:46.672 I/tun2socks( 9687): NOTICE(tun2socks): entering event loop
10-18 01:05:47.143 I/GoLog   ( 9647): from udp:127.0.0.1:44515 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 01:05:47.166 I/GoLog   ( 9647): from DNS accepted udp:1.1.1.1:53 [dns -> chain]
10-18 01:05:47.305 I/GoLog   ( 9647): Not Using Prepared: udp,162.159.192.1:2408
10-18 01:05:47.734 I/GoLog   ( 9647): Not Using Prepared: tcp,www.gstatic.com:443
10-18 01:05:51.156 I/GoLog   ( 9647): Not Using Prepared: udp,8.8.8.8:53
10-18 01:05:51.156 I/GoLog   ( 9647): from DNS accepted udp:8.8.8.8:53 [dns -> direct]
10-18 01:05:51.508 I/GoLog   ( 9647): from udp:127.0.0.1:46059 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
```

**Comment by emisemok** [comment]
bpb
معذرت ک شلوغ کردم این ایشو رو🙏
--------- beginning of main
10-18 01:11:55.480 I/GoLog   (12867): loading core config
10-18 01:11:55.481 I/GoLog   (12867): Preparing Domain: 188.114.99.168:1074
10-18 01:11:55.482 I/GoLog   (12867): Prepare Result:
10-18 01:11:55.482 I/GoLog   (12867):  Domain: 188.114.99.168
10-18 01:11:55.482 I/GoLog   (12867):  Port: 1074
10-18 01:11:55.482 I/GoLog   (12867):  IPs: [188.114.99.168]
10-18 01:11:57.269 I/GoLog   (12867): new core
10-18 01:11:59.857 I/GoLog   (12867): start core
10-18 01:11:59.860 I/GoLog   (12867): [Warning] core: Xray 1.8.23 started
10-18 01:11:59.887 I/GoLog   (12867): Not Using Prepared: udp,8.8.8.8:53
10-18 01:11:59.887 I/GoLog   (12867): from DNS accepted udp:8.8.8.8:53 [dns -> direct]
10-18 01:11:59.896 I/GoLog   (12867): Using Prepared: 188.114.99.168
10-18 01:11:59.912 D/com.MahsaNet.MahsaNG(12867): [/data/app/com.MahsaNet.MahsaNG-49DZcsM4fkGENP7_gY_vRg==/lib/arm/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
10-18 01:11:59.916 D/com.MahsaNet.MahsaNG(12867): Process[pid=12905, hasExited=false]
10-18 01:11:59.916 D/com.MahsaNet.MahsaNG(12867): libtun2socks.so check
10-18 01:11:59.916 D/com.MahsaNet.MahsaNG(12867): /data/user/0/com.MahsaNet.MahsaNG/files/sock_path
10-18 01:11:59.929 I/tun2socks(12905): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-18 01:11:59.971 D/com.MahsaNet.MahsaNG(12867): sendFd tries: 0
10-18 01:11:59.973 I/tun2socks(12905): NOTICE(tun2socks): entering event loop
10-18 01:12:00.135 I/GoLog   (12867): from udp:127.0.0.1:46093 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 01:12:00.137 I/GoLog   (12867): from DNS accepted udp:1.1.1.1:53 [dns >> chain-1]
10-18 01:12:00.391 I/GoLog   (12867): from udp:127.0.0.1:43545 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 01:12:00.946 I/GoLog   (12867): Not Using Prepared: tcp,[2a00:1450:4001:82a::2003]:443
10-18 01:12:00.949 I/GoLog   (12867): fdConn unix.Connect err, Close Fd: 82 Err: network is unreachable
10-18 01:12:00.950 I/GoLog   (12867): Not Using Prepared: tcp,[2a00:1450:4001:82a::2003]:443
10-18 01:12:00.950 I/GoLog   (12867): fdConn unix.Connect err, Close Fd: 82 Err: network is unreachable
10-18 01:12:01.053 I/GoLog   (12867): Not Using Prepared: tcp,142.250.181.227:443
10-18 01:12:02.213 I/GoLog   (12867): from udp:127.0.0.1:34767 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 01:12:02.394 I/GoLog   (12867): from udp:127.0.0.1:58657 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 01:12:02.552 I/GoLog   (12867): from tcp:127.0.0.1:39586 accepted tcp:[2a00:1450:400c:c0b::bc]:5228 [socks-in -> chain-1]
10-18 01:12:03.969 I/GoLog   (12867): from tcp:127.0.0.1:39594 accepted tcp:149.154.167.92:443 [socks-in -> chain-1]
10-18 01:12:03.969 I/GoLog   (12867): from tcp:127.0.0.1:39596 accepted tcp:149.154.167.91:5222 [socks-in -> chain-1]
10-18 01:12:03.969 I/GoLog   (12867): from tcp:127.0.0.1:39598 accepted tcp:149.154.167.92:5222 [socks-in -> chain-1]
10-18 01:12:04.556 I/GoLog   (12867): from tcp:127.0.0.1:39602 accepted tcp:[2a03:2880:f176:81:face:b00c:0:4c63]:443 [socks-in -> chain-1]
10-18 01:12:08.771 I/GoLog   (12867): from udp:127.0.0.1:45084 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 01:12:08.775 I/GoLog   (12867): from udp:127.0.0.1:41368 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
این لاگ پنل ورژن پایینتر هستش ک همه جوره متصل میشه
![Uploading Screenshot_۲۰۲۴۱۰۱۸-۰۱۱۲۱۱_MahsaNG.jpg…]()

**Comment by bia-pain-bache** [comment]
آپدیت اخیر تغییری در کانفیگ وارپ ندادم، شما با دو تا Endpoint متفاوت دارید تست میگیرید، شرایط تست باید مشابه باشه.

**Comment by emisemok** [comment]
پنل رو ریست هم کردم ب پیشفرض ولی تاثیری در خروجی نداشت
این لاگ هایی ک براتون فرستادم از دو پنل متفاوت هستن اولی آخرین ورژن و دومی برا ورژن پایینتر ک هیچ مشکلی در هیچکدوم از پروتکل هاش نداره

**Comment by bia-pain-bache** [comment]
اون ورژنی که میگید کار میکنه اندپوینتش 188.114.99.168 هست ولی ورژن 2.6.9 که میگید کار نمیکنه پیشفرض پنل هست.

**Comment by emisemok** [comment]
بله تغییر دادم و ای پی پورت هم بهش دادم ولی کماکان کار نمیده
چون تنظیمات برا همه پنل هایی ک ساختم یکسان بوده و انتظار مشکل وارپ رو تو این پنل آخری نداشتم میتونم لاگ این پنل هم بفرستم ک اونم چک کنید

**Comment by bia-pain-bache** [comment]
لطف میکنید، چون در لاگی که گذاشتید من اروری نمیبینم که بفهمم مشکل چیه.

**Comment by emisemok** [comment]
این لاگ پنل با ای پی پورتی ک جدید گرفتم و وارد کردم

--------- beginning of main
10-18 02:11:54.673 I/GoLog   (20986): loading core config
10-18 02:11:54.674 I/GoLog   (20986): Preparing Domain: 162.159.193.202:894
10-18 02:11:54.686 I/GoLog   (20986): Prepare Result:
10-18 02:11:54.686 I/GoLog   (20986):  Domain: 162.159.193.202
10-18 02:11:54.686 I/GoLog   (20986):  Port: 894
10-18 02:11:54.686 I/GoLog   (20986):  IPs: [162.159.193.202]
10-18 02:11:56.787 I/GoLog   (20986): new core
10-18 02:11:59.331 I/GoLog   (20986): start core
10-18 02:11:59.338 I/GoLog   (20986): [Warning] core: Xray 1.8.23 started
10-18 02:11:59.417 D/com.MahsaNet.MahsaNG(20986): [/data/app/com.MahsaNet.MahsaNG-49DZcsM4fkGENP7_gY_vRg==/lib/arm/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
10-18 02:11:59.421 D/com.MahsaNet.MahsaNG(20986): libtun2socks.so check
10-18 02:11:59.422 D/com.MahsaNet.MahsaNG(20986): Process[pid=21027, hasExited=false]
10-18 02:11:59.423 D/com.MahsaNet.MahsaNG(20986): /data/user/0/com.MahsaNet.MahsaNG/files/sock_path
10-18 02:11:59.437 I/tun2socks(21027): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-18 02:11:59.484 D/com.MahsaNet.MahsaNG(20986): sendFd tries: 0
10-18 02:11:59.486 I/tun2socks(21027): NOTICE(tun2socks): entering event loop
10-18 02:11:59.640 I/GoLog   (20986): from udp:127.0.0.1:54297 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:11:59.646 I/GoLog   (20986): from DNS accepted udp:1.1.1.1:53 [dns -> chain]
10-18 02:11:59.719 I/GoLog   (20986): Using Prepared: 162.159.193.202
10-18 02:12:00.568 I/GoLog   (20986): Not Using Prepared: tcp,www.gstatic.com:443
10-18 02:12:03.645 I/GoLog   (20986): Not Using Prepared: udp,8.8.8.8:53
10-18 02:12:03.645 I/GoLog   (20986): from DNS accepted udp:8.8.8.8:53 [dns -> direct]
10-18 02:12:04.644 I/GoLog   (20986): from udp:127.0.0.1:50735 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:04.644 I/GoLog   (20986): from udp:127.0.0.1:55066 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.391 I/GoLog   (20986): from udp:127.0.0.1:47524 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.392 I/GoLog   (20986): from udp:127.0.0.1:55768 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.392 I/GoLog   (20986): from udp:127.0.0.1:60081 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.402 I/GoLog   (20986): from udp:127.0.0.1:48284 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.407 I/GoLog   (20986): from udp:127.0.0.1:44931 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.421 I/GoLog   (20986): from udp:127.0.0.1:50030 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.430 I/GoLog   (20986): from udp:127.0.0.1:44010 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.453 I/GoLog   (20986): from udp:127.0.0.1:58337 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.453 I/GoLog   (20986): from udp:127.0.0.1:44682 accepted udp:192.168.1.1:53 [socks-in -> dns-out]
10-18 02:12:05.482 I/GoLog   (20986): from udp:127.0.0.1:40429 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.496 I/GoLog   (20986): from udp:127.0.0.1:41299 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.498 I/GoLog   (20986): from udp:127.0.0.1:53851 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.514 I/GoLog   (20986): from udp:127.0.0.1:33865 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.528 I/GoLog   (20986): from udp:127.0.0.1:49166 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.547 I/GoLog   (20986): from udp:127.0.0.1:35393 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.549 I/GoLog   (20986): from udp:127.0.0.1:34379 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.559 I/GoLog   (20986): from udp:127.0.0.1:48434 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.570 I/GoLog   (20986): from udp:127.0.0.1:49260 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.611 I/GoLog   (20986): from udp:127.0.0.1:36062 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.617 I/GoLog   (20986): from udp:127.0.0.1:36805 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.619 I/GoLog   (20986): from udp:127.0.0.1:34506 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.622 I/GoLog   (20986): from udp:127.0.0.1:38323 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.622 I/GoLog   (20986): from udp:127.0.0.1:50448 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:05.626 I/GoLog   (20986): from udp:127.0.0.1:44613 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.490 I/GoLog   (20986): from udp:127.0.0.1:39104 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.508 I/GoLog   (20986): from udp:127.0.0.1:54091 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.512 I/GoLog   (20986): from udp:127.0.0.1:57739 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.525 I/GoLog   (20986): from udp:127.0.0.1:54468 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.532 I/GoLog   (20986): from udp:127.0.0.1:38636 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.543 I/GoLog   (20986): from udp:127.0.0.1:37219 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.563 I/GoLog   (20986): from udp:127.0.0.1:51542 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.571 I/GoLog   (20986): from udp:127.0.0.1:42533 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.577 I/GoLog   (20986): from udp:127.0.0.1:37491 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.627 I/GoLog   (20986): from udp:127.0.0.1:42634 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.633 I/GoLog   (20986): from udp:127.0.0.1:43121 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.636 I/GoLog   (20986): from udp:127.0.0.1:48905 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.638 I/GoLog   (20986): from udp:127.0.0.1:48455 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.640 I/GoLog   (20986): from udp:127.0.0.1:56534 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:06.642 I/GoLog   (20986): from udp:127.0.0.1:55566 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:08.519 I/GoLog   (20986): from udp:127.0.0.1:57525 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:08.653 I/GoLog   (20986): from udp:127.0.0.1:53250 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:08.665 I/GoLog   (20986): from udp:127.0.0.1:45143 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:09.012 I/GoLog   (20986): from udp:127.0.0.1:54461 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:09.014 I/GoLog   (20986): from udp:127.0.0.1:56653 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:09.018 I/GoLog   (20986): from udp:127.0.0.1:46467 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:09.070 I/GoLog   (20986): from udp:127.0.0.1:56182 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:09.651 I/GoLog   (20986): from udp:127.0.0.1:47294 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:09.651 I/GoLog   (20986): from udp:127.0.0.1:59621 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:10.029 I/GoLog   (20986): from udp:127.0.0.1:45853 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:10.032 I/GoLog   (20986): from udp:127.0.0.1:60476 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:10.032 I/GoLog   (20986): from udp:127.0.0.1:54145 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:12.056 I/GoLog   (20986): from udp:127.0.0.1:46047 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:13.526 I/GoLog   (20986): from udp:127.0.0.1:39602 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:13.526 I/GoLog   (20986): from udp:127.0.0.1:37444 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:13.526 I/GoLog   (20986): from udp:127.0.0.1:49923 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:13.657 I/GoLog   (20986): from udp:127.0.0.1:51849 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:13.673 I/GoLog   (20986): from udp:127.0.0.1:38042 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:14.076 I/GoLog   (20986): from udp:127.0.0.1:35817 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:14.518 I/GoLog   (20986): from udp:127.0.0.1:43951 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:14.651 I/GoLog   (20986): from udp:127.0.0.1:60923 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:14.651 I/GoLog   (20986): from udp:127.0.0.1:58288 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:14.651 I/GoLog   (20986): from udp:127.0.0.1:53603 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:14.663 I/GoLog   (20986): from udp:127.0.0.1:36164 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:15.085 I/GoLog   (20986): from udp:127.0.0.1:39635 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:17.034 I/GoLog   (20986): from udp:127.0.0.1:49524 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:17.060 I/GoLog   (20986): from udp:127.0.0.1:42016 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:18.097 I/GoLog   (20986): from udp:127.0.0.1:35495 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:18.533 I/GoLog   (20986): from udp:127.0.0.1:58691 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:18.535 I/GoLog   (20986): from udp:127.0.0.1:36101 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:18.535 I/GoLog   (20986): from udp:127.0.0.1:42468 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.525 I/GoLog   (20986): from udp:127.0.0.1:36267 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.525 I/GoLog   (20986): from udp:127.0.0.1:44998 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.527 I/GoLog   (20986): from udp:127.0.0.1:54635 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.662 I/GoLog   (20986): from udp:127.0.0.1:56847 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.662 I/GoLog   (20986): from udp:127.0.0.1:43003 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.665 I/GoLog   (20986): from udp:127.0.0.1:50347 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.672 I/GoLog   (20986): from udp:127.0.0.1:60405 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:19.674 I/GoLog   (20986): from udp:127.0.0.1:39407 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:20.091 I/GoLog   (20986): from udp:127.0.0.1:39045 accepted udp:8.8.8.8:53 [socks-in -> dns-out]
10-18 02:12:20.091 I/GoLog   (20986): from udp:127.0.0.1:41146 accepted udp:8.8.8.8:53 [socks-in -> dns-out]

و این فقط مشکل من نیست چند نفر از دوستان دیگه هم این مشکل رو داشتن و منتظر شدن ک کس دیگه ای پیش قدم شه ولی کسی ایشو نزد
عزیز من ازینکه وقتتو میگیرم بازم عذرخواهی میکنم شما اونقدری لطف و محبت صبوری داشتی ک همه مسببین این مشکلات فدای ی تار موی شما هم بشن کمه🙏

**Comment by emisemok** [comment]
ای پی پورت پنلی ک کار میکرد رو با ای پی پورت پنل ۲.۶.۹ جایگزین کردم و مشکل برطرف شد
بازم معذرت میخوام ک وقتتو گرفتم
❤🙏

**Comment by bia-pain-bache** [comment]
خواهش میکنم، مهم اینه مشکل برطرف شد ;)
