### ISSUE TITLE
باز نکردن برخی سایت ها

### ISSUE THREAD

**Issue by javademadi** [bia-pain-bache/BPB-Worker-Panel#421]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام. خدا قوت .  من همون تنظیمات دیفالت رو تقریبا قرار دادم بر روی پنل ولی بعضی از سایت های داخلی و برخی از سایت های خارجی هنگامی که V2rayN رو فعال میکنم باز نمیشن . حتی خود پنل هم اگر روشن کنم پروکسی رو دیگه باز نمیشه که بخوام تنظیماتش رو تغییر بدم و باید خاموشش کنم .از فرگمنت و نرمال استفاده میکنم.
![Screenshot 2024-10-18 151144](https://github.com/user-attachments/assets/41e2d6fc-2851-4ff7-9b32-93c91f7d82da)

### Relevant log output | لاگ برنامه یا پنل

```shell
2024/10/18 15:11:36 [Error] [4133808810] transport/internet/websocket: failed to dial to bpb-panel-64q.pages.dev:443 > io: read/write on closed pipe
```

**Comment by hosseinit1988** [comment]
دقیقا همین مشکل رو دارم
نسخه 2.6.7 این مشکل رو نداره

**Comment by bia-pain-bache** [comment]
سلام، proxy ip شخصی بذارید.

**Comment by javademadi** [comment]
> سلام، proxy ip شخصی بذارید.
تشکر مشکل حل شد

**Comment by hameed-maleki** [comment]
> سلام، proxy ip شخصی بذارید.

از کجا میشه ip proxy خوب پیدا کرد مرجعی سراغ دارید
