### ISSUE TITLE
باز نکردن سایت در نرم افزار های آیفون

### ISSUE THREAD

**Issue by hosseinit1988** [bia-pain-bache/BPB-Worker-Panel#422]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با درود و احترام
عرض ادب و خسته نباشید.من در گوشی آیفون و اینترنت ایرانسل با نرم افزار های Streisand , V2box,Hiddify,V2rayTun و Foxray حتی تست زدم و بای باز کردن سایتها کلا مشکل داشتم.زمانی به نسخه 2.6.7 باز میگردم این مشکل نیست.
با تشکر

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

نرم افزار های Streisand , V2box,Hiddify,V2rayTun و Foxray

### Relevant log output | لاگ برنامه یا پنل

```shell
باز نکردن سایت ها
```

**Comment by bia-pain-bache** [comment]
سلام، ممنون. proxy ip شخصی بذارید.

**Comment by hosseinit1988** [comment]
یعنی ip تمیز کلادفلر بگذارم ؟!🤔

**Comment by bia-pain-bache** [comment]
به آموزش‌ها مراجعه کنید توضیح دادم. فرق داره.

**Comment by hosseinit1988** [comment]
حق با شما بود.ببخشید دقت نکرده بودم.عالی شد
سپاس از زحمات شما
