### ISSUE TITLE
اضافه کردن vmess

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#423]
### Feature description | توضیحات ویژگی

vmess هم میتونید در نسخه های بعدی اضافه کنید؟

**Comment by bia-pain-bache** [comment]
هیچ‌فرقی با هم ندارن وقتی TLS استفاده میکنید. اون تروجان هم اضافیه ؛)

**Comment by developer861** [comment]
گرفتم.
بازم دمتون گرم.
فقط یه مشکل خیلی ریزی ui پنل داره اونم اینه که اون دکمه تغییر به تم سیاهش دایره هاش هم مرکر نیستن(از سمت راست مماسن) تو iphone 8 گفتم اطلاع بدم :)

**Comment by developer861** [comment]
آقا قابلیت تغییر نام یا استیکر کانفیگا هم بذارید خوب میشه 
استیکر دیفالتش یه جوریه :))))))
