### ISSUE TITLE
 Why was "NO TLS" removed?  2.6.9 and 2.7

### ISSUE THREAD

**Issue by xinycq** [bia-pain-bache/BPB-Worker-Panel#425]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

2.6.9 and 2.7

Why was "NO TLS" removed?
Thanks!

![111](https://github.com/user-attachments/assets/c9d7f9ed-bbe0-4360-b471-9f1a5fd71825)

### Relevant log output | لاگ برنامه یا پنل

```shell
Why was "NO TLS" removed? 2.6.9 and 2.7
Thanks!
```

**Comment by bia-pain-bache** [comment]
It only works on Workers deployment and without custom domain.

**Comment by yemaozi000736** [comment]
能不能添加no tls

**Comment by bia-pain-bache** [comment]
Deploy using Workers and it appears on your panel.
