### ISSUE TITLE
برگرداندن متود قبلی 

### ISSUE THREAD

**Issue by mani20078** [bia-pain-bache/BPB-Worker-Panel#429]
### Feature description | توضیحات ویژگی

سلام ممنونم بابت ورکر و پنل فوق العادتون میشه فایل worker.js هل رو مثل قبلا کنید که بشه استیکر هاش و uuid رو از تو خود کد ادیت کرد تو کد جدیدتون نمیشه. یا اگر راهی داره لطف میکنید بگید ممنونم.
![problem](https://github.com/user-attachments/assets/53e10c14-ab44-4625-b899-6601519885db)

**Comment by bia-pain-bache** [comment]
سلام خواهش میکنم.
روشش تغییر کرده، به آموزش راه‌اندازی ورکر مراجعه کنید.
