### ISSUE TITLE
The upload speed of Irancell and some operators has slowed down

### ISSUE THREAD

**Issue by MohammadGC** [bia-pain-bache/BPB-Worker-Panel#43]
Hello and don't be tired. It's been a week since the upload speed has improved on Irancell, and it doesn't matter whether it's fragmented or not, because it's been disrupted on Cloudflare's IPs. And if you need to make special settings on the v2rayNg program, please help.

**Comment by MohammadGC** [comment]
What I noticed is that Irancell has updated its firewall and the fragment is no longer responsive.
 I didn't change the settings of the fragment inside the panel. Do I have to make any special settings?
![Uploading Screenshot from 2024-05-01 11-31-15.png…]()

**Comment by bia-pain-bache** [comment]
Hi, Please set Fragment settings like this:

Length: 10-30
Interval: 1-3

**Comment by MohammadGC** [comment]
Hello again. Unfortunately, it had no effect and the pings have increased greatly both on Irancell and on the hamrahe Aval. Both normal and fragmented configs have been damaged.

**Comment by emisemok** [comment]
فارسی بنویس مگه مجبوری 
خب همراه اول ایرانسل فقط برا ی خراب شده س
و برای مشکلت تو پنل اون مقادیری ک میذاری برای فرگمنت خیلی مهم هستن و بنا ب اپراتور متفاوت هستن

**Comment by MohammadGC** [comment]
شرمنده به اشتباه فکر میکردم که حتمی باید انگلیسی بنویسم تا این که دیدم دوستان دیگر هم فارسی مینویسند .

**Comment by bia-pain-bache** [comment]
اگر انگلیسی بنویسید کمک میکنه به بقیه که غیر فارسی زبان هستن ولی چون مشکل ایرانسل به ایران مربوط میشه ایرادی نداره. اون پینگی که بالا میره پینگ handshake هست و روی پینگ اصلی تاثیر خاصی نداره، اسپیدتست ملاکه. ولی فعلا ایرانسل منطقه به منطقه و ساعت به ساعت رفتار متفاوتی داره، برای بعضیا جواب میده بعضیا نه.
