### ISSUE TITLE
افزودن یک نام دامنه سفارشی همچنان به وب سایت speedtest هدایت می شود. آیا می توانید بپرسید که آیا uuid پیش فرض تغییر کرده است؟

### ISSUE THREAD

**Issue by writersguidelines** [bia-pain-bache/BPB-Worker-Panel#431]
### Feature description | توضیحات ویژگی

افزودن یک نام دامنه سفارشی همچنان به وب سایت speedtest هدایت می شود. آیا می توانید بپرسید که آیا uuid پیش فرض تغییر کرده است؟

**Comment by bia-pain-bache** [comment]
I don't get the point, thanks for your consideration, but no need to type in Farsi.

**Comment by writersguidelines** [comment]
Dear teacher, I have two problems to feedback to you, adding a custom domain name will still jump to the speedtest website, it is recommended to fix it, and the second default uuid and modify it. We used to change the code manually, but now your code is encrypted, we are worried about privacy leaks, and your code has helped people a lot, and I am very grateful to you.

**Comment by bia-pain-bache** [comment]
First of all adding a custom domain has nothing to do with speedtest, the purpose is to change workers or pages main domain.
Secondly, the code is not encrypted, just built by wrangler. Please refer to instructions to learn how to change parameters like UUID and Trojan pass...

**Comment by samimi67** [comment]
سلام چند روزه ابدیت ندادی نگرانت شدیم

**Comment by bia-pain-bache** [comment]
به زودی ؛)
