### ISSUE TITLE
Error 1034 cloudflare

### ISSUE THREAD

**Issue by XyHK-HUC** [bia-pain-bache/BPB-Worker-Panel#436]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Please enable cookies.
Error 1034
Ray ID: 8d608d9abd030eba • 2024-10-21 10:27:06 UTC
Edge IP Restricted
What happened?
You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (dash.cloudflare.com) resolved to an IP address that the owner of the website does not have access to.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.

Was this page helpful? Yes No
Thank you for your feedback!

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Please enable cookies.
Error 1034
Ray ID: 8d608d9abd030eba • 2024-10-21 10:27:06 UTC
Edge IP Restricted
What happened?
You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (dash.cloudflare.com) resolved to an IP address that the owner of the website does not have access to.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.

Was this page helpful? Yes No
Thank you for your feedback!

### Relevant log output | لاگ برنامه یا پنل

```shell
Please enable cookies.
Error 1034
Ray ID: 8d608d9abd030eba • 2024-10-21 10:27:06 UTC
Edge IP Restricted
What happened?
You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (dash.cloudflare.com) resolved to an IP address that the owner of the website does not have access to.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.

Was this page helpful? Yes No
Thank you for your feedback!
```

**Comment by bia-pain-bache** [comment]
Please set a custom proxy ip.

**Comment by samimi67** [comment]
میشه دامنه ir رو پشت کلود فلر بذاریم 
جواب میده ?

**Comment by bia-pain-bache** [comment]
آره میشه.
