### ISSUE TITLE
Add support for cfnat for automatic cf ip optimization

### ISSUE THREAD

**Issue by fatinghenji** [bia-pain-bache/BPB-Worker-Panel#446]
### Feature description | توضیحات ویژگی

https://github.com/cmliu/CFnat-Windows-GUI

**Comment by vadash** [comment]
how would it work? bpb adds another entry with 127.0.0.1:1234 port and this app works as detour before, right?

**Comment by fatinghenji** [comment]
Similar to the local selection of cleanip? My native language is not English, I don't quite understand what you mean. I just hope that the bpb panel can support adding addresses like 127.0.0.1:1234 to the cleanip column to match this software.

**Comment by fatinghenji** [comment]
No, it's cross-platform. The app I mentioned is just a call with a GUI.
In the zip package provided in [this](https://t.me/CF_NAT/38840) connection, you can see that it is a cross-platform application.
![图片](https://github.com/user-attachments/assets/8d832651-fbfe-4b97-9688-4b091a4151be)

**Comment by vadash** [comment]
> It's not cross platform and i don't add such features to panel for now.

Its easy to implement. Just allow validation for 127.0.0.1:port for clean ip. Here is example singbox. It will work just fine

```
    {
      "tag": "cfnet",
      "server": "127.0.0.1",
      "server_port": 1234,
      "type": "vless",
      "uuid": "REDACTED",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "REDACTED",
        "insecure": true,
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      },
      "transport": {
        "type": "ws",
        "path": "/REDACTED",
        "headers": {
          "Host": [
            "REDACTED"
          ]
        }
      }
    }
```

**Comment by bia-pain-bache** [comment]
Even being cross-platform, still I cannot recommend 3rd-party app that I cannot approve its security, please use in your own risk.
