### ISSUE TITLE
Subscription link for mihomo-party

### ISSUE THREAD

**Issue by fatinghenji** [bia-pain-bache/BPB-Worker-Panel#448]
### Feature description | توضیحات ویژگی

Please see this issue [[Bug] error when adding bpb's clash subscription link](https://github.com/mihomo-party-org/mihomo-party/issues/291), according to the developer's answer, there is a problem with the subscription link provided by the bpb panel.

**Comment by bia-pain-bache** [comment]
Please submit an issue and fill in required fields and also client specifications and Panel version.
