### ISSUE TITLE
add clash nyanpasu to clash client list

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#450]
### Feature description | توضیحات ویژگی

it's a good clash client written in rust

**Comment by developer861** [comment]
are you sure?
i'm already using it in desktop with your panel's full normal sub and it's working

**Comment by developer861** [comment]
oh i forgot i'm using the latest beta version so i think it will be added in the next stable release

**Comment by bia-pain-bache** [comment]
No, I'm not sure, just guessed from documentation ;)
