### ISSUE TITLE
clash sub not working in stash 

### ISSUE THREAD

**Issue by Pigeonszz** [bia-pain-bache/BPB-Worker-Panel#456]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

the app look forward a yaml file instead of json

### Relevant log output | لاگ برنامه یا پنل

```shell
the app look forward a yaml file instead of json
```

**Comment by bia-pain-bache** [comment]
Please update to the latest version and in DNS Settings, set it to rule.
