### ISSUE TITLE
مشکل هیدیفای

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#459]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

من کانفیگارو برای اپ هیدیفای هم تو ios هم linux mint تست کردم ولی با هیچکدوم کار نکرد و در لینوکس بعضی وقتا کرش هم میکنه نمیدونم مشکل از کانفیگای پنله یا خود کلاینت 

### Relevant log output | لاگ برنامه یا پنل

```shell
no log
```

**Comment by bia-pain-bache** [comment]
اگر سوالات متداول رو خوندی و مشکل برطرف نشده باید به خودشون تیکت بزنی، روی اندروید و ویندوز و لینوکس تست شده مشکلی نداره.

**Comment by developer861** [comment]
بله مشکل از کلاینته 
  به نسخه ۲.۰۵ برگشتم درست شد

**Comment by ashkanrostami7** [comment]
منم هر چی میسازم رو هیدیفای میزنه نا معتبر یا خطا دیگه میده
