### ISSUE TITLE
add udp noise in warp pro for xray core

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#463]
### Feature description | توضیحات ویژگی

https://xtls.github.io/config/outbounds/freedom.html#outboundconfigurationobject
قبلا این ریکيستو زده بودم میشه دوباره تست کنید اگه کار کرد اضافه کنید؟

**Comment by bia-pain-bache** [comment]
هیچ دستاورد جدیدی نداشتم، اگر خودتون تست کردید نتیجه گرفتید لطفا به اشتراک بذارید.

**Comment by dragonbreath2000** [comment]
``` json
{
    "dns": {
      "hosts": {
        "domain:googleapis.cn": "googleapis.com"
      },
      "servers": [
        "1.1.1.1"
      ]
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "destOverride": [
            "http",
            "tls"
          ],
          "enabled": true
        },
        "tag": "socks"
      },
      {
        "listen": "127.0.0.1",
        "port": 10809,
        "protocol": "http",
        "settings": {
          "userLevel": 8
        },
        "tag": "http"
      }
    ],
    "log": {
      "loglevel": "warning"
    },
  
  
  
    "outbounds": [
      
      {
        "protocol": "wireguard",
        "settings": {
          "address": [
            "172.16.0.2/32",
            "2606:4700:110:8d3e:21e7:361b:611:3255/128"
          ],
          "mtu": 1280,
          "peers": [
            {
              "endpoint": "162.159.192.186:8742",
              "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
            }
          ],
          "reserved": [107,47,15],
          "secretKey": "sCvmeko7th9HKSUjG81gciBecuey8tmOLqsh8mzmwVQ="
        },
        "streamSettings": {
            "sockopt": {
               "dialerProxy": "noise"
            }
         },
        "tag": "warpMain"
      },
      {
        "protocol": "freedom",
        "settings": {},
        "tag": "direct"
      },
      {
        "protocol": "freedom",
        "settings": {
            "noises":[
                {
                    "type":"base64",
                    "packet":"7nQBAAABAAAAAAAABnQtcmluZwZtc2VkZ2UDbmV0AAABAAE=",
                    "delay":"10-16"
                  }
            ]
        },
        "tag": "noise"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "block"
      }
    ],
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "enabled": true
        },
  
        {
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "warpMain",
          "port": "53",
          "type": "field"
        },
        
        {
          "id": "5627785659655799759",
          "type": "field",
          "port": "0-65535",
          "outboundTag": "warpMain",
          "enabled": true
        }
      ]
    }
  }
  ```
سلام
اینو تست کنید
برای من کار می کنه
![noise](https://github.com/user-attachments/assets/c25db0f2-f4fd-4e1c-97d5-93a6042fae16)
اون پکت اول ک نوشته DNS درواقع نویزه ک تو کانفیگ با base64 گزاشتم

**Comment by developer861** [comment]
@bia-pain-bache

**Comment by developer861** [comment]
@dragonbreath2000 
@bia-pain-bache 
الان تست کردم کار میکنه

**Comment by developer861** [comment]
خب الان روی دو اپراتور تست کردم مبین نت و ایرانسل
روی مبین نت جواب میده ولی با ایرانسل هنوز مشکل داره احتمالا پارامتراشو اگه عوض کنیم اونم درست میشه

**Comment by developer861** [comment]
@dragonbreath2000 
الان دیدم خودتون اینو به xray pr داده بودین دمتون گرم:)

**Comment by developer861** [comment]
type:rand
packet:10-15
delay:1-1
با ایرانسل و مبین نت کار میکنه

**Comment by developer861** [comment]
{
    "dns": {
      "hosts": {
        "domain:googleapis.cn": "googleapis.com"
      },
      "servers": [
        "1.1.1.1"
      ]
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "destOverride": [
            "http",
            "tls"
          ],
          "enabled": true
        },
        "tag": "socks"
      },
      {
        "listen": "127.0.0.1",
        "port": 10809,
        "protocol": "http",
        "settings": {
          "userLevel": 8
        },
        "tag": "http"
      }
    ],
    "log": {
      "loglevel": "warning"
    },
  
  
  
    "outbounds": [
      
      {
        "protocol": "wireguard",
        "settings": {
          "address": [
            "172.16.0.2/32",
            "2606:4700:110:8d3e:21e7:361b:611:3255/128"
          ],
          "mtu": 1280,
          "peers": [
            {
              "endpoint": "188.114.98.224:7559",
              "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
            }
          ],
          "reserved": [107,47,15],
          "secretKey": "sCvmeko7th9HKSUjG81gciBecuey8tmOLqsh8mzmwVQ="
        },
        "streamSettings": {
            "sockopt": {
               "dialerProxy": "noise"
            }
         },
        "tag": "warpMain"
      },
      {
        "protocol": "freedom",
        "settings": {},
        "tag": "direct"
      },
      {
        "protocol": "freedom",
        "settings": {
            "noises":[
                {
                    "type":"rand:10-20",
                    "packet":"10-15",
                    "delay":"1-1"
                  }
            ]
        },
        "tag": "noise"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "block"
      }
    ],
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "enabled": true
        },
  
        {
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "warpMain",
          "port": "53",
          "type": "field"
        },
        
        {
          "id": "5627785659655799759",
          "type": "field",
          "port": "0-65535",
          "outboundTag": "warpMain",
          "enabled": true
        }
      ]
    }
  }

**Comment by developer861** [comment]
`{
"dns": {
"hosts": {
"domain:googleapis.cn": "googleapis.com"
},
"servers": [
"1.1.1.1"
]
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 10808,
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"userLevel": 8
},
"sniffing": {
"destOverride": [
"http",
"tls"
],
"enabled": true
},
"tag": "socks"
},
{
"listen": "127.0.0.1",
"port": 10809,
"protocol": "http",
"settings": {
"userLevel": 8
},
"tag": "http"
}
],
"log": {
"loglevel": "warning"
},

"outbounds": [
  
  {
    "protocol": "wireguard",
    "settings": {
      "address": [
        "172.16.0.2/32",
        "2606:4700:110:8d3e:21e7:361b:611:3255/128"
      ],
      "mtu": 1280,
      "peers": [
        {
          "endpoint": "188.114.98.224:7559",
          "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
        }
      ],
      "reserved": [107,47,15],
      "secretKey": "sCvmeko7th9HKSUjG81gciBecuey8tmOLqsh8mzmwVQ="
    },
    "streamSettings": {
        "sockopt": {
           "dialerProxy": "noise"
        }
     },
    "tag": "warpMain"
  },
  {
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  },
  {
    "protocol": "freedom",
    "settings": {
        "noises":[
            {
                "type":"rand:10-20",
                "packet":"10-15",
                "delay":"1-1"
              }
        ]
    },
    "tag": "noise"
  },
  {
    "protocol": "blackhole",
    "settings": {
      "response": {
        "type": "http"
      }
    },
    "tag": "block"
  }
],
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "inboundTag": [
        "api"
      ],
      "outboundTag": "api",
      "enabled": true
    },

    {
      "ip": [
        "1.1.1.1"
      ],
      "outboundTag": "warpMain",
      "port": "53",
      "type": "field"
    },
    
    {
      "id": "5627785659655799759",
      "type": "field",
      "port": "0-65535",
      "outboundTag": "warpMain",
      "enabled": true
    }
  ]
}
}'

**Comment by developer861** [comment]
> {
"dns": {
"hosts": {
"domain:googleapis.cn": "googleapis.com"
},
"servers": [
"1.1.1.1"
]
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 10808,
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"userLevel": 8
},
"sniffing": {
"destOverride": [
"http",
"tls"
],
"enabled": true
},
"tag": "socks"
},
{
"listen": "127.0.0.1",
"port": 10809,
"protocol": "http",
"settings": {
"userLevel": 8
},
"tag": "http"
}
],
"log": {
"loglevel": "warning"
},

"outbounds": [
  
  {
    "protocol": "wireguard",
    "settings": {
      "address": [
        "172.16.0.2/32",
        "2606:4700:110:8d3e:21e7:361b:611:3255/128"
      ],
      "mtu": 1280,
      "peers": [
        {
          "endpoint": "188.114.98.224:7559",
          "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
        }
      ],
      "reserved": [107,47,15],
      "secretKey": "sCvmeko7th9HKSUjG81gciBecuey8tmOLqsh8mzmwVQ="
    },
    "streamSettings": {
        "sockopt": {
           "dialerProxy": "noise"
        }
     },
    "tag": "warpMain"
  },
  {
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  },
  {
    "protocol": "freedom",
    "settings": {
        "noises":[
            {
                "type":"rand:10-20",
                "packet":"10-15",
                "delay":"1-1"
              }
        ]
    },
    "tag": "noise"
  },
  {
    "protocol": "blackhole",
    "settings": {
      "response": {
        "type": "http"
      }
    },
    "tag": "block"
  }
],
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "inboundTag": [
        "api"
      ],
      "outboundTag": "api",
      "enabled": true
    },

    {
      "ip": [
        "1.1.1.1"
      ],
      "outboundTag": "warpMain",
      "port": "53",
      "type": "field"
    },
    
    {
      "id": "5627785659655799759",
      "type": "field",
      "port": "0-65535",
      "outboundTag": "warpMain",
      "enabled": true
    }
  ]
}
}

**Comment by developer861** [comment]
`{
"dns": {
"hosts": {
"domain:googleapis.cn": "googleapis.com"
},
"servers": [
"1.1.1.1"
]
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 10808,
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"userLevel": 8
},
"sniffing": {
"destOverride": [
"http",
"tls"
],
"enabled": true
},
"tag": "socks"
},
{
"listen": "127.0.0.1",
"port": 10809,
"protocol": "http",
"settings": {
"userLevel": 8
},
"tag": "http"
}
],
"log": {
"loglevel": "warning"
},

"outbounds": [
  
  {
    "protocol": "wireguard",
    "settings": {
      "address": [
        "172.16.0.2/32",
        "2606:4700:110:8d3e:21e7:361b:611:3255/128"
      ],
      "mtu": 1280,
      "peers": [
        {
          "endpoint": "188.114.98.224:7559",
          "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
        }
      ],
      "reserved": [107,47,15],
      "secretKey": "sCvmeko7th9HKSUjG81gciBecuey8tmOLqsh8mzmwVQ="
    },
    "streamSettings": {
        "sockopt": {
           "dialerProxy": "noise"
        }
     },
    "tag": "warpMain"
  },
  {
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  },
  {
    "protocol": "freedom",
    "settings": {
        "noises":[
            {
                "type":"rand:10-20",
                "packet":"10-15",
                "delay":"1-1"
              }
        ]
    },
    "tag": "noise"
  },
  {
    "protocol": "blackhole",
    "settings": {
      "response": {
        "type": "http"
      }
    },
    "tag": "block"
  }
],
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "inboundTag": [
        "api"
      ],
      "outboundTag": "api",
      "enabled": true
    },

    {
      "ip": [
        "1.1.1.1"
      ],
      "outboundTag": "warpMain",
      "port": "53",
      "type": "field"
    },
    
    {
      "id": "5627785659655799759",
      "type": "field",
      "port": "0-65535",
      "outboundTag": "warpMain",
      "enabled": true
    }
  ]
}
}`

**Comment by developer861** [comment]
{
    "dns": {
      "hosts": {
        "domain:googleapis.cn": "googleapis.com"
      },
      "servers": [
        "1.1.1.1"
      ]
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "destOverride": [
            "http",
            "tls"
          ],
          "enabled": true
        },
        "tag": "socks"
      },
      {
        "listen": "127.0.0.1",
        "port": 10809,
        "protocol": "http",
        "settings": {
          "userLevel": 8
        },
        "tag": "http"
      }
    ],
    "log": {
      "loglevel": "warning"
    },
    "outbounds": [
      
      {
        "protocol": "wireguard",
        "settings": {
          "address": [
            "172.16.0.2/32",
            "2606:4700:110:8d3e:21e7:361b:611:3255/128"
          ],
          "mtu": 1280,
          "peers": [
            {
              "endpoint": "188.114.08.224:7559",
              "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
            }
          ],
          "reserved": [107,47,15],
          "secretKey": "sCvmeko7th9HKSUjG81gciBecuey8tmOLqsh8mzmwVQ="
        },
        "streamSettings": {
            "sockopt": {
               "dialerProxy": "noise"
            }
         },
        "tag": "warpMain"
      },
      {
        "protocol": "freedom",
        "settings": {},
        "tag": "direct"
      },
      {
        "protocol": "freedom",
        "settings": {
            "noises":[
                {
                    "type":"rand:10-20",
                    "packet":"10-15",
                    "delay":"1-1"
                  }
            ]
        },
        "tag": "noise"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "block"
      }
    ],
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "enabled": true
        },
          {
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "warpMain",
          "port": "53",
          "type": "field"
        },
          {
          "id": "5627785659655799759",
          "type": "field",
          "port": "0-65535",
          "outboundTag": "warpMain",
          "enabled": true
        }
      ]
    }
  }

**Comment by developer861** [comment]
@dragonbreath2000 

میتونیم اندازه پکت ساخته شده به طور رندوم رو مشخص کنیم؟

**Comment by dragonbreath2000** [comment]
> @dragonbreath2000
> 
> میتونیم اندازه پکت ساخته شده به طور رندوم رو مشخص کنیم؟

set type to rand
set packet to 10-50(min-max)

**Comment by dragonbreath2000** [comment]
> @dragonbreath2000
> 
> میتونیم اندازه پکت ساخته شده به طور رندوم رو مشخص کنیم؟

type rand and packet 10-15 is already random,not sure what u mean,packet:10-15 means min of 10 and max of 15

**Comment by developer861** [comment]
> > @dragonbreath2000
> > میتونیم اندازه پکت ساخته شده به طور رندوم رو مشخص کنیم؟
> 
> type rand and packet 10-15 is already random,not sure what u mean,packet:10-15 means min of 10 and max of 15 bytes

can i change the minimum and maximum value of randomly generated noises? are they fixed?

**Comment by developer861** [comment]
> > @dragonbreath2000
> > میتونیم اندازه پکت ساخته شده به طور رندوم رو مشخص کنیم؟
> 
> type rand and packet 10-15 is already random,not sure what u mean,packet:10-15 means min of 10 and max of 15 bytes

متوجه شدم یعنی اون ۱۰تا ۱۵ حجم پکت هاست. فکر میکردم تعداد پکت هاییه که قراره ارسال شه

خب تعداد پکت هایی که قراره ارسال بشن چطوریه؟

**Comment by bia-pain-bache** [comment]
دوستان روی ایرانسل که وارپ بدون مشکل کار میکنه، اصلا نیازی به نویز نیست، مشکل اپراتورایی مثل همراه اول و شاتل هست، اگر مقادیری پیدا کردید که روی این دو اپراتور کار میکنه به اشتراک بذارید وگرنه نویز Xray مثل نویز NikaNG و MahsaNG کاربردی نیست برای ما.
