### ISSUE TITLE
Use UBlock Origin Extension Filter List

### ISSUE THREAD

**Issue by silent1360** [bia-pain-bache/BPB-Worker-Panel#465]
### Feature description | توضیحات ویژگی

سلام 

توی سورس دیدم شما از این لیست استفاده کردین :  
 url: "https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-category-ads-all.srs",

اگه امکانش هست از فیلتر لیستهای UBlock Origin Extension برای بلاک لیست استفاده کنید . فوق العاده بلاک لیست کاملیه حتی تبلیغات یوتیوب رو هم بلاک میکنه که این خیلی کاربرد داره 

آدرس گیت هاب : https://github.com/gorhill/uBlock

یا اگه فرصتش رو ندارید  ممنون میشم راهنمایی کنید خودم چطور میتونم این کارو انجام بدم

**Comment by bia-pain-bache** [comment]
سلام، دیتابیس‌هاش متفاوته و روی کلاینت‌ها قابلیت پیاده‌سازی نداره، بعضی از asset ها از منابعش استفاده کردن ولی نمیشه مستقیم بکار گرفت. تبلیغات یوتیوب رو فقط از طریق مرورگر میشه بلاک کرد.

**Comment by silent1360** [comment]
به نظرتون اگه من  یکی از لیستهاشو توی Routing  برنامه NekoRay وارد کنم باعث کندی سرعت نت میشه ؟

**Comment by bia-pain-bache** [comment]
مساله اصلا سرعت نیست، برنامه‌ها اون فرمت رو نمیخونن تا جایی که من میدونم.

**Comment by silent1360** [comment]
من با کمک chatgpt  فرمتش رو به شکلی که برای NekoRay  قابل فهم باشه تبدیل کردم . ولی خوب حدود 6000 رکورد هست

**Comment by bia-pain-bache** [comment]
اصلا بحث روتینگ فایل‌ها باید داخل کلاینت باشن، سمت سرور فایده نداره، میتونید برای خودتون بسازید و داخل اپ استفاده کنید.

**Comment by dj56959566** [comment]
请问我原先是2.6的代码，现在2.7会更自动更新代码吗………

**Comment by bia-pain-bache** [comment]
worker deployment or pages? @dj56959566

**Comment by bia-pain-bache** [comment]
I don't know what is fox github. If you sync your fork, it will automatically update panel after few seconds.

**Comment by dj56959566** [comment]
yes
