### ISSUE TITLE
توضیحات proxy ip

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#466]
### Feature description | توضیحات ویژگی

https://github.com/NiREvil/vless/blob/main/sub/ProxyIP.md

این صفحه رو میتونید به بخش proxy ip اضافه کنید توضیحات خوبی داره

**Comment by bia-pain-bache** [comment]
در حال حاضر یک سرور اختصاص داده شده که سلامت Proxy IP های پیشفرض رو هر نیم ساعت چک میکنه، متاسفانه نمیتونم منابع دیگه رو معرفی کنم چون IP سالم نباشه یوزر به مشکل میخوره و اول از همه سراغ من میاد. میتونید خودتون به اشتراک بذارید.
