### ISSUE TITLE
مستقیم شدن captcha کلودفلر

### ISSUE THREAD

**Issue by hosseinc** [bia-pain-bache/BPB-Worker-Panel#468]
### Feature description | توضیحات ویژگی

سلام
با توجه به اینکه معمولا آیپی‌ها کثیفه و کپچا میاره و به سختی تایید میشه، امکانش هست که دایرکت یا بای‌پس بشه و از کانفیگ رد نشه؟

**Comment by bia-pain-bache** [comment]
No it's not possible unfortunately...you can bypass it but it doesn't help.

**Comment by hosseinc** [comment]
راهی نیست این مشکل حداقل کمتر اتفاق بیفته؟
