### ISSUE TITLE
add multiple proxy ip support

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#470]
### Feature description | توضیحات ویژگی

میشه قابلیت اضافه کردن چند پروکسی آیپی رو اضافه کنید؟
مثلا برای اضافه کردن کانفیگ vless باید چند کانفیگ همزمان اضافه کنیم و تست کنیم چون بعضی از کانفیگ های vless وصل نمیشن و یکی یکی باید اضافه کنیم و تست کنیم

**Comment by bia-pain-bache** [comment]
Maybe a test button for healthy Proxy IP does the job, I can implement it. However your suggestion makes it complicated.

**Comment by developer861** [comment]
> Maybe a test button for healthy Proxy IP does the job, I can implement it.

that would be a good option

>However your suggestion makes it complicated.

why is that?
isn't it like having multiple clean ips or warp endpoints?

**Comment by bia-pain-bache** [comment]
Just pre-released 2.7.2 and adding multiple proxy IPs in Panel or CF Dashboard is implemented.

**Comment by 9thChasingWindGirl** [comment]
> 刚刚预发布了 2.7.2，并实现了在面板或 CF 仪表板中添加多个代理 IP。

TypeError: Parsing a Body as FormData requires a Content-Type header. at updateDataset (functionsWorker-0.6737908003454263.js:4558:35) at async getDataset (functionsWorker-0.6737908003454263.js:4552:21) at async handlePanel (functionsWorker-0.6737908003454263.js:6081:41) at async Object.fetch (functionsWorker-0.6737908003454263.js:9153:20)
![image](https://github.com/user-attachments/assets/1b3ab6c4-6039-43ab-9d08-347a30d40ed7)

**Comment by Derag69** [comment]
There is a problem, what is the solution to enter the panel?
![Uploading Screenshot 2024-11-12 232724.png…]()

**Comment by bia-pain-bache** [comment]
Is this a new deployment or just updated?

**Comment by Derag69** [comment]
new deploymen

**Comment by bia-pain-bache** [comment]
Please wait for stable release, thanks for reporting, I'll check it.

**Comment by Derag69** [comment]
Thank you for your hard work. Good luck. We are waiting

**Comment by developer861** [comment]
> Just pre-released 2.7.2 and adding multiple proxy IPs in Panel or CF Dashboard is implemented.

tnx:))))))))))))))))))

does it support multiple chain proxy too? or only proxy ip?

**Comment by bia-pain-bache** [comment]
2.7.2 bugs fixed and updated. Please try again. Also it would be appreciated if you submit a new issue for different topics.

**Comment by developer861** [comment]
> Maybe a test button for healthy Proxy IP does the job, I can implement it. However your suggestion makes it complicated.

deployed it, works fine

**Comment by Derag69** [comment]
Thank you for your hard work. May you always be successful🙏
