### ISSUE TITLE
adding some clean ip domains as default 

### ISSUE THREAD

**Issue by developer861** [bia-pain-bache/BPB-Worker-Panel#473]
### Feature description | توضیحات ویژگی

sky.rethinkdns.com , fbi.gov , time.is , www.wto.org , ip.sb , zula.ir , creativecommons.org , go.inmobi.com , cdnjs.com

you can add these domains to worker's default clean ips it can help lower the ping of best ping config and resist pages and worker domain filtering

**Comment by bia-pain-bache** [comment]
I'm not gonna do it, clean IP should be scanned on local ISP.
