### ISSUE TITLE
label ip addresses, local dns does not seem to support doh addresses

### ISSUE THREAD

**Issue by 9thChasingWindGirl** [bia-pain-bache/BPB-Worker-Panel#474]
### Feature description | توضیحات ویژگی

I created two cloud flare pages, one from [edgetunnel](https://github.com/cmliu/edgetunnel) repositories and one fork from you (pre 2.7.2)

In the work.js file provided by edgetunnel, we can define ADD variable, attach custom label and flag to ip address
![image](https://github.com/user-attachments/assets/6d1ba115-813d-4c63-a8f2-44e971bf30bd)

- 172.67.45.173 #香港HKG 172.67.45.173
- 104.22.56.169 #香港HKG 104.22.56.169
- 104.16.216.135 #香港HKG 104.16.216.135
- 172.67.32.189 #香港HKG 172.67.32.189
- 172.67.17.190 #香港HKG 172.67.17.190
- 104.17.134.0 #香港HKG 104.17.134.0
- 172.67.43.248 #香港HKG 172.67.43.248
- 104.22.29.74 #香港HKG 104.22.29.74
- 104.16.209.227 #香港HKG 104.16.209.227
- 104.16.47.65 #香港HKG 104.16.47.65
- 104.22.52.212 #香港HKG 104.22.52.212
- 104.22.58.228 #香港HKG 104.22.58.228
……

so it would be seem like this:

![image](https://github.com/user-attachments/assets/07524979-919b-4c7a-806a-6639e656b334)

this may prevent social accounts from being frozen due to **frequent IP changes**

and this is bpb panel :

![image](https://github.com/user-attachments/assets/bb2839fe-184f-4102-a251-57a520343691)

the last thing is that local dns doesn't seem to support doh and doesn't support multiple addresses.

![image](https://github.com/user-attachments/assets/ea15d836-a80c-4fe1-94ef-eeed3dcc401b)

**Comment by bia-pain-bache** [comment]
1- what's the point of adding flags? your IP will be usually germany, no matter where is the location of node.
2- Why do you need DOH for local addresses? Is there any problem resolving local domains using udp dns? can you provide an example?

**Comment by 9thChasingWindGirl** [comment]
> 1- what's the point of adding flags? your IP location will be usually germany, no matter where is the location of node. 2- Why do you need DOH for local addresses? Is there any problem resolving local domains using udp dns? can you provide an example?
For the first point I just want to be able to make the network nodes look cleaner or customizable in the proxy software, that's all.
The second,  when copying remote dns as local, I found that doh was not available, and multiple dns were not available, not just doh.

**Comment by 9thChasingWindGirl** [comment]
> 1- what's the point of adding flags? your IP location will be usually germany, no matter where is the location of node. 2- Why do you need DOH for local addresses? Is there any problem resolving local domains using udp dns? can you provide an example?

For the first point I just want to be able to make the network nodes look cleaner or customizable in the proxy software, that's all.
The second, when copying remote dns as local, I found that doh was not available, and multiple dns were not available, not just doh.

**Comment by bia-pain-bache** [comment]
Configs used to show node IPs, however clients UI issues forced me to make it cleaner and display them only using numbers and format.
DOH is banned almost in all countries like iran and China, and it's only resolving local domain which are bypassed or outbound domains, so it can be a udp DNS like 223.5.5.5 in your region or even your router gateway if connected to a local network.
I can help better if you provide an example which needs doh for local DNS.
