### ISSUE TITLE
Geoip & Geosite of Turkey & Afghanistan 

### ISSUE THREAD

**Issue by Graveyard9988** [bia-pain-bache/BPB-Worker-Panel#479]
### Feature description | توضیحات ویژگی

درود
از انجایی که فیلترینگ مقطعی در کشور ترکیه و فیلترینگ دائمی در افغانستان  اعمال می شود، هیدیفای جهت بای پس سایت ها و ایپی های این دو کشور، نسبت به جمع اوری و اپدیت فایل های جئو ترکیه و افغانستان با پسوند srs (مخصوص سینگ باکس) را تهیه کرده که از لینک زیر قابل مشاهده ست:

https://github.com/hiddify/hiddify-geo/tree/rule-set/country

بنابراین خواهشمندم که پنل را مجهز به رول های بای پس ترکیه و افغانستان (مخصوص سینگ باکس) کنید.

برای ترجمه موقتی به ترکی استانبولی هم از هوش مصنوعی جهت ترجمه به زبان کشور نامبرده کنید.

سپاس

**Comment by bia-pain-bache** [comment]
متاسفانه بقیه دیتابیس‌ها این دو کشور رو ندارن و نمیتونم فقط برای یک هسته‌ی خاص فیچر اضافه کنم.

**Comment by bia-pain-bache** [comment]
متاسفانه نمیتونم فیچری اضافه کنم که روی دو هسته از ۳ هسته کار میکنه، یوزر سردرگم میشه و طبق تجربه من باید اینجا پاسخگو باشم که واقعا فرصتشو ندارم. قسمت custom rules در آپدیت جدید اضافه میشه که میتونید دستی دامنه یا ip اضافه کنید.
