### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by Siavash1291** [bia-pain-bache/BPB-Worker-Panel#486]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

هنوز مشکل کرش کردن اپ ها با بی پی بی حل نشده متاسفانه. طبق تحقیقی هم که کردم عده ی زیادی این مشکل رو دارن. رو بعضی دیوایس ها هم این مشکل وجود نداره ظاهراً. هر ترفندی هم که میزنیم جواب نمیده متأسفانه

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Just run bpb sub on any app

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

**Comment by Siavash1291** [comment]
من خودم همین مشکل رو روی اندروید ۱۲ خام دارم. ولی اهدا کردم به یکی از دوستان که اندروید ۱۴ سامسونگ داره میگه هیچ مشکلی ندارم و خیلی راضی هست. اما با تحقیقی که تو گروه ها انجام دادم دیدم خیلی ها این مشکل رو دارن. مشکل هم روی هیدیفای و سینگ باکس هست

**Comment by developer861** [comment]
> من خودم همین مشکل رو روی اندروید ۱۲ خام دارم. ولی اهدا کردم به یکی از دوستان که اندروید ۱۴ سامسونگ داره میگه هیچ مشکلی ندارم و خیلی راضی هست. اما با تحقیقی که تو گروه ها انجام دادم دیدم خیلی ها این مشکل رو دارن. مشکل هم روی هیدیفای و سینگ باکس هست. در حالی که با فیلترشکن های دیگه مثل وینداسکرایب همچین مشکلی وجود نداره

احتمالا از آخرین نسخه هیدیفای استفاده میکنید که خیلی باگ داره میتونید از کلاینت های دیگه مثل v2rayng استفاده کنید یا از نسخه 2.05 هیدیفای استفاده کنید
