### ISSUE TITLE
Ability to import clean ip from list

### ISSUE THREAD

**Issue by Graveyard9988** [bia-pain-bache/BPB-Worker-Panel#487]
### Feature description | توضیحات ویژگی

درود

امکان دریافت آیپی تمیز از فرمت های

https://github.com/RododoIsHere/cf-clean-ips/blob/main/list.json
و

https://github.com/NiREvil/Harmony/blob/main/cf-clean.json

و با قابلیت تفکیک برای هر اپراتور (اگر در فرمت ایمپورت شده، اسم اپراتور قید شده باشد ، مثل لینک اول)

سپاس

**Comment by bia-pain-bache** [comment]
سلام، روش دقیق برای هر اپراتور تست لوکال هست که در ورژن جدید یه اسکنر دقیق اصافه شده، حتی منطقه به منطقه هم متفاوته، بنابراین این کار توجیهی نداره، باید لوکال تحت شبکه‌ی خودتون تست کنید.

**Comment by bia-pain-bache** [comment]
خواهش میکنم، ورژن جدید منظورم ۲.۷.۳ بود که در حال تسته هنوز. به زودی منتشر میشه.
