### ISSUE TITLE
scan and test a list of proxy IPs

### ISSUE THREAD

**Issue by Airuop** [bia-pain-bache/BPB-Worker-Panel#488]
### Feature description | توضیحات ویژگی

Hi. Please add a text field for importing a list of proxy IPs and the ability to scan and test a list of proxy IPs that we import into the Panel.

**Comment by Airuop** [comment]
> Hi, Multi proxy ips is added in 2.7.3, you can test pre-release. Also a server is deployed to test default proxy ips every 30 minutes, but it's not possible to fully test custom ips in panel. So you can choose one of ips from default proxy ips.

Version 2.7.1 works fine in pages, but version 2.7.2 and 2.7.3 do not work after being deployed in a page.
So I used 2.7.1 and I cannot upgrade.

**Comment by bia-pain-bache** [comment]
Because it's not released yet, you test by workers.

**Comment by Airuop** [comment]
> Because it's not released yet, you test by workers.

In the release description, can you add say deploy in  pages or workers for help us ?

**Comment by bia-pain-bache** [comment]
The version is obvious from repository main page image. Also links in tutorials are always pointing to stable releases, and I announce releases in my X account. Sorry but i can't document everything, it will be a book that way.
