### ISSUE TITLE
Add Sublink Problem In Hiddify And V2Box

### ISSUE THREAD

**Issue by hosseinit1988** [bia-pain-bache/BPB-Worker-Panel#490]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با درود و احترام
عرض ادب و خسته نباشید
مشکل لینک ساب روی نرم افزار های هیدیفای و  V2box بر روی گوشی آیفون داشتم.نسخه 2.7.1 این مشکل وجود نداره و به راحتی لینک ساب اضافه میشه و کانفیگ ها مشاهده می شود.
با تشکر
موفق و موید باشید

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

Add Config With QRCode in Hiddify and v2box App On iphone

### Relevant log output | لاگ برنامه یا پنل

```shell
error
```

**Comment by bia-pain-bache** [comment]
سلام، سلامت باشید.
بله مشکل داشت گزارش دادن دوباره ۲.۷.۳ رو آپدیت کردم. الان تست کنید نباید مشکلی باشه.
