### ISSUE TITLE
Privacy Error

### ISSUE THREAD

**Issue by hosseinc** [bia-pain-bache/BPB-Worker-Panel#491]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام
خیلی از اوقات این اتفاق میفته و لزوما همیشه با گوگل نیست.
![9 png](https://github.com/user-attachments/assets/1d90435a-0559-40e0-88f6-961cb4413305)

و با یکبار رفرش کردن پیج اوکی میشه. آیا مشکل از کد هست یا مشکلی در مرورگر؟

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

**Comment by bia-pain-bache** [comment]
سلام،
برای دامنه‌های گوگل این اتفاق افتاده؟
ممکنه به خیلی عوامل مربوط باشه مثل Proxy IP یا block ads و ... با تنظیمات پیشفرض پنل تست کنید ببینید چنین مشکلی هست یا نه. ترجیحا یه Proxy IP تمیز هم بذارید.

**Comment by hosseinc** [comment]
نه برای سایت‌های دیگه این اتفاق میفته

ممنون

**Comment by bia-pain-bache** [comment]
اگر برای سایت‌های دیگه هست مربوط به Proxy IP میشه. یه تمیزشو باید انتخاب کنید.
