### ISSUE TITLE
failed to start v2rayng when i use fragment  json config

### ISSUE THREAD

**Issue by hadiaghajani** [bia-pain-bache/BPB-Worker-Panel#5]
in log
infra/conf/serial: failed to parse json config > infra/conf: failed to parse DNS config > infra/conf:failed to build nameserver > infra/conf: invalid domain rule: geosite:category-ir > infra/conf: failed to load  geosite: CATEGORY-IR > infra/conf: list not found in geosite.dat: CATEGORY-IR

when i edited config and remove these lines :
"geosite:category-ads-ir":"127.0.0.1"  in hosts
"geosite:category-ir" in servers
"geosite:category-ir" in routing > domain
"geosite:category-ads-ir" end of config 
problem solved

sorry for bad english

**Comment by bia-pain-bache** [comment]
No problem, Please update geo assets regarding instructions.
