### ISSUE TITLE
مشکل با سایتهای پشت کلودفلر و ثابت نشدن ای پی 

### ISSUE THREAD

**Issue by zendesher** [bia-pain-bache/BPB-Worker-Panel#50]
سلام و تشکر از زحمتی که میکشین.
بسیار عالی و کار راه اندازه. 
چنتا مشکل دیدم با روش pages
1-سایتای پشت کلودفلر بازنمیشن 
2-هر نوع کانفیگی برای چین پراکسی وارد کردم ای پی پروکسی رو نگرفت و ای پی با هر اتصال عوض شد.
3- برای ثابت کردن ای پی با گذاشتن ای پی کار نمیکنه و ثابت نمیشه و دومرتبه با هر اتصال عوض میشه ای پی

**Comment by bia-pain-bache** [comment]
سلام ممنون، بخاطر اینه که آموزش رو مطالعه نمیکنید:
1- در تنظیمات remote DNS رو به این شکل بذار:
https://8.8.8.8/dns-query

2- چین پروکسی فقط رو کانفیگ فرگمنت اعمال میشه، بعدش باید ساب رو هم آپدیت کنی.
3- IP Proxy منظورته؟

**Comment by zendesher** [comment]
ممنون از پاسختون
1-2 رو چک میکنم حتما
3- بله مثلا 
IPv4: 104.28.212.150 Türkiye Cloudflare, Inc.
رو گذاشتم اما بازم ای پی متغیر میگیره !

**Comment by bia-pain-bache** [comment]
داری ip تمیز رو میذاری داخل Proxy IP! این دو تا متفاوتن. لطفا آموزش راه‌اندازی قسمت proxy ip رو مطالعه کن.

**Comment by zendesher** [comment]
خب من میخوام ای پی کلود فلر ترکیه بگیره ! مگه مباید ای پی کلود فلر ترکیه بذارم ؟

**Comment by sahar-km** [comment]
> خب من میخوام ای پی کلود فلر ترکیه بگیره ! مگه مباید ای پی کلود فلر ترکیه بذارم ؟ توی اون لیست پراکی ای پی ترکیه ندیدم من ! همچین کاری میشه انحام داد ؟ ضمن اینکه از پراکسی آی پی های اون لیستم میذارم اما دومرتبه بصورت رندوم انتخاب میکنه با وحود دپلوی محدد بعد از اعمال تغییرات !

سلام وقت بخیر، با اجازه دوستمون میخواستم بگم من از [:::اینجا:::](https://github.com/NiREvil/vless/blob/main/sub/ProxyIP.md) که برای یکی از آشناها هست برمیدارم پروکسی آی‌پی، از همین روش bpb پیدا میکنن میذارن ولی خب تست میکنن چندروز یکبار چندتا قرار میدن تو این صفحه، میتونی سر بزنی، اتفاقا ترکیه هم بود به چشمم خورده

**Comment by zendesher** [comment]
> > خب من میخوام ای پی کلود فلر ترکیه بگیره ! مگه مباید ای پی کلود فلر ترکیه بذارم ؟ توی اون لیست پراکی ای پی ترکیه ندیدم من ! همچین کاری میشه انحام داد ؟ ضمن اینکه از پراکسی آی پی های اون لیستم میذارم اما دومرتبه بصورت رندوم انتخاب میکنه با وحود دپلوی محدد بعد از اعمال تغییرات !
> 
> سلام وقت بخیر، با اجازه دوستمون میخواستم بگم من از [:::اینجا:::](https://github.com/NiREvil/vless/blob/main/sub/ProxyIP.md) که برای یکی از آشناها هست برمیدارم پروکسی آی‌پی، از همین روش bpb پیدا میکنن میذارن ولی خب تست میکنن چندروز یکبار چندتا قرار میدن تو این صفحه، میتونی سر بزنی، اتفاقا ترکیه هم بود به چشمم خورده

ممنون ازتون امتحان کردین با دپلوی روی پیجز ثابت شد ای پی ؟

**Comment by zendesher** [comment]
چک کردم متاسفانه ثابت نشدن ای پی کماکان هستش !

**Comment by sahar-km** [comment]
> چک کردم متاسفانه ثابت نشدن ای پی کماکان هستش !

من اصلا متوجه منظورتون از بازت ثابت نشدن آی‌پی نمیشم، اصلا نمیدونم کجا تست میگیرین که بهتون آی‌پی های رندوم نشون میده، بله من آی‌پی ثابت دارم همیشه، یه وورکر دارم پروکسی آی‌پی آلمان میذارم همیشه داخلش و یک پیج دارم با متغیر PROXYIP براش یه پروکسی آی‌پی آمریکا گذاشتم و دوماهه همونه، سایت های پشت کلادفلر هم باز میشن به راحتی، تنها در صورتی اینا رندوم میشن که از دامین ها استفاده کنی، دامین‌هایی مثل `ipdb.rr.nu` یا`cdn-all.xn--b6gac.eu.org` که بهشون کلی آی‌پی فوروارد شده از اینا استفاده کنیم بله رندوم میشه بعد هر بار کانکت دیسکانکت کردن، لوکیشن اکثر نودهای کلادفلر آلمان هستش یعنی فک کنم کلا آلمان باشه تاحالا جای دیگه به چشمم نخورده، بهتره به نظرم ماهم پروکسی آی‌پی آلمان بذاریم یدونه یا دوتا، من از سایت چک هاست چک میکنم و سایت whoer.net و امثال ip.sb و browserleaks.com/ip و ....
واقعا ایده دیگه ای ندارم درباره سوال شما، امیدوارم مشکلتون حل بشه، موفق باشید

**Comment by zendesher** [comment]
> > چک کردم متاسفانه ثابت نشدن ای پی کماکان هستش !
> 
> من اصلا متوجه منظورتون از ثابت نشدن آی‌پی نمیشم، اصلا نمی‌دونم کجا تست میگیرین که بهتون آی‌پی‌های رندوم نشون میده، بله من آی‌پی ثابت دارم همیشه، یه وورکر دارم پروکسی آی‌پی آلمان میذارم داخلش و یک پیج دارم با متغیر `PROXYIP` یه پروکسی آی‌پی آمریکا گذاشتم و دوماهه همونه، سایت های پشت کلادفلر هم باز میشن به راحتی، تنها در صورتی اینا رندوم میشن که از دامین ها استفاده کنی، دامین‌هایی مثل `ipdb.rr.nu` یا`cdn-all.xn--b6gac.eu.org` که بهشون کلی آی‌پی فوروارد شده از اینا استفاده کنیم بله رندوم میشه بعد هر بار کانکت دیسکانکت کردن، لوکیشن اکثر نودهای کلادفلر آلمان هستش یعنی فک کنم کلا آلمان باشه تاحالا جای دیگه به چشمم نخورده، به نظرم بهتره ماهم پروکسی آی‌پی آلمان بذاریم یدونه یا دوتا، من از سایت چک هاست چک میکنم و سایت whoer.net و امثال ip.sb و browserleaks.com/ip و .... واقعا ایده دیگه ای ندارم درباره سوال شما، امیدوارم مشکلتون حل بشه، موفق باشید

سلام و ممنون از توضیحتون من از ورکر استفاده نمیکنم و روی pagesکلادفلر انجام دادم bpbرو دوتا environmet variable اد کردم برای uuid و proxyip به این ترتیب
![IMG_20240502_060615](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/91010383/e273d7a9-45bf-4ffe-bd29-4b3cbb44a9b5)
و ممکنه با ورکر درست کار کنه ولی روی pages که نتونستم آی پی ثابت بگیرم! ممنون از توضیحتون

**Comment by emisemok** [comment]
![Screenshot_۲۰۲۴۰۵۰۷-۰۱۳۰۱۱_Chrome](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/162907498/858176ad-576f-4b9d-bde9-2c64fd3bdaf8)
تنها در صورتی ک اون کادر چین پراکسی کانفیگ ویلس کشور خاصی رو قرار بدین ای پی ثابت رو بهتون میده

**Comment by zendesher** [comment]
> ![Screenshot_۲۰۲۴۰۵۰۷-۰۱۳۰۱۱_Chrome](https://private-user-images.githubusercontent.com/162907498/328329854-858176ad-576f-4b9d-bde9-2c64fd3bdaf8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzI3MjAsIm5iZiI6MTcxNTA3MjQyMCwicGF0aCI6Ii8xNjI5MDc0OTgvMzI4MzI5ODU0LTg1ODE3NmFkLTU3NmYtNGI5ZC1iZGU5LTJjNjRmZDNiZGFmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwOTAwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDgxYWUxY2ZhYTdjOTY0NTNkN2VkYWY1NmYyYTViMTEzZTgwNTExOTdkYjE1ZGQ0ZTNhODRlNmI3OTJhYmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4-vAzl-Oc54aM6H6ZQWmausvIp_COIOv7SmHRlWRJUg) تنها در صورتی ک اون کادر چین پراکسی کانفیگ ویلس کشور خاصی رو قرار بدین ای پی ثابت رو بهتون میده

کانفیگ ویلس ساده هم گذاشتم داخل chain proxy ولی بازم آی پی اون کانفیگ ویلس رو روی normal sub نمیگیرم ؟! 
از ساب fragment هم نتونستم نتیجه بگیرم 
Service failure
میده و وصل نمیشه !

**Comment by bia-pain-bache** [comment]
من بالاتر نوشتم لطفا آموزش رو مطالعه کنید ولی ظاهرا بی‌فایده بود!
استفاده از Chain Proxy فقط روی کانفیگای فرگمنت اتفاق میافته، بعد از اعمالش هم باید ساب فرگمنت رو آپدیت کنید.
اگر کانفیگ فرگمنت وصل نمیشه باید Geo assets رو آپدیت کنید یا اینکه قسمت Routing پنل رو کلا غیر فعال کنید.
