### ISSUE TITLE
https://bpb-worker-panel-a4w.pages.dev/  page can't open  

### ISSUE THREAD

**Issue by yangsc6** [bia-pain-bache/BPB-Worker-Panel#503]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Sorry, you have been blocked
You are unable to access bpb-worker-panel-a4w.pages.dev

### Relevant log output | لاگ برنامه یا پنل

```shell
Sorry, you have been blocked
You are unable to access bpb-worker-panel-a4w.pages.dev
```

### Panel version | نسخه‌ی پنل

Sorry, you have been blocked
You are unable to access bpb-worker-panel-a4w.pages.dev

**Comment by yangsc6** [comment]
![Uploading 微信截图_20241125093229.png…]()

**Comment by shulng** [comment]
Redeploy Workers or Pages

**Comment by yangsc6** [comment]
^_^

**Comment by beidao349** [comment]
我的也打不开了

**Comment by fgr178707** [comment]
+1 
![image](https://github.com/user-attachments/assets/b44e919d-2a95-4fe6-bf99-f33a2feab97e)

**Comment by whiskey0705** [comment]
> Redeploy Workers or Pages

redeploy cant solve the issue

**Comment by shulng** [comment]
> > Redeploy Workers or Pages
> 
> redeploy cant solve the issue 

![Screenshot_2024_1125_093203.png](https://github.com/user-attachments/assets/23400802-d653-4137-8b65-28811adf5cbd)

Change this to another name and try

**Comment by beidao349** [comment]
删除后，重新部署，可以解决

**Comment by whiskey0705** [comment]
> > > Redeploy Workers or Pages
> > 
> > 
> > redeploy cant solve the issue
> 
> ![Screenshot_2024_1125_093203.png](https://private-user-images.githubusercontent.com/132723284/389338534-23400802-d653-4137-8b65-28811adf5cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTk4OTEsIm5iZiI6MTczMjQ5OTU5MSwicGF0aCI6Ii8xMzI3MjMyODQvMzg5MzM4NTM0LTIzNDAwODAyLWQ2NTMtNDEzNy04YjY1LTI4ODExYWRmNWNiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwMTUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTkxZDhhZjU0MzJjMGIyMjE4YTdhOGQyOTBmMmE2NGM5Y2Y5ZGEwZTI5MGJmNjZmYjBhMjcxMmU3MzJkOWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zxzqhc8cTcyqcP7SDsEKbpY05BgKOF4WRdjGcuE8hkE)
> 
> Change this to another name and try

I changed the name but still not working.

**Comment by fgr178707** [comment]
之前部署的删除 然后项目命名那重新命个名 就好了
Delete the previous deployment, rename the project, and rebind the domain.

**Comment by fgr178707** [comment]
> I changed the name but still not working.

Then there's still a problem with the name. It's better not to have bpb in it.

**Comment by zero-hugo** [comment]
不行啊，删除了重新部署，项目名也改了，还是被禁止啊。

**Comment by shulng** [comment]
> 不行啊，删除了重新部署，项目名也改了，还是被禁止啊。

改成其他名字

**Comment by zhd-love** [comment]
项目名称中不要出现 "bpb"。

**Comment by zero-hugo** [comment]
> 项目名称中不要出现 "bpb"。

删除项目重新部署，然后项目名改了个完全不相干的名字，还是不行欸。用网友提供的混淆worker.js代码的方法，也不行，不知道是不是我哪里操作错了。你们都能用了吗？

**Comment by shulng** [comment]
> > 项目名称中不要出现 "bpb"。
> 
> 删除项目重新部署，然后项目名改了个完全不相干的名字，还是不行欸。用网友提供的混淆worker.js代码的方法，也不行，不知道是不是我哪里操作错了。你们都能用了吗？

能用，并且都没问题我尝试拿一个新账号，复现你这个问题，但是没有出现你这个问题

**Comment by bia-pain-bache** [comment]
Updated 2.7.5 right now. Apparently this project is being reported! 
There are tips:

1- update now and if issue persists, delete project and deploy new one. (for pages deployments, avoid using `bpb` keyword in project name).
2- if still blocked, create new github and cloudflare account using a valid Email like Gmail, not fake mail or temporary mail.

**Comment by Acer-bdog** [comment]
> Updated 2.7.5 right now. Apparently this project is being reported! There are tips:
> 
> 1- update now and if issue persists, delete project and deploy new one. (for pages deployments, avoid using `bpb` keyword in project name). 2- if still blocked, create new github and cloudflare account using a valid Email like Gmail, not fake mail or temporary mail.

我删除重新部署，项目改为tshop,manse,还是1101错误，换另外一个账号，同样1101，最后重新注册一个账号，Download 成zip文件上传部署，还是1101，没法子了，┭┮﹏┭┮

**Comment by shulng** [comment]
> > Updated 2.7.5 right now. Apparently this project is being reported! There are tips:
> > 1- update now and if issue persists, delete project and deploy new one. (for pages deployments, avoid using `bpb` keyword in project name). 2- if still blocked, create new github and cloudflare account using a valid Email like Gmail, not fake mail or temporary mail.
> 
> 我删除重新部署，项目改为tshop,manse,还是1101错误，换另外一个账号，同样1101，最后重新注册一个账号，Download 成zip文件上传部署，还是1101，没法子了，┭┮﹏┭┮

如果Pages不行的话，你试试Workers部署
