### ISSUE TITLE
مشکل در اتصال فرگمنت

### ISSUE THREAD

**Issue by techjoyment** [bia-pain-bache/BPB-Worker-Panel#51]
کانفیگ‌های فرگمنت متصل نمیشن. ورژن V2rayN ویندوز روی ۶.۴۳ هست. جئو فایل هم آپدیت شدن. تنظیمات خاص دیگری نیاز هست؟

**Comment by bia-pain-bache** [comment]
نه. باید لاگ v2rayN رو اینجا بذاری

**Comment by techjoyment** [comment]
2024/05/05 21:51:51 [Error] app/dns: failed to retrieve response for clients2.google.com. > Post "https://8.8.8.8/dns-query": context deadline exceeded
2024/05/05 21:51:51 [Error] app/dns: failed to retrieve response for clients2.google.com. > Post "https://8.8.8.8/dns-query": context deadline exceeded

با dns پیشفرض هم همین مشکل رو داره

**Comment by bia-pain-bache** [comment]
نمیدونم شاید DNS سیستمت تغییر کرده. با کانفیگای نرمالم همینه؟

**Comment by leohaghighi** [comment]
من هم همین مشکل رو دارم هرکاری میکنم با proxy chain وصل نمیشه. با دی ان اس های مختلف پراکسی های مختلف چک کردم، نرمال و فرگمنت خوب کار میکنن ولی هر پراکسی چین ای وارد میکنم از کار میوفته کلن کانفیگار فرگمنت.
با streisand هم همین مساله هست
2024/05/06 02:13:26 [Error] app/dns: failed to retrieve response for web.whatsapp.com. > Post "https://8.8.8.8/dns-query": context deadline exceeded
2024/05/06 02:13:26 [Error] app/dns: failed to retrieve response for web.whatsapp.com. > Post "https://8.8.8.8/dns-query": context deadline exceeded

**Comment by techjoyment** [comment]
من هم proxy chainوارد کردم ولی بدون اون هم همین مشکل هست.

**Comment by bia-pain-bache** [comment]
به خیلی فاکتور ربط داره مهمترینش اینکه کانفیگ سالم باشه و فرمتش استاندارد باشه. آپدیت جدید رو امتحان کنید، من نمیتونم بدون دیدن فرمت کانفیگ نظر بدم. تمام کانفیگ هایی که اعلام کردم رو با پنل xui ساختم و تست کردم.
