### ISSUE TITLE
 چطور کارمیکنه؟WorkerLess

### ISSUE THREAD

**Issue by MohammadGC** [bia-pain-bache/BPB-Worker-Panel#52]
سلام و خسته نباشید خدمت شما .
۱-ببخشید این WorkerLess چطور کار میکنه من با همه اوپراتور ها ازش تست گرفتم و پینگش خیلی عالی  هست و لی فقط روی همراه اول کار میکنه .
جریانش چیه؟
2- و یه سوال دیگه هم داشتم اونم اینه که  این چند روزه کلا سرعت اینترنت ها خیلی پایین اومده روی همه اوپراتورها  و این فرگمن ها  و کانفیگ های نرمال هم جواب گو نیست و خیلی پینگ ها بالا رفته چه با فرگمنت و چه کانفییگ های نرمال ولی روی اوپراتور مخابرات خیلی خوبه.
3- آیا راه حلی برای این مشکل به وجود آمده وجود دارد؟ . و این که آیا این پلن ضعیف شده یا کلا مشکل از خود اینترنت ها هست ؟
ممنون میشم راهنمایی کنید.

**Comment by emisemok** [comment]
اون ورکلس ای پی ایرانه ی چیز تو مایه های وارپ کلا استفاده نکنی امن تره
بعدشم وقتی ک از سمت اپراتور نت جون نداره چ با و چ بی فرگمنت راهکاری نداره

**Comment by MohammadGC** [comment]
ممنون از راهنمایی ها خیلی متشکرم.

**Comment by bia-pain-bache** [comment]
این کانفیگ رو برای کارایی مثل یوتیوب دیدن و وبگردی استفاده کن عالیه. برای کارای حساس یا امنیتی توصیه نمیشه اصلا. روی نت‌های مختلف مقادیر فرگمنت خودشو میخواد. روی ایرانسل ممکنه خوب کار نکنه.
