### ISSUE TITLE
Ip6

### ISSUE THREAD

**Issue by mabna2** [bia-pain-bache/BPB-Worker-Panel#55]
تو برنامه نمیشه ای پی ۶ بذاریم؟ من نتونستم سرعت بهتری داره نسبت به ۴ چطوری میشه اضافه کرد ممنونم

**Comment by bia-pain-bache** [comment]
کانفیگ IPv6 خودش پیشفرض میده دو تا نیازی نیست.

**Comment by lyd123qw2008** [comment]
我测试了，不支持访问 ipv6 的网站，不知是否可以优化

**Comment by Mikael1993** [comment]
> کانفیگ IPv6 خودش پیشفرض میده دو تا نیازی نیست.

من یک issues باز کردم درباره این که ایا میشه رنج ای پی از یک کشور خاص رو بتونیم دریافت کنیم و هربار وقتی ای پی عوض شد از یک کشور ای پی رو بهمون بده ولی متاسفانه حذف شد

ایا شدنی هست؟

**Comment by mabna2** [comment]
> کانفیگ IPv6 خودش پیشفرض میده دو تا نیازی نیست.

میدونم میده ولی میخوام بیشتر بذارم برای سرعتش با کد وارپ میتونم اضافه کنم تست کردم از دیروز شد ولی میخوام با پنل اضافه کنم نتونستم

**Comment by mabna2** [comment]
> کانفیگ IPv6 خودش پیشفرض میده دو تا نیازی نیست.

اونجا که نوشته Chain Proxy از اون میتونی استفاده کنی کد وی لس یا وی ام اس بذار اونجا از ای پی ثابت استفاده میکنه

**Comment by mabna2** [comment]
> 我测试了，不支持访问 ipv6 的网站，不知是否可以优化

您可以在 Hiddify 中使用 ip 6，但在其他程序中它很慢且不稳定，使用 warp 代码，它可以轻松连接，使用 ip 6 而不是 ip 4

**Comment by lyd123qw2008** [comment]
> > 我测试了，不支持访问 ipv6 的网站，不知是否可以优化
> 
> 您可以在 Hiddify 中使用 ip 6，但在其他程序中它很慢且不稳定，使用 warp 代码，它可以轻松连接，使用 ip 6 而不是 ip 4

感谢答复
