### ISSUE TITLE
فعلا منتظرم ببینم آیا مشکل ۱۱۰۱ رو حل کردم یا نه امروز نتیجه رو میگم

### ISSUE THREAD

**Issue by hamedp-71** [bia-pain-bache/BPB-Worker-Panel#554]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام ، تا الان که قطع نشده پنل و نرفته به ارور ۱۱۰۱ و هیچ حساسیتی به رگوست نداشته این رو اول بگم بالای ۱۰۰ هزارتا رو رد کرده و قطع نشده ، خب اسم رو یک چیز دیگر گذاشتم مثل روزهای قبل ، دیشب و حتی امروز صبح برای اطمینان رمز تروجان رو تغییر دادم ، برای اطمینان بیشتر کد ورکر رو هم یک بار تبدیل کردم و جایگزین کردم ، اینم بگم این کارها و برای ۳ تا پیجس مختلف انجام دادم روی هر کدوم یک کار انجام دادم ، یعنی همه کارها رو روی یکی انجام ندادم مثلاً رمز تروجان رو روی یکی فقط عوض کردم و کد ورکر یکی دیگشون رو تغییر دادم و همینطوری فعلا منتظرم ببینم قطع میشن یا نه .

اگر قطع نشد میتونم بگم که چیکار کنید و راه کارش خیلی ساده هست و نیازی به این کارهایی ک انجام دادم یا می‌دین نداره . حتی یکی از دوستان هم امروز اشاره کردن به اون راه کاری ک می‌خوام بگم .

خلاصه منتظر این یکی دو ساعت تا ظهر هستم این ساعات سرنوشت ساز هست برای من همه 😁😁

### Relevant log output | لاگ برنامه یا پنل

```shell
راهکار رفع ارور ۱۱۰۱ کلودفلر
```

### Panel version | نسخه‌ی پنل

۲.۷.۶ و ۲.۷.۵

**Comment by hamedp-71** [comment]
> ما منتظریم

انگار حل هست . فقط جهت اطمینان میخوام یکم بیشتر کار کنه تا کامل بتونم بگم حلش کردم و بگم چیه ولی خیلی آسون هست و یکی دو گزارش قبل من هم یک نفر بهش اشاره کرده خیلی کوتاه . مشکل رو هم از داخل گیتهاب باید حل کرد ن کلودفلر . اما کلودفلر اون رو از گیتهاب شناسایی میکنه و مانع میشه .

**Comment by aghacooleri** [comment]
مرسی حامد جان

**Comment by Mahdi-SEi** [comment]
اگر امکانش هست میشه این راه حل رو تو یه جایی حدودی بگی چون من این چند ساعتی که امروز صبح همه ی اکانت های گیتهاب و کلودفلر باهم از کار افتادن همه ی ورژن ها و شدیدا نیاز دارم بهش الان

**Comment by liMilCo** [comment]
برای من هم هنوز داره کار میکنه ...
نکته جالب اینجاست که من 2 تا اکانت داشتم از اول پروژه bpb باهاشون کار میکردم و تا همین دیشب هم مشکلی نداشتن ، دقیقا وقتی که شروع کردم تحقیق روی این مشکل با یه اکانت دیگه (هم گیتهاب هم کلود) کلا با یک کامپیوتر دیگه، اون دوتا پیج هم بسته شدن ، چشمم کردن ...
مشکل اینه که کلودفلر دوره ای کد ها رو برای ویروس اسکن میکنه و مثلا کد ورژن 2.7.6 رو شناسایی کرده و همه کسانی که از این کد استفاده میکنن رو میبنده ...
هرکسی باید کد خودشو داشته باشه = خودش کد رو درهم کنه ...

**Comment by liMilCo** [comment]
اگر وقت کردم این تغیرات روی کد ورژن 2.7.4 که خوب کار میکنه میدم
اول نام bpb در kv تغییر داده بشه
بجای speadtest یه سایت دیگه بالا بیاد (یا حتی بشه تو تنظیمات هر کسی تغییر بده)
بجای /panel و  /login و  /sub یه کلمه دیگه جایگزین بشه

**Comment by Ali-aga-AA** [comment]
لطفا سریع تر ارائه بدید تا ما هم تست کنیم

**Comment by hamedp-71** [comment]
> لطفا سریع تر ارائه بدید تا ما هم تست کنیم

چشم حتما . اگر خواستین زودتر بفهمین میتونید به تلگرام بیاین تو پیوی بگم تست کنید .

**Comment by amir-zarandi** [comment]
درود ....

موردی که فرمودین درست بود؟ قطع نشده؟

**Comment by hamedp-71** [comment]
> درود ....
> 
> موردی که فرمودین درست بود؟ قطع نشده؟

بخاطر بار سنگین قطع شد . مشکل از ما نیست کلودفلر تصمیم گرفته جلوی CDN هایی که برای VPN استفاده میشند رو ببنده .

**Comment by amir-zarandi** [comment]
پس کلا کنسله قضیه

**Comment by amir-zarandi** [comment]
> > درود ....
> > موردی که فرمودین درست بود؟ قطع نشده؟
> 
> بخاطر بار سنگین قطع شد . مشکل از ما نیست کلودفلر تصمیم گرفته جلوی CDN هایی که برای VPN استفاده میشند رو ببنده .


پس کلا کنسله قضیه

**Comment by Ali-aga-AA** [comment]
> > > درود ....
> > > موردی که فرمودین درست بود؟ قطع نشده؟
> > 
> > 
> > بخاطر بار سنگین قطع شد . مشکل از ما نیست کلودفلر تصمیم گرفته جلوی CDN هایی که برای VPN استفاده میشند رو ببنده .
> 
> پس کلا کنسله قضیه

متاسفنه اینجوریه باید به دنبال راه های دیگه باشیم.....
