### ISSUE TITLE
اپ سینگ باکس

### ISSUE THREAD

**Issue by pichoko** [bia-pain-bache/BPB-Worker-Panel#555]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

برای ایمپورت کردن کانفینگ سینگ باکس داخل آخرین ورژن اپ مشکل وجود داره
![1B3F43DB-4196-412F-B611-A2B0AD72DA25](https://github.com/user-attachments/assets/41bd8fde-ea83-4eb9-befb-6b4a28fcb76b)

### Relevant log output | لاگ برنامه یا پنل

```shell
Pages
```

### Panel version | نسخه‌ی پنل

2.7.6

**Comment by pichoko** [comment]
ورژن سینگ باکس ۱.۱۰.۳ هست

**Comment by hamedp-71** [comment]
> ورژن سینگ باکس ۱.۱۰.۳ هست

من که تست کردم الان مشکلی نداشت برام 🤔

**Comment by pichoko** [comment]
پس فکر کنم باید پروژه رو پاک کنم دوباره نصب کنم

**Comment by hamedp-71** [comment]
> پس فکر کنم باید پروژه رو پاک کنم دوباره نصب کنم

میخوای تلگرام بهم پیام بده لینک بدم تست کن ببین برات کار می‌کنه یا نه ، آیدیم هست : hamedp71

**Comment by pichoko** [comment]
پیام گذاشتم برات
