### ISSUE TITLE
گزارش

### ISSUE THREAD

**Issue by coolnum1** [bia-pain-bache/BPB-Worker-Panel#557]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

درود من 5 تا اکانت هر کدام با UUID های متفاوت و تروجان پسورد های متفاوت داشتم همه بسته شده و ارور 1101 دریافت میکنند. در ضمن 3 تا ورژن قدیمی بودند و 2 تا دیگه ورژن جدید.همه با email های منحصر به فرد و متفاوت(برای افرادی که ساخته بودم بود ایمیل ها)

### Relevant log output | لاگ برنامه یا پنل

```shell
.
```

### Panel version | نسخه‌ی پنل

.

**Comment by hamedp-71** [comment]
> ### Attention | توجه
> * [x]  I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد
> 
> ### What Happened? | چه اتفاقی افتاده؟
> درود من 5 تا اکانت هر کدام با UUID های متفاوت و تروجان پسورد های متفاوت داشتم همه بسته شده و ارور 1101 دریافت میکنند. در ضمن 3 تا ورژن قدیمی بودند و 2 تا دیگه ورژن جدید.همه با email های منحصر به فرد و متفاوت(برای افرادی که ساخته بودم بود ایمیل ها)
> 
> ### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟
> _No response_
> 
> ### Relevant log output | لاگ برنامه یا پنل
> ```shell
> .
> ```
> 
> ### Panel version | نسخه‌ی پنل
> .

داداش یک هفته هست داریم باهاش میجنگیم بخون بقیه اونایی که گزارش کردن رو 😁 احتمالش هست امروز یک راه حل بگم ، فعلا برا من مشکلی پیش نیومده امروز ، اگر امروز کار کرد حلش کردم وگرنه می شما هنوز باید پیگیر بمونم

**Comment by coolnum1** [comment]
از اون 5 تا 3 تاش رو استفاده نمیکردن به کسایی که داده بودم(دیتا رد و بدل نمیشده) با این حال تا دیشب وصل میشدن  تا ساعت 3 صبح

**Comment by liMilCo** [comment]
مشکل از کلودفلر هست نه فیلترچی؛ مهم اینه که کلودفلر سرس کد رو داره و میتونه پروژه رو از داخل اسکن کنه ...

**Comment by hamedp-71** [comment]
> مشکل از کلودفلر هست نه فیلترچی؛ مهم اینه که کلودفلر سرس کد رو داره و میتونه پروژه رو از داخل اسکن کنه ...

چی بگم والا هنوز داره کار میکنه برام و بدون مشکل . منتظرم شب شد میگم چیکار کنید .

**Comment by Iranpress** [comment]
ظاهرا کلود فلر مشکل API داشته و دیشب رفعش کرده حالا این مشکل روی worker هست یا Pages اطلاعی ندارم من هم 4-5 تا اکانت داشتم که همشون این مشکل رو خوردن حتی با RollBack و نصب مجدد هم مشکل رفع نشده توی صفحه اصلی BPB گفته شده که اسم پروژه رو تغییر بدید اما تغییری حاصل نشده!

**Comment by hamedp-71** [comment]
> ظاهرا کلود فلر مشکل API داشته و دیشب رفعش کرده حالا این مشکل روی worker هست یا Pages اطلاعی ندارم من هم 4-5 تا اکانت داشتم که همشون این مشکل رو خوردن حتی با RollBack و نصب مجدد هم مشکل رفع نشده توی صفحه اصلی BPB گفته شده که اسم پروژه رو تغییر بدید اما تغییری حاصل نشده!

اون قسمت تغییر اسم پروژه رو میتونی بهم نشون بدی کجاس کجا نوشته با عرض معذرت البته . لینک مستقیم بذار نگاه کنم لطف میکنی برام .
