### ISSUE TITLE
مشکل در اتصال

### ISSUE THREAD

**Issue by ITheEqualizer** [bia-pain-bache/BPB-Worker-Panel#56]
زمانی که کانفیگ روی برنامه sing-box روی آیفون وارد میشه، خود به خود بعد از چند ثانیه قطع میشه.
این مورد به دلیل مشکل کانفیگ هستش یا برنامه؟

**Comment by bia-pain-bache** [comment]
ورژن برنامه رو چک کنید بالای 1.8.10 باشه. از طریق Worker دپلوی کردی یا Pages؟

**Comment by ITheEqualizer** [comment]
> ورژن برنامه رو چک کنید بالای 1.8.10 باشه. از طریق Worker دپلوی کردی یا Pages؟

آخرین ورژن یعنی 1.8.11 هستش و Worker.

**Comment by bia-pain-bache** [comment]
دامنه‌های ورکر اختلال دارن بعضی وقتا، چون فرگمنت هم نداره مشکل میشه. لطفا از Pages استفاده کن.
