### ISSUE TITLE
گزارش جامع حل ارور 1101

### ISSUE THREAD

**Issue by Ali-aga-AA** [bia-pain-bache/BPB-Worker-Panel#561]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

دوستان من همه راه هایی که تا الان 15:45 1403/09/08 ارائه کردین بودین (چه در خود همین قسمت ایشو ها و چه در گروه های دیگه) رو با اکانت های خودم و اکانت هایی که کاملا نو باز کردم با ایمیل های واقعی که خودم داشتم تست کردم فقط یکیشون جواب داد که اونم تغییر نام پروژه بود که فقط 2 ساعت دوام آورد و بعدش مجددا قطع شد.
من چند تا پیشنهاد دارم که ازتون میخوام تستش بکنین چون من اصلا وقت ندارم و نتیجه رو زیر همین ایشو بگید.
راه حل 1 (موقت) : تست کنید ببینید با فورک کردن نسخه های قبلی پروژه مثل نسخه 2.7.0  یا حتی نسخه 2.6.8 یا نسخه 2.6 مشکل درست میشه یا نه که به صورت موقت از اونا استفاده کنیم تا یه راه حل دائمی و درست و حسابی براش تست و پیدا کنیم.
یا حتی با obfuscation تست کنید نسخه های قبلی رو ببینید جواب میده یا نه.(همین مورد رو خودمم دارم الان تست میکنم ایده دیگه ای دارید تست و پیاده سازی کنید).
راه حل 2 (ممکنه به تغییر در کد نیاز باشه از برنامه نویسان عزیز درخواست کمک دارم) : تست کنید و ببینید خود همین کد یا با تغییرات توی کد میشه همین رو روی CDN های دیگه سوار و استفاده کرد؟
راه حل 3 : من احساس میکنم توی سطح های بیشتر obfuscation حتی خود low  و سطوح medium و high به دلیل اینکه کد خیلی پیچیده میشه از cpu time کلود فلر بالاتر میره از طرفی هم که پلن ما رایگان هست مزید بر علت، ازتون و مخصوصا برنامه نویسان چه ازاد و چه برنامه نویسان خود این پروژه زحمت بکشن و قسمت های مختلف رو جدا کنن.
منظورم اینه که بیایین و قسمت کانفیگ های BPB Normal , BPB Fragment , BPB Full Normal , BPB Warp , BPB Warp Pro رو به شکل یه پروژه جدا در بیارن و در صورتی که بازم با obfuscation از cpu time کلود فلر بالاتر رفت کلا قسمت GUI رو حذف کنید و فقط با استفاده از قسمت Variables خود pages بتونیم proxy ip  و ایپی تمیز و ... رو تنظیم کنیم در این صورت کد سبک میشه و میتونیم از سطوح obfuscation متوسط و بالا هم استفاده کنیم و به ارور 
Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit
بر نخوریم.
از یاری و زحمات همه شما و تیم bia pain bache متشکرم.

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

دیپلوی کردن اخرین نسخه پنل BPB  و مشاهده ارور 1101

### Relevant log output | لاگ برنامه یا پنل

```shell
Error 1101.
Worker threw expection.
```

### Panel version | نسخه‌ی پنل

2.7.0 و به بعد.

**Comment by Ali-aga-AA** [comment]
دوستان درسته خیلی دراز نوشتم و سرتون رو درد آوورم اما اینا رو تست کنید تا بتونیم موفق بشیم

**Comment by Ali-aga-AA** [comment]
خب الان با نسخه 2.7 به مشکل خوردم

**Comment by hamedp-71** [comment]
داداش من موفق شدم و به چند نفر هم گفتم تست کردن . امشب میگم همه حلش کنید

**Comment by Ali-aga-AA** [comment]
> داداش من موفق شدم و به چند نفر هم گفتم تست کردن . امشب میگم همه حلش کنید

اوکیه مرسی ازتون.
واقعا ولی یه سوال.
میشه همین پروژه رو روی یه CDN ریخت؟

**Comment by Ali-aga-AA** [comment]
ببخشید روی یه CDN دیگه

**Comment by Ali-aga-AA** [comment]
> > > داداش من موفق شدم و به چند نفر هم گفتم تست کردن . امشب میگم همه حلش کنید
> > 
> > 
> > اوکیه مرسی ازتون. واقعا ولی یه سوال. میشه همین پروژه رو روی یه CDN ریخت؟
> 
> اون رو باید از حرفه‌ای ها بپرسی من مبتدی هستم درحد ابتدایی .

مرسی

**Comment by hamedp-71** [comment]
> > > > داداش من موفق شدم و به چند نفر هم گفتم تست کردن . امشب میگم همه حلش کنید
> > > 
> > > 
> > > اوکیه مرسی ازتون. واقعا ولی یه سوال. میشه همین پروژه رو روی یه CDN ریخت؟
> > 
> > 
> > اون رو باید از حرفه‌ای ها بپرسی من مبتدی هستم درحد ابتدایی .
> 
> مرسی

آیدی تلگرامم هست : hamedp71 خواستی بیا بگم تست کن .

**Comment by RezaFKH** [comment]
بچه با دیپلوی مجدد به وسیبه ورکر و پیجز با ویرایش اسم هم حتی درست نمیشه.
یه نسخه 2.4.5 داشتم که بالا میاد از طریق ورکر اما کانفیگ هاش کار نمیکنن.

**Comment by liMilCo** [comment]
> بچه با دیپلوی مجدد به وسیبه ورکر و پیجز با ویرایش اسم هم حتی درست نمیشه. یه نسخه 2.4.5 داشتم که بالا میاد از طریق ورکر اما کانفیگ هاش کار نمیکنن.

تمام کد هایی که اینجا فورک شدن حتی اونایی که obfuscation شدن توی کلودفلر به عنوان ویروس شناسایی میشن و نسب کنی بند میشه ...
اگر خودت obfuscation کنی شاید کار کنه ...
 پروژه های ورژن قدیم مثل bpb26.pages.dev رو کلودفلر هنوز شناسایی نکرده و پنل بالا میاد اما کانفیگ کار نمیکنه ...

**Comment by Ali-aga-AA** [comment]
> > بچه با دیپلوی مجدد به وسیبه ورکر و پیجز با ویرایش اسم هم حتی درست نمیشه. یه نسخه 2.4.5 داشتم که بالا میاد از طریق ورکر اما کانفیگ هاش کار نمیکنن.
> 
> تمام کد هایی که اینجا فورک شدن حتی اونایی که obfuscation شدن توی کلودفلر به عنوان ویروس شناسایی میشن و نسب کنی بند میشه ... اگر خودت obfuscation کنی شاید کار کنه ... پروژه های ورژن قدیم مثل bpb26.pages.dev رو کلودفلر هنوز شناسایی نکرده و پنل بالا میاد اما کانفیگ کار نمیکنه ...

منم تونستم بالا بیارم اما کانفیگ هاش فقط ۲۴ ساعت کار کرد و بعد ۲۴ ساعت دیگه هم کلا بن شد.

**Comment by Ali-aga-AA** [comment]
> > ببخشید روی یه CDN دیگه
> 
> این خدمات رو فقط کلودفلر میده و مستقیما به CDN ربطی نداره ، خدماتی برای دولوپر ها هست... این BPB Normal , BPB Fragment , BPB Full Normal , BPB Warp , BPB Warp Pro ها پکیج های مخطلف نیستن. کانفیگ های مخطلف از یک پکیج هستن ، برنامه کمی سنگین شده ولی به نسبت کیفیتش هم بالا رفته ... اگربگردی پکیج های مشابه و خیلی خیلی ساده تری هم هستن که اونها هم دقیقا مثل پروژه bpb همشون بند شدن ...

اوکیه........
الان نمیشه به قول شما همین پروژه رو روی دولوپر های دیگه سوار کرد؟

**Comment by Ali-aga-AA** [comment]
دوستان یه چیزی.
تعدادی از دوستان توی ایشو های دیگه اظهار داشتن که یه اکانت داشتن که درست کار می کرده و بعد اینکه با یه دستگاه و اکانت دیگه همین پروژه رو دیپلوی می کردن اونی که سالم بود هم بن میشد.
منظورم اینه که شاید کلود فلر بر اساس آیپی و مکان داره پنل های BPB رو بن میکنه.
من که ندارم اما دوستانی که فیلترشکن با آیپی ثابت آمریکا یا آلمان تست کنند و با یک اکانت کلود فلر و گیت هاب که تازه ساختن با اون فیلترشکن که مکان رو تغییر داره تست کنند ببینن بالا میاد یا نه.
البته دقت کنند که هم اسم پروژه ای که توی گیت هاب فورک می‌کنند رو تغییر بدند هم اسم پروزه توی کلود فلر.

**Comment by liMilCo** [comment]
> پنل های BPB رو بن میکنه

دوستان فیلترچی ایران یا چین نیستن که اینقدر فعالانه دنبال ماجرا باشن، بن شدن اون اکانتهای دیگه شانسی بوده.
گلودفلر خیلی ساده کدهایی که داریم تو سرورش اجرا میکنیم رو چک میکنه، اگر ردی از کدهای فیلترشکنی پیدا کنه بن میکنه ...
یا اینکه اینقدر obfuscation سنگین اجرا میکنن که فشار زیادی به CPU میاره باز هم بن میکنه ...

**Comment by Ali-aga-AA** [comment]
> دوستان یه چیزی. تعدادی از دوستان توی ایشو های دیگه اظهار داشتن که یه اکانت داشتن که درست کار می کرده و بعد اینکه با یه دستگاه و اکانت دیگه همین پروژه رو دیپلوی می کردن اونی که سالم بود هم بن میشد. منظورم اینه که شاید کلود فلر بر اساس آیپی و مکان داره پنل های BPB رو بن میکنه. من که ندارم اما دوستانی که فیلترشکن با آیپی ثابت آمریکا یا آلمان تست کنند و با یک اکانت کلود فلر و گیت هاب که تازه ساختن با اون فیلترشکن که مکان رو تغییر داره تست کنند ببینن بالا میاد یا نه. البته دقت کنند که هم اسم پروژه ای که توی گیت هاب فورک می‌کنند رو تغییر بدند هم اسم پروزه توی کلود فلر. ممکنه کمی غیر عقلانی به نظر برسه اکا تست کنید ضرری نداره چون تعدادی از شواهد داره اینو نشون میده !!

دوستان لطفا اینو تست کنید.

**Comment by majidfrs** [comment]
> > دوستان یه چیزی. تعدادی از دوستان توی ایشو های دیگه اظهار داشتن که یه اکانت داشتن که درست کار می کرده و بعد اینکه با یه دستگاه و اکانت دیگه همین پروژه رو دیپلوی می کردن اونی که سالم بود هم بن میشد. منظورم اینه که شاید کلود فلر بر اساس آیپی و مکان داره پنل های BPB رو بن میکنه. من که ندارم اما دوستانی که فیلترشکن با آیپی ثابت آمریکا یا آلمان تست کنند و با یک اکانت کلود فلر و گیت هاب که تازه ساختن با اون فیلترشکن که مکان رو تغییر داره تست کنند ببینن بالا میاد یا نه. البته دقت کنند که هم اسم پروژه ای که توی گیت هاب فورک می‌کنند رو تغییر بدند هم اسم پروزه توی کلود فلر. ممکنه کمی غیر عقلانی به نظر برسه اکا تست کنید ضرری نداره چون تعدادی از شواهد داره اینو نشون میده !!
> 
> دوستان لطفا اینو تست کنید.
 
من تست کردم ولی نشد
اکانت تازه گیت انگار بسازی نمیزاره فورک کنی چیزی فکر کنم باید چند روز بگذره
ولی ورکر رو با اکانت تازه کلاد ساختم ارور داد
با آی پی آمریکا بود

نمیدونم کسی فکر کرده ممکنه بخاطر نام KV هم یاشه که اسمشو BPB باید گذاشت

**Comment by Ali-aga-AA** [comment]
> > > دوستان یه چیزی. تعدادی از دوستان توی ایشو های دیگه اظهار داشتن که یه اکانت داشتن که درست کار می کرده و بعد اینکه با یه دستگاه و اکانت دیگه همین پروژه رو دیپلوی می کردن اونی که سالم بود هم بن میشد. منظورم اینه که شاید کلود فلر بر اساس آیپی و مکان داره پنل های BPB رو بن میکنه. من که ندارم اما دوستانی که فیلترشکن با آیپی ثابت آمریکا یا آلمان تست کنند و با یک اکانت کلود فلر و گیت هاب که تازه ساختن با اون فیلترشکن که مکان رو تغییر داره تست کنند ببینن بالا میاد یا نه. البته دقت کنند که هم اسم پروژه ای که توی گیت هاب فورک می‌کنند رو تغییر بدند هم اسم پروزه توی کلود فلر. ممکنه کمی غیر عقلانی به نظر برسه اکا تست کنید ضرری نداره چون تعدادی از شواهد داره اینو نشون میده !!
> > 
> > 
> > دوستان لطفا اینو تست کنید.
> 
> من تست کردم ولی نشد اکانت تازه گیت انگار بسازی نمیزاره فورک کنی چیزی فکر کنم باید چند روز بگذره ولی ورکر رو با اکانت تازه کلاد ساختم ارور داد با آی پی آمریکا بود
> 
> نمیدونم کسی فکر کرده ممکنه بخاطر نام KV هم یاشه که اسمشو BPB باید گذاشت

خب شما یه حرکتی بی زحمت بزنید.
شما با همون آیپی آمریکا ورکر رو بسازید ولی هنوز kv رو تنظیم نکنید و ببینید بالا میاد یا نه.
چون kv نباشه پنل بالا میاد ولی تنظیمات سئو نمیشه و ارور میده.
شما kv رو تنظیم نکنید با آیپی آمریکا اگه بالا اومد یعنی مشکل از kv اگه نشد باید چیزای دیگه چک بشه.

**Comment by majidfrs** [comment]
> > > > دوستان یه چیزی. تعدادی از دوستان توی ایشو های دیگه اظهار داشتن که یه اکانت داشتن که درست کار می کرده و بعد اینکه با یه دستگاه و اکانت دیگه همین پروژه رو دیپلوی می کردن اونی که سالم بود هم بن میشد. منظورم اینه که شاید کلود فلر بر اساس آیپی و مکان داره پنل های BPB رو بن میکنه. من که ندارم اما دوستانی که فیلترشکن با آیپی ثابت آمریکا یا آلمان تست کنند و با یک اکانت کلود فلر و گیت هاب که تازه ساختن با اون فیلترشکن که مکان رو تغییر داره تست کنند ببینن بالا میاد یا نه. البته دقت کنند که هم اسم پروژه ای که توی گیت هاب فورک می‌کنند رو تغییر بدند هم اسم پروزه توی کلود فلر. ممکنه کمی غیر عقلانی به نظر برسه اکا تست کنید ضرری نداره چون تعدادی از شواهد داره اینو نشون میده !!
> > > 
> > > 
> > > دوستان لطفا اینو تست کنید.
> > 
> > 
> > من تست کردم ولی نشد اکانت تازه گیت انگار بسازی نمیزاره فورک کنی چیزی فکر کنم باید چند روز بگذره ولی ورکر رو با اکانت تازه کلاد ساختم ارور داد با آی پی آمریکا بود
> > نمیدونم کسی فکر کرده ممکنه بخاطر نام KV هم یاشه که اسمشو BPB باید گذاشت
> 
> خب شما یه حرکتی بی زحمت بزنید. شما با همون آیپی آمریکا ورکر رو بسازید ولی هنوز kv رو تنظیم نکنید و ببینید بالا میاد یا نه. چون kv نباشه پنل بالا میاد ولی تنظیمات سئو نمیشه و ارور میده. شما kv رو تنظیم نکنید با آیپی آمریکا اگه بالا اومد یعنی مشکل از kv اگه نشد باید چیزای دیگه چک بشه.

من اینم انجام دادم - kv ندادم بهش
تو همون صفحه که فایل آپلود میشه سمت راستش پیش نمایش داره - اون تو لودیمگ مونده
ویزیت سایت میزنی با اضافه کردن یا نکردن پنل 
این ارور رو میده
The connection for this site is not secure
sweet-sound-c9b9.qmh99285.workers.dev uses an unsupported protocol.
ارورهای مرتبط با کلاد نمیده مثل 1101
ولی وارد پنل هم نمیتونی بشی

**Comment by majidfrs** [comment]
خب بالاخره بعد چندین بار تلاش  - همون ارور رو دوباره داد و اینبار من kvنزده بودم
با وی پی ان هم بودم
شک من به این برای این بود یبار داشتم میساختم و تو پیشنمایش برعکس وضعیت های قبلش بنر bpb   رو نشون میداد
وقتی رفتم kv زدم ارور داد
ولی خب انگار بهش مربوط نبوده

**Comment by majidfrs** [comment]
اون شخص چینی که فورکش کرده مال اون کار میکنه - البته من چون وی پی ان ام روشن بود انجام دادم دیگه نمیدونم اصلا این مربوطه به قضیه یا نیست
ولی حداقل فعلا کار میکنه تو این 10 دقیقه ای که ساختم
با اکانت های خودم بودم تازه هم نبود پیچش رو ساختم
نمیدونم بعدا اینم بن میکنه کلاد یا نه
اون فورکی که کرده رو شما هم فورک کنید  اسمش یه چیز دیگه بزارید
و طبق روال معمول برید کلاد متصل کنید بسازید و وارد پنل بشید
https://github.com/lu-lingyun/BPB-Worker-Panel

**Comment by liMilCo** [comment]
## دوستان توجه کنید وقتی از پروژه ی دیگران فورک کنید یعنی همه دارین دقیقا از یک کد استفاده میکنید که وقتی چند نفر از اون کد استفاده میکنن کلودفلر شناسایی میکنه و همه رو میبنده ...
شما خودتون باید سرس کد اصلی رو بگیرین و obfuscation کنید ...

**Comment by Ali-aga-AA** [comment]
> اون شخص چینی که فورکش کرده مال اون کار میکنه - البته من چون وی پی ان ام روشن بود انجام دادم دیگه نمیدونم اصلا این مربوطه به قضیه یا نیست ولی حداقل فعلا کار میکنه تو این 10 دقیقه ای که ساختم با اکانت های خودم بودم تازه هم نبود پیچش رو ساختم نمیدونم بعدا اینم بن میکنه کلاد یا نه اون فورکی که کرده رو شما هم فورک کنید اسمش یه چیز دیگه بزارید و طبق روال معمول برید کلاد متصل کنید بسازید و وارد پنل بشید https://github.com/lu-lingyun/BPB-Worker-Panel

ممنون تستش میکنم

**Comment by Ali-aga-AA** [comment]
![Screenshot 2024-11-29 141927](https://github.com/user-attachments/assets/f29a42c6-98f6-4f96-8105-4ed8b3f3fcf1)
الانم مشکلی که پیش اومد اینجوری شد راهی براش دارید؟

**Comment by Ali-aga-AA** [comment]
فکر کنم چون همه فایل ها اپلود نشدن برای همینه

**Comment by liMilCo** [comment]
> فکر کنم چون همه فایل ها اپلود نشدن برای همینه

فقط فایل _worker.js مهمه بقیه فایل ها اضافه هستن ...

**Comment by Ali-aga-AA** [comment]
یعنی نیاز نیست clash.js  و بقیه فایل ها رو هم اپلود کنم؟

**Comment by Ali-aga-AA** [comment]
> > فکر کنم چون همه فایل ها اپلود نشدن برای همینه
> 
> فقط فایل _worker.js مهمه بقیه فایل ها اضافه هستن ...

پس چرا اونجوری شد؟

**Comment by Ali-aga-AA** [comment]
> > فکر کنم چون همه فایل ها اپلود نشدن برای همینه
> 
> فقط فایل _worker.js مهمه بقیه فایل ها اضافه هستن ...

الان همه فایل های پروژه رو اپلود کردم ولی بازم ارور تصویر بالا رو بهم داد.

**Comment by Ali-aga-AA** [comment]
بچه ها بالا اومد...............................
فقط کافیه که نسخه 2.7.4 رو بدون obfuscation توی قسمت pages به جای connect git گزینه upload assets رو بزنید و تمام.

**Comment by RezaFKH** [comment]
![image](https://github.com/user-attachments/assets/24d71228-b82c-49bf-871c-70a6783e36c9)

پروژه رو به صورت asset هم آپلود کردم و یک kv هم براش ساختم و دادم بهش ولی باز دوباره همون ارور 1101 رو میده و نمیاد بالا

**Comment by Ali-aga-AA** [comment]
> ![image](https://private-user-images.githubusercontent.com/75258272/391090936-24d71228-b82c-49bf-871c-70a6783e36c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4OTM5ODQsIm5iZiI6MTczMjg5MzY4NCwicGF0aCI6Ii83NTI1ODI3Mi8zOTEwOTA5MzYtMjRkNzEyMjgtYjgyYy00OWJmLTg3MWMtNzBhNjc4M2UzNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE1MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYmViZGNkZDAxY2E3NDMyYzhmY2M1ZTE5YmFkYzk5NmE1OTBkZGU4MzZhYjUzYWE0NDY0NTkxNWJhY2Y0NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4MVP9MWfFopxQVhtGeHPj_4vR5FcvYMxsNlmEvlpo2k)
> 
> پروژه رو به صورت asset هم آپلود کردم و یک kv هم براش ساختم و دادم بهش ولی باز دوباره همون ارور 1101 رو میده و نمیاد بالا

دوست عزیز اولا اینکه اسم پروژه داد میزنه !😐
دوما وقتی که پروژه رو باز کردین قسمت کامنت شده آخر کد رو بردارید و فایلworker.js _ رو obfuscation سطح متوسط یا medium بزنید.
ببینید اوکی میشه یا نه.
سوما بعد ساختن kv رو ست نکنین یه ۱۵ الی ۲۰ دقیقه صبر بکنید و دیدین که پنل بالا اومد و ارور kv داد،بعدش تنظیمات مربوط به رمز کانفیگ های تروجان،UUID و ... انجام بدید.
