### ISSUE TITLE
دوستان یک راه حل ساده میگم که واقعا کارساز هست

### ISSUE THREAD

**Issue by hamedp-71** [bia-pain-bache/BPB-Worker-Panel#586]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

این راه حل برای اونایی هست که تونستن وارد پنل بشن و هنوز ارور 1101 رو ندیدن .

خب باید یک DNS تهیه کنید و در قسمت Remote DNS داخل پنل بزارید و تمام .
کلیه ترافیکتون از اون dns عبور میکنه و کلودفلر نمیتونه دقیق شناسایی کنه و به این شکل شما میتونید از شر بسته شدن و ارور 1101 خلاص بشید .

فعلا با این راهکار من تونستم که بگم پنل هام بسته نشدن . چون داخل کلودفلر رگوستم رو خیلی پایین نشون میده و cpu خیلی کم درگیر میشه .

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1101 Error Fix

### Relevant log output | لاگ برنامه یا پنل

```shell
این راه حل برای اونایی هست که تونستن وارد پنل بشن و هنوز ارور 1101 رو ندیدن .

خب باید یک DNS تهیه کنید و در قسمت Remote DNS داخل پنل بزارید و تمام .
کلیه ترافیکتون از اون dns عبور میکنه و کلودفلر نمیتونه دقیق شناسایی کنه و به این شکل شما میتونید از شر بسته شدن و ارور 1101 خلاص بشید .
```

### Panel version | نسخه‌ی پنل

2.7.6

**Comment by Tigervpnorg** [comment]
سلام درورد یه سوال اگه از ورکر استفاده کنیم و دامنه خودمون رو ست کنیم 100 هزار درخواست رو رد کنه قطع میشه یا فعال میمونه؟

**Comment by hamedp-71** [comment]
> سلام درورد یه سوال اگه از ورکر استفاده کنیم و دامنه خودمون رو ست کنیم 100 هزار درخواست رو رد کنه قطع میشه یا فعال میمونه؟

فعال میمونه . بنظرم پیجس بساز تا بیشتر از 100 هزار تا رگوست رو هم بتونی استفاده کنی بدون دردسر . فعلا من رگوستم رسیده امروز به 1و نیم میلیون تا الان که ساعت 21:43 هست البته از ساعت 11 قبل از ظهر راه اندازیش کردم .

**Comment by hamedp-71** [comment]
دوستان اینم راه کار فعال موندن پیجس درکلودفلر . دیگه من حرف و حدیثی ندارم بگم . بازم میگگم اونایی که در باز کردن پنل مشکل ندارن و فقط بعد کارکردش دچار مشکل قطعی و ارور 1101 میشن میتونن با اومدن به تلگرام به آدرس آیدیم : hamedp71 اگر مشکل داشتن بپرسن و من راهنماییشون کنم . خلاصه وار میگم فعلا با همین روش کلودفلر خر شد و پنل بسته نمیشه حتی رکوئست شما بره بالای 100 .

**Comment by majidfrs** [comment]
سلام
از کدوم دی ان ای استفاده کنیم ؟ از همین دی ان اس های عمومی ؟ مثل دی ان اس گوگل؟
اصل قضیه رو مبهم گذاشتی که
