### ISSUE TITLE
مشکل در ست نشدن kv برای روش pages

### ISSUE THREAD

**Issue by DarkKingTNi** [bia-pain-bache/BPB-Worker-Panel#593]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

سلام وقت بخیر
در روش پیجز کی وی طبق آموزش ست کردم ولی بازم ارور میده ست نشده
در صورتی که در روش ورکر طبق آموزش بدون مشکل ست شد و اومد بالا
ممنون میشم راهنمایی کنید

### Relevant log output | لاگ برنامه یا پنل

```shell
1000
```

### Panel version | نسخه‌ی پنل

2.7.7

![Screenshot 2024-12-01 112334](https://github.com/user-attachments/assets/22d635cf-bfcd-4650-a79b-5c6c4c34e545)

**Comment by MacyBaston** [comment]
بعد اینکه kv ست کردی یه بارم دوباره آپلود کن فایل زیپ رو بعد بزن رو دامین اینبار که میاد یه لینکم داره اونو کپی کن بعد مراحل که گفته رو ادامه بده

**Comment by developer861** [comment]
وقتی kv رو ست کردید باید دوباره دیپلوی کنید که روش دیپلوی با آپلود فرق داره که دوستمون گفتن 
تو تب deployment روی create deployment بزنید و دوباره فایل رو وارد کنید

**Comment by emisemok** [comment]
بنا ب تجربه شخصی با ی مرورگر دیگه و غیرفعال کردن افزونه ها و اکانت کلود و گیتهاب جدید موفق شدم پیجز رو راه اندازی کنم با همون روش قدیمی

**Comment by tomach07** [comment]
سلام
uuid و Trojan Password از کجا به دست بیاریم
