### ISSUE TITLE
ایردات اپدیت 

### ISSUE THREAD

**Issue by hubgitme** [bia-pain-bache/BPB-Worker-Panel#60]
سلام
سپاس بخاطر زحماتتون .
اپدیت جدید 2.3.5
چند ایراد داره.
1.پنل از حالت یکتا بودن خارج شدن،باعدد و حروف ترکیبی شروع میشد. الان با رمز هرکی میتونی با ادرس زیر وارد شد

https://bpb-worker-page-panel.pages.dev/panel
2. با ادرس قبلی تغییرات پنل و ساب در (page) بروزرسانی نمیشه ،
3. ادرس جدید میده با همون id قبل.(هردو نوع کانفیگ قابل استفاده هستند).

**Comment by bia-pain-bache** [comment]
سلام. متوجه مشکل نمیشم، من الان هر پسوردی وارد کردم نشد!
بروزرسانی هم انجام شده اون بالا زده 2.3.5
مورد 3 رو نمیتونم بخونم چپ‌چین شده.

**Comment by hubgitme** [comment]
مورد 3
لینک سابسکریبشن هست که در اپدیت جدید تغییر کرده.قسمت اول لینک دچار تغییر.
(نکته با این وجود هم کانفیگها ی قبل هم جدید کار میکنن  )
قبلا اگر 
https://xxx.bpb-worker-page-panel.pages.dev/sub/uuid#BPB-Normal

بود
لینک جدید در پنل اپدیت جدید 
https://yyy.bpb-worker-page-panel.pages.dev/sub/uuid#BPB-Normal

**Comment by bia-pain-bache** [comment]
شما از لینک اشتباهی استفاده میکنید! با هر بار آپدیت یک لینک جدید تولید میشه که اینها برای تست هستن. داخل داشبورد از قسمت Production باید visit site رو بزنید، این لینک اصلیه که هیچوقت هم تغییر نمیکنه.

**Comment by mohammad35322** [comment]
چطور میتونیم آدرس پنل ثابت واسه خودمون تعریف کنیم تا لینک اشتراک ثابتی هم داشته باشیم؟ آیا با این کار ممکنه دامین پنل فیلتر بشه و این تغییر دامین نیازه؟
اگر قابلیت لینک اشتراک کاستوم یا یه چیزه ثابتی شبیه اون اضافه بشه عالی میشه.

**Comment by hubgitme** [comment]
ادرس پنل همون اسمی پروژه هست که تعریف میکنی .حالا اسم ورکر باشه یا اسم پیج،ولی اگر میخوای کاملا ثابت باشه. دامین بخر.
و کلادفلر کن،یه سابدامین با اسم ثابت میسازی،خیلی کوتاه و هر اسمی که بخوای.

**Comment by bia-pain-bache** [comment]
از قسمت production روی visit site بزنید این لینک ثابته و هیچ نیازی به دامنه نیست. به بقیه لینکها کاری نداشته باشید اونا متغیر هستن
