### ISSUE TITLE
حل مشکل اررور ۱۱۰۱ error 1101 problem solved

### ISSUE THREAD

**Issue by pichoko** [bia-pain-bache/BPB-Worker-Panel#603]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

طبق امتحان هایی که کردم اگر remote dns رو تغییر بدین و در حد‌ امکان شخصی باشه اررور ۱۱۰۱ دیگه نمیاد براتون و بازم تضمینی نیست براش برای بعضیا ممکن هست کار نکنه

### Relevant log output | لاگ برنامه یا پنل

```shell
Remote dns
```

### Panel version | نسخه‌ی پنل

2.7.7

**Comment by hamedp-71** [comment]
> ### Attention | توجه
> * [x]  I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد
> 
> ### What Happened? | چه اتفاقی افتاده؟
> طبق امتحان هایی که کردم اگر remote dns رو تغییر بدین و در حد‌ امکان شخصی باشه اررور ۱۱۰۱ دیگه نمیاد براتون و بازم تضمینی نیست براش برای بعضیا ممکن هست کار نکنه
> 
> ### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟
> _No response_
> 
> ### Relevant log output | لاگ برنامه یا پنل
> ```shell
> Remote dns
> ```
> 
> ### Panel version | نسخه‌ی پنل
> 2.7.7

ن داداش کارساز نبود اون رو من 3 روز قبل امتحان کردم و هنوز دارم کارهای دیگری رو امتحان میکنم که شاید به نتیجه برسم .

**Comment by pichoko** [comment]
چشمش نزنم دو روزه وصله

**Comment by hamedp-71** [comment]
> چشمش نزنم دو روزه وصله

نسخه 2.7.8 برای من هم فعلا 3 روزی هست متصل هست . دست هم بهش نمیزنم ببینم چی میشه .

**Comment by kigfyg** [comment]
نسخه 2.7.8 که موثع نصب ارور 1101 میده ولی از طریق خود کلادفلر میاره میونمرمز جدید رو وارد کنم ولی بعدش دیگه از طریق همون خود پنل کلادفلر هم دیگه نمیاره
