### ISSUE TITLE
دریافت ارور

### ISSUE THREAD

**Issue by hamidreza2000m** [bia-pain-bache/BPB-Worker-Panel#608]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

یه خطا دریافت میکنم با این متن 
❌ Something went wrong!
⚠️ KV Dataset is not properly set! Please refer to tutorials
در صورتی که هنوز به مرحله ی ست کردن kv نرسیدم ، بعد که kv رو ست کردم هم باز همین ارور میاد و صفحه ای که uuid و تروجان رو بده و لینکش نیست ، بارها kv رو حذف کردم و با دقت مجددا نامگذاری و سیو کردم ولی همچنان همین ارور رو دریافت میکنم

### Relevant log output | لاگ برنامه یا پنل

```shell
ظ
```

### Panel version | نسخه‌ی پنل

2.7.8

**Comment by hamidreza2000m** [comment]
![image](https://github.com/user-attachments/assets/d0bdebfa-ee17-4134-b70a-b808da9bb5aa)

**Comment by zcemu** [comment]
If it's a page, you need to re-upload the ZIP file.

**Comment by RezaFKH** [comment]
برای رفتن به صفحه uuid که پسورد هم جنریت کنه، همون صفحه ای که میگه something went wrong  رو آخر دامنش یه secrets/ بزنی وارد صفحه ای که میخوای میشی.

**Comment by hamidreza2000m** [comment]
I re-uploaded the ZIP file. then fixed

**Comment by saeedml73** [comment]
> I re-uploaded the ZIP file. then fixed

سلام
چجوری باید آپلود کرد؟
کدوم قسمته؟
