### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Freaky-coder-dude** [bia-pain-bache/BPB-Worker-Panel#609]
### Attention

- [X] I searched and no similar issues were found

### What Happened?

Just as soon as I started to use version 2.7.8 and updated my cloudflare worker with the script the panel won't open anymore

### Relevant log output

```shell
I just see a page saying "Error 1103" with these under it:

What happened?
You've requested a page on a website that is on the Cloudflare network.

What can I do?
If you are the owner of this website and you believe that this page is being shown in error:
you should contact Cloudflare Support.
```

### Panel version

2.7.8

**Comment by theking12b** [comment]
DUDE 
read all the open issues
dont open unneccesary issue
we all have problem 
also provide more detail about your problem

**Comment by Freaky-coder-dude** [comment]
I fixed it 😎
