### ISSUE TITLE
发现个新鲜的问题，看直播时候很明显，用的时候好像会断流，断一下然后自动连上，一会又断又连上，我用的上传zip部署的，咋回事啊，都这样吗

### ISSUE THREAD

**Issue by flylj999** [bia-pain-bache/BPB-Worker-Panel#611]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

发现个新鲜的问题，看直播时候很明显，用的时候好像会断流，断一下然后自动连上，一会又断又连上，我用的上传zip部署的，咋回事啊，都这样吗

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

发现个新鲜的问题，看直播时候很明显，用的时候好像会断流，断一下然后自动连上，一会又断又连上，我用的上传zip部署的，咋回事啊，都这样吗

### Relevant log output | لاگ برنامه یا پنل

```shell
发现个新鲜的问题，看直播时候很明显，用的时候好像会断流，断一下然后自动连上，一会又断又连上，我用的上传zip部署的，咋回事啊，都这样吗
```

### Panel version | نسخه‌ی پنل

发现个新鲜的问题，看直播时候很明显，用的时候好像会断流，断一下然后自动连上，一会又断又连上，我用的上传zip部署的，咋回事啊，都这样吗

**Comment by zhugensheng1996** [comment]
出现错误提示Sorry, you have been blocked
