### ISSUE TITLE
حل مشکل فیلترینگ pages.dev

### ISSUE THREAD

**Issue by liMilCo** [bia-pain-bache/BPB-Worker-Panel#617]
# 💞 دامنه رایگان برای BPB  🔫

> اگر` مشکل 1101 حل کرده باشید وارد خان دوم میشد که حل مشکل فیلترینگ pages.dev هست.

### 😳😱💀 جللخالق؛ سالهاست که جیکور مشکلی نداشت اما یک روز بعد از این آموزش جیکور باگ آیپی های آزادش رو بست و یک گام به فیلتر شدن دامنه های جیکور نزدیک شدیم ...

 **🌪🌦🌧 کلودفلر پنل ها رو میبنده، جیکور ایپی های آزاد رو میبنده، ایران اینترنت آزاد رو میبنده 😎😂 دمه همه دوستان وسط این میدان جنگ گرم ...**

---

## روش اول:
خیلی ساده دامنه را به پروژه کلودفلر متصل میکنیم:
برای این روش اگر یک اکانت قدیمی در [freedns] داشته باشید (_به اکانت های جدید اجازه اتصال با CNAME را نمیدهد_) یا در سایت www.noip.com یک ساب دامنه رایگان ثبت کنید (_دامنه های این سایت عموما در ایران فیلتر هستن_) یا یک دامنه غیررایگان داشته باشد و از ساب دامنه آن استفاده کنید:
خیلی ساده سابدامنه ساخته شده را با روش CNAME به  MY-PROJ.pages.dev (دامنه پروژه خود) متصل کنید. بعد در کلودفلر - پروژه خود - در بخش Custom domains به روش `My DNS provider` دامنه را به پیج خود متصل کنید، اگر همه چیز درست باشد حدود 5 دقیقه دامنه فعال خواهد شد ...

> 😳 _یه نکته ای رو متوجه شدم که در اینترنت ایرانسل اگر از دامنه با CNAME به دامنه فیلتر متصل باشه مشکل نداره اما بقیه ای-اس-پی ها اگر دامنه مرجع فیلتر باشه این دامنه غیرقابل دسترسی میشه؛ در نهایت بعد از اینکه کلودفلر دامنتون رو تایید کرد و دامنه به پروژه متصل شد دوباره از پنل DNS دامنه حالت CNAME رو به حالت A تغییر دهید و یکی از IP4 هایی که به دامنه پیچ تون متصل هست رو وارد کنید._

😉 همچنین شما میتوانید از کسی که اکانت فعال و قدیمی در [FreeDNS] دارد بخواهید دامنه ای را با روش CNAME ثبت کند و مقدار آن را دامنه پیج شما را بدهد، بعد شما وارد اکانت کلودفلر خود شده و آن دامنه را به پیج خود متصل کنید بعد از تایید توسط کلودفلر و اکتیو شدن دامنه؛ آن شخص دامنه را از پنل خود حذف کند و شما با اکانت جدید دقیقا همان دامنه را به روش A با مقدار (IP4 دامنه پیج خود) مجدد ثبت کنید.

[این آموزش هم مطالعه کنید.](https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/pages_installation_fa.md#4--%D8%A7%D8%AA%D8%B5%D8%A7%D9%84-%D8%AF%D8%A7%D9%85%D9%86%D9%87-%D8%A8%D9%87-pages)

![image](https://github.com/user-attachments/assets/f5f56479-a3a8-4100-b839-103b86e76d60)

### با استفاده از سایت GCore و ساب دامنه رایگان حقیقی:
با این روش اول در سایت [FreeDNS] یک سابدامنه رایگان ثبت کنید، و ای-پی آن را با روش A روی **92.223.124.62** ذخیره کنید.
بعد وارد سایت GCore  شده و دامنه ای که ثبت کرده اید را در اینجا وارد کنید. در این بخش بجای ایپی از دامنه MY-PROJ.pages.dev یا ای-پی آن دامنه استفاده کنید.
اگر بدون مشکل دامنه شما رو پذیرفت گزینه SSL را فعال کنید و یک certificate رایگان برای دامنه بگیرید.
(در اینترنت و یوتیوب آموزش های زیاد برای ساخت اکانت رایگان در جیکور هست)
اتصال به pages رو آخر میگم:

### استفاده از دامنه فیک در GCore
برای این روش در سایت GCore یک دامنه غیر واقعی مثلا (sdfsfegsg.com یا a.de) ثبت کنید. 
_البته به تازگی دامنه های .ir در جیکور بسته شده اند و هیچ دامنه ای را با این پسوند نمیتوانید ثبت کنید._
از انجا که این دامنه فیک است و به جیکر متصل نمیباشد نمیتواند SSL اختصاصی برای آن بگیرید.

## اتصال به GCore به کلودفلر pages
فرض میکنیم دامنه BPB شما در پیج MY-PROJ.pages.dev میباشد:
در جیکور وارد تنظیمات دامنه خود شوید:
🏃 در بخش Origin pull protocol
حتمی گزینه HTTPS را انتخاب کنید (چون کلودفلر فقط از این پروتکل استفاده میکند)

![image](https://github.com/user-attachments/assets/bee81058-33dc-4bad-b656-86a210f66f13)

🏃 زیر این گزینه در بخش Pull content from وارد گزینه Edit this group بشوید:
در بخش Origin source دامنه پیج خود را وارد کنید (MY-PROJ.pages.dev) بعد ذخیره کرده و به صفحه قبل بازگردید.

![image](https://github.com/user-attachments/assets/e8316a45-8f44-41ae-8e9d-8bd592f7de79)

🏃 گزینه Host header فعال کنید و در Custom Host header دوباره همان دامنه پیج خود  (MY-PROJ.pages.dev)  را وارد کرده و ذخیره کنید.
_این تنظیم برای اتصال به پیج واجب است_

![image](https://github.com/user-attachments/assets/a3ba0a72-305b-44d8-9aaf-9edcb6a2a0fc)

**توجه کنید بعد از تغییرات حدودا بیش از نیم ساعت طول میکشد تا تنظیمات اعمال شود.**

## تنظیمات کانفیگ
اگر از روش دوم استفاده کرده اید و یک ساب دامنه حقیقی به جیکور متصل کرده اید خیلی ساده در کانفیگ بجای MY-PROJ.pages.dev این دامنه را قرار دهید. پورت حتمی 443 باشد و بقیه تنظیمات هم مثل کانفیگ اصلی خود پیج.

![image](https://github.com/user-attachments/assets/5f5fc18d-6c21-461e-9418-e158ff5fcc69)

---

اگر از روش سوم استفاده کرده اید و دامنه فیک دارید:
👈 در تنظیمات کانفیگ بجای **address** میتوانید [ **gcore.com** ] یا ای-پی تمیز جیکور یا یک سابدامنه پشت جیکور مثل cdn.gcore.com استفاده کنید. [اینجا](https://check-host.net/check-dns?host=gcore.com) میتوانید چند ای-پی مخطلف پیدا کنید و تست کنید که آیا کار میکند یا نه.

👈 در بخش **host** یا _comuflage domain (host)_ همان دامنه فیکی که در جیکور ثبت کرده اید قرار دهید.

👈 در بخش **SNI** باید یک دامنه پشت جیکور باشد قرار دهید خیلی ساده همان  [ **gcore.com** ] قرار دهید.

## تنظیمات دستی در v2rayNG

![image](https://github.com/user-attachments/assets/a1e1fe38-4e96-4951-9d48-940d3cb57053)

## تنظیمات در پنل BPB برای سابسکرپشن:

![image](https://github.com/user-attachments/assets/553b0253-9b31-4654-824d-8b51a6fee6e3)

---
> شما میتوانید موقع استفاده از جیکور از اتصال غیر امن و بدون TLS متصل شوید که باید پورت را 80 بگزارید در بعضی از خدمات دهندگان مثل ایرانسل سرعت بهتری دارد و در همراه اول کار نمیکند اما در کل امنیت این اتصال پایین است.

## کانفیگ ها 
بعد از وارد کردن این کافنیگ ها آنها را ویرایش کرده و بجای x.com دامنه جیکور خود را قرار دهید
همچنین باید UUID را تغییر دهید.

```shell
vless://00000000-0000-4000-8000-000000000000@gcore.com:80?type=ws&host=x.com&path=%2FTDncy4ESqxsjL2fT%2FMTMyLjIyNi4xMTQuNzQ%3Fed%3D2560#%F0%9F%91%AB%20BPB%3AGCore

vless://00000000-0000-4000-8000-000000000000@cdn.gcore.com:443?encryption=none&security=tls&sni=cdn.gcore.com&alpn=http%2F1.1&fp=chrome&allowInsecure=1&type=ws&host=x.com&path=%2FTDncy4ESqxsjL2fT%2FMTMyLjIyNi4xMTQuNzQ%3Fed%3D2560#%F0%9F%91%AB%20BPB%3AGCore+TLS

```

**Comment by santozl064** [comment]
سلام چه روش هایی میشه توضیح بدی داداش ؟
