### ISSUE TITLE
choose best  length and interval values for my network

### ISSUE THREAD

**Issue by mtbmby** [bia-pain-bache/BPB-Worker-Panel#63]
یه اسکریپت لطفا معرفی کنید یا تو پنل قرار بدین که بیاد با یه سری تست بهترین مقادیر فرگمنت مخصوص اینترنت کاربر رو بهش بگه که تو پنل وارد کنه.
مثل اسکریپتایی که آیپی تمیز میدن.

**Comment by bia-pain-bache** [comment]
نداریم همچین چیزی. شرایط اینترنت ایران هم بی‌ثبات و شبکه‌ی همراه هم افتضاحه، حتی اگه اسکریپتی بنویسن همش خطا داره.
