### ISSUE TITLE
Workerless config not working 

### ISSUE THREAD

**Issue by oftenhamed** [bia-pain-bache/BPB-Worker-Panel#65]
درود، ممنون بابت زحماتت و خسته نباشی!

کانفیگ workerless خطای start services failure می‌ده، باوجودیکه پینگ real delay داره.

بقیه‌ی کانفیگ‌ها به‌خوبی کار می‌کنن.

مشکل به‌نظرت کجاست؟

ممنون بابت کمک.

**Comment by Diana-Cl** [comment]
سلام رفیق وقت بخیر ببخشید دیگه نخواستم یکی جدیدش رو باز کنم همینجا نوشتم، جسارتا مبخواستم بدونم اک بخوام **Remote DNS** رو برای کانفیگ ‌های عادی تغییر بدم کدوم لاین از کد رو باید ویرایش کنم، مثلا بخوام از ادگارد یا rethink استفاده کنم داخل کد، اون DoH ک در لاین هجدهم کد هست رو تغییر بدم؟ سک دارم حقیقتا، مننون میشم راهنمایی کنید.💙

**Comment by bia-pain-bache** [comment]
`کانفیگ workerless خطای start services failure می‌ده، باوجودیکه پینگ real delay داره.`

سلامت باشی، یه نفر دیگه هم این مشکلو داشت گفت آپدیت کردم به ۱.۸.۲۳ درست شد. در هر صورت مشکل از سمت کانفیگ نیست.

`اگه بخوام Remote DNS رو برای کانفیگ ‌های عادی تغییر بدم کدوم لاین از کد رو باید ویرایش کنم، مثلا بخوام از ادگارد یا Rethink استفاده کنم`

برای کانفیگ نرمال باید داخل تنظیمات کلاینت عوضش کنید، کاری به کد نداره.

**Comment by Diana-Cl** [comment]
> برای

- 

> برای کانفیگ نرمال باید داخل تنظیمات کلاینت عوضش کنید، کاری به کد نداره.

یک دنیا ممنونم

**Comment by oftenhamed** [comment]
> `کانفیگ workerless خطای start services failure می‌ده، باوجودیکه پینگ real delay داره.`
> 
> سلامت باشی، یه نفر دیگه هم این مشکلو داشت گفت آپدیت کردم به ۱.۸.۲۳ درست شد. در هر صورت مشکل از سمت کانفیگ نیست.
>

ورژن من هم ١.٨.٢٣ است، اما باز هم همین خطا رو دارم. 🤔
با حذف و نصب مجدد و حتی توی یک گوشی دیگه هم همینه وضعیت.
باز هم ممنونم ازت. ♥️

**Comment by bia-pain-bache** [comment]
متاسفانه مشکل کلاینته، چون اکثرا بدون مشکل وصل شدن. میتونید یه بار Clear cache, Clear data کنید و برنامه رو پاک کنید از گوگل‌پلی نصب کنید ، Geo asset آپدیت کنید و امتحان کنید. راه دیگه‌ای به ذهن من نمیرسه.
