### ISSUE TITLE
bpb面板未混淆源码

### ISSUE THREAD

**Issue by zhuqq2020** [bia-pain-bache/BPB-Worker-Panel#655]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

bpb面板未混淆的源码如何生成或者获取？

### Relevant log output | لاگ برنامه یا پنل

```shell
bpb面板未混淆的源码如何生成或者获取？
```

### Panel version | نسخه‌ی پنل

bpb面板未混淆的源码如何生成或者获取？

**Comment by DifferentSparkler** [comment]
感觉应该是识别了特征码，换一种混淆方式，把那些图标什么的去掉，那些东西不能混淆

**Comment by zhuqq2020** [comment]
> 感觉应该是识别了特征码，换一种混淆方式，把那些图标什么的去掉，那些东西不能混淆

我自混淆2.7.5的代码部署都可以使用，希望有未加密的代码 每个人使用自混淆一次就可以 ，作者发布的混淆后的代码官方可以精确封杀

**Comment by DifferentSparkler** [comment]
用勇哥的混淆代码部署就没有问题，建议换混淆方式，最后一段代码没有必要就去掉，这个很容易识别

**Comment by zhuqq2020** [comment]
> 用勇哥的混淆代码部署就没有问题，建议换混淆方式，最后一段代码没有必要就去掉，这个很容易识别

是的我就用的勇哥的混淆代码来混淆bpb 2.7.5源代码 在部署就没问题 所以找找最新没混淆的源代码

**Comment by wubengda** [comment]
我也在问，但是作者好像不给源码，用作者提供的最新版的混淆代码无论怎么部署都是会1101，我找到2.7.4的源码，自己混淆后，一直都能用。现在问题是无法改变优选IP，只能暂时弃用了，虽然还是感觉BPB面板好用。

**Comment by chen-jingliang** [comment]
https://github.com/lu-lingyun/BPB-Worker-Panel
使用这位作者的BPB混淆版本，他同步发行，可以成功部署。

**Comment by Nagisa077** [comment]
> 我也在问，但是作者好像不给源码，用作者提供的最新版的混淆代码无论怎么部署都是会1101，我找到2.7.4的源码，自己混淆后，一直都能用。现在问题是无法改变优选IP，只能暂时弃用了，虽然还是感觉BPB面板好用。
@lizhi123le 

can you share you 2.7.4 source js？ thanks。

**Comment by zcemu** [comment]
上面那个同步的，我在前几个版本用过，当时用他的上传就能用，后来原作者版新版我用了没事就没再用了。

**Comment by honglifushi** [comment]
panel面板登录默认密码是什么？

**Comment by zhuqq2020** [comment]
> panel面板登录默认密码是什么？
See the instructions/panel to set your own password.

**Comment by zcemu** [comment]
> panel面板登录默认密码是什么？

存在KV里的，忘记就删除KV重新建立，网页哪里会让你重新设置

**Comment by wubengda** [comment]
> > 我也在问，但是作者好像不给源码，用作者提供的最新版的混淆代码无论怎么部署都是会1101，我找到2.7.4的源码，自己混淆后，一直都能用。现在问题是无法改变优选IP，只能暂时弃用了，虽然还是感觉BPB面板好用。
> > @lizhi123le
> 
> can you share you 2.7.4 source js？ thanks。可以分享一下2.7.4源码吗？谢谢。

这个，现在还正常使用。。https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/c6285a3237b538df3e9efd15741ff041deb6953f/_worker.js

**Comment by zhuqq2020** [comment]
end

**Comment by zhuqq2020** [comment]
自己已解决！
