### ISSUE TITLE
[Testing] [Improvements] custom obfuscation

### ISSUE THREAD

**Issue by vadash** [bia-pain-bache/BPB-Worker-Panel#656]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

Src (do not use directly)
[worker_source_DO_NOT_USE.zip](https://github.com/user-attachments/files/18148390/worker_source_DO_NOT_USE.zip)

![settings](https://github.com/user-attachments/assets/380fbfff-072a-490d-be39-1ee23cbd060c)

ID is old UUID, PASS is old TROJAN_PASS and DBNAME is name of KV database

Pick any of obfuscated files below

[worker-e1bb67f9-cf00-4896-8790-918dd42b3aad.zip](https://github.com/user-attachments/files/18148230/worker-e1bb67f9-cf00-4896-8790-918dd42b3aad.zip)

[worker-fed298cf-d306-47bd-bb34-d6d14722fc54.zip](https://github.com/user-attachments/files/18148320/worker-fed298cf-d306-47bd-bb34-d6d14722fc54.zip)

[worker-009535f2-85cf-4510-a667-5edfb14242e2.zip](https://github.com/user-attachments/files/18148332/worker-009535f2-85cf-4510-a667-5edfb14242e2.zip)

**Comment by lizhi123le** [comment]
> ### Attention | توجه
> * [x]  I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد
> 
> ### What Happened? | چه اتفاقی افتاده؟
> Src (do not use directly) [worker_source_DO_NOT_USE.zip](https://github.com/user-attachments/files/18148390/worker_source_DO_NOT_USE.zip)
> 
> ![settings](https://private-user-images.githubusercontent.com/1397582/396051621-380fbfff-072a-490d-be39-1ee23cbd060c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDU2NDQsIm5iZiI6MTczNDM0NTM0NCwicGF0aCI6Ii8xMzk3NTgyLzM5NjA1MTYyMS0zODBmYmZmZi0wNzJhLTQ5MGQtYmUzOS0xZWUyM2NiZDA2MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMTAzNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE1OTJjZmFhNWQxY2YzYjU1ZTg2NTU4YTc3OTdhODFmMGNkY2ZmYmI4ODhkYTBjYjE4M2VmMzE3MjgwMTU0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.flRMUEOifQ2BfB_EI9eRDrWPMYfdiYY_kOuHZKSya6w)
> 
> ID is old UUID, PASS is old TROJAN_PASS and DBNAME is name of KV database
> 
> Pick any of obfuscated files below
> 
> [worker-e1bb67f9-cf00-4896-8790-918dd42b3aad.zip](https://github.com/user-attachments/files/18148230/worker-e1bb67f9-cf00-4896-8790-918dd42b3aad.zip)
> 
> [worker-fed298cf-d306-47bd-bb34-d6d14722fc54.zip](https://github.com/user-attachments/files/18148320/worker-fed298cf-d306-47bd-bb34-d6d14722fc54.zip)
> 
> [worker-009535f2-85cf-4510-a667-5edfb14242e2.zip](https://github.com/user-attachments/files/18148332/worker-009535f2-85cf-4510-a667-5edfb14242e2.zip)

There's no problem with this
![屏幕截图 2024-12-16 183531](https://github.com/user-attachments/assets/a27bdf15-380d-4e3b-a5d0-6fa8df13f970)

**Comment by hxyx2024** [comment]
不折腾了，部署后只用2天就1101，

**Comment by DifferentSparkler** [comment]
用了你的混淆代码，自定义变量，目前可以正常部署，就是不知道可以活多久

**Comment by DifferentSparkler** [comment]
你这个是用的什么方式混淆的，能不能混淆一下最新的代码

**Comment by EvanderYang** [comment]
> 不折腾了，部署后只用2天就1101，

自己混淆的代码，用了三天了。
个人实践出一个真理，如果要想使用长久，别随多数，要特例独行。

**Comment by MSLight** [comment]
Working Fine.
@vadash 
Please describe your steps to obfscute `worker_source_DO_NOT_USE.zip`

**Comment by foodiemee4** [comment]
It's working fine for now. Can you please explain how to obfuscate ?

**Comment by vadash** [comment]
> Please describe your steps to gnerate and obfscute `worker_source_DO_NOT_USE.zip`

Its private obfuscator. I see what I can do with public tools

**Comment by MSLight** [comment]
> Its private obfuscator. I see what I can do with public tools

Ok. Just explain how to generate main source [not obfscuted source]?

**Comment by vadash** [comment]
> > Its private obfuscator. I see what I can do with public tools
> 
> Ok. Just explain how to generate main source [not obfscuted source], please?

    # Remove the output directory if it exists
    Remove-Item -Recurse -Force -Path .\output\
    # Build the worker
    npx wrangler deploy --dry-run --outdir output
    # Rename worker

That what I do in windows. To install wrangler do
[package.json.zip](https://github.com/user-attachments/files/18180980/package.json.zip)
 https://developers.cloudflare.com/workers/wrangler/install-and-update/

npm install wrangler --save-dev

**Comment by vadash** [comment]
Improved, pick any 30 of zips

[bpb_obfs_pack.zip](https://github.com/user-attachments/files/18197844/bpb_obfs_pack.zip)

**Comment by vadash** [comment]
[bpb_obfs_pack.zip](https://github.com/user-attachments/files/18197913/bpb_obfs_pack.zip)
Synced to latest source, improved obfuscation, 30 ish builds to choose

**Comment by zhuqq2020** [comment]
> [bpb_obfs_pack.zip ](https://github.com/user-attachments/files/18197913/bpb_obfs_pack.zip) [bpb-obfs-pack-2.zip](https://github.com/user-attachments/files/18203032/bpb-obfs-pack-2.zip)
> 
> 同步到最新源，改进混淆（现在完全隐藏 vless、trojan、bpb 等单词），100 多个构建可供选择 不要忘记更改环境变量（如 png）

已成功，但是还是不会生成主源代码

**Comment by zhuqq2020** [comment]
> [bpb_obfs_pack.zip](https://github.com/user-attachments/files/18197913/bpb_obfs_pack.zip) [bpb-obfs-pack-2.zip](https://github.com/user-attachments/files/18203032/bpb-obfs-pack-2.zip)
> 
> Synced to latest source, improved obfuscation (now fully hides words like vless, trojan, bpb), 100+ builds to choose Dont forget to change env variables (like in png)
> 
> ![image](https://private-user-images.githubusercontent.com/1397582/397842508-eda30746-ae8b-4476-bbd5-86b108f5887c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDYxNDgsIm5iZiI6MTczNDc0NTg0OCwicGF0aCI6Ii8xMzk3NTgyLzM5Nzg0MjUwOC1lZGEzMDc0Ni1hZThiLTQ0NzYtYmJkNS04NmIxMDhmNTg4N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjFUMDE1MDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY2NGI0MzRkZWU2ZjZjN2U5NjdkOGFlYjNmN2U3MWU2MDFkNWU3NzcxNjk2Y2Q4YTFmYmUwM2RhNjZmNjRjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.n4xWc2lW0kvp8-8Q1o7tcAWEXj9iZLfwXnItZCeAKjM)

I have already generated the source code according to the boss’s configuration, but I still haven’t learned how to do it!

**Comment by ZhangWei-KUMO** [comment]
感谢楼上各位的付出，但是我坚持了三天还是挂了。

**Comment by lizhi123le** [comment]
> 感谢楼上各位的付出，但是我坚持了三天还是挂了。

你改过CF的.dev域名的子域名称没有？没改大概率处于管控状态

**Comment by ZhangWei-KUMO** [comment]
> > 感谢楼上各位的付出，但是我坚持了三天还是挂了。
> 
> 你改过CF的.dev域名的子域名称没有？没改大概率处于管控状态

什么？还有改域名？

**Comment by lizhi123le** [comment]
> > > 感谢楼上各位的付出，但是我坚持了三天还是挂了。
> > 
> > 
> > 你改过CF的.dev域名的子域名称没有？没改大概率处于管控状态
> 
> 什么？还有改域名？

最好改一下哦，被1101的子域可能被重点管控，就是改cf的那个.dev子域，不是项目.dev域名

**Comment by ZhangWei-KUMO** [comment]
> > > > 感谢楼上各位的付出，但是我坚持了三天还是挂了。
> > > 
> > > 
> > > 你改过CF的.dev域名的子域名称没有？没改大概率处于管控状态
> > 
> > 
> > 什么？还有改域名？
> 
> 最好改一下哦，被1101的子域可能被重点管控，就是改cf的那个.dev子域，不是项目.dev域名

我现在自定义了域名，看看能坚持多久

**Comment by vadash** [comment]
Do you guys use workers? I run pages with custom domain name (free https://register.us.kg/). 1 page per device, never going over 100k per day

I also use chain proxy since my cheap VPS ($11/year) is not available directly

**Comment by lizhi123le** [comment]
> Do you guys use workers? I run pages with custom domain name (free https://register.us.kg/). 1 page per device, never going over 100k per day
> 
> I also use chain proxy since my cheap VPS ($11/year) is not available directly

I always use pages deployment, custom domain name, GitHub automatic synchronization is more convenient

**Comment by MSLight** [comment]
@vadash 
How to set PROXYIP in your obfscuted workers?

**Comment by vadash** [comment]
> @vadash How to set PROXYIP in your obfscuted workers?

code is same, navigate use env.PROXYIP  or set directly in web 
![image](https://github.com/user-attachments/assets/d4963d13-29b6-4411-a4c0-8b0281900b5c)

**Comment by RezaFKH** [comment]
I don't know the versions of all the zip files, but I picked the first one, 2.7.8.
It's been about one week which is working correctly and I can't set custom Sni and domain in the panel, because it doesn't work properly. (maybe the sni has a problem!)
Anyway, thank you for these files. I hope they work correctly to the end.

**Comment by vadash** [comment]
> Anyway, thank you for these files. I hope they work correctly to the end.

can always edit KV directly. Its json formated

**Comment by hameed-maleki** [comment]
Please tell me what tool you used to obfuscate it and what settings?

**Comment by MSLight** [comment]
There is an error in `WARP PRO SUB` with your obfscuted version @vadash 

```
MAZE Panel 2.8.1 
❌ Something went wrong!
⚠️ TypeError: Cannot read properties of null (reading '0') at aCZUOJ (worker.mjs:1:423320) at extractWireguardParams (worker.mjs:1:440901) at g (worker.mjs:1:781683) at buildSingBoxWarpOutbound (worker.mjs:1:782607) at e (worker.mjs:1:786030) at worker.mjs:1:788053 at Array.forEach () at getSingBoxWarpConfig (worker.mjs:1:787912) at async Object.fetch (worker.mjs:1:821972)
```

**Comment by vadash** [comment]
> There is an error in `WARP PRO SUB` with your obfscuted version @vadash

sorry guys, I only use https://github.com/kyochikuto/sing-box-plus, fragment sub, clean ips + chain proxy to https://racknerdtracker.com/?product=810/1-gb-kvm-vps-a-must-grab-deal---leb-exclusive

**Comment by MSLight** [comment]
> 
> sorry guys, I only use https://github.com/kyochikuto/sing-box-plus, fragment sub, clean ips + chain proxy to https://racknerdtracker.com/?product=810/1-gb-kvm-vps-a-must-grab-deal---leb-exclusive ($11-12 per year with decent speed and bandwidth)

Your changes causes this problem. please fix

**Comment by vadash** [comment]
https://github.com/vadash/BPB-Worker-Panel-Releases

new builds with changelog and repo

**Comment by zhuqq2020** [comment]
> There is an error in `WARP PRO SUB` with your obfscuted version @vadash
> 
> ```
> MAZE Panel 2.8.1 
> ❌ Something went wrong!
> ⚠️ TypeError: Cannot read properties of null (reading '0') at aCZUOJ (worker.mjs:1:423320) at extractWireguardParams (worker.mjs:1:440901) at g (worker.mjs:1:781683) at buildSingBoxWarpOutbound (worker.mjs:1:782607) at e (worker.mjs:1:786030) at worker.mjs:1:788053 at Array.forEach () at getSingBoxWarpConfig (worker.mjs:1:787912) at async Object.fetch (worker.mjs:1:821972)
> ```
> 
> ![Screenshot_26-12-2024_1267_luci0010 pages dev](https://private-user-images.githubusercontent.com/125489319/398682764-b2797301-f870-4117-936a-5b4499b52350.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzODQ0NjQsIm5iZiI6MTczNTM4NDE2NCwicGF0aCI6Ii8xMjU0ODkzMTkvMzk4NjgyNzY0LWIyNzk3MzAxLWY4NzAtNDExNy05MzZhLTViNDQ5OWI1MjM1MC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjhUMTEwOTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU2ZGJhZjZkYzRkNWIzZTA4ZGI4NWY2ZmNhYmY2NzcxYTI5MDE4ZjM3ZTVkMDcwNTdmYWM5YmIyZGY4NjgxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ny_IKpgv-RbOND1xn0AOwuDH-hM43nKuFBr3wpmWoZc)

https://github.com/zhuqq2020/BPB-Worker-Panel/releases/tag/2.8.1
