### ISSUE TITLE
سوال درباره Chain Proxy

### ISSUE THREAD

**Issue by CyrusTheV** [bia-pain-bache/BPB-Worker-Panel#69]
ممنون بابت همه زحمتهایی که میکشید.
Chain Proxy فقط برای کانفیگ های فرگمنت قابل استفاده هست؟ ممکنه برای سایر کانفیگ ها هم اضافه بشه؟

**Comment by bia-pain-bache** [comment]
خواهش میکنم، v2rayNG قابلیتشو نداره متاسفانه.

**Comment by CyrusTheV** [comment]
> خواهش میکنم، v2rayNG قابلیتشو نداره متاسفانه.

sing-box 
هم نداره؟

**Comment by bia-pain-bache** [comment]
تو سینگ‌باکس میتونید از قسمت group ساب رو ادیت کنید و کانفیگ مدنظر رو قسمت Landing بذارید. اینجوری رو کل ساب اعمال میشه.
