### ISSUE TITLE
MOBILE FRAGMENT - Streisand

### ISSUE THREAD

**Issue by Airuop** [bia-pain-bache/BPB-Worker-Panel#7]
سلام 
نسخه 2.2 تب MOBILE FRAGMENT کانفیگ های Streisand داخل برنامه ایمپورت شد اما قابل استفاده نیست پس از کانکت شدن قطع میشد.
توی کانفیگ ها موردی هست که با برنامه سازگار نیست.

**Comment by bia-pain-bache** [comment]
مشکل از Geo asset هست. اگر جایی داره که میشه دستی آپلود کرد، از لینکی که توی آموزش گذاشتم دانلود کن و ایمپورت کن.

**Comment by Airuop** [comment]
> مشکل از Geo asset هست. اگر جایی داره که میشه دستی آپلود کرد، از لینکی که توی آموزش گذاشتم دانلود کن و ایمپورت کن.

https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat

این دو لینک هم وارد کرده بودم، درست نشد، مشکل از جای دیگه هست.

**Comment by liamnees** [comment]
> سلام نسخه 2.2 تب MOBILE FRAGMENT کانفیگ های Streisand داخل برنامه ایمپورت شد اما قابل استفاده نیست پس از کانکت شدن قطع میشد. توی کانفیگ ها موردی هست که با برنامه سازگار نیست.

قسمت بلاک کشورها را خاموش کن توی تنظیمات سابسکرایب فرگمنت

**Comment by bia-pain-bache** [comment]
توییتر مطرح کردم و اکثرا بدون مشکل وصل میشن، بعضیا فقط با اینستا مشکل دارن. در هر صورت کانفیگ JSON در صورتی که روی v2rayNG کار میکنه باید روی Streisand هم وصل بشه چون جفتشون xray-core هستن. اگر کلا وصل نمیشید مشکل استثنایی هست که بدون لاگ نمیشه بررسی کرد. ولی توصیه میکنم داخل پنل از DNS کلادفلر بعنوان remote استفاده نکنید، پیشفرض یا 8.8.8.8 پیشنهاد میشه، ورکر با DNS کلادفلر مشکل داره.

**Comment by Airuop** [comment]
> توییتر مطرح کردم و اکثرا بدون مشکل وصل میشن، بعضیا فقط با اینستا مشکل دارن. در هر صورت کانفیگ JSON در صورتی که روی v2rayNG کار میکنه باید روی Streisand هم وصل بشه چون جفتشون xray-core هستن. اگر کلا وصل نمیشید مشکل استثنایی هست که بدون لاگ نمیشه بررسی کرد. ولی توصیه میکنم داخل پنل از DNS کلادفلر بعنوان remote استفاده نکنید، پیشفرض یا 8.8.8.8 پیشنهاد میشه، ورکر با DNS کلادفلر مشکل داره.

روی v2rayNG کار میکنه فقط با Streisand مشکل داره DNS هم 8.8.8.8 ست کردم اما تاثیری نداشت




> 
> قسمت بلاک کشورها را خاموش کن توی تنظیمات سابسکرایب فرگمنت

این تنظیم رو من جایی ندیدم کجا هست ؟

**Comment by bia-pain-bache** [comment]
متاسفانه Streisand یه سری باگ داره، کاری از من برنمیاد. ساب نرمال رو وارد کن و دستی فرگمنت ست کن روش.
اون کامنت دوستمون برای پنل سنایی و علیرضا بود، اینجا همچین گزینه‌ای نداریم.
