### ISSUE TITLE
FR : Trojan

### ISSUE THREAD

**Issue by amijafi** [bia-pain-bache/BPB-Worker-Panel#70]
Feature request 
a Chinese user has deployed trojan over workers

https://github.com/cmliu/epeius

is it possible to integrate it into your panel?

**Comment by bia-pain-bache** [comment]
I still haven't come to conclusion which profit does it add to connection in Iran's network. The main difference between protocols was encryption while used without TLS, however we are using TLS now and I don't find any profit in using Trojan.

**Comment by amijafi** [comment]
It helps using full potential of workers as censorship bypass tool and make your great panel even better

**Comment by bia-pain-bache** [comment]
Thanks, but in which way it helps? The main issue of using TLS Websocket is SNI itself not http obfuscation.
