### ISSUE TITLE
مینی اپ های تلگرام باز نمیشن

### ISSUE THREAD

**Issue by koroshyazdi252** [bia-pain-bache/BPB-Worker-Panel#71]
سلام و خسته نباشید.
تا دیروز به خوبی میشد مینی اپ های تلگرام رو باز کرد و استفاده کرد ولی امروز هرچی سعی کردم جواب نداد .
لطفا راهنمایی کنید. ممنونم.

**Comment by bia-pain-bache** [comment]
سلام، سلامت باشید.
متاسفانه باهاشون آشنایی ندارم، ممکنه با تعویض Proxy IP اوکی بشه.
