### ISSUE TITLE
کانفیگ های فرگمنت خورده برای مخابرات جواب نمیده

### ISSUE THREAD

**Issue by koroshyazdi252** [bia-pain-bache/BPB-Worker-Panel#72]
سلام و عرض ادب.
 ببخشید چطور میشه از کانفگ های فرگمن خورده پنل با اپراتور مخابرات هم وصل بشیم؟

**Comment by bia-pain-bache** [comment]
سلام،
مثل بقیه‌ی اپراتورها. باید مشکل رو به من بگید. بعضا میگن مخابرات بدون فرگمنت هم اوکیه با IP تمیز.

**Comment by koroshyazdi252** [comment]
چیزی که من تست کردم قسمت best ping  برای مخابرات ok ولی بازم ضعیفه 
فک کنم مربوط به اون اعدادی با شه که توی تنظیمات پنل برای فرگمنت تنظیم میکنیم.
بهترین تنظیمات فرگمنت هابرای هر اپراتور چی باید قرار داد.؟

**Comment by mahdimahdi0099** [comment]
سلام  ip تمیز بدست بیارم ممنون میشم کمک کنی

**Comment by bia-pain-bache** [comment]
اعداد هر اپراتوری بصورت تجربی بدست میاد، باید از کسایی که مخابرات دارن بپرسید. IP تمیز هم اسکنرش تو پنل هست، vpn رو قطع کنید و اسکن کنید.
