### ISSUE TITLE
warp کلادفلر

### ISSUE THREAD

**Issue by Butcher82** [bia-pain-bache/BPB-Worker-Panel#73]
آیا امکان این هست که توی پنل گزینه ای اضافه بشه که اتصال به کانفیگ ها از طریق وارپ انجام شود؟

**Comment by bia-pain-bache** [comment]
چه مزیتی داره؟

**Comment by bia-pain-bache** [comment]
همه‌ی اپراتورها الان باید مستقیم به کانفیگ وصل بشن مگر اینکه دامین فیلتر شده باشه، حالا ممکنه سرعت بد باشه. اون تنظیمات مختص هیدیفای هست هست، متاسفانه نمیتونم رو کل پنل اعمال کنم.

**Comment by Butcher82** [comment]
اوکی ممنون، دمتون گرم بخاطر زحماتتون ❤️

**Comment by bia-pain-bache** [comment]
خواهش میکنم ❤️
