### ISSUE TITLE
مصرف زیاد ورکر

### ISSUE THREAD

**Issue by Hamed-Republic** [bia-pain-bache/BPB-Worker-Panel#74]
سلام و ممنون بابت زحماتی که میکشید
ورکر عالیه فقط در مقایسه به سایر ورکر ها یی که تست کردم مصرف بسیار بالاتری داره و محدودیت ۱۰ هزار درخواست رو رد میکنه  ایا راهی هست که مصرف شو کاهش داد؟

**Comment by bia-pain-bache** [comment]
سلام ممنون، خودش چیزیو مصرف نمیکنه، بستگی به مصرف شما داره.
اگر از طریق pages دپلوی کنید ایمیل ۱۰۰ هزار رو میگیرید ولی کار میکنه، نامحدوده.
