### ISSUE TITLE
در خود پنل proxyip و  uuid تغیر

### ISSUE THREAD

**Issue by koroshyazdi252** [bia-pain-bache/BPB-Worker-Panel#75]
سلام و ارادت .
یک سوالی برام پیش اومده و اونم این هست که آیا امکانش هست که uuid و proxy ip  رو روی خود پنل تغیر بدیم و نیازی نباشه که بریم داخل خود کلاد فلر و این uuid و پروکسی رو تغیر بدیم؟
چون این کلاد فلر هرز چند گاهیی دچار مشکل داخلی میشه و یا یک سری مشکلات برای ورود به کلاد فلر مخصوصا زمانی که اینترنت ضعیف میشه که باعث میشه همان زمان نشه اون تنظیمات مربوطه رو ثبت کرد.

**Comment by bia-pain-bache** [comment]
سلام، سایت کلادفلر فیلتر نیست بدون vpn واردش بشید. proxy ip چند وقتی هست اضافه شده به پنل ولی آموزششو بخونید به مشکل نخورید. UUID امکانپذیر نیست.
