### ISSUE TITLE
قطع کامل اتصال با نت مخابرات

### ISSUE THREAD

**Issue by neganmj** [bia-pain-bache/BPB-Worker-Panel#76]
سلام، ورکر و پیج bpb با نت مخابرات از کار افتاده، چند نفری هم تو یوتیوب کامنت هاشون رو خوندم نوشته بودن برا اونا هم از کار افتاده
لطفا اگه مشکل از پنل هستش برطرفش کنید یا اگه تنظیمات خاصی برای خود پنل و پنل کلودفلر وجود داره که باید تغییرش بدیم اینجا بنویسید
فکر نکنم مشکل از دی ان اس داخل PROXYIP پنل کلودفلر باشه، چون با بهترین دی ان اس هم که اصلا قطعی نداره هم تست کردم ولی بازم مشکل پا برجاعه
هم دی ان اس داخل کلودفلر پنل رو تغییر دادم و retry deployment کردم و داخل v2ray هم آپدیت ساب زدم، هم آی پی خود پنل bpb هم ست کردم و بازم آپدیت ساب زدم ولی بازم مشکل پا برجاعه.
همین امروز این داستان پیش اومده، خواهش میکنم پیگیری کنید اسیر شدیم از دست این سایبریا با این اختلال انداختنشون...
مرسی از همه دولوپر های عزیز.

**Comment by neganmj** [comment]
و یچیز دیگه که با وجود انجام دادن همه این کار ها، اضافه کردن چندتا آی پی تمیز و حتی پاک کردن آی پی تمیز خود پنل اصلی و ProxyIP پنل کلودفلر، تو همه این مراحل که تست real delay ، بازم پینگ نمیده و حتی اگرم بده، با یه سرعت افتضاح در حد چند کیلوبایت بر ثانیه که هیچی بالا نمیاره وصل میشه و چند دیقه بعد کلا از کار میوفته.
این پنل شما واقعا عالی بود و حتی یه دوستی بود میگف یک سال بدون مشکل باهاش کار میکرد تا اینکه سه چهار هفته پیش یسریا شروع کردن تو یوتیوب آموزش استفاده از BPB، از اونجا اختلال ها شروع شد تا به الان که کلا از کار افتاده.

**Comment by neganmj** [comment]
> تست روی ADSL مخابرات


پس برای من چرا باید بعد سه هفته قطع شه؟
تنظیم خاصی توی پنل bpb، توی پنل کلودفلر،
آی پی یا dns خاصی نیاز داره کلا هرچی لطفا همینجا بگید
هزار بار دی ان اس عوض کردم تو دوتا پنل، انواع اقسام آی پی های ثابت و غیره گذاشتم براش، حتی زنگ زدم isp خط رو هم ریست کردم ، اصلا انگار نه انگار
مگه میشه فقط برای یه عده اینطوری قطع شه برای یه عده دیگه نه....

**Comment by bia-pain-bache** [comment]
بله متاسفانه خیلی به منطقه‌ی مخابراتی و شهر ربط داره، خیلیا دچار مشکل شدن. بدون فرگمنت فقط از اسکنر ip تمیز اضافه کنید شاید تغییر کنه. DNS هم از 1.1.1.1 استفاده نکنید.

**Comment by neganmj** [comment]
> بله متاسفانه خیلی به منطقه‌ی مخابراتی و شهر ربط داره، خیلیا دچار مشکل شدن. بدون فرگمنت فقط از اسکنر ip تمیز اضافه کنید شاید تغییر کنه. DNS هم از 1.1.1.1 استفاده نکنید.

**Comment by neganmj** [comment]
متاسفانه معلوم نیس از منطقه ماعه یا چی، ولی اگه دوستان تونستن مشکل رو برطرف کنن، لطفا همینجا تجربیاتشون رو به اشتراک بزارن.
از تیم دولوپر های عزیز هم خواهش میکنم تا جایی که از دستتون بر میاد رو bypass کردن این مشکل تمرکز کنید، تعداد کسایی که پنل براشون از کار افتاده خیلی خیلی زیاد تر از ایناست.

**Comment by bahadordor** [comment]
دقیقا منم مثل شما همین مشکل رو دارم، اینترنت مخابرات "ADSL" کرج کلا یا پینگ نمیده یا بالا 8 هزار میده تقریبا 3 روزی میشه.
هر راهی هم که فکر کنید رفتم و جواب نگرفتم.
اگه تونستین درست کنید به منم بگین.
ممنونم.

**Comment by bia-pain-bache** [comment]
دوستان اختلال سراسری هست، روی بقیه اپراتورا هم وضعیت خیلی بهتر از این نیست. یه راهکار برای ایرانسل تو توییتر دادم میگن برای مخابراتم اوکیه، امتحانش کنید.

**Comment by koroshyazdi252** [comment]
> دوستان اختلال سراسری هست، روی بقیه اپراتورا هم وضعیت خیلی بهتر از این نیست. یه راهکار برای ایرانسل تو توییتر دادم میگن برای مخابراتم اوکیه، امتحانش کنید.

بی زحمت لینک تویترتان را برای ما هم بفرستید
با تشکر.

**Comment by neganmj** [comment]
یچیزی که برام واقعا عجیبه، اینه که هر پنل bpb که ساختم، برای خودم و خانوادم، همگی پسووردشون عوض شده خود به خود و هیچکدوم کار نمیده...

**Comment by koroshyazdi252** [comment]
سلام و خسته نباشید آقا من این hiddify رو نصب کردم روی اندروید و لینوکس ازش تست گرفتم با توجه به توضیحات خوب شما دوست عزیز در تویتر .
و خیلی خوب کار میکنه بدون مشکل .
فقط این که این hiddify برای ios هم موجود هست ؟
چون من هرچی سرچ میکنم توی اپ استور ios  این hiddify رو پیدا نمیکنم.
ممنون میشم که راهنمایی کنید.

**Comment by koroshyazdi252** [comment]
یه سوال دیگه داشتم ولی نخواستم یه issues جدید باز کنم .
سوالم اینه که آیا امکانش هست که از برنامه openvpn استفاده کرد؟
 چون شنیدم که Open VPN خیلی بهتر میتونه فیلترینگ رو دور بزنه 
یعنی بهتر از v2rayNG هست .
ممنون میشم راهنمایی کنید.

**Comment by tolidweb** [comment]
درود بر شما من هم در ابتدا هیچ مشکلی نداشتم البته روی اندروید به سختی متصل میشدم ولی روی پی سی خیلی عالی جواب میداد متاسفانه مدتی هست که روی هیچ کدوم از فرگمنت ها جواب نمیده adsl منطقه ما که از اول افتضاح بود و دیگه هیچ خریدی نمیکنم یک سوم از نت ی که خریده بودم سوخت شد از مبین نت استفاده میکنم جواب نمیده. با نت رایتل و همراه اول هم تست کردم باز جواب نداد.

**Comment by neganmj** [comment]
> درود بر شما من هم در ابتدا هیچ مشکلی نداشتم البته روی اندروید به سختی متصل میشدم ولی روی پی سی خیلی عالی جواب میداد متاسفانه مدتی هست که روی هیچ کدوم از فرگمنت ها جواب نمیده adsl منطقه ما که از اول افتضاح بود و دیگه هیچ خریدی نمیکنم یک سوم از نت ی که خریده بودم سوخت شد از مبین نت استفاده میکنم جواب نمیده. با نت رایتل و همراه اول هم تست کردم باز جواب نداد.

برای من چه با فرگمنت، چه بی فرگمنت، چه نت adsl, چه ایرانسل، چه با PROXYIP ای پی تمیز داخل کلودفلر، چه داخل پنل، چه بدون ای پی، چه با Proxy chain, چه بی پروکسی، اصلا هرچی فکرشو کنی تست کردم، ینی دریغی از یه شانس برا دانلود یه فایل چند کیلوبایتی....

مقادیر lengths اگه اشتب ننوشتم هم تغییر دادم، دی ان اس رو گذاشتم رو گوگل، بازم هیچی.

با هیدیفای هم تست کردم رو اندروید با adsl, عین guide داخل توییتر، ولی بازم هیچی که هیچی، با فرگمنت بی فرگمنت، اصلا صفر صفر.

خلاصه که بگا رفتیم بدم بگا رفتیم...

اگه دوستان زحمت بکشن در کنار اینهمه تلاششون برا فراهم کردن vpn برای مردم، به این مورد هم رسیدگی کنن ممنون میشیم همه ما مردم ایران ❤️

**Comment by bia-pain-bache** [comment]
`فقط این که این hiddify برای ios هم موجود هست ؟`

هیدیفای نسخه iOS هنوز بتا هست، منتشر میشه.

`چون شنیدم که Open VPN خیلی بهتر میتونه فیلترینگ رو دور بزنه`

این موضوع به این پروژه ربطی نداره ولی خیر اشتباهه.

`با نت رایتل و همراه اول هم تست کردم باز جواب نداد.`

همرته اول در حال حاضر مشکلی با فرگمنت نداره مگر اینکه سرعننون تو اون منطقه پایین باشه.

`اگه دوستان زحمت بکشن در کنار اینهمه تلاششون برا فراهم کردن vpn برای مردم، به این مورد هم رسیدگی کنن ممنون میشیم همه ما مردم ایران`

در حال حاضر حتی با اختلالات و کند شدن چند ضد هزار نفر دارن از همین کانفیگ‌ها استفاده میکنن! هر موردی که نیاز بوده واو به واو تو آموزش‌ها نوشتم، متاسفم کار دیگه‌ای از دستم برنمیاد...

در نهایت خواهش میکنم دیگه هیچ موضوع جدیدی اینجا ننویسید، جواب دادن خیلی سخت میشه و کسی که سوال داره هم ممکنه جوابشو نگیره. هر مورد مشخص رو یه ایشو جدید بزنید از این به بعد.

**Comment by tolidweb** [comment]
درود بر همه متاسفانه چون همه به این سرورها دسترسی دارند با توجه به ماهیت عمومی بودن سایبری ها هم میتونند مسدودشون کنند. بهترین راه اینه که خودتون با هزینه شخصی سرور اختصاصی راه اندازی کنید البته اگه توجیه اقتصادی براتون داشته باشه.

**Comment by raw-file** [comment]
سلام دلیل قطع و وصل شدن مکرر کانفیگ های پنل BPB چیه؟ 
آیا باید تنظیمات تغییر بدم؟
تو همه اپراتورها همین اتفاق میفته.

**Comment by gittfox** [comment]
@raw-file 
منم همین مشکل رو دارم. هم با پنل ورژن 2 و هم ورژن 3. روی همراه، ایرانسل و آسیاتک.

**Comment by bia-pain-bache** [comment]
آپدیت کنید به آخرین ورژن و از پنل Fingerprint رو بذارید روی chrome مثلا.
