### ISSUE TITLE
Chain Proxy  کار نمیکنه

### ISSUE THREAD

**Issue by sm-saeedmoosavi** [bia-pain-bache/BPB-Worker-Panel#77]
سلام.
من یک کانفیگ ویلس از نوع ریلیتی grpc دارم که به تنهایی کار میکنه
میخوام اونو بعنوان Chain Proxy استفاده کنم. ولی با وجودی که تغییرات در پنل ذخیره و اعمال میشه و بعدش هم ساب رو آپدیت میکنم، اما عمل نمیکنه و باز هم با کشورهای مختلف میاره.
میشه راهنمایی کنید که چرا برای من Chain Proxy جواب نمیده؟
ممنون

**Comment by bia-pain-bache** [comment]
سلام، لطفا کانفیگتون رو اینجا بذارید ولی اسم دامنه و IP و UUID رو برای امنیت تغییر بدید تا ببینم فرمت کانفیگ به چه شکل هست.

**Comment by sm-saeedmoosavi** [comment]
vless://uuu@sss:10102?hiddify=1&sni=www.tumblr.com&type=grpc&alpn=http/1.1&path=Q3CzXMNE5CK20G0CY60&serviceName=Q3CzXMNE5CK20G0CY60&mode=gun&encryption=none&fp=chrome&headerType=None&security=reality&pbk=yvYXOCAyA2i-F5qblDDGCsLeHVdt7OXRr7xuNW4axlE&sid=e5b7#service-800185

**Comment by bia-pain-bache** [comment]
این کانفیگ متعلق به هیدیفای هست و فرمت استاندارد نداره. شما باید از پنل XUI یا اپلیکیشن v2rayNG کانفیگ رو export کنید.
