### ISSUE TITLE
عدم اتصال روی تمامی اپراتورها

### ISSUE THREAD

**Issue by Mikael1993** [bia-pain-bache/BPB-Worker-Panel#78]
درود خدمت تیم BPB و همچنین دوستان عزیز

طی چند روز گذشته BPB از کار افتاده و روی هیچ اپراتوری متصل نمیشه
اگر امکان داره لطفا همین جا بگید ایا راهی داره بتونیم مثل قبل متصل بشیم

با تشکر

@bia-pain-bache

**Comment by Mikael1993** [comment]
> 
> سلام ، نه. این صفحه رو مطالعه کنید #76 به اندازه کافی جواب سوالاتت داخلشه.

سوال اینجاست که ایا این مشکل برمیگرده به کم آوردن تعداد پروکسی ها و همچنین تعداد یوزرهای بالا که استفاده میکنن از BPB
یا اینکه قطعی بخاطر محدودیتی هست که داره اعمال میشه

اگه بخاطر کم بودن پروکسی های پشت CNAME باشه میشه راحت حل کرد با مشارکت همه دوستان

**Comment by neganmj** [comment]
> اگه بخاطر کم بودن پروکسی ها باشه میشه راحت حل کرد با مشارکت همه دوستان
>
دوست عزیز خود دولوپر گفته اختلال سراسریه، پروکسی چی اخه!

**Comment by bia-pain-bache** [comment]
روش Pages هیچ محدودیتی نداره، چند روزی اختلال سراسری بود که الان بهتر شده روی اکثر اپراتورا، منطقه‌ای هم هست.

**Comment by bia-pain-bache** [comment]
سلام ممنونم،
بنظرم قرار دادن پنل در کانال خیلی اشتباهیه، شما فقط لینک ساب و یا کانفیگ رو باید در کانال قرار بدید.

**Comment by Mikael1993** [comment]
درود
آیا راه حلی برای همراه اول دارید؟
تمامی امراخورها با پینگ و سرعت خیلی خوب کار میکنه BPB
ولی همراه اول متصل نمیشه و اگر پینگ بده بالای ۲ هزار هست پینگ، کانفیگ های
فرگمنت BPB هم متصل نمیشن کلا

**Comment by bia-pain-bache** [comment]
بله فرگمنت مشکل پیدا کرده، از کانفیگ نرمال استفاده کنید، IP تمیز هم میتونه کمک کنه.
