### ISSUE TITLE
Add shadowsocks support to chain proxy

### ISSUE THREAD

**Issue by Someone7un7** [bia-pain-bache/BPB-Worker-Panel#79]
It would be amazing if you added shadowsocks support to chain proxy, I really need it man

**Comment by bia-pain-bache** [comment]
I'm afraid I can't add a feature which is not scalable. Almost most of free configs are VLESS, Also There's no big difference between SS and VLESS...

**Comment by Someone7un7** [comment]
yep but the exact IP that I want and I have is in shadowsocks method so that was why I asked, ok whatever bro
