### ISSUE TITLE
Google apps fail with Hiddify client on Android

### ISSUE THREAD

**Issue by amzaf** [bia-pain-bache/BPB-Worker-Panel#8]
وقتی لینک سابسکریپشن پنل را به هیدیفای اضافه می‌کنم گوگل کروم و سایر سرویسهای گوگل روی گوشی از کار می‌افتند ولی سایر اپها مثل تلگرام و اینستاگرام کار می‌کنند. این مشکل روی v2rayng وجود نداره و با bpb اوکی هست. جالبه که هیدیفای فقط با سابسکریپشن پنل شما اینطوری میشه ولی با یه جای دیگه تست کردم بدون مشکل کار می‌کنه

**Comment by bia-pain-bache** [comment]
به این شکل تنظیم کن امیدوارم مشکل برطرف بشه، تو تست‌ها مشکلی نداره.
remote DNS: https://8.8.8.8/dns-query
local DNS: 8.8.8.8

**Comment by amzaf** [comment]
سپاس مشکل حل شد. همون تغییر remote dns کافیه
