### ISSUE TITLE
فراموشی رمز پنل

### ISSUE THREAD

**Issue by hatinati2** [bia-pain-bache/BPB-Worker-Panel#80]
سلام وقت بخیر خسته نباشید 
رمز پنل فراموش کردم باید چیکار کنم؟

**Comment by bia-pain-bache** [comment]
سلام سلامت باشید، راهنمایی دوستمون درسته، اگر به مشکل خوردی بگو.

**Comment by hatinati2** [comment]
> سلام سلامت باشید، راهنمایی دوستمون درسته، اگر به مشکل خوردی بگو.

مرسی متشکرم
