### ISSUE TITLE
 HTTP نحوه فعال سازی کانفیگ ها بر روی پورت های

### ISSUE THREAD

**Issue by tele4mecom** [bia-pain-bache/BPB-Worker-Panel#81]
درود خدمت شما
با تستی که ما انجام دادیم همراه اول روی پورت های HTTP به خوبی متصل میشه

چطوری میتونیم کانفیگ با پورت HTTP داشته باشیم؟

ممنون میشم راهنمایی کنید

**Comment by bia-pain-bache** [comment]
سلام،
شما از دو روش میتونید انجام بدید، اول:
۱- برای Pages بیاید custom domain بذارید (پیشنهادی)
۲- از طریق Workers دپلوی کنید.

بعد tls رو در کانفیگ‌های نرمال غیرفعال کنید و پورت رو به ۸۰ تغییر بدید.

**Comment by tele4mecom** [comment]
درود مجدد
آیا راهی وجود داره بتونیم از worker بیشتر از 100هزار رکوئست در روز استفاده کنیم؟
