### ISSUE TITLE
change DNS to block porn (and also ads)

### ISSUE THREAD

**Issue by mmrabbani** [bia-pain-bache/BPB-Worker-Panel#83]
با سلام
لیست category-porn یکی از لیست های بسیار طولانی است و استفاده از آن در تجهیزات ضعیف مثل روترها ممکن است سرعت را کاهش دهد. یک راه جایگزین استفاده از adguard Family DNS (که سایت های بزرگسالان، تبلیغات، ترکرها و بدافزارهای را فیلتر میکند.) یا cloudflare family DNS (که سایت های بزرگسالان و بدافزارهای را فیلتر میکند) است. هر دو از DOH هم پشتیبانی میکنند.

لینک ها
https://adguard-dns.io/en/public-dns.html
https://developers.cloudflare.com/1.1.1.1/setup/

در صورتی که از ادگارد استفاده کنید، میتوان لیست های فعلی مثل category-ads-ir را هم حذف کرد که البته لیست بلندی نیستند، ولی میتواند برای افرادی که geosite را آپدیت نکردند از خطا جلوگیری کند.

**Comment by bia-pain-bache** [comment]
سلام 
بله ممنون، میتونید روی پنل تنظیمات دلخواه رو اعمال کنید.
