### ISSUE TITLE
عدم اتصال از امروز

### ISSUE THREAD

**Issue by dispel123** [bia-pain-bache/BPB-Worker-Panel#84]
سلام من تا چند ساعت پیش هم داشتم از فرگمنتا استفاده می کردم هم از کانفیگای معمولی الان نیم ساعته رو ویندوز هیچکدم پینگ نمیدن و رو اندروید فقط کانفیگ معمولیا وصل می شن ای پی تمیزم تست کردم چندتا و اینکه chainproxy دارم و پاکش کردم تاثیری نداشت یعنی مشکل از vps من نیست.

**Comment by mabna2** [comment]
وارپ فیلتر شده کلودفلر هم تا خرخره محدود فرگمنتم همینطور

**Comment by dispel123** [comment]
من از سرور خودم فرگمنت ساخته بودم اونم از کار افتاده الان یعنی کاریش نمیشه کرد؟

**Comment by mobin6092** [comment]
یه کاری بکنین تروخدا . با همین به زور وصل میشدم دیسکورد که دیگه نمیشه همینم .

helpppppppppppppp

**Comment by dispel123** [comment]
اگه کلاود فلرو ببندن خیلی اوضاع بد میشه اخه اصلا خودشونم به مشکل میخورن الان کسی راهی سراغ نداره که بشه الان وصل شد؟

**Comment by bia-pain-bache** [comment]
سلام،
فرگمنت فعلا مشکل داره، از کانفیگای نرمال استفاده کنید با IP های تمیز، خود کانفیگ‌هایی که پنل میده هم تمیزن نسبتا. mux حتما خاموش باشه.

**Comment by dispel123** [comment]
> سلام، فرگمنت فعلا مشکل داره، از کانفیگای نرمال استفاده کنید با IP های تمیز، خود کانفیگ‌هایی که پنل میده هم تمیزن نسبتا. mux حتما خاموش باشه.

خیلی ممنون از پاسختون چند لحظه پیش دوتا از فرگمنتا که ادرسشون ای پیه وصل شدن ولی اسپید تست و یکی از سایتایی که تمیزه و خودم دادم وصل نمیشن قراره اپدیتی ریلیز کنین یا فعلا اوضاع همینه؟
