### ISSUE TITLE
مشکل عدم اتصال

### ISSUE THREAD

**Issue by mohammadreza2049** [bia-pain-bache/BPB-Worker-Panel#86]
سلام. متأسفانه امروز تمام کانفیگ‌هاش از کار افتاد.

**Comment by aliiii73** [comment]
سینگ باکس تست کن کار می‌کنه

**Comment by mohammadreza2049** [comment]
مرسی. ولی به نظرم نیاز به یه آپدیت داره.
فیلترچی‌ها یه حرکتی زدن.
من از ورکر وحید فرید هم استفاده می‌کردم، از کار افتاد.

**Comment by aliiii73** [comment]
مشکل از فیلتر شدن مکرر آیپی هاست

در تاریخ جمعه ۲۴ مهٔ ۲۰۲۴،‏ ۱۷:۰۵ mohammadreza2049 ***@***.***>
نوشت:

**Comment by mohammadreza2049** [comment]
خب من clean IP رو بروز کردم، حتی chain Proxy هم زدم، ولی بازم وصل نشد.

**Comment by bia-pain-bache** [comment]
ظاهرا مشکل برطرف شده، معاوم نیست موقتیه یا منطقه‌ایه.

**Comment by aliiii73** [comment]
آره انگار الان v2rang هم کار می‌کنه

در تاریخ جمعه ۲۴ مهٔ ۲۰۲۴،‏ ۱۷:۳۸ bia-pain-bache ***@***.***>
نوشت:

**Comment by aliiii73** [comment]
ولی از حق نگذریم کانفیگ سینگ باکس اد بلاک عالی داره 95 درصد تبلیغات رو بلاک
می‌کنه بجز یوتویوب

در تاریخ جمعه ۲۴ مهٔ ۲۰۲۴،‏ ۱۷:۴۳ mohammadreza2049 ***@***.***>
نوشت:

**Comment by mohammadreza2049** [comment]
بله؛ الآن هم دوباره اختلال ایجاد شده.
معلوم نیست کی دوباره نشسته رو اینترنت :///

**Comment by aliiii73** [comment]
شاید با آیپی تمیز درست شه

در تاریخ شنبه ۲۵ مهٔ ۲۰۲۴،‏ ۱۰:۵۵ mohammadreza2049 ***@***.***>
نوشت:

**Comment by mohammadreza2049** [comment]
همه آی‌پی‌های تمیز رو تغییر دادم، ولی باز هم وصل نشد.

**Comment by aliiii73** [comment]
V2ray برا منم امروز قطع شده ولی singbox برام وصله

در تاریخ شنبه ۲۵ مهٔ ۲۰۲۴،‏ ۱۲:۱۹ mohammadreza2049 ***@***.***>
نوشت:

**Comment by mohammadreza2049** [comment]
هرچی هست انگار برای نرم افزار V2RayNG مشکل ایجاد کردن.
من shadowrocket نصب کردم، اونم کار می‌کنه.

**Comment by mohammadreza2049** [comment]
داداش همون گزینه فرگمنت رو از نرم افزار V2Ray غیرفعال کن و BPB بدون فرگمنت (نرمال) بزن روش، درست میشه.

**Comment by dispel123** [comment]
فرگمنتا کلا به مشکل خوردن کانفیگای نرمالم بیشترش کار نمیکنه اوناییم که کار میکنه چون هی ای پی عوض میشه خیلی جاها به مشکل میخوره

**Comment by dispel123** [comment]
دیروزم دقیقا همین موقع ها بود که به مشکل خورد عصر درست شد معلوم نیس دارن چی تست میکنن

**Comment by mohammadreza2049** [comment]
آره قطعی وصلی زیاد دارن. احتمالاً دارن روش فیلترینگ جدید پیاده می‌کنن.

**Comment by dispel123** [comment]
امروز خیلی اوضاع از دیروز بدتره حتی کانفیگای معمولیم به زور وصل میشن انگار بعضی از اپراتورا ای پی های کلاود فلرو بستن کسی راه جدیدی پیدا نکرده؟ فکر کنم باید فرگمنتو ببوسیم بذاریم کنار

**Comment by mohammadreza2049** [comment]
والا من یه پروکسی Vless پنج روزه از این سایت‌ها گرفتم زدم واسه chain Proxy ؛ پینگ اومده رو 300-400. سرعتشم واسه کارهای معمولی خوبه.

**Comment by bia-pain-bache** [comment]
روش پیشنهادی با ترکیب rethink توییتر گذاشتم، با اون وصل بشید.

**Comment by mohammadreza2049** [comment]
سپاسگزارم

**Comment by fndrp** [comment]
سلام 
BPB Panel v4.0.1 نصب کردن 
اما کانفیگ های کار نمی کنه تنظیم خاصی داره؟
