### ISSUE TITLE
workerLess dosen't work

### ISSUE THREAD

**Issue by emad465** [bia-pain-bache/BPB-Worker-Panel#87]
سلام این سرور workerLess اصلا متصل نمیشه و فقط پینگ میده ، وقتی که میخوای بهش وصل شی دکمه اتصال رو میزنی وصل نمیشه

**Comment by bia-pain-bache** [comment]
سلام،
 موارد نادری گزارش شده که به کانفیگ ربط نداره از اپلیکیشن هست، بعضا با آپدیت برنامه و بعد geo asset درست شده.
