### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by vahiddddd** [bia-pain-bache/BPB-Worker-Panel#9]
بعد از ایجاد نسخه 2.2 این پیام میاد و پنل نمیاد بالا.

**Comment by bia-pain-bache** [comment]
از نسخه‌ی ۲.۲ تغییراتی داشتیم و آموزش بروزرسانی شده. لطفا طبق اون پیش برید. از این نسخه آدرس پنل panel/ هست نه uuid/.

**Comment by vahiddddd** [comment]
آموزش جدید رو کجا می تونم ببینم ممنون

**Comment by vahiddddd** [comment]
ممنون پیداش کردم. از زحمات شما عزیزان کمال سپاس را دارم.
از همون کامنت که زدین پیداش کردم.

**Comment by vahiddddd** [comment]
> از نسخه‌ی ۲.۲ تغییراتی داشتیم و آموزش بروزرسانی شده. لطفا طبق اون پیش برید. از این نسخه آدرس پنل panel/ هست نه uuid/.

آموزش رو کجا پیدا کنم

**Comment by vahiddddd** [comment]
من خیلی ممنون مشکلم حل شد.

**Comment by Kazama988** [comment]
آقا دمت گرم اینجا پیدا کردم چطوری باید بری تو پنل

**Comment by vahiddddd** [comment]
آخر آدرس به جای uuid  از panel استفاده کن

**Comment by vahiddddd** [comment]
> آخر آدرس به جای uuid از panel استفاده کن



> آقا دمت گرم اینجا پیدا کردم چطوری باید بری تو پنل

آخر آدرس به جای uuid از panel استفاده کن

**Comment by vahiddddd** [comment]
> آقا دمت گرم اینجا پیدا کردم چطوری باید بری تو پنل


آخر آدرس به جای uuid از panel استفاده کن

**Comment by vahiddddd** [comment]
یوزر پس هر دو admin هستش
