### ISSUE TITLE
۴۴۳ UDP

### ISSUE THREAD

**Issue by CyrusTheV** [bia-pain-bache/BPB-Worker-Panel#90]
سلام توی کانفیگ ها پورت ۴۴۳ UDP بلاک شده. جدیدا یسری از اپ ها از ۴۴۳ UDP دارن استفاده میکنن !!
‌BPB جان worker رو یه آپدیت بزن یا دوستان عزیز کانفیگ خودتون رو ادیت کنید .

**Comment by JavadZohani** [comment]
سلام خوب باید چطوری کانفینگمونو ادیت کنیم و تغییراتو ایجاد کنیم؟

**Comment by CyrusTheV** [comment]
{
                "network": "udp",
                "port": 443,
                "port_range": [],
                "outbound": "block"
            },


اینو حذف کن

**Comment by bia-pain-bache** [comment]
سلام
من داخل پنل چنین کاری نکردم، مگر اینکه از منابع دیگه کد رو گرفته باشید که دستکاری شدن.

**Comment by CyrusTheV** [comment]
ساب رو که gen  میکنم این توش هست

            {
                "network": "udp",
                "port": 443,
                "port_range": [],
                "outbound": "block"
            },

**Comment by bia-pain-bache** [comment]
شما سینگ‌باکس منظورتونه. ولی در جریان باشید این ربطی به کار نکردن udp نداره، ورکرها کلا در مورد udp باگ دارن و هنوز این مساله حل نشده. مثلا تماس صوتی تصویری تلگرام کار نمیکنه. با v2rayNG هم همینه. نیازی به تغییر اون بخش کانفیگ نیست.

**Comment by CyrusTheV** [comment]
> شما سینگ‌باکس منظورتونه. ولی در جریان باشید این ربطی به کار نکردن udp نداره، ورکرها کلا در مورد udp باگ دارن و هنوز این مساله حل نشده. مثلا تماس صوتی تصویری تلگرام کار نمیکنه. با v2rayNG هم همینه. نیازی به تغییر اون بخش کانفیگ نیست.

عالی مرسی که گفتی رو تماس واتساپ مشکل داشتم نمیدونستم چیه ماجراش

**Comment by CyrusTheV** [comment]
> شما سینگ‌باکس منظورتونه. ولی در جریان باشید این ربطی به کار نکردن udp نداره، ورکرها کلا در مورد udp باگ دارن و هنوز این مساله حل نشده. مثلا تماس صوتی تصویری تلگرام کار نمیکنه. با v2rayNG هم همینه. نیازی به تغییر اون بخش کانفیگ نیست.
منظورت اینه که کلاد فلر روی سرویس ورکرزش این مشکل رو داره؟ یا کد ورکرز شما این مسيله رو داره؟

**Comment by bia-pain-bache** [comment]
روی واتسپ نباید مشکلی داشته باشه، اون بخاطر شرایط اینترنت هست.
