### ISSUE TITLE
Unable to connect , Abnormal activity!

### ISSUE THREAD

**Issue by SiliconPiratez** [bia-pain-bache/BPB-Worker-Panel#92]
سلام ، اول از شما تشکر میکنم بابت زحماتتون 
تا چندی پیش استفاده میکردم روی همراه اول ، تو همه حالت ها ورکرلس و فرگمت و نرمال مشکلی بود با پینگ زیر 400 (ایپی تمیز)
اما چند روزی هست که دچار مشکل شده و هیچ جوره وصل نمیشه و تنها اروری هم که میده tls handshake هست
کمتر از 48 ساعت پیش با pages یک پنل جدید ساختم و تغییرات خاصی هم اعمال نکردم ، حتی استفاده هم نکردم ازش ! 
مصرف شخصی هم هست تنها خودم اون هم فقط با یک دیوایس.
اما این حجم از ریکوئست از کجا اومده ؟!
![Screenshot 2024-05-27 001201](https://github.com/bia-pain-bache/BPB-Worker-Panel/assets/40206598/5799eed2-ee05-498c-8f3e-54ee709fac6a)

**Comment by bia-pain-bache** [comment]
سلام،
نت در تمام ایران مختله.  روش جدید با rethink رو توییتر بخونید. ۱۰۰ هزار درخواست مصرف ۳-۴ نفر هست. ۲۴ تا کاملا طبیعیه.
