### ISSUE TITLE
محدودیت 100 هزار رکوئست در ورکر

### ISSUE THREAD

**Issue by tele4mecom** [bia-pain-bache/BPB-Worker-Panel#93]
درود
دوستان ایا راهی داره بتونیم محدودیت 100 هزار رکوئست روزانه در ورکر رو حل کنیم( BPB با ورکر بدون مشکل کار میکنه)

**Comment by ghonchew** [comment]
سلام
باید کردیت کارد بگیرید و یه اشتراک تهیه کنید اگه میصرفه براتون.
یا با چندتا اکانت کار کنین.

**Comment by bia-pain-bache** [comment]
سلام
اگر از دامنه‌ی شخصی custom domain استفاده کنید محدودیت برطرف میشه، نیازی به کردیت کارد نیست. روش pages کلا نامحدوده حتی بدون دامنه شخصی.

**Comment by bia-pain-bache** [comment]
دست من نیست متاسفانه. روش جدید با rethink رو در توییتر بخونید.
