### ISSUE TITLE
تغییر نحوه  چیدمان ورود ای پی تمیز به ورکر

### ISSUE THREAD

**Issue by Hamed-Republic** [bia-pain-bache/BPB-Worker-Panel#94]
سلام ایا ممکنه تغییراتی داخل ورکر ایجاد کنید که به جای اینکه ای پی ها با ویرگول از هم جدا بشن با اینتر از هم جدا بشن و زیر هم قرار بگیرن؟ چون که اکثر اسکنر ها ای پی ها رو به این صورت خروجی میدن و حذف اینتر و گزاشتن ، بین ای پی ها زمان بره و خسته کننده میشه 🙏 
با تشکر

**Comment by bia-pain-bache** [comment]
سلام، در اون صورت مجبور میشم فضا رو بیشتر کنم که نمیخوام این‌کارو بکنم، هدفم مینیمال بودن پنل هست. اکر از فرگمنت استفاده میکنید نیازی به IP تمیز ندارید اصلا.

**Comment by arkanpay** [comment]
چطور نیاز به IP تمیز ندارن؟ فرگمنت فقط میاد پکت های مربوط به tlshello که شامل sni هست رو چند تکه میکنه و این موضوع هم فقط برای حالتی هست که sni فیلتر شده باشه و ارتباطی به IP تمیز نداره. مبحث IP تمیز به طور کامل از مبحث فرگمنت جداست.

**Comment by Hamed-Republic** [comment]
> سلام، در اون صورت مجبور میشم فضا رو بیشتر کنم که نمیخوام این‌کارو بکنم، هدفم مینیمال بودن پنل هست. اکر از فرگمنت استفاده میکنید نیازی به IP تمیز ندارید اصلا.
نیازی به بیشتر کردن فضا نیست فقط ورودی رو به جای ویرگول باشه

**Comment by arkanpay** [comment]
> فرگمنت همزمان کانکشن رو با IP ریزالو شده‌ی مقصد برقرار میکنه مثل کانفیگ workerless، شما اونجا اصلا پروکسی نداری (فیکه)، بخاطر همین IP تمیز تا جایی که من میدونم دیگه خیلی تاثیری نداره، تست‌ها هم همینو میگن البته.

نه اتفاقا IP تمیز و همینطور پورت، کاملا موثره. می تونی از وحید فرید بپرسی که استاد اینکاره. هم کد اسکنر نوشته و هم کد فرگمنت. به هر دو مسلطه.

**Comment by bia-pain-bache** [comment]
چشم
