### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by lord-wolf7** [bia-pain-bache/BPB-Worker-Panel#95]
یسری از سایت ها موقع استفاده اول ارور Notsafe میزنه بعد که ادامه رو میزنم not foundمیشه بیشتر تو سایت های لینک مستقیم میزارن چطور میشه مشکلش رفع کرد؟

**Comment by bia-pain-bache** [comment]
اگر از proxy ip تکی استفاده کردید توصیه میکنم عوضش کنید، اگر با پیشفرض پنل هستید توصیه میکنم proxy ip ست کنید.

**Comment by bia-pain-bache** [comment]
آموزش‌ها رو بخونبد کامل توضیح دادم.

**Comment by lord-wolf7** [comment]
من از طریق پنل کلوفلر آیپی سنگاپور اختصاص دادم منظورت همینه؟طبق آموزش خودت ولی همچنان مشکل دارم میشه بیشتر راهنمایی کنی؟یه مورد دیگه تو گوشی آیفون با برنامه straisand وقتی ساب کانفیگ نرمال میدم تلگرام راحت باز میکنه ولی ایتستاگرام و واتساپ باز نمیکنه دلیلش چی میتونه باشه؟دمت گرم بابت آموزش خوبت

**Comment by bia-pain-bache** [comment]
remote dns: https://8.8.8.8/dns-query 
بذار تو هر برنامه‌ای این مشکلو داری.

**Comment by lord-wolf7** [comment]
> remote dns: https://8.8.8.8/dns-query بذار تو هر برنامه‌ای این مشکلو داری.

تو خود پنل بزارم جای dns پیش فرض؟

**Comment by lord-wolf7** [comment]
با برنامه v2ran و v2ray ng کار میکنم برای آیفون هم straisand تو خود تنظیمات برنامه ها ست بشه؟

**Comment by bia-pain-bache** [comment]
آره برنامه

**Comment by lord-wolf7** [comment]
باید عین لینک وارد کنم یا فقط 8.8.8.8؟؟

**Comment by lord-wolf7** [comment]
![Uploading Screenshot_20240604_003731_v2rayNG.jpg…]()

**Comment by lord-wolf7** [comment]
![Uploading Screenshot_20240604_003731_v2rayNG.jpg…]()

**Comment by lord-wolf7** [comment]
![Uploading Screenshot_20240604_003731_v2rayNG.jpg…]()

**Comment by bia-pain-bache** [comment]
عین همون لینک
