### ISSUE TITLE
مشکل عجیب 

### ISSUE THREAD

**Issue by koroshyazdi252** [bia-pain-bache/BPB-Worker-Panel#96]
با عرض سلام و وقت بخیر.
حقیقت اینه که یه مشکلی عجیب برام پیش اومده و اونم اینه که 
من الان برای دوستم این کانفیگ bpb رو  براش درست کردم که استفاده کنه ولی با نت خودش که همراه اول هست بیشتر وقت ها قطع میشه ولی من که نت همراه اول خودم رو براش قابل همل میکنم که وصل بشه خیلی براش خوبه .
در صورتی که هر دوی ما اینترنت گوشیمان همراه اول است و توی یک منطقه هم هستیم .

**Comment by bia-pain-bache** [comment]
واقعیتش خیلی عوامل ممکنه باشه و هر کدوم باید تست بشه، متاسفانه من از راه دور کمکی ازم بر نمیاد.
