### ISSUE TITLE
اضافه کردن سایر پورت های کلودفلر به کانفیگ ها

### ISSUE THREAD

**Issue by arkanpay** [bia-pain-bache/BPB-Worker-Panel#97]
اگه ممکنه برای حالت بدون فرگمنت، سایر پورت های کلودفلر رو هم اضافه کنید. یعنی لینک sub به ازای هر IP سرور، چندین کانفیگ با پورت های مختلف برگردونه. چون برخی IP های تمیز مثلا با پورت 2083 کار میکنن ولی با 443 اختلال دارن.

https://developers.cloudflare.com/fundamentals/reference/network-ports/

مثل کاری که ایشون انجام دادن.

https://github.com/3Kmfi6HP/EDtunnel/blob/main/_worker.js

**Comment by bia-pain-bache** [comment]
مشکل ما در حال حاضر SNI هست و تغییر پورت هیچ تاثیری نداره. برای تست گرفتن باید نمونه آماریتون زیاد باشه و روی شبکه پایدار تست بگیرید تا متوجه یبشید. اگر اصرار دارید میتونید دستی این کارو بکنید.

**Comment by arkanpay** [comment]
والا من برای خودم که مشکلی نیست و به نسخه اصلی کد ورکر edtunnel اضافه کردم. منتها چون کار شما پنل کاربری داره و کاربر پسنده، به بقیه معرفی می کنم. زیاد پیش میاد از من IP تمیز می خوان و بهشون میدم و میگن جواب نمیده چون فقط با پورت 443 هست، هر سری باید برن کانفیگ ها رو ویرایش بزنن و پورت رو عوض کنن تا وصل بشه. برای کسایی که زیاد وارد نیستن این کار سخته. فعلا کاربرایی که با من در ارتباطن مشکل sni ندارن و با IP تمیز و عوض کردن پورت کارشون راه میوفته.
حالا این تغییر سختی هم نیست و نمونه اش رو هم فرستادم، اگه حتی اعتقادی هم به تاثیر پورت ندارین، اگه ممکنه به عنوان یه آپشن به پنل اضافه کنین. ما همه داریم سعی می کنیم کار بقیه راحت تر بشه و متصل بمونن.

**Comment by bia-pain-bache** [comment]
شما اگه یه نمونه بزرگ در نظر بگیرید، مثلا 100 تست روی هر پورت و روی یه شبکه پایدار هم تست بگیری (که تو ایران محاله) متوجه میشید میانگین خروجی تست روی همه پورت‌ها مثل همه! ولی در هر صورت من بازم بررسی میکنم اگر دیگران هم تجربه مشابهی داشته باشن حتما این کارو میکنم.
