### ISSUE TITLE
در V2ranN تست سرعت نمیتونم بدم

### ISSUE THREAD

**Issue by 3reili** [bia-pain-bache/BPB-Worker-Panel#99]
سلام
بعد از نصب انجام تمام قدم ها به طور کامل وارد پنل میتونم بشم ساب آپدیت میشود. تست پینگ هم درست میدهد اما تست سرعت نمیتواند بگیرد دیروز پیجز رو بالا آوردم با UUID و ProxyIP عوضشون هم میکنم کار نمیکند.
باید چکار کنم؟

**Comment by 3reilii** [comment]
در ضمن با تلگرام و بعضی سایت ها مشکل داره نمیاد بالا چه با آی پی های ساب چه با آی پی تمیز

**Comment by bia-pain-bache** [comment]
سلام اینجا رو چک کن لطفا
https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/configuration_fa.md

**Comment by 3reilii** [comment]
امتحان کردم و دقت کردم موقع تست سرعت با پیجز قبلی که ساختم هیچ مشکلی وجود نداره، اما با این اکانتم تلگرام وبعضی سایتا باز نمیشن

**Comment by 3reilii** [comment]
نمیشه درستش کرد؟
تاریخ پیجز قبلیم 30-5 بوده 
جدیدیا از 5-6 به بعد اما قبلیه مثل بنز کار میکنه همه جچی وصله و سریع اما جدیدیا هیچکدوم کار نمیکنن حتی ورکر هم ساختم اما برای تگرام کار نمیکنه...
تمام قدم ها رو عین فایل کانفیگ که گفتی زدم اما به جایی نرسیدم

**Comment by bia-pain-bache** [comment]
با پیجز دپلوی کن ترجیحا. dns رو طبق سوالات متداول قرار بده توی برنامه. proxy ip با clean ip فرق داره به این دقت کن. در هر دو حالت نرمال و فرگمنت هم تست کن. مشکلی که میگی مربوط به نحوه‌ی دپلوی و کانفیگ خودت هست، مشکل عمومی نیست، به ورژن هم ربطی نداره.
